profilelist1exp/unpackaged/objects/Account_Handover__c.object
<CustomObject>
    <description>This object is used to store information relating to an account deemed inportant for account transitions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The account that is related to this Account Handover record.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Handovers</relationshipLabel>
        <relationshipName>Account_Handovers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status01__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status02__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status03__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_3__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status04__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_4__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status05__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_5__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status06__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_6__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status07__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_7__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status08__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Step_8__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_1__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Update Customer contacts in SFDC; Review premier page data and ownership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_2__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Add transition strategy to Account Plan in SFDC</fullName>
                </value>
                <value>
                    <fullName>If Account Plan is in place, add transition strategy</fullName>
                </value>
                <value>
                    <fullName>Debrief call with prior/new owner before Customer call</fullName>
                </value>
                <value>
                    <fullName>No handover assigned, process handled outside SFDC.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_3__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 3</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Debrief call with prior/new owner before Customer call</fullName>
                </value>
                <value>
                    <fullName>Joint call to Customer and introduce new team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_4__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 4</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Joint call to Customer and introduce new team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_5__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 5</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Meeting(s) completed and Trip reports created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_6__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 6</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>If Customer indicates need for leadership communication, add as a task to the strategy within Account Plan</fullName>
                </value>
                <value>
                    <fullName>Leadership communication required, add as a task to the strategy within Account Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_7__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 7</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Review Customer Premier Page for standard configs, accurate pricing, EOL configurations, verify page ownership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_8__c</fullName>
        <description>To Display the values as per &quot;Tier to Step Dependency&quot;</description>
        <label>Step 8</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Tier_level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Leadership call to Customer to ensure transition is going smoothly and introduce themselves</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier_level__c</fullName>
        <description>Tier Level should be controlling field for Step fields</description>
        <label>Tier level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ACQ to R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Tier 1A</fullName>
                </value>
                <value>
                    <fullName>Tier 1B</fullName>
                </value>
                <value>
                    <fullName>Tier 2A</fullName>
                </value>
                <value>
                    <fullName>Tier 2B</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Handover</label>
    <nameField>
        <displayFormat>AH-{00000000}</displayFormat>
        <label>Account Handover Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Handovers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AccntHandoverKeyContactsCtrlTest.cls
/***********************************************************
* Revision       Release                   Name           Date                  Description   
* 1.0       0202             Vikas KH      08-Dec-2019      Impelemented TDF
***************************************************************/
@isTest
//(seeAllData=false)
private class AccntHandoverKeyContactsCtrlTest {
    Static list<Account> listAcc;
    static Account_Handover__c testAccountHandover;    
    @testSetup Static void setup(){
        list<Account> listAccTDF = TestDataFactory.createNAccount(1, 'Master Account');
        insert listAccTDF;
    }    
    static testMethod void displayTopTenAccntHandoverKeyContacts() {
        createTestData();
        Test.startTest();    
        AccntHandoverKeyContactsCtrl controller = new AccntHandoverKeyContactsCtrl (new ApexPages.StandardController(testAccountHandover)); 
        controller.getContacts();
        Account_Handover__c retrievedAccHandover = controller.accHandover;
        List<Contact> listretrievedContacts = controller.contacts ;
    system.assertNotEquals(null, retrievedAccHandover.name);        
        Test.stopTest();          
    }
    static testMethod void displayAllAccntHandoverKeyContacts() {
        createTestData();
        Test.startTest();    
        AccntHandoverKeyContactsCtrl controller = new AccntHandoverKeyContactsCtrl (new ApexPages.StandardController(testAccountHandover)); 
        controller.getAllContacts();
        controller.handleError(new TestException('This is test exception'));
        system.assertNotEquals(null, Account_Handover__c.name);        
        Test.stopTest();  
    }
    public class testException extends Exception {}
    static void createTestData() {
        //insert Account record
        //     Account testAccount = new Account(name='testAccount' + System.currentTimeMillis());        
        //     insert testAccount;
        listAcc = [select id,name from Account limit 1];  
        //insert Account Handover records
        system.assertNotEquals(null, listAcc[0].Name);
        testAccountHandover = new Account_Handover__c(Account__c=listAcc[0].Id, Tier_Level__c ='White Glove', 
                                                      Step_1__c ='Test 1', Step_2__c ='Test 2', Step_3__c ='Test 3', 
                                                      Step_4__c ='Test 4', Step_5__c ='Test 5', Step_6__c ='Test 6',
                                                      Step_7__c ='Test 7', Step_8__c ='Test 8', Status01__c ='Not Started',
                                                      Status02__c ='Not Started', Status03__c ='Not Started',
                                                      Status04__c ='Not Started', Status05__c ='Not Started',
                                                      Status06__c ='Not Started', Status07__c ='Not Started',
                                                      Status08__c ='Not Started'); 
        insert testAccountHandover ;          
    }    
}