profilelist1exp/unpackaged/objects/Account_Team__c.object
<CustomObject>
    <description>Custom Object To Capture Account Team Information from Affinity</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>A - Active
I - Delete</inlineHelpText>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Agenda_Content__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Agenda Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Content</pluralLabel>
    <recordTypes>
        <fullName>Subject</fullName>
        <active>true</active>
        <description>Select this for creating a new subject</description>
        <label>Subject</label>
    </recordTypes>
    <recordTypes>
        <fullName>Topic</fullName>
        <active>true</active>
        <description>Select this for creating a new subtopic</description>
        <label>Topic</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Agenda_Topic__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipName>Related_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Agenda Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Attendees__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role/Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Attendees</label>
    <nameField>
        <displayFormat>ATD{0000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Select this for creating a customer attendee</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Calendar_Management__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Site__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Rooms</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Select_Site__c</field>
                <operation>equals</operation>
                <valueField>$Source.Site__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Calendar Management</relationshipLabel>
        <relationshipName>Calendar_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Calendar Management (Site)</relationshipLabel>
        <relationshipName>Calendar_Management_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendar Management</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Calendar_Management__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar Management Record</label>
        <referenceTo>Calendar_Management__c</referenceTo>
        <relationshipLabel>Customer Engagements (Calendar Management) - RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_no_of_Customer_Attendees__c</fullName>
        <label>Estimated no. of Attendees</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Account) - RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Primary_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Contact) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of person requesting the event.  If you are the requestor, this should be your name.</inlineHelpText>
        <label>Requestor Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Engagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements (Site) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <recordTypes>
        <fullName>EBC</fullName>
        <active>true</active>
        <description>Use this record type for: Customer Briefing, Field Briefing, Meeting and Tour. Formerly Executive Strategy and Relationship Development</description>
        <label>Executive Briefing Center</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Room_Occupancy__c</fullName>
        <label>Room Occupancy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Select_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Rooms&amp;Tours</relationshipLabel>
        <relationshipName>Select_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <recordTypes>
        <fullName>Rooms</fullName>
        <active>true</active>
        <description>Select this for creating a new room</description>
        <label>Rooms</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <description>Select this for creating a new site</description>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Topic_Experts__c.object
<CustomObject>
    <description>BOLT &amp; GSL project for managing Presenter/Architect profiles</description>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Topic Experts</relationshipLabel>
        <relationshipName>Presenters_Architects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Topic Experts</label>
    <nameField>
        <displayFormat>TE-{0000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topic Experts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestBoltPresenterInvite.cls
/***********************************************************************************************************************
* Name          : TestBoltPresenterInvite 
* Description   : Test class for VFCntrlr_BoltPresenterInvite
* ---------------------------------------------------------
* Revision  Name        Date            Description
* 1.0       Sandhya     16.06.2011      CR 6382 -Change the subject line and email template for EBC/DSC Presenter invite.
*************************************************************************************************************************/
@isTest
private class TestBoltPresenterInvite {    

    static testMethod void TestBoltPresenterInviteTest() {        
        Account newaccount= new Account(Name= 'Test Account');        
        insert newaccount;            
        Contact con= new Contact(FirstName='ContactExcSafeWord1', LastName='ContactExcSafeWord1', AccountId=newaccount.Id,Phone='11111', Decision_Making_Role__c='Influencer', Job_Function__c='IT',Purchaser_Influence_over_Merged__c='Client-Desktops' );        
        insert con;       
         
        Id rtSite=IdLookupUtils.getRecordTypeId('Sites','Event_Location__c',true);          
        Event_Location__c testSite=new Event_Location__c(Name='testSite',Region__c='Americas',Active__c=true,recordTypeId=rtSite);        
        insert testSite;                
        
        Id rt=IdLookupUtils.getRecordTypeId('Rooms','Event_Location__c',true);        
        Event_Location__c testRoom=new Event_Location__c(Name='testRoom',Room_Occupancy__c='15',Select_Site__c=testSite.Id,recordTypeId=rt);        
        insert testRoom;                
        
        Id calrt=IdLookupUtils.getRecordTypeId('Primary Calendar RT','Calendar_Management__c',true);        
        Calendar_Management__c newCal=new Calendar_Management__c(Room__c=testRoom.Id,Site__c=testSite.Id,Date__c=System.today()+30,Start_Date__c =System.today()+30,End_Date__c =System.today()+30, Status__c='Pending');        
        insert newCal;                
        
        User testUser=[SELECT id FROM USER WHERE Isactive=true limit 1];                
        
        /* CR 6382 -Change the subject line and email template for EBC/DSC Presenter invite. */        
        Customer_Engagement__c testCE1 = new Customer_Engagement__c(Name = 'Mytest CE7',Requestor_Name__c = testUser.Id,
        Estimated_no_of_Customer_Attendees__c = 11,Primary_Account__c=newaccount.Id,Primary_Contact__c=con.Id,NDA__c='Yes',
        Calendar_Management__c=newCal.Id,Event_Status__c='Approved',Customer_Background__c='test background',
        Top_3_Pain_Points__c='Test',Objective_of_Visit__c='Test');        
        insert testCE1;                     
        
        Id subjectRt=IdLookupUtils.getRecordTypeId('Subject','Agenda_Content__c',true);        
        Agenda_Content__c testAgendaConObj = new Agenda_Content__c(Name = 'Dell Enterprise Solutions', RecordTypeId =subjectRt);        
        insert testAgendaConObj;                
        
        Id topicRt=IdLookupUtils.getRecordTypeId('Topic','Agenda_Content__c',true);               
        Agenda_Content__c testAgendaConObj2 = new Agenda_Content__c(Name = 'Test Blade Server Technology',Select_Subject__c = testAgendaConObj.Id,        
        Duration_minutes__c = 45,Engagement_Type__c = 'EBC',Event_Type__c = 'Design Sessions', RecordTypeId=topicRt);        
        insert testAgendaConObj2;                
        
        Agenda_Content__c testAgendaConObj1 = new Agenda_Content__c(Name = 'Blade Server Technology',Select_Subject__c = testAgendaConObj.Id,        
        Duration_minutes__c = 45,Engagement_Type__c = 'EBC',Event_Type__c = 'Design Sessions', RecordTypeId=topicRt);        
        insert testAgendaConObj1;                
        
        Id atopicRt=IdLookupUtils.getRecordTypeId('Agenda Topic','Agenda_Topic__c',true); //RecordTypeId=atopicRt,        
        Agenda_Topic__c testAgendaTopicObj = new Agenda_Topic__c(Name = 'Blade Server Technology', AE_Notes__c = 'AE Notes',Duration__c=45,                                            
        Topics__c=testAgendaConObj1.Id,Customer_Engagement__c = testCE1.Id,  Start_Date__c= system.today()+30);        
        insert testAgendaTopicObj;                
        
        Agenda_Topic__c testAgendaTopicObj2 = new Agenda_Topic__c(Name = 'Test Blade Server Technology', AE_Notes__c = 'AE Notes',        
        Customer_Engagement__c = testCE1.Id, RecordTypeId=atopicRt, Starting_Time__c='12:45PM', Ending_Time__c='01:45PM', Start_Date__c= system.today()+30);        
        insert testAgendaTopicObj2;                
        
        List<Attendees__c>attendeeList=new List<Attendees__c>();        
        Id topicExpertRt=IdLookupUtils.getRecordTypeId('Internal Topic Expert','Topic_Experts__c',true);                
        
        Topic_Experts__c tExpert= new Topic_Experts__c(RecordTypeId=topicExpertRt,Type__c='Presenter',Presenter_Architect_Name__c=testUser.Id);        
        insert tExpert;        
        Id tExpertRt=IdLookupUtils.getRecordTypeId('Topic Expert','Attendees__c',true);        
        
        Attendees__c newAtnd = new Attendees__c(RecordTypeId=tExpertRt, Customer_Engagement__c=testCE1.Id, Team_Member__c=tExpert.Id, Agenda_Topic__c=testAgendaTopicObj2.Id);                
        attendeeList.add(newAtnd);                 
        
        Id accountTeamRt=IdLookupUtils.getRecordTypeId('Account Team','Attendees__c',true);                
        Attendees__c newAccAtnd = new Attendees__c(RecordTypeId=accountTeamRt, Account_Team__c= testUser.Id, Customer_Engagement__c=testCE1.Id,Attendee_Name__c='TestAccTeam',Role__c='Test Role',Account_name__c=newaccount.Name);                
        attendeeList.add(newAccAtnd);                                
        
        Id cusTeamRt=IdLookupUtils.getRecordTypeId('Customer','Attendees__c',true);                
        Attendees__c newCusAtnd = new Attendees__c(RecordTypeId=cusTeamRt, Customer_Engagement__c=testCE1.Id,Customer_Attendee__c= con.Id,Attendee_Name__c='TestCustomer',Role__c='Test Role',Account_name__c=newaccount.Name);                
        attendeeList.add(newCusAtnd);                                
        
        Id venTeamRt=IdLookupUtils.getRecordTypeId('Vendor/Partner','Attendees__c',true);                
        Attendees__c newVenAtnd = new Attendees__c(RecordTypeId=venTeamRt, Customer_Engagement__c=testCE1.Id,Customer_Attendee__c= con.Id,Attendee_Name__c='TestVendor',Role__c='Test Role');                
        attendeeList.add(newVenAtnd);                       
        
        Id dellIntRt=IdLookupUtils.getRecordTypeId('Dell Internal','Attendees__c',true);                
        Attendees__c newDellIntAtnd = new Attendees__c(RecordTypeId=dellIntRt, Customer_Engagement__c=testCE1.Id,Customer_Attendee__c= con.Id,Attendee_Name__c='TestDellInt',Role__c='Test Role');                
        attendeeList.add(newDellIntAtnd);        
        insert attendeeList;        
        
        PageReference pageRef = new PageReference('/apex/BoltPresenterInvite?id='+testAgendaTopicObj2.Id);        
        Test.setCurrentPage(pageRef);                
        
        Test.startTest();        
        VFCntrlr_BoltPresenterInvite controller = new VFCntrlr_BoltPresenterInvite(new ApexPages.StandardController(testAgendaTopicObj2));        
        controller.getShowInvite();        
        controller.getAttendeesToList();        
        controller.getCustomerEngagement();        
        controller.getSite();        
        controller.getAgendaTopic();        
        controller.getSpeakerStr();        
        controller.getstartDateOfEvent();        
        controller.getUserTimeZone();        
        controller.getAnalystEmail();        
        controller.getAttendeeCustomerList();        
        controller.getAttendeeCustomerList();        
        controller.getAttendeeAccTeamList();        
        controller.getAttendeeDellIntList();        
        controller.getAttendeeVendorList();        
        /* CR 6382 -Change the subject line and email template for EBC/DSC Presenter invite. */        
        controller.getattendingAccntLst();        
        controller.getinstallBaseIdList();        
        controller.getDellIntAttFlag();        
        controller.getVendorAttFlag();        
        controller.getCustomerAttFlag();        
        controller.getAccTeamAttFlag();        
        controller.getOldAttendeeFlag();        
        controller.getNoteList();        
        controller.getAttachmentList();        
        controller.getComments();        
        controller.setComments('Test');        
        controller.getMessage();        
        controller.setMessage('test');        
        controller.getBaseURL();        
        controller.getSubjectEdit();        
        controller.setSubjectEdit('Test');        
        controller.getShowMessage();                        
        
        PageReference  pageRefExpected=new PageReference('/'+testAgendaTopicObj2.Id);        
        controller.email = 'teck_kee_chin@dell.com';
        PageReference  pageRefActual=controller.sendinvite();                      
        System.assertEquals(pageRefExpected.getURL(),pageRefActual.getURL());        
        Test.stopTest();    
    }
}