profilelist1exp/unpackaged/objects/Account_Team__c.object
<CustomObject>
    <description>Custom Object To Capture Account Team Information from Affinity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Teams</relationshipLabel>
        <relationshipName>Account_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Attendees__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attendee_Name__c</fullName>
        <label>Attendee Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role/Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Attendees</label>
    <nameField>
        <displayFormat>ATD{0000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Select this for creating a customer attendee</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Attending_Accounts__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements – RETIRED</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipName>CE_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attending Accounts</label>
    <nameField>
        <displayFormat>CEA{0000000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attending Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <recordTypes>
        <fullName>EBC</fullName>
        <active>true</active>
        <description>Use this record type for: Customer Briefing, Field Briefing, Meeting and Tour. Formerly Executive Strategy and Relationship Development</description>
        <label>Executive Briefing Center</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Role__c.object
<CustomObject>
    <description>This object is to create and maintain the roles for the teams that uses geography based owner assignment process for the relationship leads and Account Plays.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AttendeeController.cls
/*************************************************************************************************************************
* Name          : AttendeeController
* Description   : Add account team attendees
* ---------------------------------------------------------
* Revision  Name        Date            Description
* 1.0       Sandhya     16.06.2011      CR 6382 -Change the subject line and email template for EBC/DSC Presenter invite.
* 2.0       Rahul       28.June-2018    Code Reduce!
**************************************************************************************************************************/

public with sharing class AttendeeController{
    public String ceRecord;
    public List<AccountTeamMember> teamMemberList = new List<AccountTeamMember>();
    public List<TeamDetails> teamDetail = new List<TeamDetails>();
    public List<Attendees__c> newAttendeeList = new List<Attendees__c>();
    public List<SelectOption> options = new List<SelectOption>();
    public Boolean listSizeNotZero = False;
    public Boolean errorForNoAccountTeam = False;
    public String accountName;
 
    /*CR 6372 : Search function for Customer and account team attendees*/
    public String accntTMember {get; set;}
    public List<Id> acctTeamIds = new List<Id>();
    public Boolean searchErrorForNoAccountTeam = False;
    public Boolean searchListSizeNotZero = False;

    public AttendeeController(ApexPages.StandardController controller) {
        ceRecord = ApexPages.currentPage().getParameters().get('CEId');
    }
      
    public class TeamDetails{
        public Boolean selected{get;set;}
        public AccountTeamMember acc{get;set;}
        public TeamDetails(AccountTeamMember accnt){
           acc = accnt; 
           selected = false;
        }
    }
  
    public void setaccountName(String accountName){   
        this.accountName = accountName;    
    }
   
    public String getaccountName(){ 
        return accountName;
    }
    
    public List<SelectOption> getaccountNames() {
        try{ 
            options.clear(); 
            
            for (Attending_Accounts__c account : [select Account__c, Account__r.Name, Name,Customer_Engagement__c from Attending_Accounts__c where Customer_Engagement__c=:ceRecord]){
                options.add(new SelectOption(account.Account__r.Name, account.Account__r.Name));
            } 
        }
        catch(Exception e){
            PageUtils.addError('Exception Occured while listing account team');
        }
        return options;
    }
    
    public Boolean getlistSizeNotZero() {
        return listSizeNotZero;
    }
    
    public Boolean geterrorfornoaccountteam() {
        return errorfornoaccountteam;
    }
     
    public PageReference Next() {
         teamDetail.clear();
         //List<Id> acctTeamIds = new List<Id>();    //CR 6372
         try{
             for(Attendees__c atnd :  [select Account_Team__c from Attendees__c where Customer_Engagement__c=:ceRecord]){
                 acctTeamIds.add(atnd.Account_Team__c);
             }
             
             teamMemberList = [select UserId, AccountId,User.Name, TeamMemberRole From AccountTeamMember where Account.Name=:accountName and UserId NOT IN :acctTeamIds];        
             if(teamDetail == null){
                 teamDetail = new List<TeamDetails>();
             }
             for(AccountTeamMember acc : teamMemberList){
                  teamDetail.add(new TeamDetails(acc));
             }
             if(teamDetail.size() >0){
                  errorForNoAccountTeam = FALSE;
                  listSizeNotZero = TRUE;
                  //CR 6372
                  searchListSizeNotZero = true;
                  searchErrorForNoAccountTeam = false;                              
             }
             else{
                  errorForNoAccountTeam = TRUE;
                  listSizeNotZero = False; 
                  //CR 6372
                  searchListSizeNotZero = false; 
                  searchErrorForNoAccountTeam = false;                   
             }
         }
         catch(Exception e){
            PageUtils.addError('Exception Occured while retreiving attendee List');
         }
         return NULL;
    }
 
    /*CR 6372 : Search function for Customer and account team attendees : Start*/
    public PageReference Search() {
         teamDetail.clear();

         try{
             for(Attendees__c atnd :  [select Account_Team__c from Attendees__c where Customer_Engagement__c=:ceRecord]){
                 acctTeamIds.add(atnd.Account_Team__c);
             }

             string teamMemberquery = 'select UserId, AccountId,User.Name, TeamMemberRole  From AccountTeamMember where Account.Name=:accountName and UserId NOT IN :acctTeamIds';
                teamMemberquery = teamMemberquery + ' and ' + 'User.Name like ' + '\'%' + accntTMember + '%\'' ;
       
              teamMemberList = Database.query(teamMemberquery);
              
             if(teamDetail == null){
                 teamDetail = new List<TeamDetails>();
             }
             for(AccountTeamMember acc : teamMemberList){
                  teamDetail.add(new TeamDetails(acc));
             }
             if(teamDetail.size() >0){
                  searchErrorForNoAccountTeam = FALSE;
                  listSizeNotZero = TRUE;
                  searchListSizeNotZero = true;          
             }
             else{
                  searchErrorForNoAccountTeam = TRUE;
                  listSizeNotZero = true; 
                  searchListSizeNotZero = false;
             }
         }
         catch(Exception e){
            PageUtils.addError('Exception Occured while retreiving attendee List');
         }    
        return null;
    }
    /*CR 6372 : Search function for Customer and account team attendees : End*/
        
    public List<TeamDetails> getAccountTeamMember() {
         return teamDetail;        
    }
    
    public void setAccountTeamMember(List<AccountTeamMember> newteamMemberList){
         teamMemberList = newTeamMemberList;
    }
    
    public PageReference Save(){
         try{
             Id rtList=IdLookupUtils.getRecordTypeId('Account Team','Attendees__c',true);
             for (TeamDetails team : teamDetail ){
                if (team.selected == TRUE) {
                    /* CR 6382 -Change the subject line and email template for EBC/DSC Presenter invite. */
                    Attendees__c attendeeList = new Attendees__c(Attendee_Name__c=team.acc.User.Name,RecordTypeId= rtList,
                                                Account_Team__c=team.acc.UserId,Role__c=team.acc.TeamMemberRole, 
                                                Customer_Engagement__c=ceRecord,Account_Name__c=accountName);
                    newAttendeeList.add(attendeeList);
                }
             }
             if(newAttendeeList.size()>0){
                 insert newAttendeeList;
             }
         }
         catch(Exception e){
            PageUtils.addError('Exception Occured while saving the record');
         }
         return PageUtils.redirect('/'+ceRecord);
    }
    
    public PageReference Cancel(){
        return PageUtils.redirect('/'+ceRecord);
    }
    
    /*CR 6372 : Search function for Customer and account team attendees*/   
    public Boolean getsearcherrorfornoaccountteam() {
        return searcherrorfornoaccountteam;    
    }
    public Boolean getsearchListSizeNotZero() {
        return searchListSizeNotZero;    
    }       
}