profilelist1exp/unpackaged/objects/Account_Play__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plays</relationshipLabel>
        <relationshipName>Sales_Plays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Campaign_Vehicle__c</fullName>
        <label>Campaign Vehicle(Not In Use)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advisory Councils</fullName>
                    <color>#0B6FCE</color>
                    <label>Advisory Councils</label>
                </value>
                <value>
                    <fullName>Assessment (HW/Services)</fullName>
                    <color>#78C953</color>
                    <label>Assessment (HW/Services)</label>
                </value>
                <value>
                    <fullName>CXO Events</fullName>
                    <color>#E27001</color>
                    <label>CXO Events</label>
                </value>
                <value>
                    <fullName>Dell Day</fullName>
                    <color>#A845DC</color>
                    <label>Dell Day</label>
                </value>
                <value>
                    <fullName>DM</fullName>
                    <color>#F3D904</color>
                    <label>DM</label>
                </value>
                <value>
                    <fullName>Door Opener (High Value)</fullName>
                    <color>#A53711</color>
                    <label>Door Opener (High Value)</label>
                </value>
                <value>
                    <fullName>Door Opener (Value)</fullName>
                    <color>#66E9BD</color>
                    <label>Door Opener (Value)</label>
                </value>
                <value>
                    <fullName>eDM/Email</fullName>
                    <color>#0B24BE</color>
                    <label>eDM/Email</label>
                </value>
                <value>
                    <fullName>eSeminar/Webcast/Webinar</fullName>
                    <color>#419249</color>
                    <label>eSeminar/Webcast/Webinar</label>
                </value>
                <value>
                    <fullName>Lattice Sales Touch</fullName>
                    <color>#FFFF66</color>
                    <label>Lattice Sales Touch</label>
                </value>
                <value>
                    <fullName>Multiple Vehicles</fullName>
                    <color>#B6E32E</color>
                    <label>Multiple Vehicles</label>
                </value>
                <value>
                    <fullName>Non-Marketing</fullName>
                    <color>#000000</color>
                    <label>Non-Marketing</label>
                </value>
                <value>
                    <fullName>Online Advertising</fullName>
                    <color>#641CCF</color>
                    <label>Online Advertising</label>
                </value>
                <value>
                    <fullName>Online Inbound</fullName>
                    <color>#F96FB7</color>
                    <label>Online Inbound</label>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                    <color>#2F5D85</color>
                    <label>Roadshow</label>
                </value>
                <value>
                    <fullName>Sales Touch</fullName>
                    <color>#AFCADF</color>
                    <label>Sales Touch</label>
                </value>
                <value>
                    <fullName>Seed Unit</fullName>
                    <color>#8F6429</color>
                    <label>Seed Unit</label>
                </value>
                <value>
                    <fullName>Seminar/Conference</fullName>
                    <color>#EFAE73</color>
                    <label>Seminar/Conference</label>
                </value>
                <value>
                    <fullName>Special Events</fullName>
                    <color>#57F17C</color>
                    <label>Special Events</label>
                </value>
                <value>
                    <fullName>Standalone Telemarketing</fullName>
                    <color>#0B6FCE</color>
                    <label>Standalone Telemarketing</label>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                    <color>#78C953</color>
                    <label>Trade Show</label>
                </value>
                <value>
                    <fullName>Workshop</fullName>
                    <color>#E27001</color>
                    <label>Workshop</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lattice_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lattice - IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lattice_Pre_Lead_External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Lattice - Pre Lead External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Sales_Plays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#0B6FCE</color>
                    <label>Accepted</label>
                </value>
                <value>
                    <fullName>Accepted By Sales</fullName>
                    <color>#78C953</color>
                    <label>Accepted By Sales</label>
                </value>
                <value>
                    <fullName>Accepted - Completed Follow-Up</fullName>
                    <color>#E27001</color>
                    <label>Accepted - Completed Follow-Up</label>
                </value>
                <value>
                    <fullName>Assign to Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Attempted to Contact - Awaiting Response</fullName>
                    <color>#F3D904</color>
                    <label>Attempted to Contact - Awaiting Response</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                    <color>#A845DC</color>
                    <label>Attended</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                    <color>#A53711</color>
                    <label>Bounced</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#66E9BD</color>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Clicked</fullName>
                    <color>#0B24BE</color>
                    <label>Clicked</label>
                </value>
                <value>
                    <fullName>Closed - Expired</fullName>
                    <color>#419249</color>
                    <label>Closed - Expired</label>
                </value>
                <value>
                    <fullName>Completed Follow-Up</fullName>
                    <color>#B6E32E</color>
                    <label>Completed Follow-Up</label>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                    <color>#641CCF</color>
                    <label>Contacted</label>
                </value>
                <value>
                    <fullName>Existing Opportunity</fullName>
                    <color>#F96FB7</color>
                    <label>Existing Opportunity</label>
                </value>
                <value>
                    <fullName>Existing Opportunity or Quoted</fullName>
                </value>
                <value>
                    <fullName>General comment</fullName>
                    <color>#AFCADF</color>
                    <label>General comment</label>
                </value>
                <value>
                    <fullName>Identified</fullName>
                    <color>#8F6429</color>
                    <label>Identified</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <color>#EFAE73</color>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#57F17C</color>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Invited</fullName>
                    <color>#0B6FCE</color>
                    <label>Invited</label>
                </value>
                <value>
                    <fullName>New Opportunity</fullName>
                    <color>#78C953</color>
                    <label>New Opportunity</label>
                </value>
                <value>
                    <fullName>Nominated</fullName>
                    <color>#E27001</color>
                    <label>Nominated</label>
                </value>
                <value>
                    <fullName>Nomination Rejected by Marketing</fullName>
                    <color>#A845DC</color>
                    <label>Nomination Rejected by Marketing</label>
                </value>
                <value>
                    <fullName>Nomination Rejected by Sales</fullName>
                    <color>#F3D904</color>
                    <label>Nomination Rejected by Sales</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                    <color>#A53711</color>
                    <label>Not Interested</label>
                </value>
                <value>
                    <fullName>Offered</fullName>
                    <color>#66E9BD</color>
                    <label>Offered</label>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <color>#0B24BE</color>
                    <label>Opened</label>
                </value>
                <value>
                    <fullName>Opportunity not Created</fullName>
                    <color>#419249</color>
                    <label>Opportunity not Created</label>
                </value>
                <value>
                    <fullName>Opportunity not Linked</fullName>
                    <color>#B6E32E</color>
                    <label>Opportunity not Linked</label>
                </value>
                <value>
                    <fullName>Profiled customer</fullName>
                    <color>#641CCF</color>
                    <label>Profiled customer</label>
                </value>
                <value>
                    <fullName>Purchasing Plans identified</fullName>
                    <color>#F96FB7</color>
                    <label>Purchasing Plans identified</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Play</label>
    <nameField>
        <displayFormat>AP - {000000000}</displayFormat>
        <label>Account Play #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plays</pluralLabel>
    <recordTypes>
        <fullName>Lattice</fullName>
        <active>true</active>
        <label>Lattice</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Opportunity_Account_Play_Association__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Account Play Associations</relationshipLabel>
        <relationshipName>Opportunity_Account_Play_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>preLead_External_Id__c</fullName>
        <label>preLead External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Account Play Association</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Opportunity Account Play Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Account Play Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LatticeOpportunityAPAssociationTest.cls
@isTest

private class LatticeOpportunityAPAssociationTest{
    static Account accountData;
    static Opportunity opportunityData;
    static Account_Play__c accountPlayData;
    
     static void CreateTestData() {

        accountData = new Account(Name='Test Account',
                                  Account_id__c='affinityID'    );
        insert accountData;
        opportunityData=new Opportunity(Name='oppToTest',
                                        RecordTypeId=PageUtils.getRecordTypeId('Opportunity', 'Standard Opportunity', true),
                                        Domain__c='IDM',
                                        AccountId=accountData.Id,
                                        CloseDate=System.Today(),
                                        Type='Design',
                                        Solution_Type__c='Storage',
                                        Solution_Name__c='Compellent',
                                        StageName='Plan - 1%',
                                        Marketing_Created_Opportunity__c = true,
                                        Lattice_PreLead_External_id__c='aaaa');
        accountPlayData=new Account_Play__c(Account__c=accountData.Id,
                                            RecordTypeId=PageUtils.getRecordTypeId('Account_Play__c', 'Lattice', true),
                                            Campaign_Vehicle__c='Multiple Vehicles',
                                            Lattice_IsActive__c=true,
                                            Lattice_Pre_Lead_External_ID__c='aaaa',
                                            Status__c='Existing Opportunity');
        
        insert accountPlayData;
        System.debug('-----------INSERTED AP--------------');
        insert opportunityData;
    }
    
    //testMethod to test association of Opportunity with existing AccountPlay
    static testMethod void testOpportunityWithExistingAP() {
        Test.startTest();       
        CreateTestData();
        Opportunity opp = [SELECT id,Lattice_Source_Id__c from Opportunity WHERE id = :opportunityData.id];
        System.assertEquals(opp .Lattice_Source_Id__c,accountPlayData.id);
        Test.stopTest();   
    }
    
    //testMethod to test association of Opportunity with a non existing AccountPlay
    static testMethod void testOpportunityWithoutExistingAP() {
        Test.startTest(); 
        if(accountData ==null)    {
            accountData = new Account(Name='Test Account',
                                      Account_id__c='affinityID');
            insert  accountData;  
         }
            
         Opportunity opportunityData1= new Opportunity(Name='oppToTest1',
                                        RecordTypeId= PageUtils.getRecordTypeId('Opportunity', 'Standard Opportunity', false),
                                        Domain__c='IDM',
                                        CloseDate=System.Today(),
                                        Type='Design',
                                        Solution_Type__c='Business Processing',
                                        StageName='Plan - 1%',
                                        Marketing_Created_Opportunity__c = true,
                                        AccountId=accountData.Id,
                                        Lattice_PreLead_External_id__c='bbbb');
        insert opportunityData1;
        List<Opportunity_Account_Play_Association__c> assocList=[select Opportunity__c,preLead_External_Id__c from Opportunity_Account_Play_Association__c where preLead_External_Id__c='bbbb'];
        system.assert(assocList.size()>0);
        for(Opportunity_Account_Play_Association__c assoc:assocList){
            System.assertEquals(assoc.Opportunity__c, opportunityData1.id);

        }
        Account_Play__c accountPlayData1=new Account_Play__c(Account__c=accountData.Id,
                                            RecordTypeId=PageUtils.getRecordTypeId('Account_Play__c', 'Lattice', false),
                                            Campaign_Vehicle__c='Multiple Vehicles',
                                            Lattice_IsActive__c=true,
                                            Lattice_Pre_Lead_External_ID__c='bbbb',
                                            Status__c='Existing Opportunity');
        
        insert accountPlayData1;
        Test.stopTest();   
        List<Account_Play__c> accplayupd = [SELECT id, Opportunity__c FROM Account_Play__c WHERE id =:accountPlayData1.id];
        System.assertEquals(accplayupd[0].Opportunity__c , opportunityData1.id);
    }
    
    //testMethod to test association of Opportunities with existing AccountPlay
    static testMethod void testOpportunitysWithExistingAP() {
        Test.startTest();       
        CreateTestData();
        /*Opportunity opportunityData1= new Opportunity(Name='oppToTest1',
                                        RecordTypeId= PageUtils.getRecordTypeId('Opportunity', 'Standard Opportunity', false),
                                        Domain__c='IDM',
                                        CloseDate=System.Today(),
                                        Type='Design',
                                        Solution_Type__c='Business Processing',
                                        StageName='Plan - 1%',
                                        Marketing_Created_Opportunity__c = true,
                                        AccountId=accountData.Id,
                                        Lattice_PreLead_External_id__c='bbbb');
        insert opportunityData1;
        */
        //Intoducing time delay
        for(Integer cnt=0;cnt<100000;cnt++){
        }
        Opportunity opportunityData2= new Opportunity(Name='oppToTest2',
                                        RecordTypeId= PageUtils.getRecordTypeId('Opportunity', 'Standard Opportunity', false),
                                        Domain__c='IDM',
                                        CloseDate=System.Today(),
                                        Type='Design',
                                        Solution_Type__c='Business Processing',
                                        StageName='Plan - 1%',
                                        Marketing_Created_Opportunity__c = true,
                                        AccountId=accountData.Id,
                                        Lattice_PreLead_External_id__c='bbbb');
        insert opportunityData2;
        Account_Play__c accountPlayData1=new Account_Play__c(Account__c=accountData.Id,
                                            RecordTypeId=PageUtils.getRecordTypeId('Account_Play__c', 'Lattice', false),
                                            Campaign_Vehicle__c='Multiple Vehicles',
                                            Lattice_IsActive__c=true,
                                            Lattice_Pre_Lead_External_ID__c='bbbb',
                                            Status__c='Existing Opportunity');
        
        insert accountPlayData1;
        
        List<Account_Play__c> accplayupd = [SELECT id, Opportunity__c FROM Account_Play__c WHERE id =:accountPlayData1.id];
        //System.assertEquals(accplayupd[0].Opportunity__c , opportunityData2.id);
        Test.stopTest();  
    }               
}