profilelist1exp/unpackaged/objects/Agenda_Content__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Break_Type__c</fullName>
        <label>Break Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DSC</fullName>
                    <default>true</default>
                    <label>DSC</label>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agenda Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Content</pluralLabel>
    <recordTypes>
        <fullName>Breaks</fullName>
        <active>true</active>
        <description>Select this for creating a new break</description>
        <label>Breaks</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Attending_Accounts__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipName>CE_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attending Accounts</label>
    <nameField>
        <displayFormat>CEA{0000000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attending Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Account) - RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <recordTypes>
        <fullName>EBC</fullName>
        <active>true</active>
        <description>Use this record type for: Customer Briefing, Field Briefing, Meeting and Tour. Formerly Executive Strategy and Relationship Development</description>
        <label>Executive Briefing Center</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VfController_AddCateringBreakTest.cls
@isTest
private class VfController_AddCateringBreakTest{
 static list<Opportunity> listOpp;
 static list<Account> listAcc;
 static Customer_Engagement__c testCE = new Customer_Engagement__c();
    //Account newaccount;// = new Account();
    static Opportunity newOpportunity = new Opportunity();
    static  Attending_Accounts__c newAttendingAccounts = new Attending_Accounts__c();
    static Agenda_Content__c agCon = new Agenda_Content__c();
    static List<Agenda_Content__c> listsc = new List<Agenda_Content__c >();
    static List <CateringBreakWrapper> listcb =  new List<CateringBreakWrapper> ();
    static List <Event_Location__c> listel = new List<Event_Location__c> ();
    public static void createData(){
/*        RecordType OpportunityRt = [Select Name, Id 
                                   From RecordType
                                   where sObjectType='Opportunity' and name='Run Rate Opportunity' limit 1]; */
         RecordType ceRt = [Select Name, Id 
                                   From RecordType
                                   where sObjectType='Customer_Engagement__c' and name='Dell Solution Centers' limit 1];

       //Account newaccount =new Account(Name='Test Account');
       // insert newaccount;
		listAcc = TestDataFactory.createNAccount(1, 'Master Account');
        insert listAcc;
        system.assertEquals(listAcc, listAcc);
        testCE.Name = 'Mytest CE';
        testCE.Primary_Account__c = listAcc[0].Id;
        testCE.RecordTypeId =ceRt.id;
        insert testCE;
        list<Opportunity> listOpp = TestDataFactory.createNOpportunities(1, 'Standard Opportunity');
        listOpp[0].AccountId = newAttendingAccounts.Id;
        insert listOpp;
		/*
        newOpportunity.RecordTypeId = acRecTypeId;
        newOpportunity.Name = 'Test Opportunity';
        newOpportunity.AccountId = newAttendingAccounts.Id;
        newOpportunity.StageName = 'testStage';
        newOpportunity.CloseDate = System.Today();
        insert newOpportunity; 
        */ 
        newAttendingAccounts.Customer_Engagement__c = testCE.Id;
        insert newAttendingAccounts;        
     
     
      
   List<RecordType> listrecTypCE = [Select r.Id, r.Name from RecordType r Where Id =: testCE.RecordTypeId  and IsActive=true]; 
    
    string strrecTypeName = listrecTypCE.get(0).Name == 'Dell Solution Centers' ? 'DSC' : 'EBC';
    system.debug('##### The record Type Name is  ' + strrecTypeName);
    List<RecordType> listrecTypBreak = [Select r.Id, r.Name, r.SobjectType from RecordType r Where SobjectType='Agenda_Content__c' and Name = 'Breaks' And IsActive=true];
    string strbreakRecType = listrecTypBreak.get(0).Id;
      
        agCon.Name='www';
        agCon.Break_Type__c = 'Catering';
        agCon.Active__c = true;
        agCon.RecordTypeId = strbreakRecType;
        agCon.Engagement_Type__c = strrecTypeName;
        insert agCon;
     
    }

public static testMethod void testMyController() {
        //Skip all triggers
        TriggerExecutionController.setSkipAllTriggers(true);
        createData ();
        //Revert back the skip all triggers
        TriggerExecutionController.setSkipAllTriggers(false);
        PageReference pageRef = new PageReference ('/apex/AddCateringBreak?id='+testCE.id);
        Test.setCurrentPage(pageRef);
        system.assertEquals(testCE.id, testCE.id);
        VfController_AddCateringBreak testObject = new VfController_AddCateringBreak();
        testObject.addCateringBreaks();
        List<CateringBreakWrapper> listcw=testObject.getAgendaContent() ;        
        listcw[0].isChecked=True;
        
        PageReference pr=testObject.addCateringBreaks();
        testObject.getAddCateringBreaks();
        
        PageReference pr1=testObject.backToCE() ;
               
}
}