profilelist1exp/unpackaged/objects/Agenda__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipLabel>Agendas</relationshipLabel>
        <relationshipName>Agendas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <formula>TEXT(Customer_Engagement__r.Event_Type__c)</formula>
        <label>Event Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>DATEVALUE( Start_Date_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Agenda</label>
    <nameField>
        <displayFormat>AG-{0000000000}</displayFormat>
        <label>Agenda Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <inlineHelpText>16 Characters Required for this Field.  No Spaces.

Format:  XXXX-XXXX-XXXXXX</inlineHelpText>
        <label>Cost Center</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dell_Solution_Center_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Solution Center names:
Americas: Austin, Chicago, New York, Sao Paulo, Santa Clara, Washington D.C.
APJ: Shanghai, Singapore, Sydney, Tokyo
EMEA: Bracknell, Frankfurt, Limerick, Paris
For more information please go to http://dsc.dell.com</inlineHelpText>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Engagement_Type__c</field>
                <operation>equals</operation>
                <value>DSC</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements (Dell Solution Center Site) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_no_of_Customer_Attendees__c</fullName>
        <label>Estimated no. of Attendees</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scoping</fullName>
                </value>
                <value>
                    <fullName>SoW Delivered</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Site</fullName>
                </value>
                <value>
                    <fullName>Executed by EMC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Type of Customer Engagement event</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Architectural Design Session</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Analyst Events</fullName>
                </value>
                <value>
                    <fullName>Field Briefing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GSL_End_Date__c</fullName>
        <label>Preferred End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GSL_Start_Date__c</fullName>
        <inlineHelpText>This date is not guaranteed. Date of visit will be agreed with DSC team during the evaluation process, depending on availability of all resources to meet your requirements.</inlineHelpText>
        <label>Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NDA__c</fullName>
        <inlineHelpText>Specify if the Customer NDA is available. 

It is the account team’s responsibility to ensure the customer’s NDA is in place prior to their visit.</inlineHelpText>
        <label>NDA?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Account) - RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Primary_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Contact) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of person requesting the event.  If you are the requestor, this should be your name.</inlineHelpText>
        <label>Requestor Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Engagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Compliant__c</fullName>
        <inlineHelpText>Specify if the Customer is Trade Compliant.
 
It is the account team’s responsibility to ensure that the customer is Trade Compliant prior to their visit.</inlineHelpText>
        <label>Trade Compliant?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Catering__c</fullName>
        <inlineHelpText>If yes, you will see catering options when you build your agenda and you can print catering reports for your site.</inlineHelpText>
        <label>Offer Catering?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Transportation__c</fullName>
        <inlineHelpText>If yes, Account Execs will see a transportation area where they can specify pick up and drop off times. You will also see transportation options in the build agenda screen</inlineHelpText>
        <label>Offer Transportation?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <description>Select this for creating a new site</description>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Transportation__c.object
<CustomObject>
    <description>BOLT &amp; GSL Project - object for managing transportation details</description>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Engagement</label>
        <referenceTo>Customer_Engagement__c</referenceTo>
        <relationshipLabel>Transportation</relationshipLabel>
        <relationshipName>Transportation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Type__c</fullName>
        <label>Travel Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flight arrival</fullName>
                </value>
                <value>
                    <fullName>Flight departure</fullName>
                </value>
                <value>
                    <fullName>Dinner</fullName>
                </value>
                <value>
                    <fullName>Day of briefing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transportation</label>
    <nameField>
        <label>Transportation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/TestAfterinsertupdateTravel.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAfterinsertupdateTravel {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Account newaccount= new Account(Name= 'Test Account');
        insert newaccount;    
        Contact con= new Contact(FirstName='ContactExcSafeWord1', LastName='ContactExcSafeWord1', AccountId=newaccount.Id,Phone='11111', Decision_Making_Role__c='Influencer', Job_Function__c='IT',Purchaser_Influence_over_Merged__c='Client-Desktops' );
        insert con;
        User testUser=[SELECT id FROM USER WHERE Isactive=true limit 1];
        Id rtSite=IdLookupUtils.getRecordTypeId('Sites','Event_Location__c',true);
        Event_Location__c testSite=new Event_Location__c(Name='testSite',Region__c='Americas',
                                                   Active__c=true,Engagement_Type__c='DSC',
                                                   Offer_Catering__c='No',Offer_Transportation__c='Yes',
                                                   Email__c='test_user@dell.com',
                                                   recordTypeid=rtSite);
        insert testSite;
        Customer_Engagement__c testCE1 = new Customer_Engagement__c(Name = 'Mytest CE1',Event_Type__c='Solution Briefings',Event_Status__c = 'Canceled',Cost_Center__c='1234-1234-123456',Dell_Solution_Center_Site__c=testSite.Id,Trade_Compliant__c='Yes' ,Requestor_Name__c = testUser.Id, GSL_Start_Date__c=system.Today(),GSL_End_Date__c = system.Today(),Estimated_no_of_Customer_Attendees__c = 11,Primary_Account__c=newaccount.Id,Primary_Contact__c=con.Id,NDA__c='Yes');
        insert testCE1;
        
        Transportation__c newtrans= new Transportation__c(Name='New Transportation', Travel_Type__c='Flight arrival',Start_Date__c= system.Today(), Customer_Engagement__c=testCE1.Id);
        Transportation__c newtranspt= new Transportation__c(Name='Trans for update', Travel_Type__c='Flight arrival',Start_Date__c= system.Today(), Customer_Engagement__c=testCE1.Id);
        insert newtranspt;
        newtranspt.Starting_Time__c='12.00AM';
        newtranspt.Ending_Time__c='12.30AM';
        
        Transportation__c transwithST= new Transportation__c(Name='Transportation test', Travel_Type__c='Flight arrival',Start_Date__c= system.Today(),Starting_Time__c='01.00AM', Ending_Time__c='03.00AM', Customer_Engagement__c=testCE1.Id);
        Transportation__c updtranswithST= new Transportation__c(Name='New Transportations',Travel_Type__c='Flight arrival', Starting_Time__c='01.00AM', Start_Date__c= system.Today(),Ending_Time__c='03.00AM');
        insert updtranswithST;
        Transportation__c trans= new Transportation__c(Name='New Transportatn', Travel_Type__c='Flight arrival',Starting_Time__c='01.00AM', Ending_Time__c='03.00AM', Customer_Engagement__c=testCE1.Id);
        Transportation__c updTrans= new Transportation__c(Name='Update Transportation',Travel_Type__c='Flight arrival',Start_Date__c= system.Today(), Starting_Time__c='03.00AM', Ending_Time__c='04.00AM', Customer_Engagement__c=testCE1.Id);
        insert updTrans;
        insert trans;

        Transportation__c delTrans= new Transportation__c(Name='Delete Transportation', Travel_Type__c='Flight arrival',Starting_Time__c='01.00PM', Start_Date__c= system.Today(),Ending_Time__c='03.00PM', Customer_Engagement__c=testCE1.Id);
        insert delTrans;
        Transportation__c transExcemt= new Transportation__c(Name='ex Transportation', Travel_Type__c='Flight arrival',Starting_Time__c='01.30PM', Start_Date__c= system.Today(),Ending_Time__c='03.00PM', Customer_Engagement__c=testCE1.Id);
        insert transExcemt;
        updtranswithST.Starting_Time__c='03.30AM';
        updtranswithST.Ending_Time__c='04.30AM';
        
        transExcemt.Starting_Time__c = 'abcd';
        
        Test.startTest();
        insert newTrans;
        update newtranspt;
        insert transwithST;
        update updtranswithST;      
        update transExcemt;
        delete delTrans;
        Test.stopTest();
        
        List<Transportation__c> transObjstest = [Select Id From Transportation__c where Name = 'New Transportation' and  Customer_Engagement__c =:testCE1.Id];
        system.assertequals(transObjstest.size(),1);
        List<Agenda__c> insagendaList=[select id, Travel_Id__c from Agenda__c where Travel_Id__c = :newTrans.Id ];
        system.assertequals(insagendaList.size(),0);
                
        List<Transportation__c> transObjtest = [Select Id,Starting_Time__c,Ending_Time__c From Transportation__c where Name = 'Trans for update' and  Customer_Engagement__c =:testCE1.Id];
        system.assertequals(transObjtest.size(),1);
        for(Transportation__c tr :transObjtest){
            system.assertequals(tr.Starting_Time__c,'12.00AM');
            system.assertequals(tr.Ending_Time__c,'12.30AM');
        }
        List<Agenda__c> updagendaList=[select id, Travel_Id__c, Start_Time__c,End_Time__c from Agenda__c where Travel_Id__c = :newtranspt.Id ];
        system.assertequals(updagendaList.size(),1);
        for(Agenda__c ag : updagendaList){
            system.assertequals(ag.Start_Time__c,'12.00AM');
            system.assertequals(ag.End_Time__c,'12.30AM');
        }
        
        List<Transportation__c> insTransObjstests = [Select Id From Transportation__c where Name = 'Transportation test' and  Customer_Engagement__c =:testCE1.Id];
        system.assertequals(insTransObjstests.size(),1);
        List<Agenda__c> insagendaListWithST=[select id, Travel_Id__c from Agenda__c where Travel_Id__c = :transwithST.Id ];
        system.assertequals(insagendaListWithST.size(),1);
        
        List<Transportation__c> updTransObjtest = [Select Id,Starting_Time__c,Ending_Time__c From Transportation__c where Name = 'New Transportations' and  Customer_Engagement__c =:testCE1.Id];
        system.assertequals(updTransObjtest.size(),0);
            
        List<Agenda__c> updAgendaListWithST=[select id, Travel_Id__c,Start_Time__c,End_Time__c from Agenda__c where Travel_Id__c = :updtranswithST.Id ];
        system.assertequals(updAgendaListWithST.size(),0);
        
        
        List<Transportation__c> delTransObjstest = [Select Id From Transportation__c where Name = 'Delete Transportation' and  Customer_Engagement__c =:testCE1.Id];
        system.assertequals(delTransObjstest.size(),0);
        List<Agenda__c> delAgendaList=[select id, Travel_Id__c from Agenda__c where Travel_Id__c = :delTrans.Id ];
        system.assertequals(delAgendaList.size(),0);
    }
}