profilelist1exp/unpackaged/objects/Alliance_Rebate_Request__c.object
<CustomObject>
    <fields>
        <fullName>Business_Case_Information__c</fullName>
        <inlineHelpText>Deal significance (i.e. deal size, rationale for rebate, company background, explanation of project, future business opportunities, etc.)</inlineHelpText>
        <label>Business Case Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Enterprise__c</fullName>
        <inlineHelpText>Client as Desktop / Notebook, and Enterprise as Server, Networking, Storage</inlineHelpText>
        <label>Client / Enterprise</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                    <default>true</default>
                    <label>Client</label>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dell_Standard_CPU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dell Standard CPU</label>
        <referenceTo>Alliance_STF_Price__c</referenceTo>
        <relationshipLabel>Alliance Rebate Requests</relationshipLabel>
        <relationshipName>Alliance_Rebate_Requests_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Contact__c</fullName>
        <inlineHelpText>Enter Unknown@dell.com if you don’t know your finance contact</inlineHelpText>
        <label>Finance Contact Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner_BDM_Name__c</fullName>
        <inlineHelpText>Partner contact who will help validate the request.  Please type unknown if you need help determining who BDM is</inlineHelpText>
        <label>Partner BDM Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate_Request_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rebate Request Product</label>
        <referenceTo>Rebate_Request_Product__c</referenceTo>
        <relationshipLabel>Alliance Rebate Requests</relationshipLabel>
        <relationshipName>Alliance_Rebate_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Force_Deal_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please remember to select the &quot;All Fields&quot; option in the lookup screen to optimize the search to find the right deal</inlineHelpText>
        <label>Sales Force Deal ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance Rebate Requests</relationshipLabel>
        <relationshipName>Alliance_Rebate_Request</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Work in Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendors Response</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Partner_Name__c</fullName>
        <label>Partner Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Client_Enterprise__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intel</fullName>
                </value>
                <value>
                    <fullName>Nvidia</fullName>
                </value>
                <value>
                    <fullName>Brocade</fullName>
                </value>
                <value>
                    <fullName>Mellanox</fullName>
                </value>
                <value>
                    <fullName>Broadcom/Emulex</fullName>
                </value>
                <value>
                    <fullName>AMD</fullName>
                </value>
                <value>
                    <fullName>Microsoft</fullName>
                </value>
                <value>
                    <fullName>Qlogic/Cavium</fullName>
                </value>
                <value>
                    <fullName>Qualcomm</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Toshiba</fullName>
                </value>
                <value>
                    <fullName>Ruckus</fullName>
                </value>
                <value>
                    <fullName>Xilinx</fullName>
                </value>
                <value>
                    <fullName>BigSwitch</fullName>
                </value>
                <value>
                    <fullName>Intel Bid-Bucket</fullName>
                </value>
                <value>
                    <fullName>Aerohive</fullName>
                </value>
                <value>
                    <fullName>Sonicwall</fullName>
                    <isActive>false</isActive>
                    <label>Sonicwall</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alliance Rebate Request</label>
    <nameField>
        <displayFormat>ARR-{000000}</displayFormat>
        <label>Deal / Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance Rebate Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Alliance_STF_Price__c.object
<CustomObject>
    <fields>
        <fullName>Net_Price__c</fullName>
        <label>Net Price (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Alliance STF Price</label>
    <nameField>
        <label>Proc ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alliance STF Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Rebate_Request_Product__c.object
<CustomObject>
    <fields>
        <fullName>Alliance_Rebate_Request__c</fullName>
        <label>Alliance Rebate Request</label>
        <referenceTo>Alliance_Rebate_Request__c</referenceTo>
        <relationshipLabel>Rebate Request Products</relationshipLabel>
        <relationshipName>Rebate_Request_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dell_System_Model_type__c</fullName>
        <label>Dell System (Model, type)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Name_Part_Number__c</fullName>
        <label>Part Name &amp; Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Requested__c</fullName>
        <label>Price Requested (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rebate Request Product</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Rebate Request Prod Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RebateRequestProductTriggerTest.cls
@isTest
private class RebateRequestProductTriggerTest {

  private static testMethod void testAfterInsert() {
      profile profileId =   [select Id, Name from Profile where name like '%R16.10 GBL Sales Rep%' limit 1];
        User AllianceRebateUser = new User(Username='AllianceSalesUser' + System.currentTimeMillis() + '@dell.com',
                                           Alias = 'MTU9', 
                                           Email='AllianceUser@dell.com', 
                                           FirstName='Alliance', 
                                           LastName='Sales23',  
                                           ProfileId = profileId.id,
                                           LanguageLocaleKey='zh_CN',
                                           country = 'en_IN1',
                                           LocaleSidKey='zh_CN', 
                                           EmailEncodingKey='UTF-8', 
                                           TimeZoneSidKey='America/Los_Angeles',
                                           Badge_Number__c='Test99826513usi2', 
                                           isActive = TRUE);
        insert AllianceRebateUser;
        
          Opportunity opp = AllianceRebateRequestTrigger_Test.createOpportunityInfo('Test1sdsds@gmail.com');
        
       
         
    // Create Alliance STF Price
      
      Alliance_STF_Price__c stfPrice = new Alliance_STF_Price__c(Net_Price__c = 10,Name= '123456');
      insert stfPrice;
      
      // Create Alliance Rebate Request
      
      Alliance_Rebate_Request__c arReq = new Alliance_Rebate_Request__c();
            
            arReq.Sales_Force_Deal_ID__c = opp.id;
            arReq.System_Partner_Name__c ='Intel';
            arReq.Finance_Contact__c = 'xxx@dell.com';
            arReq.Business_Case_Information__c = 'test';
            arReq.Dell_Standard_CPU__c  =stfPrice.id;
            arReq.Partner_BDM_Name__c='test';
            insert arReq ;
      
        // Create Rebate request product
     
   
            
         Rebate_Request_Product__c productObj = new Rebate_Request_Product__c();
         productObj.Quantity__c=2;
         productObj.Part_Name_Part_Number__c='test';
         productObj.Dell_System_Model_type__c='testing';
         productObj.Alliance_Rebate_Request__c= arReq.id;
         
         insert productObj ;
       
        
  }
  
  private static testMethod void testAfterUpdate() {
      Account acc = new Account(name='Account');
      insert acc;
      TriggerExecutionController.setSkipAllTriggers(True);
     Opportunity opp1 = AllianceRebateRequestTrigger_Test.createOpportunityInfo('Test1sdsds@gmail.com');
                                        
    Alliance_STF_Price__c stfPrice1 = new Alliance_STF_Price__c(Net_Price__c = 10,Name= '123456');
      insert stfPrice1 ;
      
        list<Alliance_Rebate_Request__c> allianceReabteRequests = new list<Alliance_Rebate_Request__c>();
        for(integer i=0;i<1;i++){
            allianceReabteRequests.add(new Alliance_Rebate_Request__c(System_Partner_Name__c = 'Intel',Partner_BDM_Name__c='test',
                                                                      Sales_Force_Deal_ID__c = opp1 .id,
                                                                      Client_Enterprise__c = 'Client',
                                                                      Dell_Standard_CPU__c  = stfPrice1 .id,
                                                                      Finance_Contact__c = 'abc@gmail.com'));
        }
        insert allianceReabteRequests;
        
        list<Rebate_Request_Product__c> requestProds = new list<Rebate_Request_Product__c>();
        for(Alliance_Rebate_Request__c ar : allianceReabteRequests){
            requestProds.add(new Rebate_Request_Product__c(Alliance_Rebate_Request__c = ar.id,
                                                          Price_Requested__c = 10,
                                                          Quantity__c = 2,Status__c = 'Active'));
        }
        insert requestProds;
        
        Alliance_Rebate_Request__c newRebateReq = new Alliance_Rebate_Request__c(System_Partner_Name__c = 'Intel',Partner_BDM_Name__c='test',
                                                                      Sales_Force_Deal_ID__c = opp1 .id,
                                                                      Client_Enterprise__c = 'Client',
                                                                      Dell_Standard_CPU__c  = stfPrice1 .id,
                                                                      Finance_Contact__c = 'abc@gmail.com');
                                                                      
        insert newRebateReq;
        
        for(Rebate_Request_Product__c req : requestProds){
            req.Alliance_Rebate_Request__c = newRebateReq.id;
           req.Status__c= 'Expired';
           
        }
        update requestProds;
        TriggerExecutionController.setSkipAllTriggers(False);
  }
  
  
}