profilelist1exp/unpackaged/objects/Associated_Programs_Vendors__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <formula>TEXT ( MDF_Program__r.Fiscal_Quarter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Programs/Vendors</label>
    <nameField>
        <displayFormat>APV-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Programs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Invoice__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Package__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Vendor__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Contract_Types_eligible_for__c</fullName>
        <label>Contract Types eligible for</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Based</fullName>
                </value>
                <value>
                    <fullName>Ala Carte</fullName>
                </value>
                <value>
                    <fullName>Headcount</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vendor__c.Is_this_a_Parent_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Vendor__c.Partner_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Vendors</relationshipLabel>
        <relationshipName>Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Managed</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Rebate only</fullName>
                </value>
                <value>
                    <fullName>Headcount only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Memory</fullName>
                </value>
                <value>
                    <fullName>3rd Party Monitors</fullName>
                </value>
                <value>
                    <fullName>3rd Party Peripherals</fullName>
                </value>
                <value>
                    <fullName>3rd Party Printers</fullName>
                </value>
                <value>
                    <fullName>3rd Party Projectors</fullName>
                </value>
                <value>
                    <fullName>Cameras</fullName>
                </value>
                <value>
                    <fullName>Connected Classroom</fullName>
                </value>
                <value>
                    <fullName>Dell Memory</fullName>
                </value>
                <value>
                    <fullName>Dell Monitors</fullName>
                </value>
                <value>
                    <fullName>Dell Peripherals</fullName>
                </value>
                <value>
                    <fullName>Dell Printers</fullName>
                </value>
                <value>
                    <fullName>Dell Projectors</fullName>
                </value>
                <value>
                    <fullName>Digital Signage</fullName>
                </value>
                <value>
                    <fullName>Display Accessories</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Handhelds</fullName>
                </value>
                <value>
                    <fullName>Licensing Software</fullName>
                </value>
                <value>
                    <fullName>Networking &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Cooling</fullName>
                </value>
                <value>
                    <fullName>Retail Software</fullName>
                </value>
                <value>
                    <fullName>Scanners</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Spare Parts</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Telephony/Communications</fullName>
                </value>
                <value>
                    <fullName>Televisions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Unique_Field__c</fullName>
        <label>Vendor Unique Field</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vendor</label>
    <nameField>
        <label>Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Parent company (i.e. Microsoft)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VFCntrlr_MoveMPlanProgramsTest.cls
@isTest
Private Class VFCntrlr_MoveMPlanProgramsTest{
    static  MDF_Program__c mdfProgram=new MDF_Program__c(); 
    static Vendor__c parentVendor=new Vendor__c();
    static Associated_Programs_Vendors__c apvObj=new Associated_Programs_Vendors__c(); 
    static List<User> users = new List<User>();
    static List<Associated_Programs_Vendors__c> apvList= new List<Associated_Programs_Vendors__c>();
    static Package__c packageObj=new Package__c(); 
    static List<Vendor__c> vendorList=new List<Vendor__c>(); 
    static Marketing_Plan__c mPlanVB1=new Marketing_Plan__c(); 
    static Marketing_Plan__c mPlanVB2=new Marketing_Plan__c();
    static Marketing_Plan__c mPlanAlaC=new Marketing_Plan__c();
    static Marketing_Plan__c mPlanNew=new Marketing_Plan__c();
    static Invoice__c invoiceObj=new Invoice__c(); 
    static Profile profiles;
    static VFCntrlr_MoveMPlanPrograms.APVWrapper apvWrapperElt;
    
    public static void createData(){
       
       Map<String,RecordType> vendorRT=new Map<String,RecordType>();
       
       Test.StartTest();
       RecordType mPlanVBRT=[Select Name, Id From RecordType where 
           sObjectType='Marketing_Plan__c' and name='Volume Based Marketing Plan' limit 1];
       RecordType mPlanACRT=[Select Name, Id From RecordType where 
           sObjectType='Marketing_Plan__c' and name='Ala Carte Marketing Plan' limit 1];
       
       RecordType apvRT=[Select Name, Id From RecordType where 
       sObjectType='Associated_Programs_Vendors__c' and name='Vendor Association MP' limit 1];
       
       profiles=[select id,name from Profile where name like  'MDF Program Owners' limit 1];
       
       for(RecordType rtElt:[Select Name, Id From RecordType where sObjectType='vendor__c']){
           vendorRT.put(rtElt.Name,rtElt);    
       }
      // parentVendor.name='TestVendor';
       parentVendor.name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+'A';
       parentVendor.Partner_Status__c='Active';
       parentVendor.recordTypeId=vendorRT.get('Vendor').Id;
       
       insert parentVendor;
       
       for(Integer i = 0; i<3; i++){
           vendorList.add(
               new Vendor__c(
                   Parent_Vendor__c=parentVendor.Id,
                   //Name='TestSubVendor'+i, // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
                   Name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+i, // Fenny added on 21-Feb-2013
                   Partner_Status__c='Active',
                   Partner_Type__c='Value',
                   Product_Category__c='Networking',
                   Contract_Types_eligible_for__c='Volume Based,Ala Carte',
                   recordTypeId=vendorRT.get('Sub Vendor').Id
               )
           );
       }
       
       insert vendorList;
       
       mPlanVB1.name='MPVB-001';
       mPlanVB1.Vendor__c=vendorList[0].Id;
       mPlanVB1.Fiscal_Quarter__c='FY12Q1';
       mPlanVB1.Region__c='Americas';
       mPlanVB1.Contract_Type__c='Volume Based';
       mPlanVB1.RecordTypeId=mPlanVBRT.Id;
       insert mPlanVB1; 
       
       mPlanVB2.name='MPVB-002';
       mPlanVB2.Vendor__c=vendorList[0].Id;
       mPlanVB2.Fiscal_Quarter__c='FY12Q1';
       mPlanVB2.Region__c='APJ';
       mPlanVB2.Contract_Type__c='Volume Based';
       mPlanVB2.RecordTypeId=mPlanVBRT.Id;
       insert mPlanVB2; 
       
       mPlanAlaC.name='MPAC-001';
       mPlanAlaC.Vendor__c=vendorList[0].Id;
       mPlanAlaC.Fiscal_Quarter__c='FY12Q1';
       mPlanAlaC.Region__c='Americas';
       mPlanAlaC.Contract_Type__c='Ala Carte';
       mPlanAlaC.Contract_Status__c='Pending';
       mPlanAlaC.RecordTypeId=mPlanACRT.Id;
       insert mPlanAlaC; 
       
       mPlanNew.name='MPVB-003';
       mPlanNew.Vendor__c=vendorList[0].Id;
       mPlanNew.Fiscal_Quarter__c='FY12Q1';
       mPlanNew.Region__c='EMEA';
       mPlanNew.Contract_Type__c='Volume Based';       
       mPlanNew.RecordTypeId=mPlanVBRT.Id;
       
      
        
        for(Integer i = 0; i<3; i++){           
            users.add(
                new User(
                    Username='testuser'+i+ System.currentTimeMillis()+'@dell.com',
                    Alias = 'test'+i, 
                    Email='testuser'+i+'@dell.com', 
                    FirstName='John', 
                    LastName='Doe'+i, 
                    ProfileId =profiles.Id, 
                    LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', 
                    EmailEncodingKey='UTF-8', 
                    TimeZoneSidKey='America/Los_Angeles',
                    Badge_Number__c='John.doe'+i
               )
            );
        }
        insert users;
        
        mdfProgram.Name='testMDF Program';
        mdfProgram.Program_Owner__c=users[0].id;
        mdfProgram.POP_Owner__c=users[1].id;
        mdfProgram.Program_Status__c='Approved';
        mdfProgram.Pricing_Type__c='Variable';
        mdfProgram.Fiscal_Quarter__c='FY12Q3';
        mdfProgram.OwnerId=users[2].id;
        mdfProgram.Rate_Card_Price__c=12356;
        
        insert mdfProgram;
        
        for(Integer i = 0; i<3; i++){
           apvList.add(
               new Associated_Programs_Vendors__c(
                   Status__c='Pending',
                   MDF_Program__c=mdfProgram.Id,                  
                   Vendor__c=vendorList[i].Id,
                   Marketing_Plan__c=mPlanVB1.Id,
                   recordTypeId=apvRT.Id,
                   Rate_Card_Price__c=896542,
                   Budgeted_Price__c=56932                   
               )
           );
       }
       
       insert apvList;
       
       //changes by sharad for user story 
       mPlanVB1.Currency_Code__c = 'ZAR';
       mPlanVB1.Contract_Status__c = 'Signed';
       mPlanVB1.Contract_Type__c = 'Ala Carte';
       mPlanVB1.Region__c = 'Americas';
       mPlanVB1.Fiscal_Quarter__c = 'FY12Q1';
       update mPlanVB1;
      
       mPlanVB1.Fiscal_Quarter__c = 'FY12Q4';
       mPlanVB1.Contract_Type__c  = 'Volume Based';
       update mPlanVB1;
       
       Test.StopTest(); 
    }
     
    
     public static testMethod void testVFCtlrMoveMPlanPrograms(){
         createData();       
         
        PageReference pageRef = Page.MoveMPlanPgm;
        Test.setCurrentPage(pageRef);
        VFCntrlr_MoveMPlanPrograms controller = new VFCntrlr_MoveMPlanPrograms(new ApexPages.StandardController(mPlanVB1));
        Boolean mpErr=controller.getMpErr();
        Boolean errorMsg=controller.getErrorMsg();        
        Boolean apvOptionList=controller.getAPVOptionList(); 
        List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapper=controller.getAPVWrapper(); 
        controller.setAPVWrapper(aPVWrapper);        
        List<Associated_Programs_Vendors__c> apvRecList=controller.getAPVList();
        List<Marketing_plan__c> mplanRecList=controller.getMarketingPlanList(); 
        Boolean bolMplan=controller.getMPlanOptionList(); 
        Marketing_plan__c mPlanRec=controller.getMarketingPlan(); 
        controller.setMarketingPlan(mPlanRec);
        Boolean bolCreate=controller.getCreateMPlan();
        List<SelectOption> selectOptions=controller.getContractTypeOptions();    
        String cType=controller.getContractType();
        controller.setContractType(cType);
        
    
    }
    
     public static testMethod void testMove2ExistingMPlan(){
         createData(); 
         
         List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapperLst=new List<VFCntrlr_MoveMPlanPrograms.APVWrapper>(); 
         
         for(Associated_Programs_Vendors__c apv:apvList){  
            apvWrapperElt=new VFCntrlr_MoveMPlanPrograms.APVWrapper(apv); 
            apvWrapperElt.selected=true;             
            aPVWrapperLst.add(apvWrapperElt);
        }       
        PageReference pageRef = Page.MoveMPlanPgm;
        Test.setCurrentPage(pageRef);
        VFCntrlr_MoveMPlanPrograms controller = new VFCntrlr_MoveMPlanPrograms(new ApexPages.StandardController(mPlanVB1));
        List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapper=controller.getAPVWrapper(); 
        controller.setAPVWrapper(aPVWrapperLst);   
        PageReference pageRef2=controller.move2ExistingMPlan();
       
     }     
     /*public static testMethod void testChangeMPlanOfAPV(){
         createData();
         PageReference pageRef =new PageReference('/apex/MoveMPlanPgm?mid='+mPlanAlaC.Id);
         Test.setCurrentPage(pageRef);
        VFCntrlr_MoveMPlanPrograms controller = new VFCntrlr_MoveMPlanPrograms(new ApexPages.StandardController(mPlanVB1));
        //List<Associated_Programs_Vendors__c> selectedApVList=controller.getSelectedAPVs();
        List<Marketing_plan__c> mPlanLst=controller.getMarketingPlanList();
        pageReference pageRef2=controller.changeMPlanOfAPV();
     }*/
     
     public static testMethod void testMove2NewMPlan(){
         createData();
         List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapperLst=new List<VFCntrlr_MoveMPlanPrograms.APVWrapper>(); 
         
         for(Associated_Programs_Vendors__c apv:apvList){  
            apvWrapperElt=new VFCntrlr_MoveMPlanPrograms.APVWrapper(apv); 
            apvWrapperElt.selected=true;             
            aPVWrapperLst.add(apvWrapperElt);
        }
                 
        PageReference pageRef = Page.MoveMPlanPgm;
        Test.setCurrentPage(pageRef);
        VFCntrlr_MoveMPlanPrograms controller = new VFCntrlr_MoveMPlanPrograms(new ApexPages.StandardController(mPlanVB1));
        List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapper=controller.getAPVWrapper(); 
        controller.setAPVWrapper(aPVWrapperLst);  
        PageReference pageRef2 = controller.move2NewMPlan();
        

     }
     
      public static testMethod void testSaveMPlan(){
          createData();
          
        RecordType mPlanVBRT=[Select Name, Id From RecordType where 
        sObjectType='Marketing_Plan__c' and name='Volume Based Marketing Plan' limit 1];
        Marketing_plan__c marketingPlanRecNew=new Marketing_plan__c(); 
        marketingPlanRecNew.name='MP-001';
        marketingPlanRecNew.Vendor__c=vendorList[0].Id;
        marketingPlanRecNew.Fiscal_Quarter__c='FY12Q1';
        marketingPlanRecNew.Region__c='AmericasX';
        marketingPlanRecNew.Contract_Type__c='Volume Based';
        //marketingPlanRecNew.RecordTypeId=mPlanVBRT.Id;
        
        List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapperLst=new List<VFCntrlr_MoveMPlanPrograms.APVWrapper>(); 
         for(Associated_Programs_Vendors__c apv:apvList){  
            apvWrapperElt=new VFCntrlr_MoveMPlanPrograms.APVWrapper(apv); 
            apvWrapperElt.selected=true;             
            aPVWrapperLst.add(apvWrapperElt);
        }
        
        
        PageReference pageRef =Page.MoveMPlanPgm;
        Test.setCurrentPage(pageRef);
        VFCntrlr_MoveMPlanPrograms controller = new 
        VFCntrlr_MoveMPlanPrograms(new ApexPages.StandardController(mPlanVB1));
        
        List<VFCntrlr_MoveMPlanPrograms.APVWrapper> aPVWrapper=controller.getAPVWrapper(); 
        controller.setAPVWrapper(aPVWrapperLst);
         PageReference pageRef2 = controller.move2NewMPlan();
         Marketing_plan__c marketingPlanRec=controller.getMarketingPlan();
        controller.setMarketingPlan(marketingPlanRecNew);
        String cType=controller.getContractType();
        controller.setContractType('Volume Based');
        pageReference pageRef3=controller.saveMPlan();
        
     }
}