profilelist1exp/unpackaged/objects/Associated_Programs_Vendors__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <formula>TEXT (MDF_Program__r.Business_Segment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <formula>TEXT ( MDF_Program__r.Fiscal_Quarter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT ( MDF_Program__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <formula>TEXT( MDF_Program__r.Sub_Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Programs/Vendors</label>
    <nameField>
        <displayFormat>APV-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Programs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/MDF_Program__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Corporate Events</fullName>
                </value>
                <value>
                    <fullName>Global Business</fullName>
                </value>
                <value>
                    <fullName>Int&apos;l</fullName>
                </value>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Medium Business</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Client Peripherals</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Displays</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Enterprise</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Imaging</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Operations</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Software</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>WWP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY12Q1</fullName>
                </value>
                <value>
                    <fullName>FY12Q2</fullName>
                </value>
                <value>
                    <fullName>FY12Q3</fullName>
                </value>
                <value>
                    <fullName>FY12Q4</fullName>
                </value>
                <value>
                    <fullName>FY13Q1</fullName>
                </value>
                <value>
                    <fullName>FY13Q2</fullName>
                </value>
                <value>
                    <fullName>FY13Q3</fullName>
                </value>
                <value>
                    <fullName>FY13Q4</fullName>
                </value>
                <value>
                    <fullName>FY14Q1</fullName>
                </value>
                <value>
                    <fullName>FY14Q2</fullName>
                </value>
                <value>
                    <fullName>FY14Q3</fullName>
                </value>
                <value>
                    <fullName>FY14Q4</fullName>
                </value>
                <value>
                    <fullName>FY15Q1</fullName>
                </value>
                <value>
                    <fullName>FY15Q2</fullName>
                </value>
                <value>
                    <fullName>FY15Q3</fullName>
                </value>
                <value>
                    <fullName>FY15Q4</fullName>
                </value>
                <value>
                    <fullName>FY16Q1</fullName>
                </value>
                <value>
                    <fullName>FY16Q2</fullName>
                </value>
                <value>
                    <fullName>FY16Q3</fullName>
                </value>
                <value>
                    <fullName>FY16Q4</fullName>
                </value>
                <value>
                    <fullName>FY17Q1</fullName>
                </value>
                <value>
                    <fullName>FY17Q2</fullName>
                </value>
                <value>
                    <fullName>FY17Q3</fullName>
                </value>
                <value>
                    <fullName>FY17Q4</fullName>
                </value>
                <value>
                    <fullName>FY18Q1</fullName>
                </value>
                <value>
                    <fullName>FY18Q2</fullName>
                </value>
                <value>
                    <fullName>FY18Q3</fullName>
                </value>
                <value>
                    <fullName>FY18Q4</fullName>
                </value>
                <value>
                    <fullName>FY19Q1</fullName>
                </value>
                <value>
                    <fullName>FY19Q2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                    <default>true</default>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Emerging</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                    <default>true</default>
                    <label>North America</label>
                </value>
                <value>
                    <fullName>UK-I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MDF Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDF Programs</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Scheduled occasion for partner to interact with internal sales/marketing teams.</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Scheduled occasion for partner to conduct in person or web based training with sales or marketing teams</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/POP_Line_Item__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <formula>Proof_of_Performance_POP__r.Business_Segment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proof_of_Performance_POP__c</fullName>
        <label>Proof of Performance (POP)</label>
        <referenceTo>Proof_of_Performance_POP__c</referenceTo>
        <relationshipLabel>Sub Vendors related to POP</relationshipLabel>
        <relationshipName>POP_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vendor__c.Is_this_a_Parent_Vendor__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Vendor__c.Partner_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>POP Line Items</relationshipLabel>
        <relationshipName>POP_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POP Line Item</label>
    <nameField>
        <displayFormat>POPV-{000}</displayFormat>
        <label>POP Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POP Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Proof_of_Performance_POP__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <formula>TEXT ( MDF_Program__r.Business_Segment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <formula>TEXT ( MDF_Program__r.Fiscal_Quarter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Proof of Performance (POP)</relationshipLabel>
        <relationshipName>Proof_of_Performance_POP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT ( MDF_Program__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <formula>TEXT ( MDF_Program__r.Sub_Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Region</label>
        <type>Text</type>
    </fields>
    <label>Proof of Performance (POP)</label>
    <nameField>
        <label>POP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proof of Performance (POP)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/POPFormCtrlExt.cls
public class POPFormCtrlExt {
    
    Proof_of_Performance_POP__c POPRec;
    List<POP_Line_Item__c> POPLineItemList = new List<POP_Line_Item__c>();
    // Mohan 20110606 BRD 8.4.1.3
    List<Associated_Programs_Vendors__c> apvList = new List<Associated_Programs_Vendors__c>();
    //
    public Id LastRecId;

    public POPFormCtrlExt(ApexPages.StandardController controller) {
        
        POPRec = [select Id, Name, Business_Segment__c, Fiscal_Quarter__c,
        // Mohan 20110606 BRD 8.4.1.3
        MDF_Program__c, 
        // Aman Sharma CR 8392 BR024
        Region__c,Sub_Region__c,
        //
        MDF_Program__r.name,MDF_Program__r.recordtypeid,
        // sharad chhaparwal Story 3075049 Viper(Wunderkind)
        MDF_Program__r.Program_Type__c
        from Proof_of_Performance_POP__c where id =: controller.getId() ]; 

        // Mohan 20110606 BRD 8.4.1.3
        Map<String,RecordType> MDFProgramRcdTypeMap = new Map<String,RecordType>();
        for(RecordType recType:[select id,name,SobjectType from RecordType 
                               where SobjectType='MDF_Program__c']){
            MDFProgramRcdTypeMap.put(recType.name,recType);                        
        }
        if((POPRec.MDF_Program__r.RecordTypeId == MDFProgramRcdTypeMap.get('Event').Id) ||
            (POPRec.MDF_Program__r.RecordTypeId == MDFProgramRcdTypeMap.get('Field Event').Id) ||
            (POPRec.MDF_Program__r.RecordTypeId == MDFProgramRcdTypeMap.get('Training').Id)){
            // changes done in query add last and condition for 4809142 story by sharad
            apvList = [Select a.Vendor__r.Name, a.Vendor__c, a.Id, a.Status__c From Associated_Programs_Vendors__c a where a.APV_Status__c != 'Declined' 
            and a.MDF_Program__c = :POPRec.MDF_Program__c AND a.Status__c != 'Declined'];
        
            for(Associated_Programs_Vendors__c apv: apvList){
                LastRecId = apv.Id;
            }
        }
        else{
        //  
            POPLineItemList = [select id, Vendor__r.Name, Contract_Status__c
                from POP_Line_Item__c where Proof_of_Performance_POP__c =: POPRec.Id];
            
            for(POP_Line_Item__c pop: POPLineItemList){
                LastRecId = pop.Id;
            }
        // Mohan 20110606 BRD 8.4.1.3
        }
        //
    }

    public Proof_of_Performance_POP__c getPOPRec(){
        return POPRec;
    }

    public List<POP_Line_Item__c> getPOPLineItemList(){
        
        return POPLineItemList;
    }
    
    // Mohan 20110606 BRD 8.4.1.3
    public List<Associated_Programs_Vendors__c> getApvList(){
        //System.debug('!!!!!apvList' + apvList);
        return apvList;
    }
    //
    
    public Id getLastRecId(){
        return LastRecId;
    }    
    
}