profilelist1exp/unpackaged/objects/Associated_Programs_Vendors__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <formula>TEXT ( MDF_Program__r.Fiscal_Quarter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Programs/Vendors</label>
    <nameField>
        <displayFormat>APV-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Programs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Package__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Vendor__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Contract_Types_eligible_for__c</fullName>
        <label>Contract Types eligible for</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Based</fullName>
                </value>
                <value>
                    <fullName>Ala Carte</fullName>
                </value>
                <value>
                    <fullName>Headcount</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vendor__c.Is_this_a_Parent_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Vendor__c.Partner_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Vendors</relationshipLabel>
        <relationshipName>Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Managed</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Rebate only</fullName>
                </value>
                <value>
                    <fullName>Headcount only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Memory</fullName>
                </value>
                <value>
                    <fullName>3rd Party Monitors</fullName>
                </value>
                <value>
                    <fullName>3rd Party Peripherals</fullName>
                </value>
                <value>
                    <fullName>3rd Party Printers</fullName>
                </value>
                <value>
                    <fullName>3rd Party Projectors</fullName>
                </value>
                <value>
                    <fullName>Cameras</fullName>
                </value>
                <value>
                    <fullName>Connected Classroom</fullName>
                </value>
                <value>
                    <fullName>Dell Memory</fullName>
                </value>
                <value>
                    <fullName>Dell Monitors</fullName>
                </value>
                <value>
                    <fullName>Dell Peripherals</fullName>
                </value>
                <value>
                    <fullName>Dell Printers</fullName>
                </value>
                <value>
                    <fullName>Dell Projectors</fullName>
                </value>
                <value>
                    <fullName>Digital Signage</fullName>
                </value>
                <value>
                    <fullName>Display Accessories</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Handhelds</fullName>
                </value>
                <value>
                    <fullName>Licensing Software</fullName>
                </value>
                <value>
                    <fullName>Networking &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Cooling</fullName>
                </value>
                <value>
                    <fullName>Retail Software</fullName>
                </value>
                <value>
                    <fullName>Scanners</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Spare Parts</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Telephony/Communications</fullName>
                </value>
                <value>
                    <fullName>Televisions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Unique_Field__c</fullName>
        <label>Vendor Unique Field</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vendor</label>
    <nameField>
        <label>Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Parent company (i.e. Microsoft)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/CustomerPortal_HC_Rebate_Test.cls
@isTest
private class CustomerPortal_HC_Rebate_Test {
    public static Vendor__c parentVendor = new Vendor__c ();
    public static Vendor__c subvendor = new Vendor__c();
    public static Marketing_Plan__c mp_rebates = new Marketing_Plan__c();
    public static Marketing_Plan__c mp_headcount = new Marketing_Plan__c();
    public static List <Marketing_Plan__c> mp_List = new List <Marketing_Plan__c>();
    public static List <Associated_Programs_Vendors__c> hcapvList = new List <Associated_Programs_Vendors__c>();
    public static List <Associated_Programs_Vendors__c> hcapvListpkg = new List <Associated_Programs_Vendors__c>();
    public static List <Associated_Programs_Vendors__c> apv_List = new List <Associated_Programs_Vendors__c>();
    public static List <Package__c> pkghcList = new List <Package__c>();
    public static RecordType vendorRT = [Select Id,Name from RecordType where sObjectType ='Vendor__c'and isActive=true and Name ='Vendor'];
    public static RecordType subvendorRT = [Select Id,Name from RecordType where sObjectType ='Vendor__c'and isActive=true and Name ='Sub Vendor'];
    public static RecordType mpRTRB = [Select Id,Name from RecordType where sObjectType ='Marketing_Plan__c'and isActive=true and Name ='Rebates Marketing Plan'];
    public static RecordType mpRTHC = [Select Id,Name from RecordType where sObjectType ='Marketing_Plan__c'and isActive=true and Name ='Headcount Marketing Plan'];
    public static List <MDF_Program__c> mdfpgmlist5 = new List <MDF_Program__c>{};
    public static List <MDF_Program__c> mdfpgmlist6 = new List <MDF_Program__c>{};
    public static List <MDF_Program__c> mdfpgm_list = new List <MDF_Program__c>{};
    public static Profile p1 = [SELECT Id,Name FROM profile WHERE Name like'%MDF Program Owners%' limit 1];
    public static User u1 = new User();
    
    public static void createdata(){
         TriggerExecutionController.setSkipAllTriggers(true);
        u1 = new User(alias = 'newUser', email='user1@dellteam.com',emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',localesidkey='en_US', profileid = p1.Id,Badge_Number__c='badge1',timezonesidkey='America/Los_Angeles', username='user1@dellteam.com');
        insert u1;
        
        //creating parent vendor
       //parentVendor.name='TestVendor'; // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
       parentVendor.name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+'A'; // Fenny added on 21-Feb-2013
        parentVendor.Partner_Status__c='Active';
        parentVendor.recordTypeId=vendorRT.Id;        
        insert parentVendor;
        
        // creating a sub vendor
        subvendor.Parent_Vendor__c=parentVendor.Id;
       //subvendor.Name='TestSubVendor'; // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
       subvendor.name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+'B'; // Fenny added on 21-Feb-2013
        subvendor.Partner_Status__c='Active';
        subvendor.Partner_Type__c='Value';
        subvendor.Product_Category__c='Networking';
        subvendor.Contract_Types_eligible_for__c='Volume Based,Ala Carte';
        subvendor.recordTypeId= subvendorRT.Id;        
        insert subvendor;
        
        mp_rebates.name='MP-003';
        mp_rebates.Vendor__c=subvendor.Id;
        mp_rebates.Fiscal_Quarter__c='FY12Q1';
        mp_rebates.Region__c='EMEA';
        mp_rebates.Contract_Type__c='Rebates';
        mp_rebates.RecordTypeId=mpRTRB.Id;      
        //insert mp_rebates; 
        mp_List.add(mp_rebates);
        
        mp_headcount.name='MP-004';
        mp_headcount.Vendor__c=subvendor.Id;
        mp_headcount.Fiscal_Quarter__c='FY12Q1';
        mp_headcount.Region__c='EMEA';
        mp_headcount.Contract_Type__c='Headcount';
        mp_headcount.RecordTypeId=mpRTHC.Id;      
        //insert mp_headcount;
        mp_List.add(mp_headcount);
        insert mp_List;
        for(Integer i=0;i<6;i++){
            MDF_Program__c pgm = new MDF_Program__c();
            pgm.Name = 'Name'+i+i+i+i+i;
            mdfpgmlist5.add(pgm);
            pgm.Program_Owner__c=u1.Id;
            pgm.POP_Owner__c=u1.Id;
            pgm.Fiscal_Quarter__c='FY12Q1';
            mdfpgm_list.add(pgm);
        }
        //insert mdfpgmlist5;
        
        insert mdfpgm_list;
        
        
         for(Integer i=0;i<1;i++){
            Package__c pkg = new Package__c();
            pkg.Name = 'pkg'+i;
            pkg.Marketing_Plan__c = mp_List[1].Id;
            pkg.Package_Price_del__c = 1234;
            pkg.Status__c = 'Submitted for Review';
            //insert pkg;
            pkghcList.add(pkg);         
         }
         
         insert pkghcList;
         
         for(Integer i=0;i<1;i++){
            Associated_Programs_Vendors__c apv = new Associated_Programs_Vendors__c();
            apv.Marketing_Plan__c = mp_List[1].Id;
            apv.MDF_Program__c = mdfpgm_list[0].Id;     
            apv.Status__c = 'Submitted for Review';     
            apv.Accounting_Treatment__c = 'COGS Offset';
            apv.Vendor__c = subvendor.Id; 
            //hcapvList.add(apv);   
            apv_List.add(apv);  
        
        }//insert hcapvList;
        
         
         for(Integer i=0;i<1;i++){
            Associated_Programs_Vendors__c apv = new Associated_Programs_Vendors__c();
            apv.Marketing_Plan__c = mp_List[1].Id;
            apv.MDF_Program__c = mdfpgm_list[3].Id;     
            apv.Status__c = 'Submitted for Review';     
            apv.Accounting_Treatment__c = 'COGS Offset';
            apv.Vendor__c = subvendor.Id; 
            apv.Package__c= pkghcList[i].Id;
            //hcapvListpkg.add(apv);  
            apv_List.add(apv);  
         }//insert hcapvListpkg;
         insert apv_List;
    }
    static testMethod void myUnitTest1() {
       createdata();
       //HeadCount MP
       PageReference  pr4=new PageReference('apex/CustomerPortal_MarketingPlan_HeadCount?id='+mp_List[1].Id);
       Test.setCurrentPage(pr4);
       VFCntrlr_CustomerPortal_MPlan_HeadCount mpcntrlr4 = new VFCntrlr_CustomerPortal_MPlan_HeadCount(new ApexPages.StandardController(mp_List[1]));
       Test.startTest();
       mpcntrlr4.addBillingContact();
       mpcntrlr4.addPrimaryContact();
       mpcntrlr4.addpurchaseorder();
       mpcntrlr4.savepruchaseorder();
       mpcntrlr4.saveAPV();
       
       for(Package__c pkg:mpcntrlr4.pkgList){
        pkg.PKG_Status__c='accept';
       }
       mpcntrlr4.savePKG();
       mpcntrlr4.acceptallAPV();
       mpcntrlr4.rejectallapv();
       
       mp_List[1].Billing_Contact_Name__c='hi';
       mp_List[1].Primary_Marketing_Contact_Name__c='hi';
       update mp_List[1];
       
       //mpcntrlr4.saveAPV();
       
       for(Associated_Programs_Vendors__c apvs:mpcntrlr4.apvList){
        apvs.APV_Status__c='decline';
       }
       mpcntrlr4.saveAPV();
       //mpcntrlr4.savePKG();
       //mpcntrlr4.acceptallAPV();
       mpcntrlr4.rejectallapv();
       mpcntrlr4.getApvList();
       mpcntrlr4.getpkgList();
       mpcntrlr4.cancelfn(); 
       //rebates MP
       Test.StopTest();
       TriggerExecutionController.setSkipAllTriggers(false);
    }
    static testMethod void myUnitTest2(){
       
    createdata();
    PageReference  pr3=new PageReference('apex/CustomerPortal_MarketingPlan_Rebates?id='+mp_List[0].Id);
       Test.setCurrentPage(pr3);
       VFCntrlr_CustomerPortal_MPlan_Rebates mpcntrlr3 = new VFCntrlr_CustomerPortal_MPlan_Rebates(new ApexPages.StandardController(mp_List[0]));
       Test.StartTest();
       mpcntrlr3.accept_decline_MP();
       mpcntrlr3.myMPPlan.MP_Status__c='Accept';
       mpcntrlr3.saveStatusrebates();
       mpcntrlr3.addBillingContact();
       mpcntrlr3.addPrimaryContact();
       mpcntrlr3.addpurchaseorder();
       mpcntrlr3.savepruchaseorder();
       mpcntrlr3.getRebateLineItemList();
       mpcntrlr3.cancelfn();
       mpcntrlr3.accept_decline_MP();
       mpcntrlr3.myMPPlan.MP_Status__c='Decline';
       mpcntrlr3.saveStatusrebates();          
       Test.StopTest();  
       TriggerExecutionController.setSkipAllTriggers(false);
    }
}