profilelist1exp/unpackaged/objects/Associated_Programs_Vendors__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Budgeted_Price__c</fullName>
        <label>Budgeted Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Converted_Budget_Price__c</fullName>
        <label>Converted Budget Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>POP_Status__c</fullName>
        <label>POP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Executed</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Programs/Vendors</label>
    <nameField>
        <displayFormat>APV-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Programs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/MDF_Program__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Program_Id__c</fullName>
        <displayFormat>Prog-{0000000}</displayFormat>
        <label>Program Id</label>
        <type>AutoNumber</type>
    </fields>
    <label>MDF Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDF Programs</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Programs not outlined elsewhere</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Reimbursement_Form__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Reimbursement Forms</relationshipLabel>
        <relationshipName>Reimbursement_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Form</label>
    <nameField>
        <label>Reimbursement Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reimbursement Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Vendor__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Client Peripherals</fullName>
                </value>
                <value>
                    <fullName>Displays</fullName>
                </value>
                <value>
                    <fullName>Enterprise Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Imaging</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vendor</label>
    <nameField>
        <label>Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Vendor_Reimbursement__c.object
<CustomObject>
    <fields>
        <fullName>APV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Programs/Vendors</label>
        <referenceTo>Associated_Programs_Vendors__c</referenceTo>
        <relationshipName>Vendor_Reimbersments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budgeted_Price__c</fullName>
        <label>Budgeted Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Contract Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributed_Price__c</fullName>
        <label>Distributed Expense Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipName>Vendor_Reimbersments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POP_Status__c</fullName>
        <label>POP Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <label>Program ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Form__c</fullName>
        <label>Reimbursement Form</label>
        <referenceTo>Reimbursement_Form__c</referenceTo>
        <relationshipLabel>Associated Reimbursement Vendors</relationshipLabel>
        <relationshipName>Vendor_Reimbersments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Associated Reimbursement Vendors</relationshipLabel>
        <relationshipName>Vendor_Reimbersments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Reimbursement Vendor</label>
    <nameField>
        <displayFormat>ARV -{00000000}</displayFormat>
        <label>Associated Reimbursement Vendor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Reimbursement Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AddVendorReimbursementFormCntrlr.cls
Public class AddVendorReimbursementFormCntrlr{

public String reimbursFormId;
public MDF_Program__c mdfProgram{get;set;}
public List<APVWrapper> selectedAssociatedVendorsWrapper{get;set;}
public List<Associated_Programs_Vendors__c> totalList = new List<Associated_Programs_Vendors__c>();
public String searchAlphabet;

public String getsearchAlphabet(){

    return searchAlphabet;
    
}

public void setsearchAlphabet(String alpha){

    searchAlphabet = alpha;
}
    
    public AddVendorReimbursementFormCntrlr(ApexPages.StandardSetController controller){
    
        selectedAssociatedVendorsWrapper = new List<APVWrapper>();
        if(Apexpages.currentpage().getParameters().containsKey('id')){
        
            reimbursFormId = Apexpages.currentpage().getParameters().get('Id');
        }
        
        if(reimbursFormId != null){
        
            Reimbursement_Form__c parentReimbForm = [Select Id,MDF_Program__c,(Select Id,APV__c,Distributed_Price__c FROM Vendor_Reimbersments__r) FROM Reimbursement_Form__c WHERE Id=:reimbursFormId LIMIT 1];
            Set<Id> existingAssPrgIds = new Set<Id>();
            if(!parentReimbForm.Vendor_Reimbersments__r.isEmpty()){
                existingAssPrgIds = new Set<Id>();
                for(Vendor_Reimbursement__c vrf : parentReimbForm.Vendor_Reimbersments__r){
                
                    existingAssPrgIds.add(vrf.APV__c);
                }
            }
            if(!existingAssPrgIds.isEmpty()){
                mdfProgram = [Select Id,Name,Program_Id__c,(Select Id,Name,Budgeted_Price__c,Status__c,Vendor__c,POP_Status__c,Vendor__r.name,vendor__r.Lob__c FROM Associated_Programs_Vendors__r WHERE Id NOT IN:existingAssPrgIds AND Status__c != 'declined' order by Vendor__r.name ASC) FROM MDF_Program__c WHERE Id=:parentReimbForm.MDF_Program__c  LIMIT 1];
            }
            else{
                mdfProgram = [Select Id,Name,Program_Id__c,(Select Id,Name,Budgeted_Price__c,Status__c,Vendor__c,POP_Status__c,Vendor__r.name,vendor__r.Lob__c FROM Associated_Programs_Vendors__r WHERE Status__c != 'declined' order by Vendor__r.name ASC) FROM MDF_Program__c WHERE Id=:parentReimbForm.MDF_Program__c  LIMIT 1];
            }
            
            //mdfProgram = [Select Id,Name,Program_Id__c,(Select Id,Name,Converted_Budget_Price__c,Status__c,Vendor__c FROM Associated_Programs_Vendors__r) FROM MDF_Program__c WHERE Id=:parentReimbForm.MDF_Program__c LIMIT 1];
            if(!mdfProgram.Associated_Programs_Vendors__r.isEmpty()){
            
                for(Associated_Programs_Vendors__c apv : mdfProgram.Associated_Programs_Vendors__r){
                
                if(apv.Status__c != 'declined')
                    selectedAssociatedVendorsWrapper.add(new APVWrapper(apv,mdfProgram));
                    totalList.add(apv);
                  // else
                  //  Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'No vendors have been contracted for this program, please contact program owner for assistance'));
                    
                }
                
            }
            else{
            
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'There are no available vendors for this record'));
            }
        }
    }
    
    //Wrapper class
    public class APVWrapper{
        public Associated_Programs_Vendors__c apvElt{get;set;}
        public MDF_Program__c mdPrgrm{get;set;}  
        public Boolean selected {get;set;}
        public Double distributedPrice{get;set;}
        //Constructor for wrapper class
        public APVWrapper(Associated_Programs_Vendors__c apvObj,MDF_Program__c prgrm){
            apvElt = apvObj;
            mdPrgrm = prgrm;            
            selected = false;
        }
    }
    
    public void sortByAlphabet(){
        
        if(!totalList.isEMpty()){
        
            if(searchAlphabet != null && searchAlphabet != 'All' && searchAlphabet != 'Other'){
                selectedAssociatedVendorsWrapper = new List<APVWrapper>();
                for(Associated_Programs_Vendors__c apv : totalList){
                    
                    if(apv.Vendor__r.name.startsWith(searchAlphabet)){
                    
                        selectedAssociatedVendorsWrapper.add(new APVWrapper(apv,mdfProgram));
                    }
                }
            }
            if(searchAlphabet == 'All' || searchAlphabet == 'Other'){
                selectedAssociatedVendorsWrapper = new List<APVWrapper>();
                for(Associated_Programs_Vendors__c apv : totalList){
                    
                    
                        selectedAssociatedVendorsWrapper.add(new APVWrapper(apv,mdfProgram));
                    
                }
            }
            
        }
        
    }
    
    public pagereference insertVendorReimbrsRecords(){
    
        List<Vendor_Reimbursement__c> VendorReimbrsRecords = new List<Vendor_Reimbursement__c>();
        
        for(APVWrapper wrp : selectedAssociatedVendorsWrapper ){
        
            if(wrp.selected == True){
            
                Vendor_Reimbursement__c vr = new Vendor_Reimbursement__c();
               vr.vendor__c = wrp.apvElt.Vendor__c;
                vr.lob__c = wrp.apvElt.vendor__r.lob__c;
                vr.APV__c = wrp.apvElt.Id;
                vr.Budgeted_Price__c = wrp.apvElt.Budgeted_Price__c;
                vr.Contract_Status__c = wrp.apvElt.Status__c;
                vr.POP_Status__c =    wrp.apvElt.POP_Status__c;
                vr.Program__c = wrp.mdPrgrm.Name;
                vr.Program_ID__c = wrp.mdPrgrm.Program_Id__c;
                vr.Reimbursement_Form__c = reimbursFormId;
                vr.Distributed_Price__c = vr.Distributed_Price__c;
                vr.MDF_Program__c = wrp.mdPrgrm.Id; 
                if(wrp.distributedPrice != null){
                    vr.Distributed_Price__c = wrp.distributedPrice;
                }
                                
                VendorReimbrsRecords.add(vr);
            }
        }
        
        if(!VendorReimbrsRecords.isEmpty()){
        
            Database.insert(VendorReimbrsRecords,false);
        }
        
        return new pagereference('/'+reimbursFormId);
    }
    
    
}