profilelist1exp/unpackaged/objects/Associated_Programs_Vendors__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Budgeted_Price__c</fullName>
        <label>Budgeted Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <formula>TEXT (MDF_Program__r.Business_Segment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_Program__c</fullName>
        <label>MDF Program</label>
        <referenceTo>MDF_Program__c</referenceTo>
        <relationshipLabel>Associated Vendors</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Programs/Vendors</label>
    <nameField>
        <displayFormat>APV-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Programs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Viper Project</description>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/MDF_Program__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Corporate Events</fullName>
                </value>
                <value>
                    <fullName>Global Business</fullName>
                </value>
                <value>
                    <fullName>Int&apos;l</fullName>
                </value>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Medium Business</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Client Peripherals</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Displays</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Enterprise</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Imaging</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Operations</fullName>
                </value>
                <value>
                    <fullName>S&amp;P Software</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>WWP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preferred Program</label>
        <type>Checkbox</type>
    </fields>
    <label>MDF Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDF Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Package__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABU</fullName>
                </value>
                <value>
                    <fullName>ABU S&amp;P</fullName>
                </value>
                <value>
                    <fullName>Dell Events</fullName>
                </value>
                <value>
                    <fullName>Global Mktg</fullName>
                </value>
                <value>
                    <fullName>ASAP</fullName>
                </value>
                <value>
                    <fullName>ASG</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>Consumer S&amp;P</fullName>
                </value>
                <value>
                    <fullName>CSMR</fullName>
                </value>
                <value>
                    <fullName>Int&apos;l</fullName>
                </value>
                <value>
                    <fullName>LE S&amp;P</fullName>
                </value>
                <value>
                    <fullName>PUB</fullName>
                </value>
                <value>
                    <fullName>PUB S&amp;P</fullName>
                </value>
                <value>
                    <fullName>REL</fullName>
                </value>
                <value>
                    <fullName>S&amp;P COC</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Corporate Events</fullName>
                </value>
                <value>
                    <fullName>CSMR S&amp;P</fullName>
                </value>
                <value>
                    <fullName>SMB Channel</fullName>
                </value>
                <value>
                    <fullName>SMB Direct</fullName>
                </value>
                <value>
                    <fullName>WWP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Packages</relationshipLabel>
        <relationshipName>Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Package_Price_del__c</fullName>
        <label>Package Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PackageProgramAsccociationVFctrlr.cls
public class PackageProgramAsccociationVFctrlr {

    ID packageID;
    ID marketpalnID;
    Decimal budgetprice=0;
    Decimal pkgprice=0;
    Package__c packagerec {get; set;}
    Marketing_Plan__c marketplanerec {get; set;}
    
    //Wrapper Classes
    List<MPWrapper> ListofAvailableApvs{get; set;}
    List<MPWrapper> selectedListofAvailableApvs=new List<MPWrapper>();
    
    List <Associated_Programs_Vendors__c> availableAPVList=new List<Associated_Programs_Vendors__c>();
    Public Boolean noApv=True;

    //constructor
    public PackageProgramAsccociationVFctrlr (ApexPages.StandardController controller) {
        packageID=controller.getId();
        packagerec=[select Name,Marketing_Plan__c,Package_Price_del__c,Business_Segment__c from Package__c where id=:packageID];
        availableAPVList=[select id,Name,Marketing_Plan__c,Package__c,MDF_Program__c,Status__c,Business_Segment__c,Budgeted_Price__c from Associated_Programs_Vendors__c where
                         Marketing_Plan__c=:packagerec.Marketing_Plan__c AND Package__c=Null AND Associated_Programs_Vendors__c.MDF_Program__r.Preferred_Program__c=False AND Business_Segment__c=:packagerec.Business_Segment__c ];
        if(availableAPVList.size()<=0){
            noApv=False;    
        }
        
    }

    public boolean getIsApvavailable(){
        return noApv; 
    }
    

    public pageReference updatefields(){
        List <Associated_Programs_Vendors__c> upd_apvs=new List<Associated_Programs_Vendors__c>();
        PageReference currPageRef=new PageReference('/'+packageID);
        Associated_Programs_Vendors__c apvObj;
        
        List <Associated_Programs_Vendors__c> selectedAPVList=new List<Associated_Programs_Vendors__c>();
        
        for ( MPWrapper apv: ListofAvailableApvs){
            if(apv.selected==true){
                apvObj=new Associated_Programs_Vendors__c(id=apv.apvMpElt.Id);
                if(apv.apvMpElt.Budgeted_Price__c==null){
                    apvObj.Budgeted_Price__c=0.00;
                }
                apvObj.Package__c=packageID;
                upd_apvs.add(apvObj);
                if(apv.apvMpElt.Budgeted_Price__c!=null){
                    budgetprice=budgetprice+apv.apvMpElt.Budgeted_Price__c;
                }
            }        
        } 
        if(upd_apvs.size()==0){
            ApexPages.Message msg;     
            msg = new ApexPages.Message(ApexPages.severity.FATAL,'Error: To continue, please select atleast one APV.');
            ApexPages.addMessage(msg);            
            return null;  
             
        }          
        if(upd_apvs.size()>0){
            pkgprice=packagerec.Package_Price_del__c;
            if(packagerec.Package_Price_del__c==Null){
                pkgprice=0.00;
            }
            packagerec.Package_Price_del__c=pkgprice+budgetprice;
            try {
                update upd_apvs;
                update packagerec;
            } catch (DmlException e){
                System.debug('While updating package record/APV '+e.getMessage());
            }
        }  

    return currPageRef;
    
    }

         //Wrapper class
    public class MPWrapper{
        public Associated_Programs_Vendors__c apvMpElt {get; set;}
        public Boolean selected {get; set;}

        //Constructor for wrapper class
        public MPWrapper(Associated_Programs_Vendors__c apvMpObj){
            apvMpElt = apvMpObj;
            selected = false;
        }
    } 


    public List<MPWrapper> getListofAvailableApvs(){
        MPWrapper mpWrapperElt;
        ListofAvailableApvs=new List<MPWrapper>();            
        
        for(Associated_Programs_Vendors__c apv:availableAPVList){                
            ListofAvailableApvs.add(new MPWrapper(apv));
        }
        System.debug('###AvailableAPVs'+ListofAvailableApvs); 
        return ListofAvailableApvs;
    }
        
    public void setListofAvailableApvs(List<MPWrapper> mpWrapperRecList){
        this.ListofAvailableApvs=mpWrapperRecList;
    }

}