profilelist1exp/unpackaged/objects/Associated_Programs_Vendors__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Budgeted_Price__c</fullName>
        <label>Budgeted Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <formula>TEXT ( MDF_Program__r.Fiscal_Quarter__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Plan</label>
        <referenceTo>Marketing_Plan__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <formula>MDF_Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card_Price__c</fullName>
        <label>Rate Card Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT ( MDF_Program__r.Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Associated_Programs_Vendors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Programs/Vendors</label>
    <nameField>
        <displayFormat>APV-{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Programs/Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Invoice__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Based, Ala Carte, Headcount</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY12Q1</fullName>
                </value>
                <value>
                    <fullName>FY12Q2</fullName>
                </value>
                <value>
                    <fullName>FY12Q3</fullName>
                </value>
                <value>
                    <fullName>FY12Q4</fullName>
                </value>
                <value>
                    <fullName>FY13Q1</fullName>
                </value>
                <value>
                    <fullName>FY13Q2</fullName>
                </value>
                <value>
                    <fullName>FY13Q3</fullName>
                </value>
                <value>
                    <fullName>FY13Q4</fullName>
                </value>
                <value>
                    <fullName>FY14Q1</fullName>
                </value>
                <value>
                    <fullName>FY14Q2</fullName>
                </value>
                <value>
                    <fullName>FY14Q3</fullName>
                </value>
                <value>
                    <fullName>FY14Q4</fullName>
                </value>
                <value>
                    <fullName>FY15Q1</fullName>
                </value>
                <value>
                    <fullName>FY15Q2</fullName>
                </value>
                <value>
                    <fullName>FY15Q3</fullName>
                </value>
                <value>
                    <fullName>FY15Q4</fullName>
                </value>
                <value>
                    <fullName>FY16Q1</fullName>
                </value>
                <value>
                    <fullName>FY16Q2</fullName>
                </value>
                <value>
                    <fullName>FY16Q3</fullName>
                </value>
                <value>
                    <fullName>FY16Q4</fullName>
                </value>
                <value>
                    <fullName>FY17Q1</fullName>
                </value>
                <value>
                    <fullName>FY17Q2</fullName>
                </value>
                <value>
                    <fullName>FY17Q3</fullName>
                </value>
                <value>
                    <fullName>FY17Q4</fullName>
                </value>
                <value>
                    <fullName>FY18Q1</fullName>
                </value>
                <value>
                    <fullName>FY18Q2</fullName>
                </value>
                <value>
                    <fullName>FY18Q3</fullName>
                </value>
                <value>
                    <fullName>FY18Q4</fullName>
                </value>
                <value>
                    <fullName>FY19Q1</fullName>
                </value>
                <value>
                    <fullName>FY19Q2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                    <default>true</default>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Based</fullName>
                </value>
                <value>
                    <fullName>Ala Carte</fullName>
                </value>
                <value>
                    <fullName>Headcount</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY12Q1</fullName>
                </value>
                <value>
                    <fullName>FY12Q2</fullName>
                </value>
                <value>
                    <fullName>FY12Q3</fullName>
                </value>
                <value>
                    <fullName>FY12Q4</fullName>
                </value>
                <value>
                    <fullName>FY13Q1</fullName>
                </value>
                <value>
                    <fullName>FY13Q2</fullName>
                </value>
                <value>
                    <fullName>FY13Q3</fullName>
                </value>
                <value>
                    <fullName>FY13Q4</fullName>
                </value>
                <value>
                    <fullName>FY14Q1</fullName>
                </value>
                <value>
                    <fullName>FY14Q2</fullName>
                </value>
                <value>
                    <fullName>FY14Q3</fullName>
                </value>
                <value>
                    <fullName>FY14Q4</fullName>
                </value>
                <value>
                    <fullName>FY15Q1</fullName>
                </value>
                <value>
                    <fullName>FY15Q2</fullName>
                </value>
                <value>
                    <fullName>FY15Q3</fullName>
                </value>
                <value>
                    <fullName>FY15Q4</fullName>
                </value>
                <value>
                    <fullName>FY16Q1</fullName>
                </value>
                <value>
                    <fullName>FY16Q2</fullName>
                </value>
                <value>
                    <fullName>FY16Q3</fullName>
                </value>
                <value>
                    <fullName>FY16Q4</fullName>
                </value>
                <value>
                    <fullName>FY17Q1</fullName>
                </value>
                <value>
                    <fullName>FY17Q2</fullName>
                </value>
                <value>
                    <fullName>FY17Q3</fullName>
                </value>
                <value>
                    <fullName>FY17Q4</fullName>
                </value>
                <value>
                    <fullName>FY18Q1</fullName>
                </value>
                <value>
                    <fullName>FY18Q2</fullName>
                </value>
                <value>
                    <fullName>FY18Q3</fullName>
                </value>
                <value>
                    <fullName>FY18Q4</fullName>
                </value>
                <value>
                    <fullName>FY19Q1</fullName>
                </value>
                <value>
                    <fullName>FY19Q2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                    <default>true</default>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Marketing Plans</relationshipLabel>
        <relationshipName>Marketing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Vendor__c.object
<CustomObject>
    <description>Viper Project</description>
    <label>Vendor</label>
    <nameField>
        <label>Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MassUpdateAPVControllerTest.cls
@isTest
private class MassUpdateAPVControllerTest{

  static testMethod void Test_MassUpdate_other(){
      String Name='';
       Marketing_Plan__c marketingPlan = new Marketing_Plan__c();
       marketingPlan.name='MP-001';
    // marketingPlan.Vendor__c=vendorList[0].Id;
       marketingPlan.Fiscal_Quarter__c='FY12Q1';
       marketingPlan.Region__c='Americas';
       marketingPlan.Contract_Type__c='Volume Based';
    // marketingPlan.RecordTypeId=marketingPlanRT.Id;
    // marketingPlan.invoice__c=invoiceObj.Id;
       insert marketingPlan; 
  
      ApexPages.CurrentPage().getParameters().put('id', marketingPlan.Id); 
      List<Associated_Programs_Vendors__c> listAsso=new List<Associated_Programs_Vendors__c>();
      //Associated_Programs_Vendors__c objAssProgam = new Associated_Programs_Vendors__c();
      for(integer i=0;i>2040;i++){
          listAsso.add(new Associated_Programs_Vendors__c(
          Status__c ='Pending',                     
          Rate_Card_Price__c=896542,
          Budgeted_Price__c=56932+i,
          Invoice_Amount__c=98980+i,      
          Marketing_Plan__c=marketingPlan.Id 
          ));         
      }
      insert listAsso;
           
      //ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(listAsso);
      //Associated_Programs_Vendors__c assoprm = new Associated_Programs_Vendors__c(); 
          
      PageReference pageRef = Page.MassUpdateAPV; 
      Test.setCurrentPage(pageRef); 
      ApexPages.currentPage().getParameters().put('id',marketingPlan.Id);
      ApexPages.currentPage().getParameters().put('alpha','Other');
      MassUpdateAPVController objMassUpdate = new MassUpdateAPVController();      
      objMassUpdate.standardSetCon = null;
      objMassUpdate.getCurrentList();
      objMassUpdate.standardSetCon = new ApexPages.StandardSetController(listAsso);      
      objMassUpdate.getCurrentList();
      objMassUpdate.massUpdateAPVRecrods();
      objMassUpdate.lstOfEditedAPVRecords=listAsso;       
      objMassUpdate.CancelAction();
      objMassUpdate.getDisplaySelectedList();      
      objMassUpdate.getHost();      
      objMassUpdate.getServerName();
      objMassUpdate.setServerName('host');
      objMassUpdate.totalPages=5;
      objMassUpdate.mplanErr=true;
      objMassUpdate.sortExp='Program_Name__c';
      objMassUpdate.sortDirection='ASC';
      objMassUpdate.setsortDirection('ASC');
      objMassUpdate.getsortDirection();            
      objMassUpdate.RefreshList2();
      objMassUpdate.sortField=null;
      objMassUpdate.APCList=listAsso;
      objMassUpdate.sorting();   
           
  }
  
  static testMethod void Test_MassUpdate_All(){
      String Name='';
       Marketing_Plan__c marketingPlan = new Marketing_Plan__c();
       marketingPlan.name='MP-001';
    // marketingPlan.Vendor__c=vendorList[0].Id;
       marketingPlan.Fiscal_Quarter__c='FY12Q1';
       marketingPlan.Region__c='Americas';
       marketingPlan.Contract_Type__c='Volume Based';
    // marketingPlan.RecordTypeId=marketingPlanRT.Id;
    // marketingPlan.invoice__c=invoiceObj.Id;
       insert marketingPlan; 
  
      ApexPages.CurrentPage().getParameters().put('id', marketingPlan.Id); 
      List<Associated_Programs_Vendors__c> listAsso=new List<Associated_Programs_Vendors__c>();
      //Associated_Programs_Vendors__c objAssProgam = new Associated_Programs_Vendors__c();
      for(integer i=0;i>2040;i++){
          listAsso.add(new Associated_Programs_Vendors__c(
          Status__c ='Pending',                     
          Rate_Card_Price__c=896542,
          Budgeted_Price__c=56932+i,
          Invoice_Amount__c=98980+i,      
          Marketing_Plan__c=marketingPlan.Id 
          ));         
      }
      insert listAsso;
           
      //ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(listAsso);
      //Associated_Programs_Vendors__c assoprm = new Associated_Programs_Vendors__c(); 
          
      PageReference pageRef = Page.MassUpdateAPV; 
      Test.setCurrentPage(pageRef); 
      ApexPages.currentPage().getParameters().put('id',marketingPlan.Id);
      ApexPages.currentPage().getParameters().put('alpha','All');
      MassUpdateAPVController objMassUpdate = new MassUpdateAPVController();      
      objMassUpdate.standardSetCon = null;
      objMassUpdate.getCurrentList();
      objMassUpdate.standardSetCon = new ApexPages.StandardSetController(listAsso);      
      objMassUpdate.getCurrentList();
      objMassUpdate.massUpdateAPVRecrods();
      objMassUpdate.lstOfEditedAPVRecords=listAsso;       
      objMassUpdate.CancelAction();
      objMassUpdate.getDisplaySelectedList();
      objMassUpdate.RefreshList2();
      objMassUpdate.getHost();      
      objMassUpdate.getServerName();
      objMassUpdate.setServerName('host');
      objMassUpdate.totalPages=5;
      objMassUpdate.mplanErr=true;
      objMassUpdate.sortExp='Program_Name__c';
      objMassUpdate.sortDirection='DESC';
      objMassUpdate.getsortDirection();
      objMassUpdate.setsortDirection('DESC');
      objMassUpdate.sortField=null;
      objMassUpdate.sorting();      
      objMassUpdate.APCList=listAsso;           
  }
  
  static testMethod void Test_MassUpdate_AtoZ(){
      String Name='';
       Marketing_Plan__c marketingPlan = new Marketing_Plan__c();
       marketingPlan.name='MP-001';
    // marketingPlan.Vendor__c=vendorList[0].Id;
       marketingPlan.Fiscal_Quarter__c='FY12Q1';
       marketingPlan.Region__c='Americas';
       marketingPlan.Contract_Type__c='Volume Based';
    // marketingPlan.RecordTypeId=marketingPlanRT.Id;
    // marketingPlan.invoice__c=invoiceObj.Id;
       insert marketingPlan; 
  
      ApexPages.CurrentPage().getParameters().put('id', marketingPlan.Id); 
      List<Associated_Programs_Vendors__c> listAsso=new List<Associated_Programs_Vendors__c>();
      //Associated_Programs_Vendors__c objAssProgam = new Associated_Programs_Vendors__c();
      for(integer i=0;i>2040;i++){
          listAsso.add(new Associated_Programs_Vendors__c(
          Status__c ='Pending',                     
          Rate_Card_Price__c=896542,
          Budgeted_Price__c=56932+i,
          Invoice_Amount__c=98980+i,      
          Marketing_Plan__c=marketingPlan.Id 
          ));         
      }
      insert listAsso;
           
      //ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(listAsso);
      //Associated_Programs_Vendors__c assoprm = new Associated_Programs_Vendors__c(); 
          
      PageReference pageRef = Page.MassUpdateAPV; 
      Test.setCurrentPage(pageRef); 
      ApexPages.currentPage().getParameters().put('id',marketingPlan.Id);
      ApexPages.currentPage().getParameters().put('alpha','A');
      MassUpdateAPVController objMassUpdate = new MassUpdateAPVController();      
      objMassUpdate.standardSetCon = null;
      objMassUpdate.getCurrentList();
      objMassUpdate.standardSetCon = new ApexPages.StandardSetController(listAsso);      
      objMassUpdate.getCurrentList();
      objMassUpdate.massUpdateAPVRecrods();
      objMassUpdate.lstOfEditedAPVRecords=listAsso;       
      objMassUpdate.CancelAction();
      objMassUpdate.getDisplaySelectedList();
      objMassUpdate.RefreshList2();
      objMassUpdate.getHost();      
      objMassUpdate.getServerName();
      objMassUpdate.setServerName('host');
      objMassUpdate.totalPages=5;
      objMassUpdate.mplanErr=true;
      objMassUpdate.sortExp='Program_Name__c';
      objMassUpdate.sortDirection='ASC';
      objMassUpdate.getsortDirection();
      objMassUpdate.setsortDirection('ASC');
      objMassUpdate.sortField=null;
      objMassUpdate.sorting();      
      objMassUpdate.APCList=listAsso;
         
  }
  
}