profilelist1exp/unpackaged/objects/Calendar_Management__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Record_type__c</fullName>
        <label>Event Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Site__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Rooms</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Select_Site__c</field>
                <operation>equals</operation>
                <valueField>$Source.Site__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Calendar Management</relationshipLabel>
        <relationshipName>Calendar_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Calendar Management (Site)</relationshipLabel>
        <relationshipName>Calendar_Management_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendar Management</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Engagement_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Architectural Design Session</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Analyst Events</fullName>
                </value>
                <value>
                    <fullName>Field Briefing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Room_Occupancy__c</fullName>
        <label>Room Occupancy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room_Type__c</fullName>
        <label>Room Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                    <default>true</default>
                    <label>Single</label>
                </value>
                <value>
                    <fullName>Double</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Rooms&amp;Tours</relationshipLabel>
        <relationshipName>Select_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <recordTypes>
        <fullName>Rooms</fullName>
        <active>true</active>
        <description>Select this for creating a new room</description>
        <label>Rooms</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <description>Select this for creating a new site</description>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AddMultipleRoomsControllerTest.cls
@isTest 
private class AddMultipleRoomsControllerTest {
    static List<Calendar_Management__c> testCalendarManagements=new List<Calendar_Management__c>();
    
    static Event_Location__c testSite1=new Event_Location__c();
    static Event_Location__c testSite2=new Event_Location__c();
    static Event_Location__c testRoom1=new Event_Location__c();
    static Event_Location__c testRoom2=new Event_Location__c();
    static Event_Location__c testRoom3=new Event_Location__c();
    static Calendar_Management__c testCalendarManagement1;
    
    private static testmethod void createSiteRoomTour(){
        List<RecordType> recordtypelist=[select id,name,SobjectType  from RecordType  WHERE (SobjectType='Calendar_Management__c' or sObjectType='Event_Location__c' ) and (name='Sites' OR name='Rooms' or name='Primary Calendar RT' or name='Secondary Calendar RT' )];
        Map<String, Id> recordTypeIdMap= new Map<String, Id>();
        for(RecordType r:recordtypelist){
            recordTypeIdMap.put(r.name,r.Id);
        }
    
            List<Event_Location__c> testSiteRoomTour1=new List<Event_Location__c>();    
            /*create test site */
            
            testSite1=new Event_Location__c(Name='testSite11',Region__c='Americas',Engagement_Type__c='EBC',Event__c='Briefing;vEBC;IT Conference Call;Tour',recordTypeid=recordTypeIdMap.get('Sites'),Active__c=true);
            testSiteRoomTour1.add(testSite1);
            testSite2=new Event_Location__c(Name='testSite22',Region__c='Americas',Engagement_Type__c='EBC',Event__c='Briefing;vEBC;IT Conference Call;Tour',recordTypeid=recordTypeIdMap.get('Sites'),Active__c=true);
            testSiteRoomTour1.add(testSite2);
            
            insert testSiteRoomTour1;
            /*create test rooms*/
            
            List<Event_Location__c> testSiteRoomTour=new List<Event_Location__c>();    
            testRoom1=new Event_Location__c(Name='testRoom1',Room_Occupancy__c='15',Room_Type__c='Single',Select_Site__c=testSite1.Id,recordTypeid=recordTypeIdMap.get('Rooms'),Active__c=true);
            testSiteRoomTour.add(testRoom1);
            testRoom2=new Event_Location__c(Name='testRoom2',Room_Occupancy__c='20',Room_Type__c='Double',Select_Site__c=testSite1.Id,recordTypeid=recordTypeIdMap.get('Rooms'),Active__c=true);
            testSiteRoomTour.add(testRoom2);
            testRoom3=new Event_Location__c(Name='testRoom3',Room_Occupancy__c='20',Room_Type__c='Double',Select_Site__c=testSite2.Id,recordTypeid=recordTypeIdMap.get('Rooms'),Active__c=true);
            testSiteRoomTour.add(testRoom3);
        
            insert testSiteRoomTour;
    }
    
    private static testmethod void createSiteWithoutRoom(){
        List<RecordType> recordtypelist=[select id,name,SobjectType  from RecordType  WHERE (SobjectType='Calendar_Management__c' or sObjectType='Event_Location__c' ) and (name='Sites' OR name='Rooms' or name='Primary Calendar RT' or name='Secondary Calendar RT' )];
        Map<String, Id> recordTypeIdMap= new Map<String, Id>();
        for(RecordType r:recordtypelist){
            recordTypeIdMap.put(r.name,r.Id);
        }
            List<Event_Location__c> testSiteRoomTour1=new List<Event_Location__c>();    
            /*create test site */
            
            testSite1=new Event_Location__c(Name='testSite11',Region__c='Americas',Engagement_Type__c='EBC',Event__c='Briefing;vEBC;IT Conference Call;Tour',recordTypeid=recordTypeIdMap.get('Sites'),Active__c=true);
            testSiteRoomTour1.add(testSite1);
            testSite2=new Event_Location__c(Name='testSite22',Region__c='Americas',Engagement_Type__c='EBC',Event__c='Briefing;vEBC;IT Conference Call;Tour',recordTypeid=recordTypeIdMap.get('Sites'),Active__c=true);
            testSiteRoomTour1.add(testSite2);
            insert testSiteRoomTour1;
    }
    
    private static testmethod void  createTestCalendarManagements(){
        testCalendarManagement1=new Calendar_Management__c(Site__c=testSite1.Id,Room__c=testRoom1.Id,Event_Record_type__c='IT Conference Call',Date__c=System.today()+30,Start_Date__c=System.today()+30,End_Date__c=System.today()+30,Status__c='Pending');
        testCalendarManagements.add(testCalendarManagement1);
        
        insert testCalendarManagements;
    }
    
    static testMethod void  myUnitTestAddMultipleRoomsControllerTest() {
    	List<String> lstOfAvailRooms = new List<String>();
    	lstOfAvailRooms.add(testRoom1.Id);
    	lstOfAvailRooms.add(testRoom2.Id);
    	lstOfAvailRooms.add(testRoom3.Id);
        createSiteRoomTour();
        createTestCalendarManagements();
        AddMultipleRoomsController addMultipleRoomsControllerObj = new AddMultipleRoomsController(new ApexPages.StandardController(testCalendarManagement1));
        Test.startTest();
        addMultipleRoomsControllerObj.getRoomDispaly();
        addMultipleRoomsControllerObj.getavailableRooms();
        addMultipleRoomsControllerObj.setavailableRooms(lstOfAvailRooms);
        addMultipleRoomsControllerObj.availableRooms.add(testRoom2.Id);
        addMultipleRoomsControllerObj.createRecords();
        testCalendarManagement1.Site__c=testSite2.Id;
        testCalendarManagement1.Room__c=testRoom3.Id;
        update testCalendarManagement1;
        Test.stopTest();
    }
    
    static testMethod void  testAddMultipleRoomsControllerWithoutRooms() {
        createSiteWithoutRoom();
        createTestCalendarManagements();
        AddMultipleRoomsController addMultipleRoomsControllerObj = new AddMultipleRoomsController(new ApexPages.StandardController(testCalendarManagement1));
        Test.startTest();
        addMultipleRoomsControllerObj.getRoomDispaly();
        addMultipleRoomsControllerObj.availableRooms.add(testRoom2.Id);
        addMultipleRoomsControllerObj.createRecords();
        testCalendarManagement1.Site__c=testSite2.Id;
        testCalendarManagement1.Room__c=testRoom3.Id;
        update testCalendarManagement1;
        Test.stopTest();
    }
    
    //Test Method for Recurrance Controller
    
    /*static testMethod void  myUnitTestRecurranceControllerTest() {
        createSiteRoomTour();
        createTestCalendarManagements();
        RecurranceController recurranceControllerObj = new RecurranceController(new ApexPages.StandardController(testCalendarManagement1));
        recurranceControllerObj.getType();
        recurranceControllerObj.getOccursonWeek();
        recurranceControllerObj.displayOptions();
        recurranceControllerObj.calMngmntObj.Recurring_Till__c=System.today()+90;
        Test.startTest();
        
        recurranceControllerObj.recuranceType='Daily';
        recurranceControllerObj.OccursonDay=2;
        recurranceControllerObj.createRecurringRecords();
        
        recurranceControllerObj.recuranceType='Weekly';
        recurranceControllerObj.occurson.add('2');
        recurranceControllerObj.occurson.add('3');
        recurranceControllerObj.createRecurringRecords();
        
        recurranceControllerObj.recuranceType='Monthly';
        recurranceControllerObj.OccursonDayofMonth=31;
        recurranceControllerObj.createRecurringRecords();
        
        Test.stopTest();
        
    }*/

}