profilelist1exp/unpackaged/objects/Case_Status_History__c.object
<CustomObject>
    <fields>
        <fullName>Case_Id__c</fullName>
        <label>Case Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case_Status_Histories</relationshipLabel>
        <relationshipName>Case_Status_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_In__c</fullName>
        <label>Time In</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <label>Time Out</label>
        <type>DateTime</type>
    </fields>
    <label>Case_Status_History</label>
    <nameField>
        <label>Case_Status_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Status_Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Trigger_Handler__mdt.object
<CustomObject>
    <description>A trigger handler class to run on the given sObject and trigger event</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>The Apex class to run</description>
        <inlineHelpText>The Apex class to run</inlineHelpText>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Trigger event to run this handler</description>
        <inlineHelpText>Trigger event to run this handler</inlineHelpText>
        <label>Event</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                    <default>true</default>
                    <label>BeforeInsert</label>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>BeforeUndelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <description>The sObject to run the handler on</description>
        <inlineHelpText>The sObject to run the handler on</inlineHelpText>
        <label>sObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trigger Handler</label>
    <pluralLabel>Trigger Handlers</pluralLabel>
</CustomObject>

profilelist1exp/unpackaged/objects/TriggerExecutionControl__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>RecursiveCount__c</fullName>
        <defaultValue>4</defaultValue>
        <description>Specifies total number of recursive execution.
Setting this value to 1 =&gt; Skips the recursive execution initiated because of Workflow Field Updates.</description>
        <label>Recursive Count</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trigger Execution Control</label>
</CustomObject>

profilelist1exp/unpackaged/classes/CaseHistTriggerHandlerAITest.cls
/* 
History:
Version Release         CR #        Date            Modified By     Description     
1.0		0102						04-Dec-2019		Vikas KH		Implemented TDF
*/

@IsTest
public class CaseHistTriggerHandlerAITest {
    @testsetup static void setup() { 
        list<case> listcasefromTDF=TestDataFactory.createNCases(1);
        TriggerExecutionController.setSkipAllTriggers(true);
        insert listcasefromTDF;
    }            
    static testmethod void caseHistInsertTest(){
        String strMockMetaData = '';
        Map<String, List<Boolean>> mapEvents = new Map<String, List<Boolean>> {
            'AfterInsert' => new List<Boolean>{false, false, true, false, false}
        };
            for(String strEvent : mapEvents.keySet()) {
                strMockMetaData += '{"DeveloperName": "TestHandler' + strEvent + '", '
                    + '"NamespacePrefix": "",'
                    + '"Event__c": "' + strEvent + '", '
                    + '"sObject__c": "Case_Status_History__c", "Class_Name__c": "CaseHistTriggerHandlerAI"},';
            }
        strMockMetaData = '[' + strMockMetaData.substringBeforeLast(',') + ']';
        MetadataTriggerManager.listMockMetaData = (List<Trigger_Handler__mdt>)JSON.deserializeStrict(strMockMetaData, List<Trigger_Handler__mdt>.class);       
        TriggerExecutionControl__c tec = new TriggerExecutionControl__c();
        tec.Name = 'Case_Status_History__c';
        tec.RecursiveCount__c = 2;
        insert tec;
        list<case> listCase=[select id from case];
        for(case c:listCase){
            c.Subject = 'Unit Testing'; 
        }
        update listCase;
        Case_Status_History__c csh = new Case_Status_History__c(Name = 'test1',
                                                                Case__c = listcase[0].Id,
                                                                Case_Id__c = listcase[0].Id,
                                                                Status__c = 'Completed',
                                                                Duration__c  = 8,
                                                                Time_In__c  = Datetime.now(),
                                                                Time_Out__c = Datetime.now());
        Insert csh;
        Case_Status_History__c csh1 = new Case_Status_History__c(Name = 'test2',
                                                                 Case__c = listcase[0].Id,
                                                                 Case_Id__c = listcase[0].Id,
                                                                 Status__c = 'Closed',
                                                                 Duration__c  = 8,
                                                                 Time_In__c  = Datetime.now(),
                                                                 Time_Out__c = Datetime.now());
        Insert csh1;
        system.assertNotEquals(Null, listCase[0].subject);
    }
}