profilelist1exp/unpackaged/objects/Certification_Criteria_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Criteria_Name__c</fullName>
        <label>Competency Criteria Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Sales Training</fullName>
                </value>
                <value>
                    <fullName>Second Sales Training</fullName>
                </value>
                <value>
                    <fullName>Third Sales Training</fullName>
                </value>
                <value>
                    <fullName>Fourth Sales Training</fullName>
                </value>
                <value>
                    <fullName>First Technical Training</fullName>
                </value>
                <value>
                    <fullName>Second Technical Training</fullName>
                </value>
                <value>
                    <fullName>Third Technical Training</fullName>
                </value>
                <value>
                    <fullName>Fourth Technical Training</fullName>
                </value>
                <value>
                    <fullName>Demo Unit</fullName>
                </value>
                <value>
                    <fullName>General Training Criteria</fullName>
                </value>
                <value>
                    <fullName>Approved Business Plan</fullName>
                </value>
                <value>
                    <fullName>Contractual Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certification_Criteria_Order__c</fullName>
        <label>Competency Criteria Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Certification_Criteria_Value__c</fullName>
        <inlineHelpText>Please enter a valid Demo Unit Type EQL Demo or KACE Demo or Compellent Demo or Networking Demo for Demo Unit Criteria.
Please enter Y for Yes and N for No for Approved Business Plan and Contractual Agreement. Note that the entries are case sensitive</inlineHelpText>
        <label>Competency Criteria Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Requirement_Setup__c</fullName>
        <label>Compentency Requirement Setup</label>
        <referenceTo>Certification_Requirement_Setup__c</referenceTo>
        <relationshipLabel>Competency Criteria Setups</relationshipLabel>
        <relationshipName>Certification_Criteria_Setups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Any 1</fullName>
                </value>
                <value>
                    <fullName>Any 2</fullName>
                </value>
                <value>
                    <fullName>Any 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria_Value_Ids__c</fullName>
        <description>Hidden field to store Course Ids for respective Certification Criteria Value.</description>
        <inlineHelpText>For courses that needs AND between courses , replace OR with AND . Ensure there is a space before and after AND. DON&apos;T EDIT ANY OTHER VALUES ON THE FIELD.</inlineHelpText>
        <label>Criteria Value Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Demo_Units__c</fullName>
        <inlineHelpText>Enter a valid positive number</inlineHelpText>
        <label>Number of Demo Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competency Criteria Setup</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Competency Criteria Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competency Criteria Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Certification_Requirement_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check to keep Requirement Active.</description>
        <inlineHelpText>Check to keep Requirement Active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Requirement_To__c</fullName>
        <description>Choose Global or Country or Region</description>
        <inlineHelpText>Choose Global or Country or Region</inlineHelpText>
        <label>Apply Requirement To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <description>Choose Name</description>
        <inlineHelpText>Choose Competency Name</inlineHelpText>
        <label>Competency Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Data Center Networking</fullName>
                </value>
                <value>
                    <fullName>Cloud Client-Computing</fullName>
                </value>
                <value>
                    <fullName>Cloud Solutions</fullName>
                </value>
                <value>
                    <fullName>Client Solutions</fullName>
                </value>
                <value>
                    <fullName>Workstation</fullName>
                </value>
                <value>
                    <fullName>Microsoft Platform Management</fullName>
                </value>
                <value>
                    <fullName>Endpoint Management</fullName>
                </value>
                <value>
                    <fullName>Network Security</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Data Protection</fullName>
                </value>
                <value>
                    <fullName>PS Series Storage Deployment</fullName>
                </value>
                <value>
                    <fullName>SC Series Storage Deployment</fullName>
                </value>
                <value>
                    <fullName>Networking</fullName>
                </value>
                <value>
                    <fullName>Big Data and Analytics</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>EMEA-EM - Preferred Partner</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA English</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA Portuguese</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA Spanish</fullName>
                </value>
                <value>
                    <fullName>Data Protection Adv Comp</fullName>
                </value>
                <value>
                    <fullName>Info Mgmnt–Application&amp;DataIntegration</fullName>
                </value>
                <value>
                    <fullName>Info Mgmnt–Biz Inteligence&amp;DataAnalytics</fullName>
                </value>
                <value>
                    <fullName>Security–Identity&amp;Access Mgmnt Adv Comp</fullName>
                </value>
                <value>
                    <fullName>Storage Adv Comp</fullName>
                </value>
                <value>
                    <fullName>Client Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>PowerEdge Servers Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>Client Data Security</fullName>
                </value>
                <value>
                    <fullName>OEM Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Competency Requirement Setup</label>
    <nameField>
        <label>Competency Requirement Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency Requirement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Demo_Unit__c.object
<CustomObject>
    <description>This object will contain information about the demo units.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Demo_Unit_Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Demo Unit Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Demo_Unit_Setup__c.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Demo_Unit_Setup__c</referenceTo>
        <relationshipLabel>Demo Units</relationshipLabel>
        <relationshipName>Demo_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Name__c</fullName>
        <label>Partner Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Demo Units</relationshipLabel>
        <relationshipName>Demo_Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TSR_Name__c</fullName>
        <label>TSR Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Demo Unit</label>
    <nameField>
        <displayFormat>Du-{0000000}</displayFormat>
        <label>Demo Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Demo_Unit_Setup__c.object
<CustomObject>
    <description>This object will contain information about the demo unit Setup.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Demo Unit Setup</label>
    <nameField>
        <label>Demo Unit Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Unit Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Course__c.object
<CustomObject>
    <description>Partner course details from Netexam
Tick Allow Reports, Allow Activities, Track Field History
Click Save</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Courses</relationshipLabel>
        <relationshipName>Partner_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Partner Courses</relationshipLabel>
        <relationshipName>Partner_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Completed_Date__c</fullName>
        <label>Course Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Score__c</fullName>
        <label>Course Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Partner Courses</relationshipLabel>
        <relationshipName>Partner_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Course__c</fullName>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Partner Course</label>
        <type>AutoNumber</type>
    </fields>
    <label>Partner Course</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Partner Course Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerCertDataStructuresTest.cls
@isTest
private class PartnerCertDataStructuresTest{
  static list<Course__c>  listCourse;
  static list<Account> listAcc;
  static list<contact> listCon;
  static list<Demo_Unit__c> listDemo;
  static list<Demo_Unit_Setup__c> listDemoset;
  static list<Partner_Course__c> listpartnercourse;
  static list<Certification_Criteria_Setup__c> listcertCriteriaSetup;
  static list<Certification_Requirement_Setup__c> listcertReqSetup;
    @testSetup static void setup(){
        list<Account> listAccTDF = TestDataFactory.createNAccount(1,'Partner Account');
        listAccTDF[0].status__c = 'Active';
        listAccTDF[0].Account_Country_Code__c='US';
        listAccTDF[0].Partner_Relationship__c='Registered';     
        insert listAccTDF;
        system.debug('listAccTDF>>>>>'+listAccTDF);
        list<contact> listconTDF = TestDataFactory.createNContacts(1);
        listconTDF[0].accountid = listAccTDF[0].id;
        insert listconTDF;
        List<Demo_Unit_Setup__c> listDemosetupTDF =  TestDataFactory.createNDemoUnitSetup(1);
        insert listDemosetupTDF;
        system.debug('listDemosetupTDF>>>>'+listDemosetupTDF);
        list<Demo_Unit__c> listDemoTDF = TestDataFactory.createNDemounit(2);
        listDemoTDF[0].Demo_Unit_Setup__c = listDemosetupTDF[0].Id;
        listDemoTDF[0].Partner_Account_Name__c = listAccTDF[0].id;
        listDemoTDF[0].TSR_Name__c = 'Doyle';
        listDemoTDF[0].Contact_Name__c = 'Doyle';
        listDemoTDF[1].Demo_Unit_Setup__c = listDemosetupTDF[0].Id;
        listDemoTDF[1].Partner_Account_Name__c = listAccTDF[0].id;
        listDemoTDF[1].TSR_Name__c = 'Doyle';
        listDemoTDF[1].Contact_Name__c = 'Doyle';
       insert listDemoTDF; 
        system.debug('listDemoTDF>>>>'+listDemoTDF);
        list<Course__c>  listCourseTDF = TestDataFactory.createNCourse(1);
        insert listCourseTDF;
        system.debug('listCourseTDF>>>'+listCourseTDF);
        List<Partner_Course__c> listpartnercourseTDF =  TestDataFactory.createNPartnerCourse(2);
        listpartnercourseTDF[0].Contact__c = listConTDF[0].id;
        listpartnercourseTDF[0].Account__c = listAccTDF[0].id;
        listpartnercourseTDF[0].Course__c = listCourseTDF[0].id;
        listpartnercourseTDF[0].Course_Completed_Date__c = System.today()-7;
        listpartnercourseTDF[0].Course_Score__c = 2;
        listpartnercourseTDF[1].Contact__c = listConTDF[0].id;
        listpartnercourseTDF[1].Account__c = listAccTDF[0].id;
        listpartnercourseTDF[1].Course__c = listCourseTDF[0].id;
        listpartnercourseTDF[1].Course_Completed_Date__c = System.today()-7;
        listpartnercourseTDF[1].Course_Score__c = 2;
        insert listpartnercourseTDF;
        list<Certification_Requirement_Setup__c> listcertReqSetupTDF = TestDataFactory.createNCertificationReqSetUp(1);
        listcertReqSetupTDF[0].name='newcertreqsetup';
        listcertReqSetupTDF[0].Apply_Requirement_To__c='Global';
        listcertReqSetupTDF[0].Certification_Name__c = 'Server Certified';
        insert listcertReqSetupTDF[0];
        list<Certification_Criteria_Setup__c> listcertCriteriaSetupTDF = TestDataFactory.createNCertificationCriteriaSetup(4);
        listcertCriteriaSetupTDF[0].Certification_Criteria_Name__c = 'Demo Unit';
        listcertCriteriaSetupTDF[0].Certification_Criteria_Value__c = 'EQL Demo';
        listcertCriteriaSetupTDF[0].Criteria_Value_Ids__c = listDemosetupTDF[0].Id;
        listcertCriteriaSetupTDF[0].Certification_Requirement_Setup__c = listcertReqSetupTDF[0].id;
        listcertCriteriaSetupTDF[0].Number_of_Demo_Units__c = 1;
        listcertCriteriaSetupTDF[0].Certification_Criteria_Order__c = 2;
        listcertCriteriaSetupTDF[1].Certification_Criteria_Name__c = 'First Sales Training';
        listcertCriteriaSetupTDF[1].Condition__c = 'All';
        listcertCriteriaSetupTDF[1].Certification_Criteria_Value__c = 'Blades Server';
        listcertCriteriaSetupTDF[1].Criteria_Value_Ids__c = '101';
        listcertCriteriaSetupTDF[1].Certification_Requirement_Setup__c = listcertReqSetupTDF[0].id;
        listcertCriteriaSetupTDF[1].Certification_Criteria_Order__c = 3;
        listcertCriteriaSetupTDF[2].Certification_Criteria_Name__c = 'First Technical Training';
        listcertCriteriaSetupTDF[2].Condition__c = 'All';
        listcertCriteriaSetupTDF[2].Certification_Criteria_Value__c = 'Blades Server';
        listcertCriteriaSetupTDF[2].Criteria_Value_Ids__c = '101';
        listcertCriteriaSetupTDF[2].Certification_Requirement_Setup__c = listcertReqSetupTDF[0].id;
        listcertCriteriaSetupTDF[2].Certification_Criteria_Order__c = 1;
        listcertCriteriaSetupTDF[3].Certification_Criteria_Name__c = 'General Training Criteria';
        listcertCriteriaSetupTDF[3].Certification_Criteria_Value__c = 'Blades Server';
        listcertCriteriaSetupTDF[3].Criteria_Value_Ids__c = '101';
        listcertCriteriaSetupTDF[3].Certification_Requirement_Setup__c = listcertReqSetupTDF[0].id;
        listcertCriteriaSetupTDF[3].Certification_Criteria_Order__c = 4;
		insert listcertCriteriaSetupTDF;

    }  

    public static testmethod void testPartnerCertDataStructures(){
    /*    Account acc = new Account();
        acc.name = 'Some test Account';        
        acc.status__c = 'Active';
        acc.Account_Country_Code__c='US';
        acc.Partner_Relationship__c='Registered';  
        acc.RecordTypeid = [select Id from RecordType where SobjectType = 'Account' and Name = 'Partner Account'].id;    
        insert acc;
               
        Contact con = new Contact();
        con.lastname = 'Langley';
        con.email = 'langley@xyz.com';
        con.accountid = acc.id;
        insert con;
        
        Demo_Unit_Setup__c duseql = new Demo_Unit_Setup__c(
                    Name = 'EQL Demo',
                    Active__c = true);
        insert duseql;
        
        Demo_Unit__c demoUnit = new Demo_Unit__c();
        //demoUnit.Demo_Unit_Type__c = 'EQL Demo';
        demoUnit.Demo_Unit_Setup__c = duseql.Id;
        demoUnit.Order_Number__c = '123';
        demoUnit.Order_Date__c = System.today();
        demoUnit.T_C__c = 'Yes';
        demoUnit.Partner_Account_Name__c = acc.id;
        demoUnit.TSR_Name__c = 'Doyle';
        demoUnit.Contact_Name__c = 'Doyle';
        demoUnit.Contact_Email__c = 'doyle@xyz.com';
        insert demoUnit;
        
        Demo_Unit__c demoUnit2 = new Demo_Unit__c();
        //demoUnit2.Demo_Unit_Type__c = 'EQL Demo';
        demoUnit2.Demo_Unit_Setup__c = duseql.Id;
        demoUnit2.Order_Number__c = '123';
        demoUnit2.Order_Date__c = System.today();
        demoUnit2.T_C__c = 'Yes';
        demoUnit2.Partner_Account_Name__c = acc.id;
        demoUnit2.TSR_Name__c = 'Doyle';
        demoUnit2.Contact_Name__c = 'Doyle';
        demoUnit2.Contact_Email__c = 'doyle@xyz.com';
        insert demoUnit2;

        Course__c course= new Course__c();
        course.Course_Name__c = 'Blades Server';
        course.Credit_Hours__c = 8;
        course.Course_ID__c = '101';
        course.Course_Type__c = 'Elearning';
        course.Course_Modality__c = 'ELearning';
        course.Course_Description__c = 'Dell sales';
        insert course;
      */
        listAcc =  [select id from Account limit 1];
        system.assertEquals(listAcc[0].id, listAcc[0].id);
        listcon  = [select id from Contact limit 1];
        listDemoset = [select id from Demo_Unit_Setup__c limit 1];
        listCourse = [select id from Course__c limit 1 ];
        listpartnercourse = [select id,Contact__c,Account__c,Course__c from Partner_Course__c limit 2];
        listcertReqSetup = [select id,Apply_Requirement_To__c,Certification_Name__c,name from Certification_Requirement_Setup__c limit 1];
        listcertCriteriaSetup = [select id,Certification_Criteria_Name__c,Criteria_Value_Ids_PostFixFormat__c,Certification_Criteria_Value__c,Criteria_Value_Ids__c,Certification_Requirement_Setup__c,Number_of_Demo_Units__c,Certification_Criteria_Order__c from Certification_Criteria_Setup__c limit 4];
     /*   Partner_Course__c pc = new Partner_Course__c();
        pc.Contact__c = listCon[0].id;
        pc.Account__c = listAcc[0].id;
        pc.Course__c = listCourse[0].id;
        pc.Course_Completed_Date__c = System.today()-7;
        pc.Course_Score__c = 2;
        insert pc;
        
        Partner_Course__c pc2 = new Partner_Course__c();
        pc2.Contact__c = listCon[0].id;
        pc2.Account__c = listAcc[0].id;
        pc2.Course__c = listCourse[0].id;
        pc2.Course_Completed_Date__c = System.today()-7;
        pc2.Course_Score__c = 2;
        insert pc2;

        Certification_Requirement_Setup__c certReqSetup = new Certification_Requirement_Setup__c();
        certReqSetup.name='newcertreqsetup';
        certReqSetup.Apply_Requirement_To__c='Global';
        certReqSetup.Certification_Name__c = 'Server Certified';
        insert certReqSetup;
        
        Certification_Criteria_Setup__c certCriteriaSetup = new Certification_Criteria_Setup__c();
        certCriteriaSetup.Certification_Criteria_Name__c = 'Demo Unit';
        certCriteriaSetup.Certification_Criteria_Value__c = 'EQL Demo';
        certCriteriaSetup.Criteria_Value_Ids__c = listDemoset[0].Id;
        certCriteriaSetup.Certification_Requirement_Setup__c = certReqSetup.id;
        certCriteriaSetup.Number_of_Demo_Units__c = 1;
        certCriteriaSetup.Certification_Criteria_Order__c = 2;
        insert certCriteriaSetup;

        Certification_Criteria_Setup__c certCriteriaSetup2 = new Certification_Criteria_Setup__c();
        certCriteriaSetup2.Certification_Criteria_Name__c = 'First Sales Training';
        certCriteriaSetup2.Condition__c = 'All';
        certCriteriaSetup2.Certification_Criteria_Value__c = 'Blades Server';
        certCriteriaSetup2.Criteria_Value_Ids__c = '101';
        certCriteriaSetup2.Certification_Requirement_Setup__c = certReqSetup.id;
        certCriteriaSetup2.Certification_Criteria_Order__c = 3;
        insert certCriteriaSetup2;

        Certification_Criteria_Setup__c certCriteriaSetup3 = new Certification_Criteria_Setup__c();
        certCriteriaSetup3.Certification_Criteria_Name__c = 'First Technical Training';
        certCriteriaSetup3.Condition__c = 'All';
        certCriteriaSetup3.Certification_Criteria_Value__c = 'Blades Server';
        certCriteriaSetup3.Criteria_Value_Ids__c = '101';
        certCriteriaSetup3.Certification_Requirement_Setup__c = certReqSetup.id;
        certCriteriaSetup3.Certification_Criteria_Order__c = 1;
        insert certCriteriaSetup3;

        Certification_Criteria_Setup__c certCriteriaSetup4 = new Certification_Criteria_Setup__c();
        certCriteriaSetup4.Certification_Criteria_Name__c = 'General Training Criteria';
        certCriteriaSetup4.Certification_Criteria_Value__c = 'Blades Server';
        certCriteriaSetup4.Criteria_Value_Ids__c = '101';
        certCriteriaSetup4.Certification_Requirement_Setup__c = certReqSetup.id;
        certCriteriaSetup4.Certification_Criteria_Order__c = 4;
        insert certCriteriaSetup4;
*/
        PartnerCertDataStructures certds = new PartnerCertDataStructures();
        PartnerCertDataStructures.Accountdata accdata = new PartnerCertDataStructures.Accountdata(listAcc[0].id);
        PartnerCertDataStructures.Criteria criteria = new PartnerCertDataStructures.Criteria();
        PartnerCertDataStructures.Criteria criteria2 = new PartnerCertDataStructures.Criteria(listcertCriteriaSetup[0]);
        PartnerCertDataStructures.Criteria criteria3 = new PartnerCertDataStructures.Criteria(listcertCriteriaSetup[1]);
        PartnerCertDataStructures.Criteria criteria4 = new PartnerCertDataStructures.Criteria(listcertCriteriaSetup[2]);
        PartnerCertDataStructures.Criteria criteria5 = new PartnerCertDataStructures.Criteria(listcertCriteriaSetup[3]);
        PartnerCertDataStructures.DemoCriteria demoCriteria = new PartnerCertDataStructures.DemoCriteria();
        PartnerCertDataStructures.CriteriaWithExpression criteriaExp = new PartnerCertDataStructures.CriteriaWithExpression('first;second;third',';');
        
    }
}