profilelist1exp/unpackaged/objects/Certification_Prerequisites_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Requirement_Setup__c</fullName>
        <label>Competency Requirement Setup</label>
        <referenceTo>Certification_Requirement_Setup__c</referenceTo>
        <relationshipName>Certification_Prerequisites_Setups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Any 1</fullName>
                </value>
                <value>
                    <fullName>Any 2</fullName>
                </value>
                <value>
                    <fullName>Any 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prerequisites_Ids__c</fullName>
        <label>Prerequisites_Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Prerequisites__c</fullName>
        <label>Prerequisites</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Competency Prerequisites Setup</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>Competency Prerequisites Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competency Prerequisites Setups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Certification_Requirement_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Prerequisites__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Competencies consist of Prerequisites</description>
        <inlineHelpText>Check if requirement consist of prerequisites courses/competencies</inlineHelpText>
        <label>Prerequisites</label>
        <type>Checkbox</type>
    </fields>
    <label>Competency Requirement Setup</label>
    <nameField>
        <label>Competency Requirement Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency Requirement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VFCntrlr_CertPrerequisite.cls
public with sharing class VFCntrlr_CertPrerequisite {
    private Certification_Prerequisites_Setup__c cpSetup;  
           
    public Integer OptionNum{get;set;}
    public boolean chkSelectAll {get; set;}

    //Table Row Class for initiallising values.
    public class TableRow{      
        public string crOption{get;set;}        
        public Boolean isSelected{get;set;}
        public integer OptionNumber{get; set;}
        public String Course_code {get;set;}
        
        public TableRow(String cr,string code, boolean sel, integer cnt){
            crOption = cr;           
            Course_code =code;
            isSelected = sel;
            OptionNumber = cnt;
        }
    }
    List<TableRow> certCriteria {get; set;}
    
    public List<TableRow> getCertTraining(){     
        certCriteria = new List<TableRow>(); 
        Integer cnt = 1;  
        
        if (cpSetup.Prerequisites__c!= null){
            list<String> cCodeLst = cpSetup.Prerequisites_Ids__c.split(';');           
            for (String str : cpSetup.Prerequisites__c.split(';')){
                if (str.trim() != ''){
                    //String s = str.remove('[');
                    //s = str.remove(']');
                    str = str.replace(' [OR] ',' OR ');
                    str = str.replace(' [AND] ',' AND ');
                    
                    certCriteria.Add(new TableRow(str,cCodeLst.get(cnt-1), false, cnt));
                    cnt++;
                }
            }           
        }
        return certCriteria;        
    }

    public VFCntrlr_CertPrerequisite(ApexPages.StandardController stdController){
        Id id = ApexPages.currentPage().getParameters().get('id');
              
        cpSetup = (id == null) ? new Certification_Prerequisites_Setup__c() : 
                    [select Name,Certification_Requirement_Setup__c,       
                         Prerequisites__c, Condition__c, Prerequisites_Ids__c
                         from Certification_Prerequisites_Setup__c
                         where id = :id ];
             
        if (id == null){
            String lkid = null; 
            lkid = ApexPages.currentPage().getParameters().get('retURL');
            try{
              if (lkid != null && lkid != ''){            
                lkid = lkid.substring(1, lkid.length());    
                  cpSetup.Certification_Requirement_Setup__c =  lkid ;
                }
            }
            catch(Exception e){
            }     
        }
        chkSelectAll = false;
    }
    public void SavePrerequisite(){
        try {
            upsert(cpSetup);
        } 
        catch(System.DMLException e) {
            ApexPages.addMessages(e);  
        } 
    }
    public PageReference save() {
        SavePrerequisite();        
        return null;   
    } 
    public PageReference saveClose() {
        SavePrerequisite();
        return (new ApexPages.StandardController(cpSetup)).view();      
    }   
    
    public PageReference deleteCourse() {     
        string tmp='';
        string tmpCode='';            
        for (Integer i =0; i < certCriteria.size();i++) {       
            if(certCriteria.get(i).isSelected){

                //System.debug('true');                                                
            }
            else{
                if(tmp==''){           
                    tmp = certCriteria.get(i).crOption;                  
                    tmpCode= certCriteria.get(i).Course_code ;                  
                }
                else{
                    tmp = tmp + ';' + certCriteria.get(i).crOption;
                    tmpCode= tmpCode+ ';' + certCriteria.get(i).Course_code ;
                }
            }            
        }
        cpSetup.Prerequisites__c= tmp;  
        cpSetup.Prerequisites_Ids__c= tmpCode;                 
        chkSelectAll = false;  
        return null;    
    }
    
    public pageReference delCourse(){
        string tmp='';
        string tmpCode='';
                 
        //compare option number and cnt
        for (Integer i =0; i < certCriteria.size();i++) {
            if(i == (OptionNum-1)){
                //system.debug('true' +i);
            }
            else{
                if(tmp==''){           
                    tmp = certCriteria.get(i).crOption;                  
                    tmpCode= certCriteria.get(i).Course_code ;                  
                }
                else{
                    tmp = tmp + ';' + certCriteria.get(i).crOption;
                    tmpCode= tmpCode+ ';' + certCriteria.get(i).Course_code ;
                }
            }
        }
        cpSetup.Prerequisites__c= tmp;  
        cpSetup.Prerequisites_Ids__c= tmpCode;        
        chkSelectAll = false;  
        return null;
    }       
   //.............................
   public Certification_Prerequisites_Setup__c getcpSetup() {
        return cpSetup;

    } 

}