profilelist1exp/unpackaged/objects/Certification_Requirement_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Apply_Requirement_To__c</fullName>
        <description>Choose Global or Country or Region</description>
        <inlineHelpText>Choose Global or Country or Region</inlineHelpText>
        <label>Apply Requirement To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <description>Choose Name</description>
        <inlineHelpText>Choose Competency Name</inlineHelpText>
        <label>Competency Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Data Center Networking</fullName>
                </value>
                <value>
                    <fullName>Cloud Client-Computing</fullName>
                </value>
                <value>
                    <fullName>Cloud Solutions</fullName>
                </value>
                <value>
                    <fullName>Client Solutions</fullName>
                </value>
                <value>
                    <fullName>Workstation</fullName>
                </value>
                <value>
                    <fullName>Microsoft Platform Management</fullName>
                </value>
                <value>
                    <fullName>Endpoint Management</fullName>
                </value>
                <value>
                    <fullName>Network Security</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Data Protection</fullName>
                </value>
                <value>
                    <fullName>PS Series Storage Deployment</fullName>
                </value>
                <value>
                    <fullName>SC Series Storage Deployment</fullName>
                </value>
                <value>
                    <fullName>Networking</fullName>
                </value>
                <value>
                    <fullName>Big Data and Analytics</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>EMEA-EM - Preferred Partner</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA English</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA Portuguese</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA Spanish</fullName>
                </value>
                <value>
                    <fullName>Data Protection Adv Comp</fullName>
                </value>
                <value>
                    <fullName>Info Mgmnt–Application&amp;DataIntegration</fullName>
                </value>
                <value>
                    <fullName>Info Mgmnt–Biz Inteligence&amp;DataAnalytics</fullName>
                </value>
                <value>
                    <fullName>Security–Identity&amp;Access Mgmnt Adv Comp</fullName>
                </value>
                <value>
                    <fullName>Storage Adv Comp</fullName>
                </value>
                <value>
                    <fullName>Client Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>PowerEdge Servers Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>Client Data Security</fullName>
                </value>
                <value>
                    <fullName>OEM Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose Country</description>
        <inlineHelpText>Choose Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Certification_Requirement_Setups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Choose Region. Duplicate value of Region should not be allowed.</description>
        <inlineHelpText>Choose Region.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apply_Requirement_To__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>---None---</fullName>
                    <default>true</default>
                    <label>---None---</label>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>EMEA-EM</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Competency Requirement Setup</label>
    <nameField>
        <label>Competency Requirement Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency Requirement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Master_Program_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Apply_Requirement_To__c</fullName>
        <description>Choose Global, Country or Region.</description>
        <inlineHelpText>Choose Global, Country or Region.</inlineHelpText>
        <label>Apply Requirement To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <description>Choose Competency Name</description>
        <inlineHelpText>Choose Competency Name</inlineHelpText>
        <label>Competency Name</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Data Center Networking</fullName>
                </value>
                <value>
                    <fullName>Cloud Client-Computing</fullName>
                </value>
                <value>
                    <fullName>Cloud Solutions</fullName>
                </value>
                <value>
                    <fullName>Client Solutions</fullName>
                </value>
                <value>
                    <fullName>Workstation</fullName>
                </value>
                <value>
                    <fullName>Microsoft Platform Management</fullName>
                </value>
                <value>
                    <fullName>Endpoint Management</fullName>
                </value>
                <value>
                    <fullName>Network Security</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Data Protection</fullName>
                </value>
                <value>
                    <fullName>PS Series Storage Deployment</fullName>
                </value>
                <value>
                    <fullName>SC Series Storage Deployment</fullName>
                </value>
                <value>
                    <fullName>Networking</fullName>
                </value>
                <value>
                    <fullName>Big Data and Analytics</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>EMEA-EM - Preferred Partner</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA English</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA Portuguese</fullName>
                </value>
                <value>
                    <fullName>Onboarding - LA Spanish</fullName>
                </value>
                <value>
                    <fullName>Client Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>PowerEdge Servers Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>Client Data Security</fullName>
                </value>
                <value>
                    <fullName>OEM Solutions</fullName>
                </value>
                <value>
                    <fullName>Modular Infrastructure Deployment Services Competency</fullName>
                </value>
                <value>
                    <fullName>Entry Level Storage</fullName>
                </value>
                <value>
                    <fullName>Campus Networking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose Country</description>
        <inlineHelpText>Choose Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Master Program Setups</relationshipLabel>
        <relationshipName>Master_Program_Setups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Choose Region. Duplicate value of Region should not be allowed.</description>
        <inlineHelpText>Choose Region.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apply_Requirement_To__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                    <default>true</default>
                    <label>--None--</label>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>EMEA-EM</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Master Program Setup</label>
    <nameField>
        <label>Master Program Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Program Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VFCntrlr_MasterProgram_ReqList.cls
public with sharing class VFCntrlr_MasterProgram_ReqList {
    //variables for paging
    private static final Integer PAGE_SIZE=10;
    public Integer currentPage {get; private set;}    
    public Integer lastPage {get; private set;}
    public Boolean hasPreviousAndNext;     
    public Boolean hasNext {get; private set;}    
    public Boolean hasPrevious {get; private set;}
    public Integer NoOfRecords {get; private set;}    
    public Id pageID = null;
    //public string appReq = '';
    //public string region = '';
    //public string country = '';
    List<String> certNames = new List<String>();
    
    private List<Certification_Requirement_Setup__c> recReqList = new List<Certification_Requirement_Setup__c>();
    
    public VFCntrlr_MasterProgram_ReqList (ApexPages.StandardController stdController){
         hasNext = false;
         hasPrevious = false;       
         lastPage = 0;
         currentPage= 0;
         NoOfRecords=0;
         pageID = ApexPages.currentPage().getParameters().get('id');         
         system.debug('page id: ' +pageID);
        if(pageID != null){
         Master_Program_Setup__c masterList = [SELECT Certification_Name__c, Apply_Requirement_To__c, Region__c, Country__c 
                                                 FROM Master_Program_Setup__c  
                                                 WHERE id =:pageId];
        
         //appReq = masterList.Apply_Requirement_To__c;
         //region = masterList.Region__c;
         //country = masterList.Country__c;         
         if (masterList.Certification_Name__c != null)
             certNames = masterList.Certification_Name__c.split(';');
         
         recReqList = (List<Certification_Requirement_Setup__c>) this.setCon.getRecords(); 
        }

    }   
    
     private ApexPages.StandardSetController setCon {
     get { 
         if(this.setCon == null) {             
             /*//region - chk region       
             if(appReq == 'Region'){             
                this.setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT id, name, Apply_Requirement_To__c, Certification_Name__c 
                     FROM Certification_Requirement_Setup__c 
                     WHERE Apply_Requirement_To__c =:appReq 
                     AND Region__c  = :region
                     AND Certification_Name__c IN :certNames]));                                     
                system.debug(setCon.getRecords());                    
             }
             //country
             else if(appReq == 'Country'){
                this.setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT id, name, Apply_Requirement_To__c, Certification_Name__c 
                     FROM Certification_Requirement_Setup__c 
                     WHERE Apply_Requirement_To__c =:appReq 
                     AND Country__c =:country
                     AND Certification_Name__c IN :certNames]));
                     system.debug('###country:###' +country);
             }
            //global
            else{}*/ //Checking apply req to
            this.setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                        [SELECT id, name, Apply_Requirement_To__c, Certification_Name__c 
                         FROM Certification_Requirement_Setup__c 
                         WHERE Certification_Name__c IN :certNames]));
                         /*
                         [SELECT id, name, Apply_Requirement_To__c, Certification_Name__c 
                         FROM Certification_Requirement_Setup__c 
                         WHERE Apply_Requirement_To__c =:appReq 
                         AND Certification_Name__c IN :certNames]));
                         */
                                     
            if(this.setCon.getResultSize()>0){                     
                this.setCon.setPageSize(PAGE_SIZE);
                setNextPrevious();
                NoOfRecords = this.setCon.getResultSize(); 
                this.setCon.last();                                        
                lastPage = this.setCon.getPageNumber();
                this.setCon.first();                        
                currentPage = this.setCon.getPageNumber();
            }                           
        }   
        return this.setCon;        
     }        
     set;
    }
     
     //Function get called when user click on  'Save & Next' link   
     public PageReference next() {        
        if (hasNext){  
            try {
                //save changed records before displaying next list of records    
                this.setCon.save();
                this.setCon.next();             
                currentPage = this.setCon.getPageNumber();
                setNextPrevious();  
            } 
            catch(Exception e){
                ApexPages.addMessages(e);
                return null;
            }           
        }     
        return null;    
     }        
     
     //Function get called when user click on  'Save & previous' link  
     public PageReference previous() {        
        if (hasPrevious){ 
            try {
                this.setCon.save();
                this.setCon.previous();            
                currentPage = this.setCon.getPageNumber();
                setNextPrevious();      
            } 
            catch(Exception e){
                ApexPages.addMessages(e);
                return null;
            }                    
        }        
        return null;    
     }        
     
     //Set values for hasNext and hasPrevious booleans    
     private void setNextPrevious() {        
        if (this.setCon.getHasNext()) {            
            hasNext = true;        
        }        
        else {            
            hasNext = false;        
        }        
        if (this.setCon.getHasPrevious()) {            
            hasPrevious = true;        
        }        
        else {            
            hasPrevious = false;        
        }    
     }
     
    //getter methods
    public boolean getHasPreviousAndNext(){        
        return (hasPrevious && hasNext);    
    }
    
    public List<Certification_Requirement_Setup__c> getReqList(){           
        return recReqList ;
    }           
}