profilelist1exp/unpackaged/objects/ClickCountSetup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is keeping a set of metadata specifically for any link where its click (with metadata info) will be recorded into SF1_Adoption__c.</description>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_To_URL__c</fullName>
        <label>Route To URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Action__c</fullName>
        <label>User Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Click Count Metadata Setup</label>
</CustomObject>

profilelist1exp/unpackaged/classes/ClickCountFeederCtrlTest.cls
/*****************************************************************************************************************
* Name          : ClickCountFeederCtrlTest
* Description   : To Test the code coverage of ClickCountFeederCtrlTest
* ---------------------------------------------------------
* Revision  Name                Date                Description
* 1.0       Jessie              8th March 2017      CR14055: Story 3089187:SFDC Resource Centre Link Updates & Tracking 
******************************************************************************************************************/

@isTest

private class ClickCountFeederCtrlTest {
    
    private static ClickCountSetup__c objTestSetupMetadata ;
    
    private static testMethod void testSFDCResourceCentre(){
        
        createClickCountSetupMetadata();

        Test.startTest();
                
        PageReference ClickCountFeederPage =Page.ClickCountFeeder;
        
        ClickCountFeederPage.getParameters().put('name','Test_Test');
        
        Test.SetCurrentPage(ClickCountFeederPage);
        
        ClickCountFeederCtrl clickCountFeeder = new ClickCountFeederCtrl ();
        clickCountFeeder.routeToLink();
        
        System.assertEquals(objTestSetupMetadata.Route_To_URL__c , clickCountFeeder.objClickCountSetup.Route_To_URL__c);
        System.assertEquals(objTestSetupMetadata.Object_Name__c, clickCountFeeder.objClickCountSetup.Object_Name__c);
        System.assertEquals(objTestSetupMetadata.Region__c, clickCountFeeder.objClickCountSetup.Region__c);
        System.assertEquals(null, clickCountFeeder.strRecordId);
        System.assertEquals(objTestSetupMetadata.Source__c, clickCountFeeder.objClickCountSetup.Source__c);
        System.assertEquals(objTestSetupMetadata.User_Action__c, clickCountFeeder.objClickCountSetup.User_Action__c);        
               
        Test.stopTest(); 
        
    }
    
    private static testMethod void testException(){
        
        createClickCountSetupMetadata();
        
        Test.startTest();
        
        PageReference ClickCountFeederPage =Page.ClickCountFeeder;
        
         ClickCountFeederPage.getParameters().put('name','Test_Test2');
          
        Test.SetCurrentPage(ClickCountFeederPage);
        
        ClickCountFeederCtrl clickCountFeeder = new ClickCountFeederCtrl ();
        clickCountFeeder.routeToLink();
               
        Test.stopTest(); 
        
    }
    
    private static void createClickCountSetupMetadata(){
        
         objTestSetupMetadata = new ClickCountSetup__c (Name='Test_Test', Object_Name__c='Test Object Name', Route_To_URL__c = 'http://www.test.com?abc=abc');
         
         insert objTestSetupMetadata ;
    
    }
}