profilelist1exp/unpackaged/objects/CMAP_Queue_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains Manual Assignment Queue names and its Ids</description>
    <fields>
        <fullName>Queue_Id__c</fullName>
        <label>Queue Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CMAP Queue Settings</label>
</CustomObject>

profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -ISO 3166 Country Code||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <externalId>true</externalId>
        <label>ISO 3166-1 Country Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enable_for_FAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable for FAP?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAP_Country_Value__c</fullName>
        <label>FAP Country Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Mass_Upload_Lead_Request__c.object
<CustomObject>
    <description>Custom object to upload multiple leads request.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Mass_Upload_Lead_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Mass_Upload_Lead_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Email_ID__c</fullName>
        <label>Partner Email ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Partner_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Mass_Upload_Lead_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mass Lead Upload Request</label>
    <nameField>
        <displayFormat>MLUR-{000000}</displayFormat>
        <label>MLUR Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Lead Upload Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadUtilitiesTest.cls
/* 
 * Revision CR Number   Release No      Date            Modified By     Description
 * -------- ---------   ----------      -----------     ------------    -----------
 * 1.0      CR 10747    16.03           25-Feb-2015     Ragu            Created test method for LeadUtilities.updateLeadStatusForPartnerMLURs()
 * 2.0      CR 13068    FY17-DCS-0602   04-May-2016     Gan             Set the seeAllData to false in the Test class, random catch
 */
 
@isTest(SeeAllData=false)
private class LeadUtilitiesTest {
    
    //2.0
     @testSetup static void populateCMAPCustomSetting() {
        CMAP_Queue_Settings__c eClerxQueue = new CMAP_Queue_Settings__c(Name = 'Channel_eClerx', Queue_Id__c = '00GA0000002y6hl', Queue_Name__c = 'Channel_eClerx');
        Database.insert(eClerxQueue);
    
        Country__c cntry = new Country__c(Name ='UNITED KINGDOM', Code__c='GB', CurrencyIsoCode='USD', FAP_Country_Value__c='UNITED KINGDOM (UK)', Region__c ='EMEA', Enable_for_FAP__c = true);
        Database.insert(cntry);   
    }
    
    static testMethod void test_updateLeadStatusForPartnerMLURs() {
        // Skip all the triggers to avoid Too Many SOQL Query issue
        TriggerExecutionController.setSkipAllTriggers(true);
        
        CMAP_TestDataGenerator testData = new CMAP_TestDataGenerator();
        testData.getAccount(true);
        testData.getContact(true);
        testData.getPartnerUser(true);
        testData.getCampaign(true);
        CMAP_Helper.skipInsert = true;
        System.debug('XXXX:+tesst');
        
        Mass_Upload_Lead_Request__c mulrObj = new Mass_Upload_Lead_Request__c(Campaign__c = testData.campObj.Id,
            Partner_User__c = testData.partnerUser.Id,
            Partner_Email_ID__c = testData.partnerUser.Email,
            Partner_Account__c = testData.accountObj.Id,
            Status__c = 'New');
        insert mulrObj;
        
        // Revert back the skip all triggers
        TriggerExecutionController.setSkipAllTriggers(false);
        
        Id leadRTId = StaticFactory.getRecordTypeIdByName('Lead','Channel Lead - Cleansing & Scoring Complete');
        
        // Start Testing
        Test.startTest();
        
        list<Lead> lstLeads = new list<Lead>();
        Lead leadObj = new Lead(LastName = 'Test Lead 1',
            Email = 'testcmap@cmaptest.com',
            Status = 'Open - Channel Lead',
            Phone = '88967544',
            RecordTypeId = leadRTId,
            Country = 'US',
            Partner_Account__c = testdata.accountObj.Id,
            Campaign__c  = testdata.campObj.Id,
            Company = 'Test Company',
            Partner_User__c = testdata.PartnerUser.Id,
            Ready_For_Scoring__c = false,
            Lead_Score__c = 'High Priority (Extremely hot leads; SLA = 48 hours)',
            Are_you_a_Dell_Partner__c = 'Yes',
            Mass_Lead_Upload_Request_ID__c = mulrObj.Id);
        lstLeads.add(leadObj);
        
        Lead leadObjAlt = new Lead(LastName = 'Test Lead 2',
            Email = 'testcmap@cmaptest.com',
            Status = 'Open - Channel Lead',
            Phone = '88967544',
            RecordTypeId = leadRTId,
            Country = 'US',
            Partner_Account__c = testdata.accountObj.Id,
            Campaign__c  = testdata.campObj.Id,
            Company = 'Test Company',
            Partner_Admin__c = userinfo.getuserID(),//testdata.PartnerUser.Id,
            Ready_For_Scoring__c = false,
            Lead_Score__c = 'High Priority (Extremely hot leads; SLA = 48 hours)',
            Are_you_a_Dell_Partner__c = 'Yes',
            Mass_Lead_Upload_Request_ID__c = mulrObj.Id);
        lstLeads.add(leadObjAlt);
        
        try{
              insert lstLeads;
                    System.debug('Shue lstLeads----'+lstLeads);
        }catch(Exception ex){
            system.debug('$$$$$$$ This insertion failed '+ex.getMessage());
        }
        
        map<id,Lead> Mapoldleads = new map<id,Lead>();
      
        
        for(Lead newLead: [select id,Ready_For_Scoring__c from Lead where id in :lstLeads]){
        Mapoldleads.put(newLead.id,newLead);
        }
        
        for(Lead newLead1:lstLeads){
              newLead1.Ready_For_Scoring__c=true;
                     
        }
        update lstLeads;
             
        system.debug('$$$$ lstleads'+lstleads);
        LeadUtilities.updateLeadStatusForPartnerMLURs(lstLeads,Mapoldleads);
        
               
        Test.stopTest();
        // End Testing
    }
    
    static testMethod void test_rollupLeadsAndContactsForCampaign() {
        LeadTestData.iNumberOfLeads = 5;
        LeadTestData.bCreate = false;
        LeadTestData.createDirectLead2();
        list<Lead> lstDirectLeads2 = LeadTestData.lstLeads;
        
        CampaignTestData.iNumberOfCampaigns = 1;
        CampaignTestData.createCampaign2();
        list<Campaign> lstCampaigns = CampaignTestData.lstCampaigns;
        
        Test.startTest();
        
        Database.insert(lstDirectLeads2);
        
        lstDirectLeads2[4].Campaign__c = lstCampaigns[0].Id;
        Database.update(lstDirectLeads2);
        
        Database.delete(lstDirectLeads2[4]);
        
        Test.stopTest();
    }
     //StartV2.2
 /*static testMethod void test_populateLeadOwnerRole() {
 
        TriggerExecutionController.setSkipAccountTriggers(true);
        TriggerExecutionController.setSkipCampaignTriggers(true);
        LeadAssignment_TestHelper.createAccounts();
        Account euAccount = LeadAssignment_TestHelper.endUserAccount;
        LeadAssignment_TestHelper.createAccountTeam();
        
        CampaignTestData.bCreate = false;
        CampaignTestData.iNumberOfCampaigns = 1;
        CampaignTestData.createCampaign2();
        list<Campaign> lstCampaigns = CampaignTestData.lstCampaigns;
        lstCampaigns[0].Secondary_Role__c = 'Inside Sales Rep';
        lstCampaigns[0].Follow_Up_Role__c = 'Account Executive';
        insert lstCampaigns;
        
        Test.startTest();
        LeadTestData.bCreate = false;
        LeadTestData.iNumberOfLeads = 1;
        LeadTestData.createDirectLead2();
        list<Lead> lstLeads = LeadTestData.lstLeads;
        lstLeads[0].Account__c = euAccount.Id;        
        lstLeads[0].Campaign__c = lstCampaigns[0].Id;        
        insert lstLeads;
        //update lead owner manually 
        lstLeads[0].OwnerId = UserInfo.getUserId();        
        update lstLeads;
        
        UserTestData.iNumberOfUsers = 1;
        UserTestData.bCreate = false;
        UserTestData.createInternalUsers();
        list<User> lstUsers = UserTestData.lstUsers;
       // insert lstUsers;
     
        system.debug('Account id'+euAccount.Id);
        system.debug('userid'+lstUsers[0].id);
        lstLeads[0].OwnerId = lstUsers[0].id;   
        lstLeads[0].Status = 'Account Suggestion Completed';
        lstLeads[0].Website = 'http://website';
     //   update lstLeads;
        
        
    
        Test.stopTest();
    } */
    
    
  
}