profilelist1exp/unpackaged/objects/Contract_Terms_and_Conditions__c.object
<CustomObject>
    <description>To store terms and conditions associated with each contract</description>
    <label>Contract Terms and Conditions</label>
    <nameField>
        <displayFormat>NS-{000000000}</displayFormat>
        <label>Contract Terms and Conditions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

force-app/main/default/objects/Support_Request__c/Support_Request__c.object-meta.xml
<CustomObject>
    <label>Support Request</label>
    <nameField>
        <displayFormat>SR # {000000000}</displayFormat>
        <label>Support Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Request__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the contact associated with Support Request</description>
    <label>Contact Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Opportunity__r.Account.Name</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>Support_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/CSMB_Contract_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>CSMB_Contract_Request_Type__c</fullName>
    <label>Contract Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On SOWs</fullName>
            </value>
            <value>
                <fullName>Advising on Disputes</fullName>
            </value>
            <value>
                <fullName>Amending existing terms</fullName>
            </value>
            <value>
                <fullName>Amendment/Addendum</fullName>
            </value>
            <value>
                <fullName>Interpretation/Contract Compliance</fullName>
            </value>
            <value>
                <fullName>Modify Existing Contract</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>New Contract</fullName>
            </value>
            <value>
                <fullName>Other Contract Support/Enquiry</fullName>
            </value>
            <value>
                <fullName>RFx/Bid/Proposal/Tender</fullName>
            </value>
            <value>
                <fullName>Service/SOW</fullName>
            </value>
            <value>
                <fullName>Statement of Work</fullName>
            </value>
            <value>
                <fullName>Task Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>CR#1241-Look Up field to opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>CEM_Support</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Solution_Type__c.field-meta.xml
<CustomField>
    <fullName>Solution_Type__c</fullName>
    <formula>TEXT(Opportunity__r.Solution_Type__c)</formula>
    <label>Solution Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Reassigned</fullName>
            </value>
            <value>
                <fullName>Engagement complete</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Unqualified Opp</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Pending Al Sales</fullName>
            </value>
            <value>
                <fullName>Quoting</fullName>
            </value>
            <value>
                <fullName>Proposal Submitted</fullName>
            </value>
            <value>
                <fullName>Pending AT</fullName>
            </value>
            <value>
                <fullName>SOC Monitoring</fullName>
            </value>
            <value>
                <fullName>Lost Opp</fullName>
            </value>
            <value>
                <fullName>Cancelled Opp</fullName>
            </value>
            <value>
                <fullName>Order Mgmt</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>In Quote</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>In Sustaining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Australia &amp; New Zealand (ANZ)</fullName>
            </value>
            <value>
                <fullName>Central &amp; Eastern Europe</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Middle East &amp; Africa</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>ROA/ Pacific</fullName>
            </value>
            <value>
                <fullName>South Asia &amp; Korea</fullName>
            </value>
            <value>
                <fullName>United Kingdom &amp; Ireland (UKI)</fullName>
            </value>
            <value>
                <fullName>Western Europe</fullName>
            </value>
            <value>
                <fullName>Germany/Austria</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

profilelist1exp/unpackaged/classes/CMRecordTypeForTandCControllerTest.cls
/***********************************************************
* ---------------------------------------------------------
* Revision  Name                Description
* 1.0       VIKAS KH         Implemeted TDF for 0202 Release
* 
************************************************************/

@istest
Private Class CMRecordTypeForTandCControllerTest{
    static list<Account> listAcc;
    static list<contact> listcon;
    static list<opportunity> listopp;
    static list<Support_Request__c> listSpprtReq;
    static list<Contract> listcontract;
    @testSetup static void setup(){
        OWD__c owdsetting = new OWD__c();
        owdsetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        owdsetting.Oppty_Stage10__c = 'Discover - 10%';
        owdsetting.Oppty_Stage100__c = 'Win - 100%';
        owdsetting.Oppty_Stage30__c = 'Qualify - 30%';
        owdsetting.Oppty_Stage60__c = 'Propose - 60%';
        owdsetting.Oppty_Stage90__c = 'Commit - 90%';
        owdsetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        owdsetting.Oppty_Stage1__c = 'Plan - 1%';
        insert owdsetting;
        list<Account> listAccTDF = TestDataFactory.createNAccount(1, 'End-User Account');
        TriggerExecutioncontroller.setSkipAccountTriggers(True);
        insert listAccTDF;
        list<contact> listConTDF = TestDataFactory.createNContacts(1);
        listConTDF[0].AccountID = listAccTDF[0].id;
        insert listConTDF;
        list<opportunity> listoppTDF = TestDataFactory.createNOpportunities(1, 'Standard Opportunity');
        listoppTDF[0].accountId=listAccTDF[0].id;
        TriggerExecutionController.setSkipOpportunitySplitTriggers(true);
        insert listoppTDF;
           }  

    static testMethod void myUnitTest() {
            TriggerExecutionController.setSkipAllTriggers(true);    

    //Skip all triggers to avoid Too much SOQL Query
    /*
    
    id acRecTypeId=IdLookupUtils.getRecordTypeId('End-User Account', 'Account', true);
    Account act = new account();
    act.name='TEST';
    act.recordtypeid=acRecTypeId;
    
    insert act;
    
    contact cont= new contact();
    cont.FirstName='TestContact1';
    cont.LastName='TestContactlast1';
    cont.accountId=act.Id;
    cont.Email='test@ust-global.com';
    cont.fax='01987645';
    cont.MobilePhone='0000019';
    cont.Phone='0000000';
    
    insert cont;
        
    Opportunity op = new Opportunity();
    op.accountId=act.id;
    op.name='TestOpp';
    op.Type='Run Rate';
    op.Solution_Type__c='Business Processing';
    op.StageName='Plan - 1%';
    //op.CloseDate=date.parse('12/10/2011'); // Fenny commented [18-Jul-2014]: To accommondate new VR = OpptyBookDateValidation
    op.CloseDate=System.Date.TODAY(); // Fenny added [18-Jul-2014]: To accommondate new VR = OpptyBookDateValidation
       
    insert op;
    
    //ID srRecordTypeID=IdLookupUtils.getRecordTypeId('Request CSMB Contract Support', 'Support_Request__c', true);
    ID srRecordTypeID=IdLookupUtils.getRecordTypeId('Request Contracts Support', 'Support_Request__c', true);
    Support_Request__c supReq = new Support_Request__c();
    supReq.Opportunity__c= op.id;
    supReq.CSMB_Contract_Request_Type__c='New Contract';
    supReq.Region__c='Americas';
    supReq.Sub_Region__c='Latin America';
    supReq.Contact_Name__c=cont.id;
    supReq.RecordTypeId = srRecordTypeID;
    supReq.Status__c='New';  // Fenny added [18-Jul-2014]: To accommondate new VR = OpptyBookDateValidation
    
    insert supReq;
    
    contract con = new contract();
    con.accountId=act.id;
    con.status='Pending';
    con.No_Approval_Required__c=true;
    
    insert con;
    */
   TriggerExecutioncontroller.setSkipAccountTriggers(True);
    listAcc = [select id, RecordtypeID from Account limit 1];
    listCon = [select id from contact limit 1];
    system.assertEquals(listAcc, listAcc);
        Test.startTest();
    listOpp = [select id from Opportunity limit 1];
    TriggerExecutioncontroller.setSkipOpportunitySplitTriggers(True);
   // listcontract = [select id from contract limit 1];
        list<Support_Request__c> listSpprtReq = TestDataFactory.createNSupportRequests(1, 'Request Contracts Support');
        listSpprtReq[0].Contact_Name__c=listCon[0].id;
        listSpprtReq[0].Opportunity__c= listopp[0].id;
        //listSpprtReq[0].Status__c='New';
        insert listSpprtReq;
        //listSpprtReq[0].Status__c='Accept';
        //update listSpprtReq;
        list<Contract> listcontract = TestDataFactory.createNContract(1);
        listcontract[0].AccountId = listAcc[0].id;
        listcontract[0].status='Pending';
        listcontract[0].No_Approval_Required__c=true;
        insert listcontract;

    string strstdRecTyp=IdLookupUtils.getRecordTypeId('Standard Terms and Conditions', 'Contract_Terms_and_Conditions__c', true);
    string strnonStdRecTyp = IdLookupUtils.getRecordTypeId('Non-Standard Terms and Conditions', 'Contract_Terms_and_Conditions__c', true);
    string strrecTyp=listAcc[0].RecordTypeID;
    
    //Activate skip all triggers
    TriggerExecutionController.setSkipAllTriggers(false);
    
    
    ApexPages.StandardController CMController = new ApexPages.StandardController(listcontract[0]);
    ApexPages.currentPage().getParameters().put('id', listcontract[0].id); 
    CMRecordTypeForTandCController cmRecordTypeforTandC = new CMRecordTypeForTandCController(CMController);
    cmRecordTypeforTandC.getRecordType();
    cmRecordTypeforTandC.setRecordType(strstdRecTyp);
    cmRecordTypeforTandC.getRecTypeList();
    cmRecordTypeforTandC.getrectypes();
    cmRecordTypeforTandC.redirect();
    cmRecordTypeforTandC.setRecordType(strnonStdRecTyp);
    cmRecordTypeforTandC.getRecTypeList();
    cmRecordTypeforTandC.getrectypes();
    cmRecordTypeforTandC.redirect();
    cmRecordTypeforTandC.setRecordType(strstdRecTyp);
    cmRecordTypeforTandC.getRecTypeList();
    cmRecordTypeforTandC.getrectypes();
    cmRecordTypeforTandC.redirect();
    cmRecordTypeforTandC.cancel();
    Test.stopTest();
    }
}