profilelist1exp/unpackaged/objects/Contract_Terms_and_Conditions__c.object
<CustomObject>
    <description>To store terms and conditions associated with each contract</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Non_Standard_Term_Repository</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Term</label>
        <referenceTo>CSMB_Terms_and_Conditions_Maintenance__c</referenceTo>
        <relationshipLabel>Contract Terms and Conditions</relationshipLabel>
        <relationshipName>Contract_Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms and Conditions</label>
        <referenceTo>CSMB_Terms_and_Condition__c</referenceTo>
        <relationshipLabel>Contract Terms and Conditions</relationshipLabel>
        <relationshipName>Contract_Terms_and_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_conditions_Content__c</fullName>
        <label>Terms and conditions Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contract Terms and Conditions</label>
    <nameField>
        <displayFormat>NS-{000000000}</displayFormat>
        <label>Contract Terms and Conditions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/CSMB_Terms_and_Condition__c.object
<CustomObject>
    <description>CSMB Terms and Conditions store Ideal Terms for the Repository records</description>
    <fields>
        <fullName>Standard_Term__c</fullName>
        <description>Standard_Term in the Terms and Conditions Repository.</description>
        <label>Standard Term</label>
        <referenceTo>CSMB_Terms_and_Conditions_Maintenance__c</referenceTo>
        <relationshipLabel>CSMB Terms and Conditions</relationshipLabel>
        <relationshipName>CSMB_Terms_and_Conditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Standard_Terms_and_Conditions__c</fullName>
        <label>Standard Terms and Conditions</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of the terms and conditions.</description>
        <inlineHelpText>Uncheck the checkbox if the Terms and conditions are not active anymore.</inlineHelpText>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>CSMB Terms and Condition</label>
    <nameField>
        <displayFormat>Terms{0000}</displayFormat>
        <label>Ideal Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSMB Terms and Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/CSMB_Terms_and_Conditions_Maintenance__c.object
<CustomObject>
    <description>CSMB Terms and Conditions Maintenance for storing Standard Terms and Conditions Repository</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region where the terms and conditions are applicable</description>
        <inlineHelpText>Region where the terms and conditions are applicable.</inlineHelpText>
        <label>Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>ROAPJ</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of the terms and conditions.</description>
        <inlineHelpText>Uncheck the checkbox if the Terms and conditions are not active anymore.</inlineHelpText>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>CSMB T &amp; C Maintenance</label>
    <nameField>
        <label>Standard Terms</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSMB T &amp; C Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Request__c/Support_Request__c.object-meta.xml
<CustomObject>
    <label>Support Request</label>
    <nameField>
        <displayFormat>SR # {000000000}</displayFormat>
        <label>Support Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Request__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the contact associated with Support Request</description>
    <label>Contact Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Opportunity__r.Account.Name</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>Support_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/CSMB_Contract_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>CSMB_Contract_Request_Type__c</fullName>
    <label>Contract Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On SOWs</fullName>
            </value>
            <value>
                <fullName>Advising on Disputes</fullName>
            </value>
            <value>
                <fullName>Amending existing terms</fullName>
            </value>
            <value>
                <fullName>Amendment/Addendum</fullName>
            </value>
            <value>
                <fullName>Interpretation/Contract Compliance</fullName>
            </value>
            <value>
                <fullName>Modify Existing Contract</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>New Contract</fullName>
            </value>
            <value>
                <fullName>Other Contract Support/Enquiry</fullName>
            </value>
            <value>
                <fullName>RFx/Bid/Proposal/Tender</fullName>
            </value>
            <value>
                <fullName>Service/SOW</fullName>
            </value>
            <value>
                <fullName>Statement of Work</fullName>
            </value>
            <value>
                <fullName>Task Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>CR#1241-Look Up field to opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>CEM_Support</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Solution_Type__c.field-meta.xml
<CustomField>
    <fullName>Solution_Type__c</fullName>
    <formula>TEXT(Opportunity__r.Solution_Type__c)</formula>
    <label>Solution Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Reassigned</fullName>
            </value>
            <value>
                <fullName>Engagement complete</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Unqualified Opp</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Pending Al Sales</fullName>
            </value>
            <value>
                <fullName>Quoting</fullName>
            </value>
            <value>
                <fullName>Proposal Submitted</fullName>
            </value>
            <value>
                <fullName>Pending AT</fullName>
            </value>
            <value>
                <fullName>SOC Monitoring</fullName>
            </value>
            <value>
                <fullName>Lost Opp</fullName>
            </value>
            <value>
                <fullName>Cancelled Opp</fullName>
            </value>
            <value>
                <fullName>Order Mgmt</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>In Quote</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>In Sustaining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Australia &amp; New Zealand (ANZ)</fullName>
            </value>
            <value>
                <fullName>Central &amp; Eastern Europe</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Middle East &amp; Africa</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>ROA/ Pacific</fullName>
            </value>
            <value>
                <fullName>South Asia &amp; Korea</fullName>
            </value>
            <value>
                <fullName>United Kingdom &amp; Ireland (UKI)</fullName>
            </value>
            <value>
                <fullName>Western Europe</fullName>
            </value>
            <value>
                <fullName>Germany/Austria</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

profilelist1exp/unpackaged/classes/CMStdTermsControllerTest.cls
/* 
REVISION HISTORY
================
Version     Author      Date            Release#    CR#     Description
-------     ------      ----            --------    ---     -----------
1.0         MenMee      21-Feb-2013     14.2                Too many SOQL queries exception. Move Test.startTest to the desired test section
2.0		    Vikas Kh					0202				Implemented TDF
*/

@istest
Private Class CMStdTermsControllerTest{
     static list<Account> listAcc;
    static list<contact> listcon;
    static list<user> listuser;
    static list<opportunity> listopp;
    static list<Support_Request__c> listSpprtReq;
    static list<Contract> listContract;
    static List<Contract_Terms_and_Conditions__c> listContractTms;
    static List<Contract_Terms_and_Conditions__c> listContractTm1;
    Static list<CSMB_Terms_and_Conditions_Maintenance__c> listCSMBTandCM;
    static list<CSMB_Terms_and_Condition__c> listTermsandCon;

    @testSetup static void setup(){
        list<Profile> listuserProfile = [Select id from Profile where name like '%Contract Manager' Limit 1];
        list<user> listuserTDF = TestDataFactory.createNGenralUsers(1);
        listuserTDF[0].ProfileId = listuserProfile[0].id;
        insert listuserTDF;
        list<Account> listAccTDF = TestDataFactory.createNAccount(1, 'End-User Account');
        TriggerExecutionController.setSkipAccountTriggers(True);
        insert listAccTDF;
        list<contact> listConTDF = TestDataFactory.createNContacts(1);
        listConTDF[0].AccountID = listAccTDF[0].id;
        insert listConTDF;
        list<opportunity> listoppTDF = TestDataFactory.createNOpportunities(1, 'Standard Opportunity');
        listoppTDF[0].accountId=listAccTDF[0].id;
        TriggerExecutionController.setSkipOpportunitySplitTriggers(true);
        TriggerExecutioncontroller.setSkipOpportunityTriggers(True);
        insert listoppTDF;
        list<Contract> listContrTDF = TestDataFactory.createNContract(1);
        listContrTDF[0].Accounting__c=listuserTDF[0].id;
        listContrTDF[0].AccountId = listAccTDF[0].id;
        listContrTDF[0].status='Pending';
        insert listContrTDF;
        List<CSMB_Terms_and_Conditions_Maintenance__c> listCsmBTermsMain = TestDataFactory.createNCSMBTermsANdConditionMaintenance(2);
        insert listCsmBTermsMain;
        List<CSMB_Terms_and_Condition__c> listcSMBTerms = TestDataFactory.createNCSMBTermsANdCondition(4);
        listcSMBTerms[0].Standard_Term__c=listCsmBTermsMain[1].id;
        listcSMBTerms[0].Standard_Terms_and_Conditions__c='1. The parties have reasonable right to audit one another’s facilities, books and records relating to the Agreement, to ensure compliance with performance obligations, and adequacy of performance, under the Agreement.';
        listcSMBTerms[1].Standard_Term__c=listCsmBTermsMain[1].id;
        listcSMBTerms[0].Standard_Terms_and_Conditions__c='2. The parties agree that audits are only to be conducted by an independent, internationally recognized auditing firm.';
        listcSMBTerms[2].Standard_Term__c=listCsmBTermsMain[0].id;
	    listcSMBTerms[2].Standard_Terms_and_Conditions__c='1. Customer must inspect immediately the product upon delivery to note damage to outer boxes or loss and notify Dell. (MWD for inside the box or system – timeline is not a concern for our team.)';
        listcSMBTerms[3].Standard_Term__c=listCsmBTermsMain[0].id;
	    listcSMBTerms[3].Standard_Terms_and_Conditions__c='3. If customer refuses to accept delivery, the customer is responsible for any costs incurred by Dell to store or transport the product as well as any losses to value of product.';
        insert listcSMBTerms;
 /*       List<Contract_Terms_and_Conditions__c> listContractTerms = TestDataFactory.createNContractTermsANdCondition(1, 'Standard Terms and Conditions');
        listContractTerms[0].contract__c=listContrTDF[0].id;
        listContractTerms[0].Standard_Term__c=listCsmBTermsMain[0].id;
        listContractTerms[0].Terms_and_Conditions__c=listcSMBTerms[2].id;
        listContractTerms[0].Terms_and_conditions_Content__c=listcSMBTerms[2].Standard_Terms_and_Conditions__c;
        insert listContractTerms;
        List<Contract_Terms_and_Conditions__c> listContractTerms1 = TestDataFactory.createNContractTermsANdCondition(1,'Non-Standard Terms and Conditions');
        listContractTerms1[0].contract__c=listContrTDF[0].id;
        insert listContractTerms1;
*/
    }  
    static testMethod void myUnitTest() {
    //Test.startTest(); 1.0
     // Skill all trigger to avoid too many SOQL Query Issue
    TriggerExecutionController.setSkipAllTriggers(true);
    /*
    Id acRecTypeId=IdLookupUtils.getRecordTypeId('End-User Account', 'Account', true);
    Account act = new account();
    act.name='TEST';
    act.recordtypeid=acRecTypeId;
    
    insert act;
    
    contact cont= new contact();
    cont.FirstName='TestContact1';
    cont.LastName='TestContactlast1';
    cont.accountId=act.Id;
    cont.Email='test@ust-global.com';
    cont.fax='01987645';
    cont.MobilePhone='0000019';
    cont.Phone='0000000';
    
    insert cont;
        
    Opportunity op = new Opportunity();
    op.accountId=act.id;
    op.name='TestOpp';
    op.Type='Run Rate';
    op.Solution_Type__c='Business Processing';
    op.StageName='Plan - 1%';
    //op.CloseDate=date.parse('12/10/2011'); // Fenny commented [18-Jul-2014]: To accommondate new VR = OpptyBookDateValidation
    op.CloseDate=System.Date.TODAY(); // Fenny added [18-Jul-2014]: To accommondate new VR = OpptyBookDateValidation
       
    insert op;
    
    //ID srRecordTypeID=IdLookupUtils.getRecordTypeId('Request CSMB Contract Support', 'Support_Request__c', true);
    ID srRecordTypeID=IdLookupUtils.getRecordTypeId('Request Contracts Support', 'Support_Request__c', true);
    Support_Request__c supReq = new Support_Request__c();
    supReq.Opportunity__c= op.id;
    supReq.CSMB_Contract_Request_Type__c='New Contract';
    supReq.Region__c='Americas';
    supReq.Sub_Region__c='Latin America';
    supReq.Contact_Name__c=cont.id;
    supReq.RecordTypeId = srRecordTypeID;
    supReq.Status__c='New';  // Fenny added [18-Jul-2014]: To accommondate new VR = OpptyBookDateValidation
    
    insert supReq;
    
    Profile profile = new profile();
    //for(Profile userProfile:[Select id from Profile where name like '%CSMB Contract Manager' Limit 1]){
    for(Profile userProfile:[Select id from Profile where name like '%Contract Manager' Limit 1]){
       profile=userprofile;
    }
    String username = String.valueOf(Datetime.now()).replace(' ', '_').replace(':', '_').replace('-', '_') + '@dell.com.fdev'; // Fenny added
    User user = new User(Alias = 'CM101',
              LastName = 'testCM101',
              Email = 'x.y@ust-global.com',
              Username = username,
              CommunityNickname = 'testCM101',
              EmailEncodingKey = 'ISO-8859-1',
              TimeZoneSidKey = 'America/Panama',
              LocaleSidKey = 'en_US',
              LanguageLocaleKey = 'en_US',
              ProfileId = profile.id,
              Badge_number__c='CM101');
        
    insert user;
    
    contract con = new contract();
    con.accountId=act.id;
    con.status='Pending';
    con.Accounting__c=user.id;
    
    insert con;
     */
        listAcc = [select id, RecordtypeID from Account limit 1];
        listCon = [select id from contact limit 1];
        Test.startTest();
        listOpp = [select id from Opportunity limit 1];
        TriggerExecutioncontroller.setSkipOpportunitySplitTriggers(True);
        list<Support_Request__c> listSpprtReq = TestDataFactory.createNSupportRequests(1, 'Request Contracts Support');
        listSpprtReq[0].Contact_Name__c=listCon[0].id;
        listSpprtReq[0].Opportunity__c= listopp[0].id;
        //listSpprtReq[0].Status__c='New';
        insert listSpprtReq;
        //listSpprtReq[0].Status__c='Accept';
        //update listSpprtReq;
        listContract = [select id from Contract limit 1];
   		system.assertEquals(listContract[0], listContract[0]);
   // list<CSMB_Terms_and_Conditions_Maintenance__c> newCSMBTandCList = new list<CSMB_Terms_and_Conditions_Maintenance__c>();
   // List<CSMB_Terms_and_Conditions_Maintenance__c> maintananceIdList = new List<CSMB_Terms_and_Conditions_Maintenance__c>();
    boolean bshowTandC=false;
    boolean bshowStdTandC = false;
    boolean beditTerms=false;
    boolean bshowMultiPickofTandC=true;
    boolean binactiveTermsbool=false;
    string[] listtermsToAdd = new string[]{};
    string[] listtermsToRemove = new string[]{};
    string stradd1='TAudit';
    string strremove1='TDelivery';
    set<string> setTandC= new set<string>();
    set<Id> setcurSelEditstandardTerms = new set<Id>();
    set<Id> setcurSelEditTerms = new set<Id>();
    Id contractId;
    List<selectOption> listavailableTandC = new List<selectOption>();
    listavailableTandC.add(new selectoption('TAudit','TAudit'));
    List<selectOption> listselectedTandC = new List<selectOption>();
    listselectedTandC.add(new selectoption('TDelivery','TDelivery'));
    List<selectOption> listfullAvailableTandC = new List<SelectOption>();
    listfullAvailableTandC.add(new selectoption('TAudit','TAudit'));
    listfullAvailableTandC.add(new selectoption('TDelivery','TDelivery'));
    List<Contract_Terms_and_Conditions__c> listcontractTermsandConditions = new List<Contract_Terms_and_Conditions__c>();
     listCSMBTandCM = [select id from CSMB_Terms_and_Conditions_Maintenance__c limit 2 ];
     listTermsandCon = [select id,Standard_Terms_and_Conditions__c from CSMB_Terms_and_Condition__c limit 4 ];
    /*
    CSMB_Terms_and_Conditions_Maintenance__c CSMBmaintananceObj1= new CSMB_Terms_and_Conditions_Maintenance__c();  
    CSMBmaintananceObj1.Name='TDelivery';
    CSMBmaintananceObj1.status__c=True;
    newCSMBTandCList.add(CSMBmaintananceObj1);
    
    CSMB_Terms_and_Conditions_Maintenance__c CSMBmaintananceObj2= new CSMB_Terms_and_Conditions_Maintenance__c();
    CSMBmaintananceObj2.Name='TAudit';
    CSMBmaintananceObj2.status__c=False;
    newCSMBTandCList.add(CSMBmaintananceObj2);
    
    insert newCSMBTandCList;
    
    list<CSMB_Terms_and_Condition__c> TermsList = new list<CSMB_Terms_and_Condition__c>();
 
    CSMB_Terms_and_Condition__c CSMBtermObj1= new CSMB_Terms_and_Condition__c();
    CSMBtermObj1.Standard_Term__c=CSMBmaintananceObj2.id;
    CSMBtermObj1.Standard_Terms_and_Conditions__c='Test Content';
    CSMBtermObj1.status__c=True;
    TermsList.add(CSMBtermObj1);
    
    CSMB_Terms_and_Condition__c CSMBtermObj2= new CSMB_Terms_and_Condition__c();
    CSMBtermObj2.Standard_Term__c=CSMBmaintananceObj2.id;
    CSMBtermObj2.Standard_Terms_and_Conditions__c='2. The parties agree that audits are only to be conducted by an independent, internationally recognized auditing firm.';
    CSMBtermObj2.status__c=True;
    TermsList.add(CSMBtermObj2);
    
    CSMB_Terms_and_Condition__c CSMBtermObj3= new CSMB_Terms_and_Condition__c();
    CSMBtermObj3.Standard_Term__c=CSMBmaintananceObj1.id;
    CSMBtermObj3.Standard_Terms_and_Conditions__c='1. Customer must inspect immediately the product upon delivery to note damage to outer boxes or loss and notify Dell. (MWD for inside the box or system – timeline is not a concern for our team.)';
    CSMBtermObj3.status__c=True;
    TermsList.add(CSMBtermObj3);
    
    CSMB_Terms_and_Condition__c CSMBtermObj4= new CSMB_Terms_and_Condition__c();
    CSMBtermObj4.Standard_Term__c=CSMBmaintananceObj1.id;
    CSMBtermObj4.Standard_Terms_and_Conditions__c='3. If customer refuses to accept delivery, the customer is responsible for any costs incurred by Dell to store or transport the product as well as any losses to value of product.';
    CSMBtermObj4.status__c=True;
    TermsList.add(CSMBtermObj4);
    
    insert TermsList;
    */
       list<CSMB_Terms_and_Condition__c> listnewTandCList= new list<CSMB_Terms_and_Condition__c>();
    
     //Revert back the skip all triggers
    TriggerExecutionController.setSkipAllTriggers(false);
    
    //Test.startTest();   //1.0        
    ApexPages.StandardController cMController = new ApexPages.StandardController(listContract[0]);
    ApexPages.currentPage().getParameters().put('id', listContract[0].id);
    ApexPages.currentPage().getParameters().put('isEditButtonClicked','true');
    ApexPages.currentPage().getParameters().put('isNewButtonClicked','false');
    CMStdTermsController cmStdTCon2 = new CMStdTermsController(cMController );
    ApexPages.currentPage().getParameters().put('isEditButtonClicked','false');
    ApexPages.currentPage().getParameters().put('isNewButtonClicked','true');    
    listContract[0].status='Approved';
    update listContract[0];
    CMStdTermsController cmStdTCon1 = new CMStdTermsController(CMController );    
    cmStdTCon1.getStatusForCon(listContract[0].id);
    cmStdTCon1.TandC=setTandC;
    cmStdTCon1.curSelEditstandardTerms=setcurSelEditstandardTerms;
    cmStdTCon1.curSelEditTerms=setcurSelEditTerms;
    cmStdTCon1.getavailableTandC();
    cmStdTCon1.setavailableTandC(listavailableTandC);
    cmStdTCon1.getselectedTandC();
    cmStdTCon1.setselectedTandC(listselectedTandC);
    cmStdTCon1.getfullAvailableTandC ();
    cmStdTCon1.setfullAvailableTandC (listfullAvailableTandC);
    cmStdTCon1.gettermstoadd();
    listtermstoAdd.add(stradd1);
    listtermsToRemove.add(strremove1);
    cmStdTCon1.settermstoadd(listtermstoAdd);
    cmStdTCon1.gettermsToRemove();
    cmStdTCon1.settermsToRemove(listtermsToRemove);
    cmStdTCon1.newCSMBTandCList=listCSMBTandCM;
    cmStdTCon1.getnewTandCList();
    cmStdTCon1.setnewTandCList(listnewTandCList);
    cmStdTCon1.getshowTandC();
    cmStdTCon1.setshowTandC(bshowTandC);
    cmStdTCon1.getshowMultiPickofTandC();
    cmStdTCon1.setshowMultiPickofTandC(bshowMultiPickofTandC);
    cmStdTCon1.getinactiveTermsbool();
    cmStdTCon1.setinactiveTermsbool(binactiveTermsbool);
    cmStdTCon1.addCurSelectedTandC();
    cmStdTCon1.removeCurSelectedTandC();
    cmStdTCon1.getTermsAndConditionInnerClassList(); 
    cmStdTCon1.getSelectedTermsandConditionsClassList();
    cmStdTCon1.getinactiveStdTerms();
    cmStdTCon1.getinactiveTerms(); 
    cmStdTCon1.confirmTerms();
    
    CMStdTermsController.TermsAndConditionInnerClass termsAndConditionInnerClassobj = new CMStdTermsController.TermsAndConditionInnerClass(listTermsandCon[0],True,false);
    list<CMStdTermsController.TermsAndConditionInnerClass> listTermsAndConditionInnerClassList = new list<CMStdTermsController.TermsAndConditionInnerClass>();
    listTermsAndConditionInnerClassList.add(TermsAndConditionInnerClassobj);
    cmStdTCon1.setTermsAndConditionInnerClassList(listTermsAndConditionInnerClassList);
    CMStdTermsController.SelectedTermsandConditionsClass selectedTermsAndConditionInnerClassobj = new CMStdTermsController.SelectedTermsandConditionsClass(listCSMBTandCM[1],listTermsAndConditionInnerClassList);
    list<CMStdTermsController.SelectedTermsandConditionsClass> listSelectedTermsAndConditionInnerList = new list<CMStdTermsController.SelectedTermsandConditionsClass>();
    listSelectedTermsAndConditionInnerList.add(selectedTermsAndConditionInnerClassobj);
    cmStdTCon1.setSelectedTermsandConditionsClassList(listSelectedTermsAndConditionInnerList);

    cmStdTCon1.saveTerms();
    Contract_Terms_and_Conditions__c conTermsObj = [select id,Standard_Term__c,Terms_and_conditions_Content__c from Contract_Terms_and_Conditions__c where contract__c=:listContract[0].id];
   // listContractTms = [select id from Contract_Terms_and_Conditions__c where RecordType.Name = 'Standard Terms and Conditions' limit 1];
//    System.AssertEquals('Test Content',conTermsObj.Terms_and_conditions_Content__c);
    
    ApexPages.currentPage().getParameters().put('id', listContract[0].id);
    ApexPages.currentPage().getParameters().put('isEditButtonClicked','true');
    ApexPages.currentPage().getParameters().put('isNewButtonClicked','false');   
    CMStdTermsController cmStdTCon = new CMStdTermsController(CMController );
    cmStdTCon.getStatusForCon(listContract[0].id);
    cmStdTCon.TandC=setTandC;
    cmStdTCon.curSelEditstandardTerms=setcurSelEditstandardTerms;
    cmStdTCon.curSelEditTerms=setcurSelEditTerms;
    cmStdTCon.getavailableTandC();
    cmStdTCon.setavailableTandC(listavailableTandC);
    cmStdTCon.getselectedTandC();
    cmStdTCon.setselectedTandC(listselectedTandC);
    cmStdTCon.getfullAvailableTandC ();
    cmStdTCon.setfullAvailableTandC (listfullAvailableTandC);
    cmStdTCon.gettermstoadd();
    cmStdTCon.settermstoadd(listtermstoadd);
    cmStdTCon.gettermsToRemove();
    cmStdTCon.settermsToRemove(listtermsToRemove);
    cmStdTCon.newCSMBTandCList=listCSMBTandCM;
    cmStdTCon.getnewTandCList();
    cmStdTCon.setnewTandCList(listnewTandCList);
    cmStdTCon.contractTermsandConditionsList=listcontractTermsandConditions;
    cmStdTCon.getshowTandC();
    cmStdTCon.setshowTandC(bshowTandC);
    cmStdTCon.getshowMultiPickofTandC();
    cmStdTCon.setshowMultiPickofTandC(bshowMultiPickofTandC);
    cmStdTCon.getinactiveTermsbool();
    cmStdTCon.setinactiveTermsbool(binactiveTermsbool);
    cmStdTCon.addCurSelectedTandC();
    cmStdTCon.removeCurSelectedTandC();
    cmStdTCon.confirmTerms();
    cmStdTCon.saveTerms();
    cmStdTCon.getshowStdTandC();
    Test.stopTest();
    }
}