profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Motion_Page__c.object
<CustomObject>
    <fields>
        <fullName>Domain__c</fullName>
        <formula>TEXT(Sales_Motion_Name__r.Domain__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked to Publish this Sales Motion Page</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Motion_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Motion Name</label>
        <referenceTo>Sales_Motion__c</referenceTo>
        <relationshipLabel>Sales Motion Pages</relationshipLabel>
        <relationshipName>Sales_Motion_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Name__c</fullName>
        <formula>TEXT(Sales_Motion_Name__r.Solution_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Type__c</fullName>
        <formula>TEXT(Sales_Motion_Name__r.Solution_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stages_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stages Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Motion Page</label>
    <nameField>
        <label>Page Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Motion Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Motion_Page_Section__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit_List__c</fullName>
        <label>Business Unit List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Configure_Country__c</fullName>
        <formula>HYPERLINK(&apos;/apex/SalesMotionCountryConfig?Id=&apos;&amp;Id &amp; &apos;&amp;page=country&apos;, IMAGE(&quot;resource/1329132263000/ConfigureCountry&quot;, &apos;ConfigureCountry&apos;),&apos;_parent&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Configure Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_List__c</fullName>
        <label>Country List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <formula>TEXT(Sales_Motion_Page__r.Sales_Motion_Name__r.Domain__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked to Publish this Sales Motion Page Section</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language_List__c</fullName>
        <label>Language List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region_List__c</fullName>
        <label>Region List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SalesEdge_Category__c</fullName>
        <description>SalesEdge Section Category</description>
        <label>SalesEdge Section Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Motion_Name__c</fullName>
        <formula>Sales_Motion_Page__r.Sales_Motion_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Motion Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Motion_Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Motion Page</label>
        <referenceTo>Sales_Motion_Page__c</referenceTo>
        <relationshipLabel>Sales Motion Page Sections</relationshipLabel>
        <relationshipName>Sales_Motion_Page_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SectionContentLong__c</fullName>
        <label>SectionContentLong</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Content__c</fullName>
        <label>Section Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Side_Bar__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Side Bar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solution_Name__c</fullName>
        <formula>TEXT(Sales_Motion_Page__r.Sales_Motion_Name__r.Solution_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Type__c</fullName>
        <formula>TEXT(Sales_Motion_Page__r.Sales_Motion_Name__r.Solution_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prepare - 0%</fullName>
                </value>
                <value>
                    <fullName>Plan - 1%</fullName>
                </value>
                <value>
                    <fullName>Discover - 10%</fullName>
                </value>
                <value>
                    <fullName>Qualify - 30%</fullName>
                </value>
                <value>
                    <fullName>Propose - 60%</fullName>
                </value>
                <value>
                    <fullName>Commit - 90%</fullName>
                </value>
                <value>
                    <fullName>Win - 100%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Request_Type__c</fullName>
        <label>Support Request Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Contracts Support</fullName>
                </value>
                <value>
                    <fullName>Request Custom Service Support</fullName>
                </value>
                <value>
                    <fullName>Request Global Business Ops PM Support</fullName>
                </value>
                <value>
                    <fullName>Request Pre-Sales Prod Tech Support</fullName>
                </value>
                <value>
                    <fullName>Request Pre-Sales Prod Tech Support - IM</fullName>
                </value>
                <value>
                    <fullName>Request Pre-Sales Prod Tech Support - SE</fullName>
                </value>
                <value>
                    <fullName>Request Proposal Support</fullName>
                </value>
                <value>
                    <fullName>Specialist Support Request</fullName>
                </value>
                <value>
                    <fullName>SOC Support Request</fullName>
                </value>
                <value>
                    <fullName>PG Custom SE Support Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Static Content</fullName>
                </value>
                <value>
                    <fullName>SalesEdge Content</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Motion Page Section</label>
    <nameField>
        <label>Section Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Motion Page Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/SalesMotionPageCloneCtrl.cls
/* 
Author: Micky Toms

History:
Version Date            Modified By     Description     
----------------------------------------------------------------------------------------------------
1.0     Nov-2012     Micky Toms   Created for R14.2 - VF controller for Sales Motion Page Clone page

*/
public class SalesMotionPageCloneCtrl {
    private apexpages.standardcontroller controller;
    public String currentId = ApexPages.currentPage().getParameters().get('id');
    public Sales_Motion_Page__c salesMotionsPages {get; set;}
    public List<Sales_Motion_Page_Section__c> salesMotionsPageSections {get; set;}
    List<SalesMotionPageSectionWrapper> SalesmotionPageSectionWrapperRecs=new List<SalesMotionPageSectionWrapper>();
    
    public SalesMotionPageCloneCtrl(ApexPages.StandardController controller){
        this.controller = controller;
        getSalesMotionPages();
        getSalesMotionSections();
    }
    
    private void getSalesMotionPages(){
        salesMotionsPages  = [SELECT  Name, Domain__c,IsActive__c,Sales_Motion_Name__c,Solution_Name__c,Solution_Type__c,RecordType.Name,RecordTypeId,Sort_Order__c,Stages_Enabled__c  FROM Sales_Motion_Page__c WHERE Id = :currentId limit 1]; 
        salesMotionsPages.IsActive__c=false;
        System.Debug('##salesMotionsPages'+salesMotionsPages);
    }
    /*public List<Sales_Motion_Page_Section__c> getSalesMotionSections(){
        return [SELECT Configure_Country__c, Country_List__c, Country__c, Id, Name, RecordTypeId, SalesEdge_Category__c, Sales_Motion_Page__c, Sales_Motion_Page__r.Name, SectionContentLong__c, Section_Content__c, Side_Bar__c, Sort_Order__c, Stage__c, Support_Request_Type__c, Type__c FROM Sales_Motion_Page_Section__c WHERE Sales_Motion_Page__c = :currentId ORDER BY Sales_Motion_Page__c ASC];
    }*/
    public void getSalesMotionSections(){
        salesMotionsPageSections  = [SELECT Configure_Country__c, Country_List__c,Region_List__c,Business_Unit_List__c,Language_List__c, Country__c, Id, Name, RecordTypeId,RecordType.Name, SalesEdge_Category__c, Sales_Motion_Page__c, Sales_Motion_Page__r.Name, SectionContentLong__c, Section_Content__c, Side_Bar__c, Sort_Order__c, Stage__c, Support_Request_Type__c, Type__c,IsActive__c FROM Sales_Motion_Page_Section__c WHERE Sales_Motion_Page__c = :currentId ORDER BY Sales_Motion_Page__c ASC]; 
        System.Debug('###salesMotionsPageSectionsQueryRes:' +salesMotionsPageSections);
        if(salesMotionsPageSections!=null){
            
            for(Sales_Motion_Page_Section__c lstsmps:salesMotionsPageSections ){
                System.Debug('##salesMotionsRegionList region'+lstsmps.Region_List__c);
                SalesmotionPageSectionWrapperRecs.add(new SalesMotionPageSectionWrapper(false,lstsmps.Name,lstsmps.SalesEdge_Category__c,lstsmps.Sort_Order__c,lstsmps.Type__c,lstsmps.RecordTypeId,lstsmps.Side_Bar__c,lstsmps.IsActive__c,lstsmps.Section_Content__c,lstsmps.Stage__c,lstsmps.Country_List__c,lstsmps.Region_List__c,lstsmps.Business_Unit_List__c,lstsmps.Language_List__c,lstsmps.Support_Request_Type__c));
            }
            System.Debug('##SalesmotionPageSectionWrapperRecs'+SalesmotionPageSectionWrapperRecs);
        }
        
        //return null;
    }
    public class SalesMotionPageSectionWrapper{
        public Boolean selected {get;set;}
        public string Name {get;set;}
        public string SalesEdgeCategory{get;set;}
        public Decimal SortOrder{get;set;}
        public string Type{get;set;}
        public Id RecordTypeId{get;set;}
        public Boolean Sidebar{get;set;}
        public Boolean IsActive{get;set;}
        public string SectionContent{get;set;}
        public string Stage{get;set;}
        public string Country{get;set;}
        public string Region{get;set;}
        public string BusinessUnit{get;set;}
        public string Language{get;set;}
        public string SupportReq{get;set;}
        public SalesMotionPageSectionWrapper(){
        } 
        public SalesMotionPageSectionWrapper(Boolean selvalue,String pgName,string seCategory,Decimal srtOrder,string typ,Id rectypeid,Boolean sdebar,Boolean isactve,string seccontent,string stg, string cntry,string reg,string busunit,string lang,string suppreq){
           selected=selvalue;
           Name=pgName;
           SalesEdgeCategory=seCategory;
           SortOrder=srtOrder;
           Type=typ;
           RecordTypeId=rectypeid;
           Sidebar=sdebar;
           IsActive=isactve;
           SectionContent=seccontent;
           Stage=stg;
           Country=cntry;
           Region=reg;
           BusinessUnit=busunit;
           Language=lang;
           SupportReq=suppreq;
        }
    }
    
    public PageReference Save(){
        System.Debug('SalesmotionPageSectionWrapperRecs'+SalesmotionPageSectionWrapperRecs);
        System.Debug('##salesMotionsPages'+salesMotionsPages);
        Sales_Motion_Page__c salesMotionsPagesToClone =new Sales_Motion_Page__c(); 
        List<Sales_Motion_Page__c> salesMotionsPagesToCloneSave=new List<Sales_Motion_Page__c>();
        List<Sales_Motion_Page_Section__c> lstsmpsToClone=new List<Sales_Motion_Page_Section__c>();
        string smpagecloneid;
        if(salesMotionsPages.Sales_Motion_Name__c==null || salesMotionsPages.Name==null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please ensure that you select the SalesMotion Name and enter the Page Title!!'));
            return null;
        }
        


        salesMotionsPagesToClone.Name=salesMotionsPages.Name;
        salesMotionsPagesToClone.Sales_Motion_Name__c=salesMotionsPages.Sales_Motion_Name__c;
        salesMotionsPagesToClone.IsActive__c=salesMotionsPages.IsActive__c;
        salesMotionsPagesToClone.RecordTypeId=salesMotionsPages.RecordTypeId;
        salesMotionsPagesToClone.Sort_Order__c=salesMotionsPages.Sort_Order__c;
        salesMotionsPagesToClone.Stages_Enabled__c=salesMotionsPages.Stages_Enabled__c;
        salesMotionsPagesToCloneSave.add(salesMotionsPagesToClone);
        try{
            System.Debug('##salesMotionsPagesToCloneSave'+salesMotionsPagesToCloneSave);
            Insert salesMotionsPagesToCloneSave;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }
        for(Sales_Motion_Page__c smPage:salesMotionsPagesToCloneSave){
            smpagecloneid=smPage.id;
        }
        System.Debug('##SalesmotionPageSectionWrapperRecs'+SalesmotionPageSectionWrapperRecs);
        for(SalesMotionPageSectionWrapper smpsWrapperRecs:SalesmotionPageSectionWrapperRecs){
            Sales_Motion_Page_Section__c smpsToClone=new Sales_Motion_Page_Section__c();
            if(smpsWrapperRecs.selected==true){
              smpsToClone.Sales_Motion_Page__c=smpagecloneid;
              smpsToClone.Name= smpsWrapperRecs.Name; 
              smpsToClone.RecordTypeId=smpsWrapperRecs.RecordTypeId;
              smpsToClone.Sort_Order__c= smpsWrapperRecs.SortOrder; 
              smpsToClone.Side_Bar__c=smpsWrapperRecs.Sidebar;
              smpsToClone.Type__c=smpsWrapperRecs.Type;
              smpsToClone.SalesEdge_Category__c=smpsWrapperRecs.SalesEdgeCategory;
              smpsToClone.IsActive__c=smpsWrapperRecs.IsActive;
              smpsToClone.Section_Content__c=smpsWrapperRecs.SectionContent;
              smpsToClone.Stage__c=smpsWrapperRecs.Stage;
              smpsToClone.Country_List__c=smpsWrapperRecs.Country;
              smpsToClone.Region_List__c=smpsWrapperRecs.Region;
              smpsToClone.Business_Unit_List__c=smpsWrapperRecs.BusinessUnit;
              smpsToClone.Language_List__c=smpsWrapperRecs.Language;
              smpsToClone.Support_Request_Type__c=smpsWrapperRecs.SupportReq;
              lstsmpsToClone.add(smpsToClone);
            }
            
        }
        try{
            System.Debug('##lstsmpsToClone'+lstsmpsToClone);
            Insert lstsmpsToClone;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
        }
       ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.INFO, 'SalesMotion Page Cloned Successfully!'));
        PageReference previewPage = new PageReference('/'+smpagecloneid);
        previewPage.setRedirect(true);
        return previewPage;

    }
    
    public PageReference Cancel(){
        PageReference previewPage = new PageReference('/'+currentId );
        previewPage.setRedirect(true);
        return previewPage;
    }
    
    public List<SalesMotionPageSectionWrapper> getSalesmotionPageSectionWrapperRecs(){
        return SalesmotionPageSectionWrapperRecs;
    }
    public void setSalesmotionPageSectionWrapperRecs(list<SalesMotionPageSectionWrapper> SalesmotionPageSectionWrapperRecs){
        this.SalesmotionPageSectionWrapperRecs=SalesmotionPageSectionWrapperRecs;
    }
}