profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -ISO 3166 Country Code||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <externalId>true</externalId>
        <label>ISO 3166-1 Country Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

force-app/main/default/classes/VFCntrlr_SFDCtoDSPTest.cls
@isTest
private class VFCntrlr_SFDCtoDSPTest {
    
    @testSetup static void setup() {
        OWD__c owdSetting = new OWD__c();
        owdSetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        owdSetting.Oppty_Stage10__c = 'Discover - 10%';
        owdSetting.Oppty_Stage100__c = 'Win - 100%';
        owdSetting.Oppty_Stage30__c = 'Qualify - 30%';
        owdSetting.Oppty_Stage60__c = 'Propose - 60%';
        owdSetting.Oppty_Stage90__c = 'Commit - 90%';
        owdSetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        owdSetting.Oppty_Stage1__c = 'Plan - 1%';
        insert owdSetting;
        
        list<User> listUserTdf=TestDataFactory.createNPortalUser(1);
        insert listUserTdf;
        list<Account> listAccTdf=TestDataFactory.createNAccount(1, 'Partner Account');
        listAccTdf[0].Account_Country_Code__c='CL';
        insert listAccTdf;
        list<Opportunity> listOppTdf=TestDataFactory.createNOpportunities(1, 'Standard Opportunity');
        listOppTdf[0].AccountId=listAccTdf[0].id;
        TriggerExecutioncontroller.setSkipOpportunitySplitTriggers(True);
        insert listOppTdf;
        Country__c testCountry = new Country__c(Code__c='US'); 
        Country__c testCountry2 = new Country__c(Code__c='CA'); 
        list<Country__c> listContry =new list<Country__c>{testCountry, testCountry2}; 
            insert listContry;
    }   
    static testMethod void viewAccountinDSPTest() {
        Test.startTest();
        list<Account> listAcc=[Select id,Account_ID__c from Account Limit 1];
        list<user> listUser=[Select id from user limit 1];
        list<Opportunity> listOpp=[Select id from Opportunity Limit 1];
        String strurl = Label.SFDCtoDSP;
        String strredirectvalue2 = 'account/details/';
        String strnewCurrentParams = '#'+strredirectvalue2+'/001K000000tt4BB/87765';
        String strreturnurl = strurl+strnewCurrentParams;
        PageReference pr = new PageReference(strreturnurl);
        system.debug('*********account******' + strreturnurl);
        Test.setCurrentPage(pr);
        ApexPages.currentPage().getParameters().put('country', 'US');
        VFCntrlr_SFDCtoDSP controller = new VFCntrlr_SFDCtoDSP();
        controller.navtoDSP();
        String strnewCurrentParams2 = '#'+'quote/create&accountId='+listAcc[0].Account_ID__c+'&dealid=456';
        string strreturnurl2 = strurl+strnewCurrentParams2;
        PageReference pr2= new PageReference(strreturnurl2);
        system.debug('*********quote******' + strreturnurl2);
        Test.setCurrentPage(pr2);
        VFCntrlr_SFDCtoDSP controller2 = new VFCntrlr_SFDCtoDSP();
        controller2.navtoDSP();
        string strnewCurrentParams3 = '#'+'opportunity/details/'+listAcc[0].id+'&dealid=5678';
        string strreturnurl3 = strurl+strnewCurrentParams3;
        PageReference pr3 = new PageReference(strreturnurl3);
        Test.setCurrentPage(pr3);
        VFCntrlr_SFDCtoDSP controller3 = new VFCntrlr_SFDCtoDSP();
        controller3.navtoDSP();
        string strredirectvalue4 = 'account/';
        string strnewCurrentParams4 = '#/'+strredirectvalue4+listAcc[0].id+'&dealid=5678';
        string strreturnurl4 = strurl+strnewCurrentParams4;
        PageReference pr4 = new PageReference(strreturnurl4);
        Test.setCurrentPage(pr4);
        VFCntrlr_SFDCtoDSP controller4 = new VFCntrlr_SFDCtoDSP();
        controller4.navtoDSP();
        try{
            String strnewCurrentParams5 = Label.COM_URL+'?redirectvalue=opportunity/details/&id='+listAcc[0].id+'&country=&accountId='+listAcc[0].Account_ID__c;
            PageReference  pr5=new PageReference(strnewCurrentParams5);
            Test.setCurrentPage(pr5);
            VFCntrlr_SFDCtoDSP controller5=new VFCntrlr_SFDCtoDSP();
            controller5.navToDSP();
        }catch(Exception e){
            String strerrMsg = 'Account Country Code is empty';
            System.assert(e.getMessage().contains(strerrMsg));
        }  
        PageReference  pr6=new PageReference(Label.COM_URL+'?id=backId');
        Test.setCurrentPage(pr6);
        VFCntrlr_SFDCtoDSP controller6=new VFCntrlr_SFDCtoDSP();
        controller6.back();
        Test.stopTest();
    }
}