profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||WF / APP/ FU / OM - N ||Desc -||SFA -Y/PRM-Y||VAL -  N||CR# -R10.2 # 816  ||</description>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Full Legal Name of Your Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner Requests (Country)</relationshipLabel>
        <relationshipName>R00N70000002MeXqEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dun_and_Bradstreet_DUNS_Number__c</fullName>
        <description>Dun and Bradstreet DUNS Number</description>
        <label>Dun and Bradstreet DUNS Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF - Y - PRM English Partner Registration Duplicate;PRM English Partner Registration Incomplete;PRM English Partner Registration Submitted;PRM English Partner Registration Rejected/ APP/ FU / OM - N ||Email alert-Y-PRM English Partner Registration Duplicate;PRM English Partner Registration Incomplete;PRM English Partner Registration Submitted;PRM English Partner Registration Rejected
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSAddress__c</fullName>
        <label>GU/HQ_DUNSAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSBusinessName__c</fullName>
        <label>GU/HQ_DUNSBusinessName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSCity__c</fullName>
        <label>GU/HQ_DUNSCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSCountry__c</fullName>
        <label>GU/HQ_DUNSCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSID__c</fullName>
        <label>GU/HQ_DUNSID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSPostalCode__c</fullName>
        <label>GU/HQ_DUNSPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GU_HQ_DUNSState__c</fullName>
        <label>GU/HQ_DUNSState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISDUNSUpdated__c</fullName>
        <description>Partner Registration DUNS validation</description>
        <label>System Validated DUNS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Partner Requests</relationshipLabel>
        <relationshipName>R00N70000002MeZWEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Address_1__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Address_2__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Address 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Address_3__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Address 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_City__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner Requests (Organization Country)</relationshipLabel>
        <relationshipName>R00N70000002MeaAEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Fax__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Org_Phone__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Org_Postal_Code__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_State__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Organization State / Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Model__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -|What type of business are they in, a Retail shop vs. a Distributor etc. (Used in the Partner Registration form) |
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Primary Channel Business Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OEM (Original Equipment Manufacturer)</fullName>
                </value>
                <value>
                    <fullName>CSP (Cloud Service Provider)</fullName>
                </value>
                <value>
                    <fullName>Solution Provider (Reseller)</fullName>
                </value>
                <value>
                    <fullName>Consumer Partner</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Salutation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
                <value>
                    <fullName>Miss</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>Prof.</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>State / Province</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/VFCntrlr_SendPRDataToEMC.cls
public class VFCntrlr_SendPRDataToEMC { 
    //Send PR Data to EMC
    private Partner_Request__c partnerRequest;
    private Lead suggestionLead;
    //Constructor
    public VFCntrlr_SendPRDataToEMC(ApexPages.StandardController controller) {
        partnerRequest = (Partner_Request__c)controller.getRecord();     
        partnerRequest=[SELECT Last_Name__c,Company__c,Primary_Channel_Model__c,ID,OwnerID,Org_Country__c,Org_Country__r.name,Website__c,Org_Address_1__c,Phone__c,Fax__c,
                        Org_Address_2__c,Org_Address_3__c,Org_City__c,Org_State__c,Org_Postal_Code__c,Org_Phone__c,Org_Fax__c,
                        Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,City__c,State__c,Postal_Code__c,Country__c,Lead__c,
                        First_Name__c, Salutation__c,Email__c,Dun_and_Bradstreet_DUNS_Number__c,ISDUNSUpdated__c,GU_HQ_DUNSAddress__c,GU_HQ_DUNSBusinessName__c,GU_HQ_DUNSCity__c,GU_HQ_DUNSCountry__c,GU_HQ_DUNSID__c,GU_HQ_DUNSPostalCode__c,GU_HQ_DUNSState__c,
                        Country__r.name FROM Partner_Request__c WHERE id=:partnerRequest.id];
        System.debug('#####partnerRequest'+partnerRequest);
        if(partnerRequest.Lead__c!=null){
            suggestionLead = new Lead(id=partnerRequest.Lead__c);
        }  
    }
    public PageReference sendPRDataToEMC(){
        RecordType rectype;
        String strResult;
        System.PageReference returnPage;        
       try{
           system.debug('Inside sendPRDataToEMC ***'+partnerRequest.ID );
  
         strResult=SendPartReqData.sendPRCalloutREST(partnerRequest.ID);
           system.debug('strResult after calling rest-->'+strResult+'-----');
           if(strResult=='Success' || Test.isRunningTest()){
               returnPage=  new PageReference('/'+partnerRequest.ID);  
           }else{ 
               system.debug('result-->'+strResult+'-----');
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,strResult));               
                }
        }catch(Exception e){
            system.debug('result after calling rest inside exception-->'+strResult+'-----');
            system.debug('##MN: Caught APEX exception ' + e.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,strResult));      
         }       
       return returnPage;        
    }    
    public PageReference goBacktoPRPage(){          
        PageReference returnPage=  new PageReference('/'+partnerRequest.ID); 
       return returnPage ;        
    } 
    
}