profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN (AF)</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS (AX)</fullName>
                </value>
                <value>
                    <fullName>ALBANIA (AL)</fullName>
                </value>
                <value>
                    <fullName>ALGERIA (DZ)</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA (AS)</fullName>
                </value>
                <value>
                    <fullName>ANDORRA (AD)</fullName>
                </value>
                <value>
                    <fullName>ANGOLA (AO)</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA (AI)</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA (AQ)</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA (AG)</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA (AR)</fullName>
                </value>
                <value>
                    <fullName>ARMENIA (AM)</fullName>
                </value>
                <value>
                    <fullName>ARUBA (AW)</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA (AU)</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA (AT)</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN (AZ)</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS (BS)</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN (BH)</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH (BD)</fullName>
                </value>
                <value>
                    <fullName>BARBADOS (BB)</fullName>
                </value>
                <value>
                    <fullName>BELARUS (BY)</fullName>
                </value>
                <value>
                    <fullName>BELGIUM (BE)</fullName>
                </value>
                <value>
                    <fullName>BELIZE (BZ)</fullName>
                </value>
                <value>
                    <fullName>BENIN (BJ)</fullName>
                </value>
                <value>
                    <fullName>BERMUDA (BM)</fullName>
                </value>
                <value>
                    <fullName>BHUTAN (BT)</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA (BO)</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA (BA)</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA (BW)</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND (BV)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Partner Track</label>
        <referenceTo>Partner_Track__c</referenceTo>
        <relationshipName>Partner_Locations_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Location</label>
    <nameField>
        <label>Location	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Approved_for_Partner_Finder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Find a Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profile_Published_to_Partner_Finder__c</fullName>
        <label>Profile Published to Partner Finder</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/FAP_AutoCompleteLocation.cls
/**
REVISION HISTORY
================
Version     Author      Date            Release#    CR#       Description
-------     ------      ----            --------    ---       -----------
1.0         Sandhya     18-May-2012     13.7        7110      Contexual search on Location
1.1         Fenny       19-Jul-2012     13.7        7110      CRQ 0417
1.2         Sandhya     24-Jul-2012     13.7                  Defect#: 38172 
1.3         TK Chin     07-Dec-2012     14.2        7675      Contextual Search on Location by country  
1.4         Niveda      25-May-2019     FY20-0702   17541     FAP: Auto complete City. Search by City, postal code and distance
**/
global class FAP_AutoCompleteLocation extends FAP_AutoCompleteSearch{
    

    global FAP_AutoCompleteLocation(String searchString){
        super(searchString);
    }

    public override List<String> internalExecute(){ // Ver 1.1
        final List<String> distinct = new List<String>(); // Ver 1.1
        final Map<String,String> caseInsensitiveMapTemp = new Map<String,String>(); // Ver 1.1
        final Map<String,String> caseInsensitiveMap = new Map<String,String>(); // Ver 1.1
        final String searchStrWildcarded = FAP_StringUtils.ensureStringStartsEndsWithChar(this.searchString,'%');
        final Integer searchLimit = 5;
        
        // Ver 1.3 - R14.2 - CR7675 - Add country to the queries
        Map<String,String> params = FAP_PageUtils.getParameters('countryCode');
        String strCountryCode = '';
        if(params != null && params.size() > 0){
          system.debug('######## countryCode = ' + params.values().get(0));
          //strCountryCode = 'AND Country__c like \'%\( ' + params.values().get(0)+ '/)%\' ';
          //Ver 1.4
          strCountryCode = 'AND Country__c like \'%(' + params.values().get(0) +')%\'';
        }
        
        String strQuery1;
        
        strQuery1= 'SELECT City__c FROM Partner_Location__c ' +
                        'WHERE Partner_Track__r.Approved_for_Partner_Finder__c = true ' +
                        'AND Partner_Track__r.Profile_Published_to_Partner_Finder__c = \'Yes\' ' +
                        'AND Partner_Track__r.Partner_Account__c = true ' + strCountryCode +
                        'AND City__c like \'' + this.searchString + '%\' ORDER BY City__c LIMIT 1000';
        
        system.debug('******strQuery1******'+ strQuery1);
        // Ver 1.1
        for(Partner_Location__c location : Database.query(strQuery1)){
            if((location.City__c != null) && (!caseInsensitiveMapTemp.containsKey(location.City__c.toLowerCase()))){
                caseInsensitiveMap.put(location.City__c.toLowerCase(), location.City__c);
                caseInsensitiveMapTemp.put(location.City__c.toLowerCase(), location.City__c);
            }
            //Ver 1.1
            if(caseInsensitiveMapTemp.size() == 5){ break; }
        }
        List<String> distinctStartsWithList = new List<String>();
        distinctStartsWithList.addAll(caseInsensitiveMapTemp.keySet()); // Ver 1.1
        caseInsensitiveMapTemp.clear(); // Ver 1.1
        
        // Ver 1.2 Wildcard City search
        if(distinctStartsWithList.size() < searchLimit){
            String strQuery2;
            strQuery2= 'SELECT City__c FROM Partner_Location__c ' +
                            'WHERE Partner_Track__r.Approved_for_Partner_Finder__c = true ' +
                            'AND Partner_Track__r.Profile_Published_to_Partner_Finder__c = \'Yes\' ' +
                            'AND Partner_Track__r.Partner_Account__c = true ' + strCountryCode +
                            'AND (NOT City__c like \'' + this.searchString + '%\')' + 
                            'AND City__c like \'' + searchStrWildcarded + '\' ' +
                            'ORDER BY City__c LIMIT 1000';
            
            system.debug('******strQuery2******'+ strQuery2);
            for(Partner_Location__c location : Database.query(strQuery2)){
                if((location.City__c != null) && (!caseInsensitiveMapTemp.containsKey(location.City__c.toLowerCase()))){
                    caseInsensitiveMap.put(location.City__c.toLowerCase(), location.City__c);
                    caseInsensitiveMapTemp.put(location.City__c.toLowerCase(), location.City__c);
                }
                //Ver 1.1
                if(caseInsensitiveMapTemp.size()+distinctStartsWithList.size() == searchLimit){ break; }
            }
        }
        //Ver 1.2
        List<String> distinctWildCardList = new List<String>();
        distinctWildCardList.addAll(caseInsensitiveMapTemp.keySet());

        distinctWildCardList.sort();
        distinctStartsWithList.sort();
        for(string key : distinctStartsWithList){ distinct.add(caseInsensitiveMap.get(key)); }
        for(string key : distinctWildCardList){ distinct.add(caseInsensitiveMap.get(key)); }
        system.debug('******distinct*****'+distinct);
        return distinct;
    }
   
}