profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Type__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner Types</relationshipLabel>
        <relationshipName>Partner_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Uncheck to mark a partner type as inactive.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <inlineHelpText>The Partner Type list will be sorted ascendingly in the Partner Direct Page.</inlineHelpText>
        <label>Sort Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Type</label>
    <nameField>
        <label>Partner Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Type_Field_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <inlineHelpText>Enter the partner type name</inlineHelpText>
        <label>Partner Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Partner_Type__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Partner_Type__c</referenceTo>
        <relationshipLabel>Partner Type Field Configurations</relationshipLabel>
        <relationshipName>Partner_Type_Field_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Type Field Configuration</label>
    <nameField>
        <label>Partner Type Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Type Field Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerRegistrationFieldConfigExtTest.cls
@ isTest
public class PartnerRegistrationFieldConfigExtTest {
    
    Static Partner_Type__c pt1                                              = null;
    static List<Partner_Type_Field_Configuration__c> tempFieldConfigList    = null;
    
    private static void initializedData(){
        
        Country__c ctry = [SELECT Id FROM Country__c LIMIT 1];
        pt1 = new Partner_Type__c(Name='test PT1',Country__c=ctry.Id, Is_Active__c=true, Sort_Order__c=2);
        insert pt1;
        
        PageReference pageRef = new PageReference('/apex/PartnerRegistrationFieldConfig?ptid='+pt1.Id);
        Test.setCurrentPage(pageRef);
      
        
        
    }
    
    public static testMethod void testPartnerRegistrationFieldConfigCreation(){
        initializedData();      
        ApexPages.StandardController stdController = new ApexPages.StandardController(new Partner_Type_Field_Configuration__c());
        PartnerRegistrationFieldConfigExt ptfcController = new PartnerRegistrationFieldConfigExt(stdController);        
       // system.assertEquals(0, ptfcController.tempFieldConfigList.size());        
       // system.assertEquals(true, ptfcController.isNewPartnerTypeFlag);
        
        ptfcController.doPageLoad();
        system.assertEquals(false, ptfcController.isNewPartnerTypeFlag);
        system.assert(ptfcController.tempFieldConfigList.size()==ptfcController.fieldConfigOutputList.size());
        system.debug('fieldConfigOutputList=='+ptfcController.fieldConfigOutputList.size());
        
        system.assertEquals(true,ptfcController.isAtLeastOneAgreementSelected(ptfcController.fieldConfigSegmentOutputList));
        PageReference retPageRef = ptfcController.doSave();        
        PageReference defaultRetpageRef = PageUtils.redirect('/'+pt1.id);
        system.debug('url ='+retPageRef.getUrl());
        system.debug('defaultRetpageRef ='+defaultRetpageRef.getUrl());
        system.assertEquals(retPageRef.getUrl(), defaultRetpageRef.getUrl());
    } 
    
}