profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/CTI_Call_Log__c.object
<CustomObject>
    <description>This object is for SFDC-CTI integration project to log call activity on Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CTI Call Logs</relationshipLabel>
        <relationshipName>CTI_Call_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTI Call Log</label>
    <nameField>
        <displayFormat>CTI-{000000000}</displayFormat>
        <label>CTI Call Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTI Call Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/LOT_OCEAN_Email__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LOT OCEAN Email</label>
    <nameField>
        <displayFormat>LOE-{0000000000}</displayFormat>
        <label>LOT OCEAN Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOT OCEAN Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/LOT_Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LOT Region</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOT Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Ocean_Data__c.object
<CustomObject>
    <fields>
        <fullName>CFI_Delivery_Time_in_Weeks__c</fullName>
        <description>&quot;CFI Delivery Time in Weeks&quot; label has been Changed to &quot;Configuration Services in Weeks&quot; as part of 11.7 release CR4109. Now &apos;CFI&apos; means, &apos;Configuration Services&apos;.</description>
        <label>Configuration Services in Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CFS_Delivery_Time_in_Weeks__c</fullName>
        <label>CFS Delivery Time in Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_in_country_Delivery__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Days in country Delivery</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exception_Country__c</fullName>
        <label>Exception Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_the_sea_by_ODM__c</fullName>
        <defaultValue>0.00</defaultValue>
        <inlineHelpText>This is the time taken (in Days) for the product to ship from the Original Design Manufacturer to the delivery country.</inlineHelpText>
        <label>On the sea by ODM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ocean Data</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Ocean Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ocean Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Channel_Group__c.object
<CustomObject>
    <fields>
        <fullName>Region_Name__c</fullName>
        <description>INTEG-N/NON INTEG -Y/ APEX/CC -N||
WF / APP/ FU / OM -  N||
Desc -  ||
SFA -Y/ PRM -N||
VAL -N|| 
CR# - R 9.9 # 0166 ||</description>
        <label>Region Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_Business_Unit_Name__c</fullName>
        <label>Segment Business Unit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Channel Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Channel Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/TriggerExecutionControl__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>RecursiveCount__c</fullName>
        <defaultValue>4</defaultValue>
        <description>Specifies total number of recursive execution.
Setting this value to 1 =&gt; Skips the recursive execution initiated because of Workflow Field Updates.</description>
        <label>Recursive Count</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trigger Execution Control</label>
</CustomObject>

profilelist1exp/unpackaged/classes/VFCntrlr_CTICallLogEdit_Test.cls
/*
REVISION HISTORY
================
Version    Author          Date               Description
-------    ------          ----               -------------        
1.0        venu           6-dec-2019          Implimented TestDataFactory        
*/
@isTest
public class VFCntrlr_CTICallLogEdit_Test{
    @testSetup static void setup() {
        // Create common test OWD settings 
        OWD__c owdSetting = new OWD__c();
        owdSetting.Oppty_Stage1__c = 'Plan - 1%';
        owdSetting.Oppty_Stage10__c = 'Discover - 10%';
        owdSetting.Oppty_Stage30__c = 'Qualify - 30%';
        owdSetting.Oppty_Stage60__c = 'Propose - 60%';
        owdSetting.Oppty_Stage90__c = 'Commit - 90%';
        owdSetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        owdSetting.Oppty_Stage100__c = 'Win - 100%';
        owdSetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        Insert owdSetting;

        TriggerExecutionControl__c oTec = new TriggerExecutionControl__c();
        oTec.Name = 'Opportunity';
        oTec.RecursiveCount__c = 2;
        insert oTec;

        TriggerExecutionControl__c oliTect = new TriggerExecutionControl__c();
        oliTect.Name = 'OpportunityLineItem';
        oliTect.RecursiveCount__c = 2;
        insert oliTect;

        TriggerExecutionController.setSkipAllTriggers(true);

        list<Account> listAccTdf=TestDataFactory.createNAccount(2, 'Partner Account');
        insert listAccTdf;
        list<Opportunity> listOppTdf=TestDataFactory.createNOpportunities(1, 'Channel Opportunity');
        listOppTdf[0].AccountId=listAccTdf[0].id;
        insert listOppTdf;

        TriggerExecutionController.setSkipAllTriggers(false);
    }
    public static testMethod void testMethod1(){
        TriggerExecutionController.setSkipOpportunityTriggers(true);
        TriggerExecutionController.setSkipContactTriggers(true);
        List<string> listObjectNames = new List<string>();
        listObjectNames.add('Opportunity');
        SystemBehaviorBypasser.setSkipValidationRules(listObjectNames);
        
        Opportunity objOpp;
        Ocean_Data__c objOceanData;
        LOT_REGION__c objLOTRegion;
        LOT_OCEAN_EMAIL__c objLOTOceanEmail;    
        Sales_Channel_Group__c objSalesChannelGrp;
        Account objAccount;
        
        objSalesChannelGrp = new Sales_Channel_Group__c();
        objSalesChannelGrp.Name = 'TestChannelGroup1';
        objSalesChannelGrp.Region_Name__c = 'REGION1';
        objSalesChannelGrp.Segment_Business_Unit_Name__c = 'LARGE ENTERPRISE';        
        insert objSalesChannelGrp;
        
        /* objAccount = new Account();
objAccount.Name = 'TestAccount';
objAccount.Sales_Channel__c = objSalesChannelGrp.Id;
insert objAccount;
*/
        list<Account> listAcc=[Select id from Account Limit 1];
        listAcc[0].Sales_Channel__c = objSalesChannelGrp.Id;
        update listAcc;
        CTI_Call_Log__c objCTICL = new CTI_Call_Log__c();
        objCTICL.Account__c = listAcc[0].Id;
        insert objCTICL;
        system.assertNotEquals(listAcc[0].Id, null);
        objOceanData = new Ocean_Data__c();
        objOceanData.Days_in_country_Delivery__c = 70;
        objOceanData.On_the_sea_by_ODM__c = 70;
        objOceanData.CFI_Delivery_Time_in_Weeks__c = 10;
        objOceanData.CFS_Delivery_Time_in_Weeks__c=10;
        objOceanData.Exception_Country__c = 'COUNTRY1';
        objOceanData.MSP_Incremental_in_Weeks__c = 10;
        objOceanData.Region__c = 'REGION1';
        objOceanData.Ship_Rate__c = 4;
        objOceanData.Source__c = 'Compal';
        objOceanData.Pallet_Rate__c = 2;        
        insert objOceanData;
        
        objLOTRegion = new LOT_Region__c();
        objLOTRegion.Name = 'COUNTRY1';
        objLOTRegion.Region__c = 'REGION1';
        objLOTRegion.Threshold_Region__c = 'EMEA';        
        insert objLOTRegion;
        
        objLOTOceanEmail = new LOT_OCEAN_EMAIL__c();
        objLOTOceanEmail.Country__c = objLOTRegion.Id;
        objLOTOceanEmail.Country_LE__c = 'test@testmail.com';
        objLOTOceanEmail.region__c = 'REGION1';            
        insert objLOTOceanEmail;
        
        TriggerControlHandler.setOpportunityTriggersInactive();
        TriggerExecutionController.setSkipOpportunityTriggers(true);
        
        /*   objOpp= new Opportunity (AccountID=objAccount.Id ,
RecordTypeId= '012A0000000Vjtg',
Name='TestOpp 4',
Type = 'Run Rate',
Domain__c='Deal Reg',
Solution_Type__c = 'Campus',
Solution_Name__c = 'Wireless Switches',
StageName='Commit - 90%',
Deal_Registration_Status__c = 'Recalled',
Deal_Created_Date_Time__c = System.Now(),
Deal_Expiration_Timeframe__c='60',
// Related_Parent_Opportunity__c = testParentOpportunity.Id, 
CloseDate= System.Now().Date().addDays(180),
Deal_Expiration_Date__c=System.Now().Date().addDays(4),
Request_Status__c='New', 
Forecast_Category_Override__c = 'Omitted');
insert objOpp;  
*/
        list<Opportunity> listOpp=[Select id from Opportunity Limit 1];
        
        /*     objOpp = new Opportunity();
objOpp.RecordTypeId = '012300000004zf2';
objOpp.Quote_Numbers__c = '123456';
objOpp.Customer_Requested_Delivery_Date__c = system.today() + 60;
//objOpp.StageName='Propose - 60%';
// objOpp.Probability = 60;
objOpp.AccountId = objAccount.Id;
objOpp.Name = 'TEST Oppty 1';
objOpp.CloseDate = System.today() + 30;
objOpp.Primary_Product_Delivery_Address_Region__c = 'REGION1';
objOpp.Primary_Product_Delivery_Address_Country__c = 'COUNTRY1';
objOpp.Region__c = 'APJ';
objOpp.Competitor_Lost_To__c = 'Unknown';
objOpp.CTI_Call_Log_Id__c = objCTICL.Id;
objOpp.StageName = 'Plan - 1%';
objOpp.Probability = 1;
//  Test.startTest();
insert objOpp; */
        
        TriggerExecutionController.setSkipOpportunityTriggers(false);         
        TriggerControlHandler.setOpportunityTriggersActive();
        
        Contact objCon = new Contact();
        objCon.FirstName = 'Test FName';
        objCon.LastName = 'Test LastName';
        objCon.CTI_Call_Log_Id__c = objCTICL.Id;
        objCon.AccountId = listAcc[0].Id;
        objCon.Phone = '1234567890';
        insert objCon;
        
        VFCntrlr_CTICallLogEdit objVFCTICL = new VFCntrlr_CTICallLogEdit(new ApexPages.StandardController(objCTICL));
        objVFCTICL.refreshOpportunity();
        objVFCTICL.refreshContact();
        objVFCTICL.saveRecord();
    }
    
    public static testMethod void testMethod2(){
        Test.startTest();
        List<string> listObjectNames = new List<string>();
        listObjectNames.add('Opportunity');
        SystemBehaviorBypasser.setSkipValidationRules(listObjectNames);
        Opportunity objOpp;
        Ocean_Data__c objOceanData;
        LOT_REGION__c objLOTRegion;
        LOT_OCEAN_EMAIL__c objLOTOceanEmail;    
        Sales_Channel_Group__c objSalesChannelGrp;
        //Account objAccount;
        //Account objAccount1;
        
        objSalesChannelGrp = new Sales_Channel_Group__c();
        objSalesChannelGrp.Name = 'TestChannelGroup1';
        objSalesChannelGrp.Region_Name__c = 'REGION1';
        objSalesChannelGrp.Segment_Business_Unit_Name__c = 'LARGE ENTERPRISE';        
        insert objSalesChannelGrp;
        
        /* objAccount = new Account();
objAccount.Name = 'TestAccount';
objAccount.Sales_Channel__c = objSalesChannelGrp.Id;
insert objAccount;

objAccount1 = new Account();
objAccount1.Name = 'TestAccount1';
objAccount1.Sales_Channel__c = objSalesChannelGrp.Id;
insert objAccount1;
*/
        list<Account> listAcc=[Select id from Account Limit 2];
        listAcc[0].Sales_Channel__c = objSalesChannelGrp.Id;
        listAcc[1].Sales_Channel__c = objSalesChannelGrp.Id;
        update listAcc;
        CTI_Call_Log__c objCTICL = new CTI_Call_Log__c();
        objCTICL.Account__c = listAcc[0].Id;
        insert objCTICL;
        system.assertNotEquals(listAcc[0].id, null);
        objOceanData = new Ocean_Data__c();
        objOceanData.Days_in_country_Delivery__c = 70;
        objOceanData.On_the_sea_by_ODM__c = 70;
        objOceanData.CFI_Delivery_Time_in_Weeks__c = 10;
        objOceanData.CFS_Delivery_Time_in_Weeks__c=10;
        objOceanData.Exception_Country__c = 'COUNTRY1';
        objOceanData.MSP_Incremental_in_Weeks__c = 10;
        objOceanData.Region__c = 'REGION1';
        objOceanData.Ship_Rate__c = 4;
        objOceanData.Source__c = 'Compal';
        objOceanData.Pallet_Rate__c = 2;        
        insert objOceanData;
        
        objLOTRegion = new LOT_Region__c();
        objLOTRegion.Name = 'COUNTRY1';
        objLOTRegion.Region__c = 'REGION1';
        objLOTRegion.Threshold_Region__c = 'EMEA';        
        insert objLOTRegion;
        
        objLOTOceanEmail = new LOT_OCEAN_EMAIL__c();
        objLOTOceanEmail.Country__c = objLOTRegion.Id;
        objLOTOceanEmail.Country_LE__c = 'test@testmail.com';
        objLOTOceanEmail.region__c = 'REGION1';            
        insert objLOTOceanEmail;
        
        TriggerControlHandler.setOpportunityTriggersInactive();
        TriggerExecutionController.setSkipOpportunityTriggers(true);
        
        /*    objOpp = new Opportunity();
objOpp.RecordTypeId = '012300000004zf2';
objOpp.Quote_Numbers__c = '123456';
objOpp.Customer_Requested_Delivery_Date__c = system.today() + 60;
objOpp.StageName='Propose - 60%';
objOpp.Probability = 60;
objOpp.AccountId = objAccount1.Id;
objOpp.Name = 'TEST Oppty 1';
objOpp.CloseDate = System.today() + 30;
objOpp.Primary_Product_Delivery_Address_Region__c = 'REGION1';
objOpp.Primary_Product_Delivery_Address_Country__c = 'COUNTRY1';
objOpp.Region__c = 'APJ';
objOpp.Competitor_Lost_To__c = 'Unknown';
insert objOpp; */
        /* objOpp= new Opportunity (AccountID=objAccount.Id ,
RecordTypeId= '012A0000000Vjtg',
Name='TestOpp 4',
Type = 'Run Rate',
Domain__c='Deal Reg',
Solution_Type__c = 'Campus',
Solution_Name__c = 'Wireless Switches',
StageName='Commit - 90%',
Deal_Registration_Status__c = 'Recalled',
Deal_Created_Date_Time__c = System.Now(),
Deal_Expiration_Timeframe__c='60',
// Related_Parent_Opportunity__c = testParentOpportunity.Id, 
CloseDate= System.Now().Date().addDays(180),
Deal_Expiration_Date__c=System.Now().Date().addDays(4),
Request_Status__c='New', 
Forecast_Category_Override__c = 'Omitted');
insert objOpp;  

*/
        list<Opportunity> listOpp=[Select id from Opportunity Limit 1];
        
        TriggerExecutionController.setSkipOpportunityTriggers(true);
        TriggerExecutionController.setSkipContactTriggers(true);  
        
        Contact objCon = new Contact();
        objCon.FirstName = 'Test FName';
        objCon.LastName = 'Test LastName';
        objCon.AccountId = listAcc[1].Id;
        objCon.Phone = '1234567890';
        insert objCon;
        Test.stopTest();
        
        VFCntrlr_CTICallLogEdit objVFCTICL = new VFCntrlr_CTICallLogEdit(new ApexPages.StandardController(objCTICL));
        objVFCTICL.objCTI.Opportunity__c = listOpp[0].Id;
        objVFCTICL.saveRecord();
        objVFCTICL.getRecordTypes();
        objVFCTICL.testMethod1();
        objVFCTICL.createOpportunity();
        objVFCTICL.objCTI.Contact__c = objCon.Id;
        objVFCTICL.saveRecord();
    }
}