profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Cancel_Request__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Request</fullName>
                </value>
                <value>
                    <fullName>Cancel Request</fullName>
                    <default>true</default>
                    <label>Cancel Request</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <inlineHelpText>16 Characters Required for this Field.  No Spaces.

Format:  XXXX-XXXX-XXXXXX</inlineHelpText>
        <label>Cost Center</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dell_Solution_Center_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Solution Center names:
Americas: Austin, Chicago, New York, Sao Paulo, Santa Clara, Washington D.C.
APJ: Shanghai, Singapore, Sydney, Tokyo
EMEA: Bracknell, Frankfurt, Limerick, Paris
For more information please go to http://dsc.dell.com</inlineHelpText>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Engagement_Type__c</field>
                <operation>equals</operation>
                <value>DSC</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements (Dell Solution Center Site) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_no_of_Customer_Attendees__c</fullName>
        <label>Estimated no. of Attendees</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scoping</fullName>
                </value>
                <value>
                    <fullName>SoW Delivered</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Site</fullName>
                </value>
                <value>
                    <fullName>Executed by EMC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Type of Customer Engagement event</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Architectural Design Session</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Analyst Events</fullName>
                </value>
                <value>
                    <fullName>Field Briefing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GSL_End_Date__c</fullName>
        <label>Preferred End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GSL_Start_Date__c</fullName>
        <inlineHelpText>This date is not guaranteed. Date of visit will be agreed with DSC team during the evaluation process, depending on availability of all resources to meet your requirements.</inlineHelpText>
        <label>Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NDA__c</fullName>
        <inlineHelpText>Specify if the Customer NDA is available. 

It is the account team’s responsibility to ensure the customer’s NDA is in place prior to their visit.</inlineHelpText>
        <label>NDA?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Account) - RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Primary_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Contact) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of person requesting the event.  If you are the requestor, this should be your name.</inlineHelpText>
        <label>Requestor Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Engagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Compliant__c</fullName>
        <inlineHelpText>Specify if the Customer is Trade Compliant.
 
It is the account team’s responsibility to ensure that the customer is Trade Compliant prior to their visit.</inlineHelpText>
        <label>Trade Compliant?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Catering__c</fullName>
        <inlineHelpText>If yes, you will see catering options when you build your agenda and you can print catering reports for your site.</inlineHelpText>
        <label>Offer Catering?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Transportation__c</fullName>
        <inlineHelpText>If yes, Account Execs will see a transportation area where they can specify pick up and drop off times. You will also see transportation options in the build agenda screen</inlineHelpText>
        <label>Offer Transportation?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <description>Select this for creating a new site</description>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestAfterSubmitCancelController.cls
@isTest
private class TestAfterSubmitCancelController{

    static testMethod void TestAfterSubmitCancelControllerTest() {
        Date tempStartDate = system.today();
        Date tempEndDate = system.today();
        Account newaccount= new Account(Name= 'Test Account');
        insert newaccount;    
        Contact con= new Contact(FirstName='ContactExcSafeWord1', LastName='ContactExcSafeWord1', AccountId=newaccount.Id,
                                 Phone='11111', Decision_Making_Role__c='Influencer',
                                 Job_Function__c='IT',Purchaser_Influence_over_Merged__c='Client-Desktops' );
        insert con;
        User testUser=[SELECT id FROM USER WHERE Isactive=true limit 1];
 
        Id siteId=IdLookupUtils.getRecordTypeId('Sites','Event_Location__c',true);
        Event_Location__c testSite=new Event_Location__c(Name='testSite',Region__c='Americas',
                                                         Active__c=true,Engagement_Type__c='DSC',
                                                         Offer_Catering__c='No',Offer_Transportation__c='No',
                                                         Email__c='test_user@dell.com',
                                                         recordTypeid=siteId);
        insert testSite;
        
        Id custId=IdLookupUtils.getRecordTypeId('Dell Solution Centers','Customer_Engagement__c',true);                         
        Test.startTest();
        Customer_Engagement__c CEDetail = new Customer_Engagement__c(Name = 'Pending CE',
                                                Requestor_Name__c = testUser.Id, 
                                                Cost_Center__c = '1111-1111-111111', 
                                                Estimated_no_of_Customer_Attendees__c = 11,
                                                Primary_Account__c = newaccount.Id,
                                                Primary_Contact__c = con.Id,
                                                NDA__c = 'No',
                                                Event_Status__c = 'Pending',
                                                GSL_Start_Date__c=tempStartDate,
                                                GSL_End_Date__c=tempEndDate,
                                                Event_Type__c='Design Sessions',
                                                Dell_Solution_Center_Site__c=testSite.Id,
                                                Trade_Compliant__c='No',
                                                RecordTypeId = custId);
        insert CEDetail;
        Test.stopTest();
        //PageReference  pr = new PageReference('/apex/AfterSubmitCancel?id='+CEDetail.Id);
        //PageReference  pr = new PageReference('/apex/AfterSubmitCancel?id='+CEDetail.Id);
        //Test.setCurrentPage(pr);
        AfterSubmitCancelController controller = new AfterSubmitCancelController(new ApexPages.StandardController(CEDetail));
        controller.updateCE.Cancel_Request__c='Change Request';
        controller.checkRequest();
        controller.getCEUpdateDetails();
        controller.getRequestFlag();
        controller.getSiteNameList();
        PageReference  pageRefExpected=new PageReference('/'+CEDetail.Id);
        PageReference  pageRefActual=controller.SaveButtonAction();  
        System.assertEquals(pageRefExpected.getURL(),pageRefActual.getURL()); 
        
        PageReference  pageRefCancelActual=controller.cancelButtonAction();  
        System.assertEquals(pageRefExpected.getURL(),pageRefCancelActual.getURL()); 
        
        controller.updateCE.Cancel_Request__c='Cancel Request'; 
        controller.checkRequest();
        controller.getCEUpdateDetails();
        controller.getRequestFlag();
        PageReference  pageRefRequestlActual=controller.SaveButtonAction();  
        System.assertEquals(pageRefExpected.getURL(),pageRefRequestlActual.getURL()); 
    }
}