profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Cancel_Request__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Request</fullName>
                </value>
                <value>
                    <fullName>Cancel Request</fullName>
                    <default>true</default>
                    <label>Cancel Request</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Change_Cancel_Reason__c</fullName>
        <label>Change/Cancel Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Change_Cancel_Request_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to be checked if the Change/Cancel button is clicked when the CE record is already submitted and Satus &quot;not equal to&quot; COMPLETED, CANCELLED  through code</description>
        <label>Change/Cancel Request Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Changed_To__c</fullName>
        <label>Changed Event Start Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Scoping</fullName>
                </value>
                <value>
                    <fullName>SoW Delivered</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Site</fullName>
                </value>
                <value>
                    <fullName>Executed by EMC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Type of Customer Engagement event</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Architectural Design Session</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Analyst Events</fullName>
                </value>
                <value>
                    <fullName>Field Briefing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GSL_Start_Date__c</fullName>
        <inlineHelpText>This date is not guaranteed. Date of visit will be agreed with DSC team during the evaluation process, depending on availability of all resources to meet your requirements.</inlineHelpText>
        <label>Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Changed_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Changed Site To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements (Change Site To) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_DateF__c</fullName>
        <formula>Calendar_Management__r.Start_Date__c</formula>
        <label>Confirmed Start Date</label>
        <type>Date</type>
    </fields>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <recordTypes>
        <fullName>EBC</fullName>
        <active>true</active>
        <description>Use this record type for: Customer Briefing, Field Briefing, Meeting and Tour. Formerly Executive Strategy and Relationship Development</description>
        <label>Executive Briefing Center</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Engagement_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Architectural Design Session</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Analyst Events</fullName>
                </value>
                <value>
                    <fullName>Field Briefing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <description>Select this for creating a new site</description>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AfterSubmitCancelController.cls
public class AfterSubmitCancelController{
    Boolean requestFlag=false;
    public List<Event_Location__c> locationList=new List<Event_Location__c>();
    public List<String>siteNameList = new List<String>();
    public Customer_Engagement__c updateCE{get; set;}
    public String siteSelected{get; set;}
    
    public afterSubmitCancelController(ApexPages.StandardController controller) {
        String engagement;
        this.updateCE= (Customer_Engagement__c)controller.getRecord(); 
        try{
           updateCE=[select Name,Cancel_Request__c,Change_Cancel_Reason__c ,Event_Start_Date_Changed_To__c,Event_Type__c,
                   Start_DateF__c,GSL_Start_Date__c, Id,Event_Status__c ,Site_Changed_To__c ,
                   Change_Cancel_Request_Flag__c,RecordType.Name From Customer_Engagement__c where Id=:updateCE.Id];
           if(updateCE.RecordType.Name=='Executive Briefing Center'){
               engagement='EBC';  
           }
           else{
               engagement='DSC';
           }
           locationList=[select Event__c,Id,Name FROM Event_Location__c where recordType.name='sites' and 
                       Active__c=true and Engagement_Type__c=:engagement];
           if(updateCE.Cancel_Request__c=='Change Request'){
               requestFlag=true;
           }  
        }
        catch(Exception e){
            System.debug('Exception Occured:'+e);
            PageUtils.addError('Please check the Customer Engagement'); 
        }
    }
    public PageReference cancelButtonAction() {
        return PageUtils.redirect('/'+updateCE.Id);
    }
    
    public PageReference SaveButtonAction() {
        if((updateCE.Cancel_Request__c!='Change Request')&&(updateCE.Cancel_Request__c!='Cancel Request')){
            PageUtils.addError('Please select an Action Type to submit the request'); 
            return null;  
        }
        getCEUpdateDetails();
        update updateCE;
        return PageUtils.redirect('/'+updateCE.Id);
    }
        
    public Boolean getrequestFlag(){
        return requestFlag;        
    }
    /* Generates site dropdown */
    public List<SelectOption> getSiteNameList(){
        List<SelectOption> options = new List<SelectOption>();
        if(options.size()==0){
            options.add(new SelectOption('', '-- Select One --'));
            if(locationList.size()==0){
                PageUtils.addError('No Site matching the criteria.  Please check the Customer Engagement.');
            }
            else{
                for (Event_Location__c loc: locationList){
                    options.add(new SelectOption(loc.Id, loc.Name));
                }
            }
        }
        return options;
    }
    public PageReference checkRequest(){
        if(updateCE.Cancel_Request__c=='Change Request'){
            requestFlag=true;
        }        
        if(updateCE.Cancel_Request__c=='Cancel Request'){
            requestFlag=false;
        } 
        return null;
    }
    
    public Customer_Engagement__c getCEUpdateDetails() {
        if(updateCE.Cancel_Request__c!=null){
            if(updateCE.Cancel_Request__c=='Change Request'){ 
                updateCE.Change_Cancel_Request_Flag__c=true;
                updateCE.Cancel_Request__c='Change Request';   
                updateCE.Site_Changed_To__c=siteSelected;
            }
            else{
                updateCE.Change_Cancel_Request_Flag__c=true;
                updateCE.Cancel_Request__c='Cancel Request';
            }
            return updateCE; 
        }
        else{
            return null;
        }           
    }
}