profilelist1exp/unpackaged/objects/Customer_Engagement__c.object
<CustomObject>
    <description>BOLT &amp; GSL project</description>
    <fields>
        <fullName>Customer_Background__c</fullName>
        <label>Customer Background</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Customer</fullName>
                </value>
                <value>
                    <fullName>Remote Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dell_Solution_Center_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Solution Center names:
Americas: Austin, Chicago, New York, Sao Paulo, Santa Clara, Washington D.C.
APJ: Shanghai, Singapore, Sydney, Tokyo
EMEA: Bracknell, Frankfurt, Limerick, Paris
For more information please go to http://dsc.dell.com</inlineHelpText>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Event_Location__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sites</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Engagement_Type__c</field>
                <operation>equals</operation>
                <value>DSC</value>
            </filterItems>
            <filterItems>
                <field>Event_Location__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements (Dell Solution Center Site) – RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_no_of_Customer_Attendees__c</fullName>
        <label>Estimated no. of Attendees</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Type of Customer Engagement event</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Briefing</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Architectural Design Session</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Analyst Events</fullName>
                </value>
                <value>
                    <fullName>Field Briefing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GSL_End_Date__c</fullName>
        <label>Preferred End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GSL_Start_Date__c</fullName>
        <inlineHelpText>This date is not guaranteed. Date of visit will be agreed with DSC team during the evaluation process, depending on availability of all resources to meet your requirements.</inlineHelpText>
        <label>Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NDA__c</fullName>
        <inlineHelpText>Specify if the Customer NDA is available. 

It is the account team’s responsibility to ensure the customer’s NDA is in place prior to their visit.</inlineHelpText>
        <label>NDA?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Objective_of_Visit__c</fullName>
        <label>Objective of Visit</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Potential_for_case_study__c</fullName>
        <inlineHelpText>Do you think your customer would be willing to be a reference or create a case study post the POC?</inlineHelpText>
        <label>Is there potential for a case study?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements (Primary Account) - RETIRED</relationshipLabel>
        <relationshipName>Customer_Engagements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Above_Answer__c</fullName>
        <label>Reason for Above Answer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Requestor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of person requesting the event.  If you are the requestor, this should be your name.</inlineHelpText>
        <label>Requestor Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Engagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Top_3_Pain_Points__c</fullName>
        <label>Top 3 Pain Points</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trade_Compliant__c</fullName>
        <inlineHelpText>Specify if the Customer is Trade Compliant.
 
It is the account team’s responsibility to ensure that the customer is Trade Compliant prior to their visit.</inlineHelpText>
        <label>Trade Compliant?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Engagement - RETIRED</label>
    <nameField>
        <label>Customer Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Engagements - RETIRED</pluralLabel>
    <recordTypes>
        <fullName>DSC</fullName>
        <active>true</active>
        <description>Use this record type for: Technical briefing, Hands-On Environment, Design Sessions and Proof of Concepts. Formerly Solution Deep Dive</description>
        <label>Dell Solution Centers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Event_Location__c.object
<CustomObject>
    <description>BOLT &amp; GSL project - for maintaining sites/rooms/tours</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>EBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Catering__c</fullName>
        <inlineHelpText>If yes, you will see catering options when you build your agenda and you can print catering reports for your site.</inlineHelpText>
        <label>Offer Catering?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Transportation__c</fullName>
        <inlineHelpText>If yes, Account Execs will see a transportation area where they can specify pick up and drop off times. You will also see transportation options in the build agenda screen</inlineHelpText>
        <label>Offer Transportation?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Location</pluralLabel>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <description>Select this for creating a new site</description>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/Customer_Engagements_DSCcontroller_test.cls
@isTest
public class Customer_Engagements_DSCcontroller_test{
static testmethod void myDSCtest()

{
string RTId ;
List<RecordType> RT=[select id from RecordType where SobjectType='Event_Location__c' and name='Sites' limit 1];
 for(RecordType r:RT)
    {
      RTId=r.Id;
    }

    Account acc = new Account();
    acc.Name = 'testAccount';
    insert acc;
    
    
    Event_Location__c elc = new Event_Location__c(
    Name ='test',
    Region__c ='APJ',
    Engagement_Type__c ='DSC',
    Email__c ='test@mail.com',
    Active__c = true,
    recordtypeid = RTId,
    Offer_Transportation__c ='yes',
    Offer_Catering__c ='yes');
    insert elc;
    
    Customer_Engagement__c custe = new Customer_Engagement__c(
    Name='test',
    Estimated_no_of_Customer_Attendees__c=114,
    Event_Type__c ='Breifing',
    Dell_Solution_Center_Site__c=elc.id,
    GSL_End_Date__c=System.Today(),
    GSL_Start_Date__c=System.Today(),
    Customer_Type__c='Onsite Customer',
    NDA__c='Yes',
    Trade_Compliant__c='Yes',
    Customer_Background__c='test',
    Objective_of_Visit__c='test',
    Top_3_Pain_Points__c='test',
    Potential_for_case_study__c='Yes',
    Reason_for_Above_Answer__c='test',
    Primary_Account__c = acc.id,
    Requestor_Name__c = UserInfo.getUserId()
    );
    insert custe;
    
    ApexPages.StandardController  stdCon = new ApexPages.StandardController(custe);
    Customer_Engagements_DSCcontroller dsct=new Customer_Engagements_DSCcontroller(stdCon);
    
    dsct.customerEng = custe;
    dsct.posId = elc.Id;
    dsct.editFlag = true;
    dsct.showHideErr = true;
    dsct.err = 'Please select both DSC Event Type and DSC Site';
    dsct.getsites();
    dsct.Displayerr();
    

   } 
   static testmethod void myDSCtestagain()

{
string RTId ;
List<RecordType> RT=[select id from RecordType where SobjectType='Event_Location__c' and name='Sites' limit 1];
 for(RecordType r:RT)
    {
      RTId=r.Id;
    }

    Account acc = new Account();
    acc.Name = 'testAccount';
    insert acc;
    
    
    Event_Location__c elc = new Event_Location__c(
    Name ='test',
    Region__c ='APJ',
    Engagement_Type__c ='DSC',
    Email__c ='test@mail.com',
    Active__c = true,
    recordtypeid = RTId,
    Offer_Transportation__c ='yes',
    Offer_Catering__c ='yes');
    insert elc;
    
    Customer_Engagement__c custe = new Customer_Engagement__c(
    Name='test',
    Estimated_no_of_Customer_Attendees__c=114,
    Event_Type__c = null,
    Dell_Solution_Center_Site__c=elc.id,
    GSL_End_Date__c=System.Today(),
    GSL_Start_Date__c=System.Today(),
    Customer_Type__c='Onsite Customer',
    NDA__c='Yes',
    Trade_Compliant__c='Yes',
    Customer_Background__c='test',
    Objective_of_Visit__c='test',
    Top_3_Pain_Points__c='test',
    Potential_for_case_study__c='Yes',
    Reason_for_Above_Answer__c='test',
    Primary_Account__c = acc.id,
    Requestor_Name__c = UserInfo.getUserId()
    );
    insert custe;
    
    ApexPages.StandardController  stdCon = new ApexPages.StandardController(custe);
    Customer_Engagements_DSCcontroller dsct=new Customer_Engagements_DSCcontroller(stdCon);
    
    dsct.customerEng = custe;
    dsct.customerEng.Event_Type__c = null;
    dsct.posId ='--None--';
    dsct.editFlag = false;
    dsct.showHideErr = true;
    dsct.err = 'Please select both DSC Event Type and DSC Site';
    dsct.getsites();
    dsct.Displayerr();
    

   } 
  
}