profilelist1exp/unpackaged/objects/Date_Range__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Date Range</label>
</CustomObject>

profilelist1exp/unpackaged/objects/NPS_Data__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NPS Data</relationshipLabel>
        <relationshipName>NPS_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NPS_Score__c</fullName>
        <label>NPS Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
    <label>NPS Data</label>
    <nameField>
        <label>NPS Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPS Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AccntPrevAvgNpsScoreCalculator.cls
/***********************************************************
    * Name          : AccntPrevAvgNpsScoreCalculator 
    * Description   : Class to query and retrieve the average previous NPS Score for all contacts for a list of accountClass 
    * ---------------------------------------------------------
    * Revision  Name             Date         Description
    * 1.0       Jessie Tan       24-Apr-2014  CR 9548  - Class to query and retrieve the average previous NPS Score for all 
    *                                                    contacts for a list of accountClass
    * 1.1       Kokilavani D     08-Aug-2014  CR 9548  - CRQ 0980 Changed the date range to reflect dates instead of number of days                                                                                                                                                             
************************************************************/

global class AccntPrevAvgNpsScoreCalculator extends AccntAvgNpsScoreCalculator {

    public override AggregateResult[] querySourceData(Set<Id> accountIdSet){
        
        Date_Range__c prevNPSDate = Date_Range__c.getValues('Previous_NPS_Data_Date_Range'); //v1.1
    
        //it includes 181 -360 ago. Day 181th and 360th ago is included as well.
        return [SELECT Contact__r.AccountId accountId , Contact__c, AVG(NPS_Score__c) avgScore FROM NPS_Data__c 
                    where Contact__r.AccountId in :accountIdSet
                    and (NPS_Score__c <> null and NPS_Score__c <> 0)
                    //v1.1 - Start
                    //and (Survey_Date__c = LAST_N_DAYS:360 and Survey_Date__c < LAST_N_DAYS:180 )
                    and (Survey_Date__c >= :prevNPSDate.Start_Date__c and Survey_Date__c <= :prevNPSDate.End_Date__c) //v1.1 - End
                    group by Contact__r.AccountId, Contact__c 
                    ];
         
         /*         
         return [SELECT Contact__r.AccountId accountId , Contact__c, AVG(NPS_Score__c) avgScore FROM NPS_Data__c 
                    where Contact__r.AccountId in :accountIdSet
                    and (NPS_Score__c <> null and NPS_Score__c <> 0)
                    and (Survey_Date__c = LAST_N_QUARTERS:4 and Survey_Date__c < LAST_N_QUARTERS:2 )
                    group by Contact__r.AccountId, Contact__c 
                    ];
                    
                    */
    }

}