profilelist1exp/unpackaged/objects/Demo_Unit__c.object
<CustomObject>
    <description>This object will contain information about the demo units.</description>
    <fields>
        <fullName>Partner_Account_Name__c</fullName>
        <label>Partner Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Demo Units</relationshipLabel>
        <relationshipName>Demo_Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Demo Unit</label>
    <nameField>
        <displayFormat>Du-{0000000}</displayFormat>
        <label>Demo Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Hub_Record_Deleted__c.object
<CustomObject>
    <description>Records of Partner Request, Opportunity, Competency Tracker, Partner Course, End Customer, End Customer Contact, Payment object when deleted will be moved to this staging table for Partner Hub integration.</description>
    <fields>
        <fullName>Key_Identifier__c</fullName>
        <description>Key identifier used in Partner Hub</description>
        <label>Key Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_GUID__c</fullName>
        <description>SFDC GUID of the deleted record</description>
        <label>Record GUID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Name of the object deleted</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Request</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Competency Tracker</fullName>
                </value>
                <value>
                    <fullName>Partner Course</fullName>
                </value>
                <value>
                    <fullName>End Customer</fullName>
                </value>
                <value>
                    <fullName>End Customer Contact</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Demo Unit</fullName>
                </value>
                <value>
                    <fullName>Demo Unit Setup</fullName>
                </value>
                <value>
                    <fullName>LOB Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Hub Record Deleted</label>
    <nameField>
        <displayFormat>HUB-{0000000000}</displayFormat>
        <label>Partner Hub Record Deleted</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Hub Records Deleted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/afterDeleteDemoUnitTrigrTest.cls
@isTest
private class afterDeleteDemoUnitTrigrTest {

    private static testmethod void afterDeleteDemoUnitTrigger(){
    
        Account account = new Account(name='HubTest',account_country_code__c='US');
        insert account;
        
        
        Demo_Unit__c DemoURec = new Demo_Unit__c();
        DemoURec.Partner_Account_Name__c = account.id;
        insert DemoURec;
        List <Demo_Unit__c>  DemoUTest = [Select Name, Id from Demo_Unit__c where Id = : DemoURec.id];
        delete DemoUTest;
        
        Test.startTest();
            
        List <Partner_Hub_Record_Deleted__c>  PartnerHubRecTest = [Select Key_Identifier__c, Record_GUID__c, Type__c from Partner_Hub_Record_Deleted__c where Record_GUID__c = : DemoURec.id];
        
        PartnerHubRecTest[0].Key_Identifier__c = DemoUTest[0].Name ;
        PartnerHubRecTest[0].Record_GUID__c = DemoUTest[0].Id ;
        PartnerHubRecTest[0].Type__c = 'Demo Unit' ;
                
        Test.stopTest();
        delete account;
		
    }
}