profilelist1exp/unpackaged/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <label>Partner Selected DUNS Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <inlineHelpText>End Customer mailing State</inlineHelpText>
        <label>Mailing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_city__c</fullName>
        <inlineHelpText>End Customer mailing city</inlineHelpText>
        <label>Mailing city</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_country__c</fullName>
        <label>Mailing country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_street__c</fullName>
        <inlineHelpText>End Customer mailing street</inlineHelpText>
        <label>Mailing street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005A00000018286</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>End Customers</relationshipLabel>
        <relationshipName>End_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Channel DB</fullName>
                </value>
                <value>
                    <fullName>Deal Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <inlineHelpText>Tax Id of the End Customer</inlineHelpText>
        <label>Tax Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>End Customer Zip Code</inlineHelpText>
        <label>Zip Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/End_Customer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>End Customers Contact</relationshipLabel>
        <relationshipName>End_Customers_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Channel DB</fullName>
                </value>
                <value>
                    <fullName>Deal Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>End Customer Contact</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers Contact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Mailing_Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting - Created for Generic Mail box Email Alerts to be sent based on Country.</description>
    <label>Order Support Country</label>
</CustomObject>

profilelist1exp/unpackaged/classes/DealReg_CustomerSelectionHelperTest.cls
/*
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 * 1.0      CR 13379                02-Aug-2016     Meera         Customer Selection - Check Duplicates before Adding New Customer
 * 
 * 
 *      
 */
@isTest
private class DealReg_CustomerSelectionHelperTest {

    static testMethod void dunsnumdupeTest() {
        // Create Partner Account
        TriggerExecutionController.setSkipAllTriggers(true);
        Account partneraccount = new Account(name='DupeTestAcc',account_country_code__c='US');
        insert partneraccount ;
        partneraccount.isPartner = true;
        partneraccount.Type = 'Partner';
        update partneraccount;
        
        
        
        End_Customer__c newendcutomer = new End_Customer__c();
        newendcutomer.DUNS_Number__c = '111111';
        newendcutomer.Name = 'Test Dupe DUNS Zeus';
        newendcutomer.Mailing_street__c = 'Test sreet';
        newendcutomer.Mailing_city__c = 'Test City';
        newendcutomer.Mailing_State__c = 'Test State';
        newendcutomer.Zip_Code__c = '34454';
        newendcutomer.Mailing_country__c = 'United States';
        newendcutomer.Tax_Id__c = '34567';
        newendcutomer.Source_System__c = 'Deal Registration';
        newendcutomer.Partner_Account__c = partneraccount.Id;
        insert newendcutomer;
        
        //Create end customer contact
        End_Customer_Contact__c endcustomerCntact = new End_Customer_Contact__c();
        
        endcustomerCntact.End_Customer__c = newendcutomer.id;
        endcustomerCntact.Last_Name__c = 'DupeTest';
        endcustomerCntact.Name = 'Zeus';
        endcustomerCntact.Email__c = 'NoReply@dell.com';
        endcustomerCntact.Source_System__c = 'Deal Registration';
        insert endcustomerCntact;
        
        Test.startTest();
        
        System.assertEquals(DealReg_CustomerSelectionHelper.checkEndCustomerDuplicate('111111',null,partneraccount.id).Name,newendcutomer.Name);
        System.assertEquals(DealReg_CustomerSelectionHelper.checkEndCustomerDuplicate(null,'Test Dupe DUNS Zeus',partneraccount.id).Name,newendcutomer.Name);
        System.assertEquals(DealReg_CustomerSelectionHelper.checkEndCustomerContactDuplicate('NoReply@dell.com',newendcutomer.id),'Zeus DupeTest');
        Test.stopTest();
        
        
    }
}