profilelist1exp/unpackaged/objects/Exception__c.object
<CustomObject>
    <fields>
        <fullName>Error_Codes__c</fullName>
        <label>Error Codes</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Messages__c</fullName>
        <label>Error Messages</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_type__c</fullName>
        <label>Object type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Undelete</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <label>Process Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <displayFormat>EX-{0000000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Schedule_Revenue_Batch_Setting__mdt.object
<CustomObject>
    <description>This is used to hold the batchclass excecution query rule for BatchOLIScheduleRevenueQtrCalc class</description>
    <fields>
        <fullName>BookDateFromPast__c</fullName>
        <inlineHelpText>select date to query from which bookdate the opptys to be considered</inlineHelpText>
        <label>BookDateFromPast</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IgnoreAllClosedOppty__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>check to ignore all the closed opptys in query</inlineHelpText>
        <label>IgnoreAllClosedOppty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RerunFailedRecords__c</fullName>
        <defaultValue>true</defaultValue>
        <description>to rerun the failed records during update</description>
        <inlineHelpText>check to rerun the failed records</inlineHelpText>
        <label>RerunFailedRecords</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Revenue Batch Setting</label>
    <pluralLabel>Schedule Revenue Batch Settings</pluralLabel>
</CustomObject>

profilelist1exp/unpackaged/classes/BatchOLIScheduleRevenueQtrCalc.cls
/*
* Author  : Harsha Chadalavada
* Purpose : To display Account Revenue Trends Information.
* 
* Revision   CR Number     Release No  Date            Modified By     Description
* --------   ---------     ----------  -----------     ------------    -----------
*  1.0       CR16316       FY19-0902   6-Aug-2018     Harsha          Created class to calculate revenue from OpportunityLineItemSchedule
*/

global class BatchOLIScheduleRevenueQtrCalc implements Database.Batchable<sObject>, Database.Stateful {
	
    /* Use the customized query from custom metadata "Schedule Revenue Batch Setting"  */
    
    public string OLIids; // Pass opportunityLineItem Id's as "('00k0m000003qSAf','00k0m000003iSAf','00k0m000003kSAf')"
    Public string sBookDateFromPast; 
    private static final Integer MAX_ATTEMPTS = 2;
    public boolean bRerunFailedRecords;
    public string query;
    public boolean bIgnoreAllClosedOppty;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        Schedule_Revenue_Batch_Setting__mdt srbs = [select id,RerunFailedRecords__c,BookDateFromPast__c,IgnoreAllClosedOppty__c from Schedule_Revenue_Batch_Setting__mdt limit 1];
        dateTime bookDate = ((srbs.BookDateFromPast__c != Null)? srbs.BookDateFromPast__c : Null);
        bRerunFailedRecords = srbs.RerunFailedRecords__c;
        bIgnoreAllClosedOppty = srbs.IgnoreAllClosedOppty__c;
        if(query == Null){
            query = 'SELECT id,Scheduled_Current_Qrt_Rev__c,Scheduled_Next_Qrt_Rev__c,HasRevenueSchedule '+
                'FROM opportunityLineItem '+
                'WHERE (HasRevenueSchedule = true) ';
        }
        if(bIgnoreAllClosedOppty){
            query+= 'AND (opportunity.isclosed = false) ';
        }
        if(bookDate != Null){
            sBookDateFromPast = bookDate.format('yyyy-MM-dd');
            query+= 'AND (opportunity.CloseDate >='+sBookDateFromPast+') AND (opportunity.stageName != \'Lost, Cancelled - 0%\') ';
        }
        if(OLIids!= Null){
            query+= 'AND (id in '+OLIids+') ';
        }
        system.debug('----query-----'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){       
        set<id> oliAllIds = new set<id>();
        list<opportunitylineitem> oliList = (list<opportunitylineitem>)scope;
        for(opportunitylineitem oli : oliList){
            oliAllIds.add(oli.Id);
        }        
        list<opportunitylineitem> oliUpdate = OLIScheduleRevenueQtrCalcHelper.updateSchRev(oliAllIds);
        if(Test.isRunningTest()){
            oliUpdate[0].S_P_Deal_Status__c = 'Rejected';
        }
        map<id, opportunitylineitem> oliUpdateSchRevMap = new map<id, opportunitylineitem>(oliUpdate);
        if(!oliUpdate.isempty()){
            try{
                integer iRetry=1;
                integer iRetry_dup=1;
                TriggerExecutionController.setSkipAllTriggers(true);
                Database.SaveResult[] lsrOLI;
                while(iRetry<=MAX_ATTEMPTS){
                    boolean bUpdateFail = false;
                    lsrOLI = Database.update(oliUpdate, false);
                    iRetry=3;
                    if(bRerunFailedRecords){
                        list<opportunitylineitem> oliFailedRec = new list<opportunitylineitem>();
                        for(integer i=0;i<lsrOLI.size();i++){
                            if (!lsrOLI.get(i).isSuccess()) {
                                bUpdateFail = true;
                                oliFailedRec.add(oliUpdateSchRevMap.get(oliUpdate.get(i).id));
                            }
                        }
                        if(bUpdateFail && (iRetry_dup<4)){
                            ++iRetry_dup;
                            iRetry = iRetry_dup;
                            oliUpdate.clear();
                            oliUpdate.addall(oliFailedRec);
                        }
                    }
                }
                TriggerExecutionController.setSkipAllTriggers(false);
                list<Exception__c> excpList = new list<Exception__c>();
                for(integer i=0;i<lsrOLI.size();i++){
                    if (!lsrOLI.get(i).isSuccess()) { 
                        System.debug('###DEBUG### BatchOLIScheduleRevQtrCalc update error - ' + lsrOLI.get(i).getID() + ' -- '+ lsrOLI.get(i));
                        system.debug('error record ID----'+oliUpdate.get(i).id);
                        /*Database.Error objError = lsrOLI[i].getErrors().get(0);
                        system.debug('objError----'+objError);
                    	string strErrMsg = objError.getMessage().left(240);
                        string strStatusCode = string.valueof(objError.getStatusCode()).left(240);
                        excpList.add(new Exception__c(Error_Messages__c='-Update failed-'+strErrMsg,
                                                     Object_type__c='OpportunityLineItem',
                                                     Operation__c='Update', Process_Name__c='BatchOLIScheduleRevQtrCalc',
                                                     Notes__c='BatchOLIScheduleRevQtrCalc class - updatefailed - '+lsrOLI.get(i),
                                                     Object_ID__c=oliUpdate.get(i).id,
                                                     Error_Codes__c=strStatusCode));
                        //failedOLIids.add(oliUpdate.get(i).id);*/
                    }
                }
                /*if(!excpList.isEmpty()){
                    Database.SaveResult[] lsrExcp = Database.insert(excpList, false);
                    //reRunBatchClass = true;
                	system.debug('*****Harsha****excpList : '+excpList);
                	system.debug('*****Harsha****lsrExcp : '+lsrExcp);
                   // bExceptionExist = true;
                                        
                }*/
                
            }
            catch(exception e){
                System.debug('###DEBUG### BatchOLIScheduleRevQtrCalc exception error - ' +e);
            }
            
        }
    }
    
    global void finish(Database.BatchableContext BC){
        system.debug('------BatchOLIScheduleRevQtrCalc---- FINSH METHOD-----');
        map<string, date> qtrsMap = OLIScheduleRevenueQtrCalcHelper.getFiscalQtrs();
        date nextQtrstart = qtrsMap.get('nextQtrStart');
        integer iDay = nextQtrstart.day()+2; //to start on Monday.
        integer iMonth = nextQtrstart.month();
        integer iYear = nextQtrstart.year();
        string cronTrg = '0 0 9 '+iDay+' '+iMonth+' ? '+iYear;
        BatchOLIScheduleRevenueQtrCalc_Scheduler g = new BatchOLIScheduleRevenueQtrCalc_Scheduler();
		system.schedule('BatchOLIScheduleRevenueQtrCalc_Scheduler'+system.now(), cronTrg, g);
       
    }
}