profilelist1exp/unpackaged/objects/FAP_Customization__c.object
<CustomObject>
    <description>To store the fields data that are added to Search page of Find a Partner</description>
    <fields>
        <fullName>Field_Order__c</fullName>
        <label>Field Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_label__c</fullName>
        <label>Field label</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_type__c</fullName>
        <label>User type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authenticated</fullName>
                </value>
                <value>
                    <fullName>Un-authenticated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FAP Customization</label>
    <nameField>
        <label>APIName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAP Customizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/FAP_CustomizationControllerTest.cls
@IsTest
private class FAP_CustomizationControllerTest {
    
    private static testMethod void testHidden(){
        FAP_Customization__c fapCustObj = new FAP_Customization__c(
            Field_label__c = 'Distance',
            Location__c = 'Hidden',
            Field_Order__c = 1,
            User_type__c = 'Un-authenticated',
            Region__c = 'NA',
            Is_Active__c = true);
            
            insert fapCustObj;
            
            FAP_CustomizationController controller = new FAP_CustomizationController();
            controller.fapCustObj.Region__c = 'NA';
            controller.fapCustObj.User_type__c = 'Un-authenticated';
            controller.fapCustObj.Is_Active__c =  true;
            
            system.AssertEquals(controller.fapCustObj.Is_Active__c,true);
            controller.doquery();
            controller.gethiddenSelectOptions();
            controller.selectToRegular();
           
    }    
    
     private static testMethod void tesRegular(){
         
         List<FAP_Customization__c> lstFAPCust = new List<FAP_Customization__c>{new FAP_Customization__c (Field_label__c = 'Competencies', Location__c = 'Regular',Field_Order__c = 1,User_type__c = 'Un-authenticated', Region__c = 'NA', Is_Active__c = true ),
                                                                            new FAP_Customization__c (Field_label__c = 'Industry', Location__c = 'Regular',Field_Order__c = 2,User_type__c = 'Authenticated', Region__c = 'LATAM', Is_Active__c = true )};
                                                                                
           insert lstFAPCust ;
           
           FAP_CustomizationController controller = new FAP_CustomizationController();
            controller.fapCustObj.Region__c = lstFAPCust[1].Region__c;
            controller.fapCustObj.User_type__c = lstFAPCust[1].User_type__c;
            controller.fapCustObj.Is_Active__c =  lstFAPCust[1].Is_Active__c;
            controller.doquery();
            system.AssertEquals(controller.fapCustObj.Region__c,lstFAPCust[1].Region__c);
            controller.getregularSelectOptions();
            controller.MoveUpRegular();
            controller.selectToRegular();
            controller.MoveDownRegular();
            controller.unSelectFromRegular();
            controller.save();
           
         }
         
         private static testMethod void tesRegularHidden(){
             
            List<FAP_Customization__c> lstFAPCust = new List<FAP_Customization__c>{new FAP_Customization__c (Field_label__c = 'Location', Location__c = 'Hidden',Field_Order__c = 1,User_type__c = 'Authenticated', Region__c = 'LATAM', Is_Active__c = true ),
                                                                                new FAP_Customization__c (Field_label__c = 'Distance', Location__c = 'Regular',Field_Order__c = 2,User_type__c = 'Authenticated', Region__c = 'LATAM', Is_Active__c = true ),
                                                                                new FAP_Customization__c (Field_label__c = 'Industry', Location__c = 'Regular',Field_Order__c = 3,User_type__c = 'Authenticated', Region__c = 'LATAM', Is_Active__c = true ),
                                                                                new FAP_Customization__c (Field_label__c = 'Competencies', Location__c = 'Regular',Field_Order__c = 4,User_type__c = 'Authenticated', Region__c = 'LATAM', Is_Active__c = true ),
                                                                                new FAP_Customization__c (Field_label__c = 'Find a Reseller', Location__c = 'Regular',Field_Order__c = 5,User_type__c = 'Authenticated', Region__c = 'LATAM', Is_Active__c = true )
            };
                                                                                
           insert lstFAPCust ;
            FAP_CustomizationController controller = new FAP_CustomizationController();
            controller.fapCustObj.Region__c = lstFAPCust[1].Region__c;
            controller.fapCustObj.User_type__c = lstFAPCust[1].User_type__c;
            controller.fapCustObj.Is_Active__c =  lstFAPCust[1].Is_Active__c;
            controller.doquery();
            controller.selectedRegular = new List<string>{lstFAPCust[0].Field_label__c,lstFAPCust[1].Field_label__c};
            system.Assert(controller.selectedRegular.contains(lstFAPCust[0].Field_label__c));
            controller.MoveUpRegular();
            controller.MoveDownRegular();
            controller.unSelectFromRegular();
            
            //controller.save();
            
           
           
         }
     
}