profilelist1exp/unpackaged/objects/GDM_Request__c.object
<CustomObject>
    <description>GDM Requests include the following:
 Create Account / Reactivate Account
 Change Ownership
 Customer Linkage
 Org Change
 SFDC Updates
 Access to Tools
 Deactivate Account
 Account Report
 Account Update</description>
    <fields>
        <fullName>Badge_Number__c</fullName>
        <label>Badge Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buddy_Access_End_Date__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The date on which Buddy Access needs to be removed</inlineHelpText>
        <label>Buddy Access End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Buddy_Access_Start_Date__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The date from which Buddy Access is requested</inlineHelpText>
        <label>Buddy Access Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Buddy_Access_Status__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <label>Buddy Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved and scheduled</fullName>
                </value>
                <value>
                    <fullName>Providing Access</fullName>
                </value>
                <value>
                    <fullName>Access provided</fullName>
                </value>
                <value>
                    <fullName>Removing Access</fullName>
                </value>
                <value>
                    <fullName>Access removed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buddy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The Rep that will be the back-up for the Rep on Leave</inlineHelpText>
        <label>Buddy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GDM_Requests9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments2__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>Optionally, feel free to provide any additional comments, relevant to this request</inlineHelpText>
        <label>Comments</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GDM_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GDM Request</label>
        <referenceTo>GDM_Request__c</referenceTo>
        <relationshipLabel>GDM Requests</relationshipLabel>
        <relationshipName>GDM_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROL_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ROL Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GDM_RequestsE9NC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_Requested__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <label>Reason Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sickness</fullName>
                </value>
                <value>
                    <fullName>Holidays</fullName>
                </value>
                <value>
                    <fullName>Multi-day training</fullName>
                </value>
                <value>
                    <fullName>Multi-day customer event</fullName>
                </value>
                <value>
                    <fullName>Multi-day Dell event</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rep_on_Leave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The Rep for which Buddy Access is requested</inlineHelpText>
        <label>Rep on Leave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GDM_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GDM Request</label>
    <nameField>
        <displayFormat>Req ID {0}</displayFormat>
        <label>GDM Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDM Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/Batch_OpptyShareToBuddyTest.cls
@isTest
private class Batch_OpptyShareToBuddyTest {
    private static list<Account> listAcc;
    private static List<Profile> listProfile; 
    private static GDM_Request__c objGdmReq;
    private static list<Opportunity> listOppTDF;
    private static List<User> listTestUser1; 
    Private static testMethod void testBatchDeleteAccountTeamMember() {
    TriggerExecutionController.setSkipAllTriggers(true);
        listProfile = [SELECT Id,name FROM Profile WHERE Name in ('System Administrator','R16.10 GBL EMEA Sales Rep') order by name]; 
         User objAdminUser = new User(Alias = 'standt', Email='standarduser@dell.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = listProfile.get(1).Id, userRoleId = '00E30000000w2BzEAI',  Badge_Number__c='TEST1'+System.currentTimeMillis(),
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser'+ System.currentTimeMillis() +'@dell.com');
        List<User> listtestUser = new List<User>();
        listtestUser.add(objAdminUser);
        insert listtestUser;

        listTestUser1 = new List<User>();
        for (Integer inti=0; inti<3;inti++){
            User user = new User( Username='test' +inti+ System.currentTimeMillis() + '@test.com',
                                Alias = 'test'+inti, 
                                Email='test'+ inti +'@dell.com', 
                                FirstName='Tfirst'+inti, 
                                LastName='TLast'+inti,
                                ProfileId = listProfile.get(0).Id, 
                                userRoleId = '00E30000000w2BzEAI',
                                ManagerId = listTestUser[0].id,
                                LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', 
                                EmailEncodingKey='UTF-8', 
                                TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='TEST12345'+inti);
                
            listTestUser1.add(user);   
        } 
        
    insert listTestUser1;
        System.runAs(listTestUser1[0]){     
        objGdmReq = new GDM_Request__c();
        objGdmReq.Buddy_Access_Start_Date__c = system.today();
        objGdmReq.Buddy_Access_End_Date__c = (system.today())+2;
        objGdmReq.Buddy__c = listTestUser1[0].id;
        objGdmReq.Rep_on_Leave__c = listTestUser1[1].id;
        objGdmReq.Reason_Requested__c = 'Sickness';
        objGdmReq.Comments2__c = 'Test';
        objGdmReq.RecordTypeId = IdLookupUtils.getRecordTypeId('Buddy Access','GDM_Request__c',true);
        objGdmReq.ROL_Manager__c = listTestUser[0].id;
        insert objGdmReq;
        
        list<Account> listAccTDF = TestDataFactory.createNAccount(2, 'Partner Account');
        listAccTDF[0].Type='OEM';
        listAccTDF[0].Type='MSG';
        insert listAccTDF;
        
        listOppTDF = TestDataFactory.createNOpportunities(2, 'Channel Opportunity');
        listOppTDF[0].Deal_Created_Date_Time__c=System.Today();
        listOppTDF[0].Deal_Registration_Status__c='Approved';
        listOppTDF[0].Deal_Expiration_Date__c=System.Today()+20;
        listOppTDF[0].RecordTypeid= '012A0000000Vjtg';
        listOppTDF[1].StageName='90% - Commit';
        listOppTDF[1].CloseDate=System.Today()+20;
        insert listOppTDF;
        System.assertEquals('Approved',listOppTDF[0].Deal_Registration_Status__c);
        OpportunityTeamMember testOTM1 = new OpportunityTeamMember (UserId=listTestUser1[1].Id, TeamMemberRole='OEM SR', OpportunityId=listOppTDF[0].Id);
        OpportunityTeamMember testOTM2 = new OpportunityTeamMember (UserId=listTestUser1[1].Id, TeamMemberRole='QQQ SR', OpportunityId=listOppTDF[1].Id);
        List<OpportunityTeamMember> listtestOTM = new List<OpportunityTeamMember>();
        listtestOTM.add(testOTM1);
        listtestOTM.add(testOTM2);
        
        insert listtestOTM;       
      
        }
         System.runAs(listTestUser[0]){
          if(objGdmReq != null){
            objGdmReq.Buddy_Access_Status__c = 'Approved and scheduled';
            update objGdmReq;  
          }
        }
        Batch_OpptyShareToBuddy batchObj = new Batch_OpptyShareToBuddy();              
        Database.executeBatch(batchObj);
        TriggerExecutionController.setSkipAllTriggers(false);
    }
}