profilelist1exp/unpackaged/objects/GDM_Request__c.object
<CustomObject>
    <description>GDM Requests include the following:
 Create Account / Reactivate Account
 Change Ownership
 Customer Linkage
 Org Change
 SFDC Updates
 Access to Tools
 Deactivate Account
 Account Report
 Account Update</description>
    <fields>
        <fullName>AccountAccessLevel__c</fullName>
        <description>Account Team Member history for Account Access Level</description>
        <label>AccountAccessLevel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_ID__c</fullName>
        <label>Account  ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Badge_Number__c</fullName>
        <label>Badge Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buddy_Access_End_Date__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The date on which Buddy Access needs to be removed</inlineHelpText>
        <label>Buddy Access End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Buddy_Access_Start_Date__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The date from which Buddy Access is requested</inlineHelpText>
        <label>Buddy Access Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Buddy_Access_Status__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <label>Buddy Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved and scheduled</fullName>
                </value>
                <value>
                    <fullName>Providing Access</fullName>
                </value>
                <value>
                    <fullName>Access provided</fullName>
                </value>
                <value>
                    <fullName>Removing Access</fullName>
                </value>
                <value>
                    <fullName>Access removed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buddy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The Rep that will be the back-up for the Rep on Leave</inlineHelpText>
        <label>Buddy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GDM_Requests9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseAccessLevel__c</fullName>
        <description>Account Team Member history for Case Access Level</description>
        <label>CaseAccessLevel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments2__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>Optionally, feel free to provide any additional comments, relevant to this request</inlineHelpText>
        <label>Comments</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GDM_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GDM Request</label>
        <referenceTo>GDM_Request__c</referenceTo>
        <relationshipLabel>GDM Requests</relationshipLabel>
        <relationshipName>GDM_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_New_Buddy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is New Buddy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OpportunityAccessLevel__c</fullName>
        <description>Account Team Member history for Opportunity Access Level</description>
        <label>OpportunityAccessLevel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROL_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ROL Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GDM_RequestsE9NC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_Requested__c</fullName>
        <description>This field is available on the Buddy Access request</description>
        <label>Reason Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sickness</fullName>
                </value>
                <value>
                    <fullName>Holidays</fullName>
                </value>
                <value>
                    <fullName>Multi-day training</fullName>
                </value>
                <value>
                    <fullName>Multi-day customer event</fullName>
                </value>
                <value>
                    <fullName>Multi-day Dell event</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rep_Account_Access_Level__c</fullName>
        <label>Rep Account Access Level</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Case_Access_Level__c</fullName>
        <label>Rep Case Access Level</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Opportunity_Access_Level__c</fullName>
        <label>Rep Opportunity Access Level</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_on_Leave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is available on the Buddy Access request</description>
        <inlineHelpText>The Rep for which Buddy Access is requested</inlineHelpText>
        <label>Rep on Leave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GDM_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TeamMemberRole__c</fullName>
        <description>Account Team Member history for Team Member Role</description>
        <label>TeamMemberRole</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GDM Request</label>
    <nameField>
        <displayFormat>Req ID {0}</displayFormat>
        <label>GDM Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDM Requests</pluralLabel>
    <recordTypes>
        <fullName>Buddy_Access</fullName>
        <active>true</active>
        <description>Request temporary access to another Rep&apos;s Account portfolio.</description>
        <label>Buddy Access</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/Batch_BuddyRevokeTest.cls
/*
 * Author  : Krishnakumar M
 * Purpose : Buddy Request Functionality
 * 
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 * 1.0      CR14112      05.02      20-Feb-2017     Krishnakumar    Buddy Request - Create Batch Processes to Add/Remove Buddy member to ATM
 * 2.0      CR14556      07.02      29-Jun-2017     Krishnakumar    SE148 - Fix for the Defect 3497907 Buddy Access batch process 
 * 3.0      CR16640      08.02      04-Jul-2017     Krishnakumar    SE149 - SE149 - Permanent Fix for the Defect 3497907 Buddy Access batch process
 * 4.0 		CR14846      10.01      06-Sep-2017     Nagaraju       Created TestFailure Scenario Method.
 */
@isTest
public class Batch_BuddyRevokeTest{
	
	private static Id IdATMBackupRT;
	private static User objAdminUser;
	private static List<User> listTestUser;
	private static List<Profile> listProfile;
	private static ID IdBuddyAccessRT;


	static{

		TriggerExecutionController.setSkipAllTriggers(true);
        ProcessFlowTriggerController.isTest = true;

		listProfile = [SELECT Id,name FROM Profile WHERE Name in ('System Administrator','R16.10 GBL EMEA Sales Rep') order by name]; 
		IdBuddyAccessRT = IdLookupUtils.getRecordTypeId('Buddy Access','GDM_Request__c',true);
		IdATMBackupRT = IdLookupUtils.getRecordTypeId('ATM History For Buddy Access','GDM_Request__c',true);

		objAdminUser = new User(Alias = 'standt', Email='standarduser@dell.com', 
		EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
		LocaleSidKey='en_US', ProfileId = listProfile.get(1).Id, userRoleId = '00E30000000w2BzEAI',  Badge_Number__c='TEST1'+System.currentTimeMillis(),
		TimeZoneSidKey='America/Los_Angeles', UserName='standarduser'+ System.currentTimeMillis() +'@dell.com');
		insert objAdminUser;

		listTestUser = new List<User>();
        for (Integer i=0; i<3;i++){
            User user = new User( Username='test' +i+ System.currentTimeMillis() + '@test.com',
                                Alias = 'test'+i, 
                                Email='test'+ i +'@dell.com', 
                                FirstName='Tfirst'+i, 
                                LastName='TLast'+i,
                                ProfileId = listProfile.get(0).Id, 
                                userRoleId = '00E30000000w2BzEAI',
                                ManagerId = objAdminUser.id,
                                LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', 
                                EmailEncodingKey='UTF-8', 
                                TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='TEST12345'+i );
                
            listTestUser.add(user);   
        } 
        insert listTestUser;

	}

	static testmethod void testRevokeScheduler(){

		Test.startTest();
        Datetime dt = Datetime.now().addMinutes(1);
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();

        Batch_BuddyRevokeScheduler batchRevoke = new Batch_BuddyRevokeScheduler();
        batchRevoke.intScope = 100;
        
        String jobId = System.schedule('Buddy Request Exclusion Batch', CRON_EXP, batchRevoke);

        CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];

        System.assertEquals(CRON_EXP, ct.CronExpression); 

        Test.stopTest();

	}
	static testmethod void test1Rep1Buddy(){
		
		TriggerExecutionController.setSkipAllTriggers(true);
        ProcessFlowTriggerController.isTest = true;
		List<GDM_Request__c> listBuddyReq = new List<GDM_Request__c>();
		GDM_Request__c objGdmReq;
		
		System.runAs(objAdminUser){
			Account objAccount=new Account();
			objAccount.name='test last run';
			insert objAccount;

			AccountTeamMember objRepATM=createATM(objAccount.id,listTestUser[0].id);
	        AccountTeamMember objBuddyATM=createATM(objAccount.id,listTestUser[1].id);        	        
	        System.runAs(listTestUser[0]){
	        	objGdmReq = new GDM_Request__c();
			    objGdmReq.Buddy_Access_Start_Date__c = system.today();
			    objGdmReq.Buddy_Access_End_Date__c = (system.today())+2;
			    objGdmReq.Buddy__c = listTestUser[1].id;
			    objGdmReq.Rep_on_Leave__c = listTestUser[0].id;
			    objGdmReq.Reason_Requested__c = 'Sickness';
			    objGdmReq.Comments2__c = 'Test';
			    objGdmReq.RecordTypeId = IdBuddyAccessRT;
			    objGdmReq.ROL_Manager__c = objAdminUser.id;
			    insert objGdmReq;
			    listBuddyReq.add(objGdmReq);
			    System.assertNotEquals(objGdmReq.id,null);
	        }
	        objGdmReq.Buddy_Access_Status__c = 'Access provided';
	        objGdmReq.Buddy_Access_Start_Date__c = (System.today())-2;
			objGdmReq.Buddy_Access_End_Date__c = System.today();
	        update objGdmReq;
	        system.debug('*******End-'+objGdmReq.Buddy_Access_End_Date__c);
	        System.assertEquals(objGdmReq.Buddy_Access_End_Date__c, System.today()); 
	        //System.assertEquals(objGdmReq.recordtype.developerName, 'Buddy_Access'); 
			
		}

		Test.startTest();
		Batch_BuddyRevoke revoke = new Batch_BuddyRevoke();
		Database.executeBatch(revoke);
		Test.stopTest();

        //System.assertEquals(objGdmReq.Buddy_Access_Status__c,'Access re');
	}

	// 2 Rep 1 Buddy Scenario
	static testmethod void test2Rep1Buddy(){

		TriggerExecutionController.setSkipAllTriggers(true);
        ProcessFlowTriggerController.isTest = true;

		List<GDM_Request__c> listBuddyReq = new List<GDM_Request__c>();
		GDM_Request__c objGdmReq;
		GDM_Request__c objGdmReq1;
		Id IdBuddyAccessRT = IdLookupUtils.getRecordTypeId('Buddy Access','GDM_Request__c',true);
		
		System.runAs(objAdminUser){
			Account objAccount=new Account();
			objAccount.name='test last run';
			insert objAccount;

			List<AccountTeamMember> listAtm = new List<AccountTeamMember>();
			AccountTeamMember objRepATM = createATM(objAccount.id,listTestUser[0].id);
	        AccountTeamMember objBuddyATM1 = createATM(objAccount.id,listTestUser[1].id);
	        AccountTeamMember objRepATM2 = createATM(objAccount.id,listTestUser[2].id);
	           
	         System.runAs(listTestUser[0]){
	        	objGdmReq = new GDM_Request__c();
			    objGdmReq.Buddy_Access_Start_Date__c = system.today();
			    objGdmReq.Buddy_Access_End_Date__c = (system.today())+2;
			    objGdmReq.Buddy__c = listTestUser[1].id;
			    objGdmReq.Rep_on_Leave__c = listTestUser[0].id;
			    objGdmReq.Reason_Requested__c = 'Sickness';
			    objGdmReq.Comments2__c = 'Test';
			    objGdmReq.RecordTypeId = IdBuddyAccessRT;
			    objGdmReq.ROL_Manager__c = objAdminUser.id;
			    listBuddyReq.add(objGdmReq);

			    objGdmReq1 = new GDM_Request__c();
			    objGdmReq1.Buddy_Access_Start_Date__c = system.today();
			    objGdmReq1.Buddy_Access_End_Date__c = (system.today())+2;
			    objGdmReq1.Buddy__c = listTestUser[1].id;
			    objGdmReq1.Rep_on_Leave__c = listTestUser[2].id;
			    objGdmReq1.Reason_Requested__c = 'Sickness';
			    objGdmReq1.Comments2__c = 'Test';
			    objGdmReq1.RecordTypeId = IdBuddyAccessRT;
			    objGdmReq1.ROL_Manager__c = objAdminUser.id;
			    listBuddyReq.add(objGdmReq1);
			    insert listBuddyReq;
			    System.assertNotEquals(objGdmReq.id,null);
	        }
	        objGdmReq.Buddy_Access_Status__c = 'Access provided';
	        objGdmReq.Buddy_Access_Start_Date__c = (System.today())-2;
			objGdmReq.Buddy_Access_End_Date__c = System.today();
			update objGdmReq;
			objGdmReq1.Buddy_Access_Status__c = 'Access provided';
	        update objGdmReq1;
	        system.debug('*******End-'+objGdmReq.Buddy_Access_End_Date__c);
	        System.assertEquals(objGdmReq.Buddy_Access_End_Date__c, System.today()); 
	        //System.assertEquals(objGdmReq.recordtype.developerName, 'Buddy_Access'); 

	        GDM_Request__c objATMHistory1 = createBackupATM(objRepATM,objBuddyATM1,objGdmReq,true);
            GDM_Request__c objATMHistory3 = createBackupATM(objRepATM2,objBuddyATM1,objGdmReq1,false);
		}

		Test.startTest();
		Batch_BuddyRevoke revoke = new Batch_BuddyRevoke();
		Database.executeBatch(revoke);
		Test.stopTest();

        //System.assertEquals(objGdmReq.Buddy_Access_Status__c,'Access re');
	}	

	//Rep On leave Removed By Affirinity Team.
	static testmethod void testAffirinityRemoval(){
		
		TriggerExecutionController.setSkipAllTriggers(true);
        ProcessFlowTriggerController.isTest = true;

		List<GDM_Request__c> listATMBuddy = new List<GDM_Request__c>();
		List<GDM_Request__c> listBuddyReq = new List<GDM_Request__c>();
		GDM_Request__c objGdmReq;
		GDM_Request__c objGdmReq1;
		Id IdBuddyAccessRT = IdLookupUtils.getRecordTypeId('Buddy Access','GDM_Request__c',true);
		

		System.runAs(objAdminUser){
			Account objAccount=new Account();
			objAccount.name='test last run';
			insert objAccount;

			List<AccountTeamMember> listAtm = new List<AccountTeamMember>();
			AccountTeamMember objBuddyATM=createATM(objAccount.id,listTestUser[1].id);
	        AccountTeamMember objRepATM=createATM(objAccount.id,listTestUser[0].id);
	        
	        
	         System.runAs(listTestUser[0]){
	        	objGdmReq = new GDM_Request__c();
			    objGdmReq.Buddy_Access_Start_Date__c = system.today();
			    objGdmReq.Buddy_Access_End_Date__c = (system.today())+2;
			    objGdmReq.Buddy__c = listTestUser[1].id;
			    objGdmReq.Rep_on_Leave__c = listTestUser[0].id;
			    objGdmReq.Reason_Requested__c = 'Sickness';
			    objGdmReq.Comments2__c = 'Test';
			    objGdmReq.RecordTypeId = IdBuddyAccessRT;
			    objGdmReq.ROL_Manager__c = objAdminUser.id;
			    listBuddyReq.add(objGdmReq);
			    insert listBuddyReq;
			    System.assertNotEquals(objGdmReq.id,null);
	        }
	        objGdmReq.Buddy_Access_Status__c = 'Access provided';
	        objGdmReq.Buddy_Access_Start_Date__c = (System.today())-2;
			objGdmReq.Buddy_Access_End_Date__c = System.today();
			update objGdmReq;
			
	        system.debug('*******End-'+objGdmReq.Buddy_Access_End_Date__c);
	        System.assertEquals(objGdmReq.Buddy_Access_End_Date__c, System.today()); 
	        //System.assertEquals(objGdmReq.recordtype.developerName, 'Buddy_Access'); 

	        GDM_Request__c objATMHistory1 = createBackupATM(objRepATM,objBuddyATM,objGdmReq,true);
	        
            //ATM is removed by Affinity Team
            delete objRepATM;
			
		}
		Test.startTest();
		Batch_BuddyRevoke revoke = new Batch_BuddyRevoke();
		Database.executeBatch(revoke);
		Test.stopTest();

        //System.assertEquals(objGdmReq.Buddy_Access_Status__c,'Access re');
	}	
    
    static testMethod void testFailureScenario(){
        
		TriggerExecutionController.setSkipAllTriggers(true);
        ProcessFlowTriggerController.isTest = true;

        GDM_Request__c objGdmReq;
        
         System.runAs(listTestUser[0]){
	        	objGdmReq = new GDM_Request__c();
			    objGdmReq.Buddy_Access_Start_Date__c = system.today();
			    objGdmReq.Buddy_Access_End_Date__c = (system.today())+2;
			    objGdmReq.Buddy__c = listTestUser[1].id;
			    objGdmReq.Rep_on_Leave__c = listTestUser[0].id;
			    objGdmReq.Reason_Requested__c = 'Sickness';
			    objGdmReq.Comments2__c = 'Test';
			    objGdmReq.RecordTypeId = IdBuddyAccessRT;
			    objGdmReq.ROL_Manager__c = objAdminUser.id;
			    insert objGdmReq;
			    System.assertNotEquals(objGdmReq.id,null);
	        }
        System.runAs(objAdminUser) {
	        if(objGdmReq != null){
	        	objGdmReq.Buddy_Access_Status__c = 'Access provided';
                objGdmReq.Buddy_Access_Start_Date__c = (System.today())-2;
                objGdmReq.Buddy_Access_End_Date__c = System.today();
                update objGdmReq;
	        }
    	} 	
    	       
    	Test.startTest();
        
        GDM_Request__c[] listGDM = [select id from GDM_Request__c where id =:objGdmReq.id];
    	Approval.LockResult[] lrList = Approval.lock(listGDM);
		

        Batch_BuddyRevoke revoke = new Batch_BuddyRevoke();
		Database.executeBatch(revoke);
               
        Test.stopTest();
    }
    

	static AccountTeamMember createATM(ID idAccount,ID idUser){
		AccountTeamMember objATM=new AccountTeamMember();
		objATM.AccountId= idAccount;
	    objATM.UserId= idUser;
	    objATM.AccountAccessLevel='Edit';
	    objATM.CaseAccessLevel='Read';
	    objATM.OpportunityAccessLevel='Edit';
	    objATM.TeamMemberRole = 'Inside Sales Rep';    
		insert objATM;
		return objATM;          
	}



	static GDM_Request__c createBackupATM(AccountTeamMember objRepAtm,AccountTeamMember objBuddyAtm,GDM_Request__c objGdmReq,Boolean bIsNew){
		
		GDM_Request__c objATMHistory = new GDM_Request__c();
        objATMHistory.RecordTypeId = IdATMBackupRT;
        objATMHistory.Is_New_Buddy__c = bIsNew;
        objATMHistory.Account_ID__c = objBuddyAtm.AccountId;
        objATMHistory.AccountAccessLevel__c = objBuddyAtm.AccountAccessLevel;
        objATMHistory.CaseAccessLevel__c = objBuddyAtm.CaseAccessLevel;
        //objATMHistory.GDM_Request_Id__c = objGdmReq.id;
        objATMHistory.GDM_Request__c = objGdmReq.id;
        objATMHistory.OpportunityAccessLevel__c = objBuddyAtm.OpportunityAccessLevel;
        objATMHistory.TeamMemberRole__c = objBuddyAtm.TeamMemberRole;
        objATMHistory.Rep_Account_Access_Level__c = objRepAtm.AccountAccessLevel;
        objATMHistory.Rep_Case_Access_Level__c = objRepAtm.CaseAccessLevel;
        objATMHistory.Rep_Opportunity_Access_Level__c = objRepAtm.OpportunityAccessLevel;

        insert objATMHistory;

        return objATMHistory;
	}




}