profilelist1exp/unpackaged/objects/LOT_Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_Region__c</fullName>
        <label>Threshold Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APJ ASIA</fullName>
                </value>
                <value>
                    <fullName>APJ China</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>FED</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>APJ HONG KONG, JAPAN &amp; KOREA</fullName>
                </value>
                <value>
                    <fullName>APJ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LOT Region</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOT Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Ocean_Data__c.object
<CustomObject>
    <fields>
        <fullName>CFI_Delivery_Time_in_Weeks__c</fullName>
        <description>&quot;CFI Delivery Time in Weeks&quot; label has been Changed to &quot;Configuration Services in Weeks&quot; as part of 11.7 release CR4109. Now &apos;CFI&apos; means, &apos;Configuration Services&apos;.</description>
        <label>Configuration Services in Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CFS_Delivery_Time_in_Weeks__c</fullName>
        <label>CFS Delivery Time in Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exception_Country__c</fullName>
        <label>Exception Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Time_in_Weeks__c</fullName>
        <label>Lead Time in Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MSP_Incremental_in_Weeks__c</fullName>
        <label>MSP Incremental in Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pallet_Rate__c</fullName>
        <label>Pallet Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NORTH AMERICA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_Rate__c</fullName>
        <label>Ship Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Compal / Wistron Chengdu</fullName>
                </value>
                <value>
                    <fullName>Compal / Wistron Kunshan</fullName>
                </value>
                <value>
                    <fullName>Quanta</fullName>
                </value>
                <value>
                    <fullName>Flextronics</fullName>
                </value>
                <value>
                    <fullName>Inventec</fullName>
                </value>
                <value>
                    <fullName>Foxconn China</fullName>
                </value>
                <value>
                    <fullName>Wzs</fullName>
                </value>
                <value>
                    <fullName>Qisda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ocean Data</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Ocean Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ocean Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Channel_Group__c.object
<CustomObject>
    <fields>
        <fullName>Region_Name__c</fullName>
        <description>INTEG-N/NON INTEG -Y/ APEX/CC -N||
WF / APP/ FU / OM -  N||
Desc -  ||
SFA -Y/ PRM -N||
VAL -N|| 
CR# - R 9.9 # 0166 ||</description>
        <label>Region Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment_Business_Unit_Name__c</fullName>
        <label>Segment Business Unit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Channel Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Channel Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityLOTProductListControllerTest.cls
/***********************************************************
* Revision       Release                   Name           Date                  Description   
* 1.0       0202             Vikas KH      08-Dec-2019      Impelemented TDF
***************************************************************/
@isTest 
private class OpportunityLOTProductListControllerTest{
    Static list<Account> listAcc;
    Static list<Opportunity> listOpp;
    Static list<OpportunitylineItem> listOppLineItem;
    @testSetup static void setup() {
        TriggerExecutionController.setSkipAllTriggers(true);
        list<Account> listAccTDF = TestDataFactory.createNAccount(1, 'Partner Account');
        insert listAccTDF;
        list<Opportunity> listoppTDF = TestDataFactory.createNOpportunities(1, 'Standard Opportunity');
        insert listoppTDF;
        list<OpportunitylineItem> listOpplTDF = TestDataFactory.createNOpportunityLineItem(3);
        listOpplTDF[0].Opportunityid=listoppTDF[0].id; 
        listOpplTDF[1].Opportunityid=listoppTDF[0].id;
        listOpplTDF[2].Opportunityid=listoppTDF[0].id;
        Insert listOpplTDF;     
    }
    static testmethod void testGetTableRowTextList() {
        Sales_Channel_Group__c testSalesChannelGrp = new Sales_Channel_Group__c(Name='TestChannelGroup1', Region_Name__c='REGION1', Segment_Business_Unit_Name__c='LARGE ENTERPRISE');
        insert testSalesChannelGrp;
        TriggerExecutionController.setSkipAllTriggers(true);
        //Account testAccount = new Account(Name='TestAccount', Sales_Channel__c=testSalesChannelGrp.Id);
        //insert testAccount;
        listAcc = [select id,name,Sales_Channel__c from Account];
        listAcc[0].Sales_Channel__c=testSalesChannelGrp.Id;
        TriggerExecutionController.setSkipAllTriggers(true);
        update listAcc;
        Ocean_Data__c testOceanData = new Ocean_Data__c(CFI_Delivery_Time_in_Weeks__c=10, CFS_Delivery_Time_in_Weeks__c=10,
                                                        Exception_Country__c='COUNTRY1',    Lead_Time_in_Weeks__c=10,
                                                        MSP_Incremental_in_Weeks__c=10, Region__c='REGION1',
                                                        Ship_Rate__c=4, Source__c='Compal', Pallet_Rate__c=2);
        
        insert testOceanData;
        LOT_Region__c testLOTRegion = new LOT_Region__c(Name='COUNTRY1', Region__c='REGION1', threshold_region__c='EMEA');
        insert testLOTRegion;
        //Opportunity testOppty = new Opportunity(RecordTypeId='012300000004zf2', Customer_Requested_Delivery_Date__c=system.today() + 60, StageName='Propose - 60%', Probability=60, AccountId=testAccount.Id, Name='TEST Oppty 1', CloseDate = System.today() + 30, Primary_Product_Delivery_Address_Region__c = 'REGION1', Primary_Product_Delivery_Address_Country__c = 'COUNTRY1',Region__c='APJ',Competitor_Lost_To__c='Unknown');
        //insert testOppty;
        list<Opportunity> listOpp = [select id,name from Opportunity limit 1];
        listOpp[0].AccountID = listAcc[0].id;
        listOpp[0].Customer_Requested_Delivery_Date__c=system.today() + 60;
        listOpp[0].Probability=60;
        listOpp[0].CloseDate = System.today() + 30;
        listOpp[0].Primary_Product_Delivery_Address_Region__c = 'REGION1';
        listOpp[0].Primary_Product_Delivery_Address_Country__c = 'COUNTRY1';
        listOpp[0].Region__c='APJ';
        listOpp[0].Competitor_Lost_To__c='Unknown';
        update listOpp;
    System.assertEquals(listOpp[0].Primary_Product_Delivery_Address_Region__c, 'REGION1');        
        listOpplineItem = [select id from OpportunityLineItem limit 3];
        GlobalVariables.BYPASS_ALL_LOT_OCEAN_CALCULATION = false;
        try {
            Test.startTest();
            OpportunityLOTProductListController controller = new OpportunityLOTProductListController(listOpp[0].Id, 2, true);
            List<String> listresultText = controller.getTableRowTextList();
            Test.stopTest();
        } catch (Exception e) {
        }
    }
}