profilelist1exp/unpackaged/objects/Marketing_Plan__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Based</fullName>
                </value>
                <value>
                    <fullName>Ala Carte</fullName>
                </value>
                <value>
                    <fullName>Headcount</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marketing Plan</label>
    <nameField>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/VFCntrlr_VIPERCustomerPortal.cls
global class VFCntrlr_VIPERCustomerPortal{
    public Marketing_Plan__c marketingPlan=new Marketing_Plan__c();    
    public VFCntrlr_VIPERCustomerPortal(ApexPages.StandardController stdController){
        try{
            marketingPlan=[select id,Contract_Type__c from Marketing_Plan__c where id=:stdController.getId()];
        }catch(Exception e){}
                       
              
    }
    public PageReference actionFn(){
        PageReference pageRef;
        String contractType=ApexPages.currentPage().getParameters().get('contractType');
        String idStr=ApexPages.currentPage().getParameters().get('Id'); 
        
        if(marketingPlan.Contract_Type__c=='Volume Based'){
            pageRef=new PageReference('/apex/CustomerPortal_MarketingPlan?id='+idStr);        
        }
        if(marketingPlan.Contract_Type__c=='Ala Carte'){
            pageRef=new PageReference('/apex/CustomerPortal_MarketingPlan_AlaCarte?id='+idStr);        
        }
        if(marketingPlan.Contract_Type__c=='Headcount'){
            pageRef=new PageReference('/apex/CustomerPortal_MarketingPlan_HeadCount?id='+idStr);        
        }
        if(marketingPlan.Contract_Type__c=='Rebates'){
            pageRef=new PageReference('/apex/CustomerPortal_MarketingPlan_Rebates?id='+idStr);        
        }  
        return pageRef; 
    } 

}