profilelist1exp/unpackaged/objects/OEM_Communication_Plan__c.object
<CustomObject>
    <description>Created for CR 12012 - Story 195572. This object is child of OEM Requirement.</description>
    <fields>
        <fullName>OEM_Requirement__c</fullName>
        <description>Created for CR 12012 - Story 195572.</description>
        <label>OEM Requirement</label>
        <referenceTo>OEM_Requirement__c</referenceTo>
        <relationshipLabel>OEM Communication Plan</relationshipLabel>
        <relationshipName>OEM_Communication_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Created for CR 12012 - Story 195572.</description>
        <label>Type</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>OEM Communication Plan</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Communication Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/OEM_Requirement__c.object
<CustomObject>
    <description>Created for CR11964 OEM requirement that has relationship to Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Created for CR11965 Information section&apos;s fields in OEM Requirement layout</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>OEM Requirements</relationshipLabel>
        <relationshipName>OEM_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OEM Requirement</label>
    <nameField>
        <displayFormat>OEM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

profilelist1exp/unpackaged/classes/OEMCommunicationPlanCntrlTest.cls
/*
* REVISION HISTORY
* ================

* Revision#        Author      Date        Release#        CR#     Description
* ---------        ------      ----        --------        ---     -----------
* 1.0              Fenny       1-Oct-2015  CSM1102         12015   Create OEM Communication Plan records when click on [Add] button on Communication Plan related list on OEM Requirement page
*/
/* 
* Revision   Release No       Modified By               Description
* --------   ---------        -----------               ------------               
*            0202             Venugopalachary k         Implement Test Data Factory                               
*/ 
@isTest(SeeAllData=false)
private class OEMCommunicationPlanCntrlTest{
    @testSetup static void setup() {
        // Create common test OWD settings
        OWD__c owdSetting = new OWD__c();
        owdSetting.Oppty_Stage1__c = 'Plan - 1%';
        owdSetting.Oppty_Stage10__c = 'Discover - 10%';
        owdSetting.Oppty_Stage30__c = 'Qualify - 30%';
        owdSetting.Oppty_Stage60__c = 'Propose - 60%';
        owdSetting.Oppty_Stage90__c = 'Commit - 90%';
        owdSetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        owdSetting.Oppty_Stage100__c = 'Win - 100%';
        owdSetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        Insert owdSetting;
        TriggerExecutionController.setSkipAllTriggers(true); 
        list<Account> listAccTdf=TestDataFactory.createNAccount(1, 'Partner Account');
        insert listAccTdf;
        list<Opportunity> listOppTdf=TestDataFactory.createNOpportunities(1, 'Standard Opportunity');
        listOppTdf[0].AccountId=listAccTdf[0].id;
        insert listOppTdf;
        OEM_Requirement__c req1 = new OEM_Requirement__c(Opportunity__c=listOppTdf[0].Id);
        insert req1;
        TriggerExecutionController.setSkipAllTriggers(false); 
    }
    private static testmethod void testContructor(){
        TriggerExecutionController.setSkipAllTriggers(true);
        /*  Account acc = new Account(Name='testAccount');
insert acc;
Opportunity opp = new Opportunity(Name='testOppty',
AccountId=acc.Id,
StageName='Plan - 1%', 
CloseDate=Date.today().addMonths(1));
insert opp;
OEM_Requirement__c req = new OEM_Requirement__c(Opportunity__c=opp.Id);
insert req;
*/
        OEM_Requirement__c req=[select id from OEM_Requirement__c Limit 1]; 
        OEM_Communication_Plan__c plan = new OEM_Communication_Plan__c(OEM_Requirement__c=req.Id, Type__c='Test Type');
        insert plan;
        TriggerExecutionController.setSkipAllTriggers(false);
        PageReference pr = new PageReference('/apex/OEMCommunicationPlan?retURL=/'+req.Id);
        Test.setCurrentPage(pr);
        OEMCommunicationPlanCntrl controller = new OEMCommunicationPlanCntrl(new ApexPages.StandardController(new OEM_Communication_Plan__c()));
        system.assert(controller.comPlan.Type__c == null);
        system.assert(!controller.getHasError());
        
        pr = new PageReference('/apex/OEMCommunicationPlan');
        Test.setCurrentPage(pr);
        
        controller = new OEMCommunicationPlanCntrl(new ApexPages.StandardController(new OEM_Communication_Plan__c()));
        system.assert(controller.getHasError());
        
        pr = new PageReference('/apex/OEMCommunicationPlan?retURL=/'+req.Id);
        Test.setCurrentPage(pr);
        
        controller = new OEMCommunicationPlanCntrl(new ApexPages.StandardController(plan));
        system.assert(controller.comPlan.Type__c == 'Test Type');
    }
    
    private static testmethod void testSave(){
        TriggerExecutionController.setSkipAllTriggers(true);
        
        /* Account acc = new Account(Name='testAccount');
insert acc;
Opportunity opp = new Opportunity(Name='testOppty',
AccountId=acc.Id,
StageName='Plan - 1%',
CloseDate=Date.today().addMonths(1));
insert opp;
OEM_Requirement__c req = new OEM_Requirement__c(Opportunity__c=opp.Id);
insert req;
*/
        OEM_Requirement__c req=[select id from OEM_Requirement__c Limit 1]; 
        OEM_Communication_Plan__c plan = new OEM_Communication_Plan__c(OEM_Requirement__c=req.Id, Type__c='Test Type');
        insert plan;
        
        TriggerExecutionController.setSkipAllTriggers(false);
        
        PageReference pr = new PageReference('/apex/OEMCommunicationPlan?retURL=/'+req.Id);
        Test.setCurrentPage(pr);
        
        Test.startTest();
        
        OEMCommunicationPlanCntrl controller = new OEMCommunicationPlanCntrl(new ApexPages.StandardController(new OEM_Communication_Plan__c()));
        controller.comPlan.Type__c = 'inserting comPlan';
        system.assert(controller.save().getUrl() == '/'+req.Id);
        OEM_Communication_Plan__c insertedPlan = [SELECT Type__c FROM OEM_Communication_Plan__c WHERE Id = :controller.comPlan.Id];
        system.assert(insertedPlan.Type__c == 'inserting comPlan');
        
        pr = new PageReference('/apex/OEMCommunicationPlan?Id='+plan.Id+'&retURL=/'+req.Id);
        Test.setCurrentPage(pr);
        
        controller = new OEMCommunicationPlanCntrl(new ApexPages.StandardController(plan));
        system.assert(controller.comPlan.Type__c == 'Test Type');
        controller.comPlan.Type__c = 'updating comPlan';
        controller.save();
        OEM_Communication_Plan__c updatedPlan = [SELECT Type__c FROM OEM_Communication_Plan__c WHERE Id = :plan.Id];
        system.assert(updatedPlan.Type__c == 'updating comPlan');
        
        Test.stopTest();
    }
    
    private static testmethod void testCancel(){
        TriggerExecutionController.setSkipAllTriggers(true);
        
        /* Account acc = new Account(Name='testAccount');
insert acc;
Opportunity opp = new Opportunity(Name='testOppty', 
AccountId=acc.Id,
StageName='Plan - 1%',
CloseDate=Date.today().addMonths(1));
insert opp;
OEM_Requirement__c req = new OEM_Requirement__c(Opportunity__c=opp.Id);
insert req;
*/
        OEM_Requirement__c req=[select id from OEM_Requirement__c Limit 1]; 
        TriggerExecutionController.setSkipAllTriggers(false);
        
        PageReference pr = new PageReference('/apex/OEMCommunicationPlan?retURL=/'+req.Id);
        Test.setCurrentPage(pr);
        OEMCommunicationPlanCntrl controller = new OEMCommunicationPlanCntrl(new ApexPages.StandardController(new OEM_Communication_Plan__c()));
        system.assert(controller.cancel().getUrl() == '/'+req.Id);
    }
}