profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

force-app/main/default/objects/Support_Request__c/Support_Request__c.object-meta.xml
<CustomObject>
    <label>Support Request</label>
    <nameField>
        <displayFormat>SR # {000000000}</displayFormat>
        <label>Support Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Request__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>CR#1241-Capture comments from Sales and Services/CEM team. CR#10617-Field is required on “Custom Service Support” page layout.</description>
    <inlineHelpText>For Custom Service Support, enter description of Services, customer pains and customer budget</inlineHelpText>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Customer_Contact_InformationName__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact_InformationName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact Information (Name)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Support Requests (Customer Contact Information (Name))</relationshipLabel>
    <relationshipName>Support_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <formula>TEXT(Opportunity__r.Domain__c)</formula>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Engagement_Time_Frame__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Time_Frame__c</fullName>
    <inlineHelpText>When is the customer looking to begin delivery of services?</inlineHelpText>
    <label>Engagement Time Frame</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>CR#1241-Look Up field to opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>CEM_Support</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Receive_Notification__c.field-meta.xml
<CustomField>
    <fullName>Receive_Notification__c</fullName>
    <inlineHelpText>Select Yes if you want to receive email notifications whenever the status of this request changes</inlineHelpText>
    <label>Receive Notifications</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Requestor_Comments__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Comments__c</fullName>
    <label>Requestor Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Solution_Architect__c.field-meta.xml
<CustomField>
    <fullName>Solution_Architect__c</fullName>
    <inlineHelpText>For custom and complex opportunities, request solution resources to develop the solution/cost model. Your opportunity must be at Qualify – 30%. If Opportunity Complex –DGR Qualify gate required prior to resource assignment.</inlineHelpText>
    <label>Solution Architect</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Solution_Name__c.field-meta.xml
<CustomField>
    <fullName>Solution_Name__c</fullName>
    <formula>TEXT(Opportunity__r.Solution_Name__c)</formula>
    <label>Solution Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Solution_Type__c.field-meta.xml
<CustomField>
    <fullName>Solution_Type__c</fullName>
    <formula>TEXT(Opportunity__r.Solution_Type__c)</formula>
    <label>Solution Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Specialist_Role__c.field-meta.xml
<CustomField>
    <fullName>Specialist_Role__c</fullName>
    <label>Specialist Role</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Support_Owner__c.field-meta.xml
<CustomField>
    <fullName>Support_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR#1241-User that will work on the support request</description>
    <label>Support Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Support_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Support_Owner_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Support_Owner_Team_Role__c</fullName>
    <description>CR#1241-Team role of the support owner assigned</description>
    <label>Support Owner Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Cloud APOS SS</fullName>
                <color>#0B6FCE</color>
                <label>3rd Party Cloud APOS SS</label>
            </value>
            <value>
                <fullName>3rd Party Cloud Sales Specialist</fullName>
                <color>#78C953</color>
                <label>3rd Party Cloud Sales Specialist</label>
            </value>
            <value>
                <fullName>3rd Party Quest OSS</fullName>
                <color>#E27001</color>
                <label>3rd Party Quest OSS</label>
            </value>
            <value>
                <fullName>3rd Party Software Outside Sales Spec</fullName>
                <color>#A845DC</color>
                <label>3rd Party Software Outside Sales Spec</label>
            </value>
            <value>
                <fullName>3rd Party Software Tech Sales Rep</fullName>
                <color>#F3D904</color>
                <label>3rd Party Software Tech Sales Rep</label>
            </value>
            <value>
                <fullName>3rd Party Software Tech Sales Rep Mgr</fullName>
                <color>#A53711</color>
                <label>3rd Party Software Tech Sales Rep Mgr</label>
            </value>
            <value>
                <fullName>3rd Party Softw Outside Sales Spec Mgr</fullName>
                <color>#66E9BD</color>
                <label>3rd Party Softw Outside Sales Spec Mgr</label>
            </value>
            <value>
                <fullName>3rd Party SW Capture SS</fullName>
                <color>#0B24BE</color>
                <label>3rd Party SW Capture SS</label>
            </value>
            <value>
                <fullName>3rd Party SW Quest OSS</fullName>
                <color>#419249</color>
                <label>3rd Party SW Quest OSS</label>
            </value>
            <value>
                <fullName>3rd Party SW Sales Coach</fullName>
                <color>#B6E32E</color>
                <label>3rd Party SW Sales Coach</label>
            </value>
            <value>
                <fullName>Account Executive</fullName>
                <color>#641CCF</color>
                <label>Account Executive</label>
            </value>
            <value>
                <fullName>Account Services Executive</fullName>
                <color>#F96FB7</color>
                <label>Account Services Executive</label>
            </value>
            <value>
                <fullName>Account Services Executive Manager</fullName>
                <color>#2F5D85</color>
                <label>Account Services Executive Manager</label>
            </value>
            <value>
                <fullName>Account Services Executive with ICS</fullName>
                <color>#AFCADF</color>
                <label>Account Services Executive with ICS</label>
            </value>
            <value>
                <fullName>Account System Engineer</fullName>
                <color>#8F6429</color>
                <label>Account System Engineer</label>
            </value>
            <value>
                <fullName>Account System Engineer Manager</fullName>
                <color>#EFAE73</color>
                <label>Account System Engineer Manager</label>
            </value>
            <value>
                <fullName>Affiliates Account Executive</fullName>
                <color>#57F17C</color>
                <label>Affiliates Account Executive</label>
            </value>
            <value>
                <fullName>Affiliates Inside Sales Manager</fullName>
                <color>#0B6FCE</color>
                <label>Affiliates Inside Sales Manager</label>
            </value>
            <value>
                <fullName>Affiliates Inside Sales Rep</fullName>
                <color>#78C953</color>
                <label>Affiliates Inside Sales Rep</label>
            </value>
            <value>
                <fullName>Affiliates Regional Sales Manager</fullName>
                <color>#E27001</color>
                <label>Affiliates Regional Sales Manager</label>
            </value>
            <value>
                <fullName>Affiliates Technical Sales Rep</fullName>
                <color>#A845DC</color>
                <label>Affiliates Technical Sales Rep</label>
            </value>
            <value>
                <fullName>APOS Inside Sales Manager</fullName>
                <color>#F3D904</color>
                <label>APOS Inside Sales Manager</label>
            </value>
            <value>
                <fullName>BDM Manager</fullName>
                <color>#A53711</color>
                <label>BDM Manager</label>
            </value>
            <value>
                <fullName>Bid Manager</fullName>
                <color>#66E9BD</color>
                <label>Bid Manager</label>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
                <color>#0B24BE</color>
                <label>Business Development Manager</label>
            </value>
            <value>
                <fullName>Business Development Representative</fullName>
                <color>#419249</color>
                <label>Business Development Representative</label>
            </value>
            <value>
                <fullName>Business Operations Specialist</fullName>
                <color>#B6E32E</color>
                <label>Business Operations Specialist</label>
            </value>
            <value>
                <fullName>CCC Channel Sales Director</fullName>
                <color>#641CCF</color>
                <label>CCC Channel Sales Director</label>
            </value>
            <value>
                <fullName>CCC Inside System Engineer</fullName>
                <color>#F96FB7</color>
                <label>CCC Inside System Engineer</label>
            </value>
            <value>
                <fullName>CEM Intake Inside Manager</fullName>
                <color>#2F5D85</color>
                <label>CEM Intake Inside Manager</label>
            </value>
            <value>
                <fullName>Services Intake Manager</fullName>
                <color>#F96FB7</color>
                <label>Services Intake Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

profilelist1exp/unpackaged/classes/afterInsertUpdateSupportRequestTest.cls
/* ---------------------------------------------------------
* Revision  Name        Date            Release     Description
* 1.0                                               Creation
* 2.0       Meghana     20.12.2013      15.03       OMGO CR 8973 - Remove use of field Verifiable_Outcome__c in Test Methods
* 3.0       Fenny       19-Aug-2015     CSM1102     CR11834 - Insert Services Solutioning Team Member when BOOMI update Support Owner from BLANK to a value 
* 4.0       Fenny       20-Oct-2015     CSM1102     CR 12076 - Redesign the SFDC - MyDeal integration via Boomi to make it real time
************************************************************/

@isTest

private class afterInsertUpdateSupportRequestTest {

	//insert Custom Setting for test classes -Afiq FY180203 8 Feb 2018- START
	@testSetup static void setup() {
		OWD__c OWDsetting = new OWD__c();
		OWDsetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
		OWDsetting.Oppty_Stage10__c = 'Discover - 10%';
		OWDsetting.Oppty_Stage100__c = 'Win - 100%';
		OWDsetting.Oppty_Stage30__c = 'Qualify - 30%';
		OWDsetting.Oppty_Stage60__c = 'Propose - 60%';
		OWDsetting.Oppty_Stage90__c = 'Commit - 90%';
		OWDsetting.Oppty_Stage99__c = 'Order Submitted - 99%';
		OWDsetting.Oppty_Stage1__c = 'Plan - 1%';
		
		insert OWDsetting;
	}	
	//insert Custom Setting for test classes -Afiq FY180203 8 Feb 2018 - END

    // 4.0 - Start
    static testMethod void integrateMyDealTest(){
        TriggerExecutionController.setSkipAllTriggers(true);
        Account acc = new Account(Name='testAccount'); 
        insert acc;
        Blob blobFile=Blob.valueOf('Unit Test Attachment Body');
        Contact con = new Contact(FirstName='test',LastName='Test2',Email='test@dell.com',MailingStreet='test',MailingCity='test',MailingState='test',
                        MailingCountry='test',AccountId=acc.Id,Phone='12345');
        insert con;
        
        Opportunity oppty = new Opportunity(AccountId = acc.Id, Name = 'testOpportunity', RecordTypeId = '012300000004zf2AAA', CurrencyIsoCode = 'USD', Type = 'Renewal',
                                                    CloseDate = system.Today(), Domain__c = 'Non Domain', Solution_Type__c = 'Cloud Integration', Solution_Name__c = 'Boomi Solution',
                                                    StageName = 'Plan - 1%',Quest_Software_Contact__c= con.id);
        insert oppty;
        TriggerExecutionController.setSkipAllTriggers(false);
        
        Test.startTest();
        String CSS_RECORDTYPEID = IdLookupUtils.getRecordTypeId('Request Custom Service Support', 'Support_Request__c', true);
        Support_Request__c cssSR = new Support_Request__c(RecordTypeId = CSS_RECORDTYPEID, Receive_Notification__c = 'Yes', Opportunity__c = oppty.Id,
                                            Requestor_Comments__c = 'testComment', Specialist_Role__c = 'testRole',Engagement_Time_Frame__c=Date.today(),
                                            Support_Owner__c = UserInfo.getUserId(), Solution_Architect__c = 'Yes', Customer_Contact_InformationName__c = con.Id,
                                            Support_Owner_Team_Role__c = 'Services Intake Manager',Status__c='New',Project_Type__c='CWS',Project_Duration_months__c =1,
                                            Suggested_Delivery_Method__c='Custom',Decision_Date__c=Date.today(),Primary_Work_Delivery_Language__c='Spanish');
        ProcessFlowTriggerController.isTest = true;
        insert cssSR;
        

        //5.0 Start
        ContentVersion testContentInsert =new ContentVersion(); 
        testContentInsert.Title = 'TestFile';
        testContentInsert.VersionData =blobFile;      
        testContentInsert.PathOnClient ='/';     
        testContentInsert.origin = 'H'; 
        insert testContentInsert;     

        ContentVersion testContent = [SELECT id,contentdocumentid FROM ContentVersion where id =:testContentInsert.id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=oppty.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testContent.contentdocumentid;
        insert contentlink;

        // This update is to cover code of OpportunityUtilities.pushCustomServiceSupportRequestToMyDeal
        Opportunity oldOpp = [SELECT Id, Contract_Term__c FROM Opportunity WHERE Id = :oppty.Id];
        Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>();
        oldOppMap.put(oldOpp.Id, oldOpp);
        
        oppty.Contract_Term__c = 123;
        Map<Id, Opportunity> newOppMap = new Map<Id, Opportunity>();
        newOppMap.put(oppty.Id, oppty);
        
        OpportunityUtilities.pushCustomServiceSupportRequestToMyDeal(oldOppMap, newOppMap);
        Test.stopTest();
        
        // 4.0 - Because the integration callout is a @future method, so not able to do assert test the result here
    }
    // 4.0 - End
    
    // 3.0 - Start
    static testMethod void insertServicesSolutioningTeamWhenBOOMIInsertSR(){
        CSSR_Pursuit_Support__c pursuitSupp = new CSSR_Pursuit_Support__c(Name = 'Finance', Resource_Type_Name__c = 'Resource Name', Pursuit_Team_Mailbox__c = 'test@test.com');
        insert pursuitSupp;
        
        TriggerExecutionController.setSkipAllTriggers(true);
        User boomi = new User(Username='Test1'+System.currentTimeMillis() +'@dell.com', 
                                Alias = 'Test1', Email='testSalesUser1'+'@dell.com', LastName='Test1', ProfileId = '00eA0000000hNqFIAU', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', EmailEncodingKey='UTF-8', TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='Test1'+System.currentTimeMillis());
        insert boomi;
        
        Account acc = new Account(Name='testAccount');     
        
        Opportunity oppty = new Opportunity(AccountId = acc.Id, Name = 'testOpportunity', RecordTypeId = '012300000004zf2AAA', CurrencyIsoCode = 'USD', Type = 'Renewal',
                                                    CloseDate = system.Today(), Domain__c = 'Non Domain', Solution_Type__c = 'Cloud Integration', Solution_Name__c = 'Boomi Solution',
                                                    StageName = 'Plan - 1%');
        
        // RT = Request Custom Service Support
        // Has Support Owner when insert Support Request
        // User is boomi user
        Support_Request__c cssSR = new Support_Request__c(RecordTypeId = '012700000005e26AAA', Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = UserInfo.getUserId(), Specialist_Role__c = 'testRole',
                                            Support_Owner__c = UserInfo.getUserId(), Services_Finance_Support__c = 'Yes', Pricing_Cycle_Status__c = 'Preliminary/indicative pricing', 
                                            HW_SW_or_other_Financing_Dell_owned__c = 'Yes', Customer_Pricing_Due_Date__c = system.today(), Support_Owner_Team_Role__c = 'Services Intake Manager');
        
        
        system.runAs(boomi){
            insert acc; 
            insert oppty;
            Contact testCont = new Contact();
            testCont.FirstName='test';
            testCont.LastName='Test2';
            testCont.Email='test@dell.com';
            testCont.MailingStreet='test';
            testCont.MailingCity='test';
            testCont.MailingState='test';
            testCont.MailingCountry='test';
            testCont.phone = '11211211';
            testCont.MobilePhone = '1211121';
            testCont.Eloqua_ID__c = '1';
            testCont.AccountId=acc.id;
            insert testCont;
            TriggerExecutionController.setSkipAllTriggers(false);
            
            cssSR.Opportunity__c = oppty.Id;
            insert cssSR;
        }
        Integer recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount > 0);
        
        Test.startTest();
        
        // RT = Request Specialist Support
        // Has Support Owner when insert Support Request
        // User is boomi user
        Support_Request__c specialistSR2 = new Support_Request__c(RecordTypeId = '012A0000000ViNJIA0', Opportunity__c = oppty.Id, Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = UserInfo.getUserId(), Specialist_Role__c = 'testRole',
                                            Support_Owner__c = UserInfo.getUserId(), Support_Owner_Team_Role__c = 'Services Intake Manager');
        system.runAs(boomi){
            insert specialistSR2;
        }
        recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :specialistSR2.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount == 0);

        Test.stopTest();
    } // 3.0 - End

    // 3.0 - Start
    static testMethod void insertServicesSolutioningTeamWhenBOOMIUpdateSupportOwner(){
        CSSR_Pursuit_Support__c pursuitSupp = new CSSR_Pursuit_Support__c(Name = 'Finance', Resource_Type_Name__c = 'Resource Name', Pursuit_Team_Mailbox__c = 'test@test.com');
        insert pursuitSupp;
        
        TriggerExecutionController.setSkipAllTriggers(true);
        User boomi = new User(Username='Test1'+System.currentTimeMillis() +'@dell.com', 
                                Alias = 'Test1', Email='testSalesUser1'+'@dell.com', LastName='Test1', ProfileId = '00eA0000000hNqFIAU', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', EmailEncodingKey='UTF-8', TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='Test1'+System.currentTimeMillis());
        insert boomi;
        
        Account acc = new Account(Name='testAccount');     
        
        Opportunity oppty = new Opportunity(AccountId = acc.Id, Name = 'testOpportunity', RecordTypeId = '012300000004zf2AAA', CurrencyIsoCode = 'USD', Type = 'Renewal',
                                                    CloseDate = system.Today(), Domain__c = 'Non Domain', Solution_Type__c = 'Cloud Integration', Solution_Name__c = 'Boomi Solution',
                                                    StageName = 'Plan - 1%');
        
        // RT = Request Custom Service Support
        // Has Support Owner when insert Support Request, but Support Owner Team Role != Services Intake Manager
        // User is boomi user       
        Support_Request__c cssSR = new Support_Request__c(RecordTypeId = '012700000005e26AAA', Opportunity__c = oppty.Id, Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = UserInfo.getUserId(), Specialist_Role__c = 'testRole', Services_Finance_Support__c = 'Yes', Pricing_Cycle_Status__c = 'Preliminary/indicative pricing', 
                                            HW_SW_or_other_Financing_Dell_owned__c = 'Yes', Customer_Pricing_Due_Date__c = system.today(),
                                            Support_Owner__c = UserInfo.getUserId(), Support_Owner_Team_Role__c = 'Alliance Account Executive');
        system.runAs(boomi){
            insert acc; 
            insert oppty;
            TriggerExecutionController.setSkipAllTriggers(false);

            cssSR.Opportunity__c = oppty.Id;
            insert cssSR;
        }
        Integer recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount == 0);
        
        // RT = Request Custom Service Support
        // No Support Owner when insert Support Request, but later update to have Support Owner. After that, update once again the Support Request record
        // User is boomi user
        Support_Request__c cssSR2 = new Support_Request__c(RecordTypeId = '012700000005e26AAA', Opportunity__c = oppty.Id, Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = UserInfo.getUserId(), Specialist_Role__c = 'testRole', Services_Finance_Support__c = 'Yes', Pricing_Cycle_Status__c = 'Preliminary/indicative pricing', 
                                            HW_SW_or_other_Financing_Dell_owned__c = 'Yes', Customer_Pricing_Due_Date__c = system.today());
        system.runAs(boomi){
            insert cssSR2;
        }
        recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR2.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount == 0);
        
        Test.startTest();
        
        cssSR2.Support_Owner__c = UserInfo.getUserId();
        cssSR2.Support_Owner_Team_Role__c = 'Services Intake Manager';
        system.runAs(boomi){
            update cssSR2;
        }
        Integer recordCount2 = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR2.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount2 > 0);
        
        cssSR2.Comments__c = 'Testing on inserting services solutioning team';
        system.runAs(boomi){
            update cssSR2;
        }
        recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR2.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount == recordCount2);

        // RT = Request Custom Service Support
        // No Support Owner when insert Support Request, later update to have Support Owner
        // BUT, the Servies Solutioning TEam record already exists
        // User is boomi user
        Support_Request__c cssSR4 = new Support_Request__c(RecordTypeId = '012700000005e26AAA', Opportunity__c = oppty.Id, Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = UserInfo.getUserId(), Specialist_Role__c = 'testRole', Services_Finance_Support__c = 'Yes', Pricing_Cycle_Status__c = 'Preliminary/indicative pricing', 
                                            HW_SW_or_other_Financing_Dell_owned__c = 'Yes', Customer_Pricing_Due_Date__c = system.today());
        system.runAs(boomi){
            insert cssSR4;
        }

        Services_Solutioning_Team__c team = new Services_Solutioning_Team__c(Solution_Team_Member__c = UserInfo.getUserId(), Solution_Team_Role__c = 'Services Intake Manager', 
                                                                                Support_Request_ID__c = cssSR4.Id);
        insert team;
        
        cssSR4.Support_Owner__c = UserInfo.getUserId();
        cssSR4.Support_Owner_Team_Role__c = 'Services Intake Manager';
        system.runAs(boomi){
            update cssSR4;
        }
        List<Services_Solutioning_Team__c> teams = [SELECT Id FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR4.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(teams.size() == 1);
        system.assert(team.Id == teams[0].Id);
        
        Test.stopTest();
    } // 3.0 - End

    // 3.0 - Start
    static testMethod void insertServicesSolutioningTeamWhenNonBOOMIInsertSR(){
        CSSR_Pursuit_Support__c pursuitSupp = new CSSR_Pursuit_Support__c(Name = 'Finance', Resource_Type_Name__c = 'Resource Name', Pursuit_Team_Mailbox__c = 'test@test.com');
        insert pursuitSupp;
        
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        TriggerExecutionController.setSkipAllTriggers(true);
        User boomi = new User(Username='Test1'+System.currentTimeMillis() +'@dell.com', 
                                Alias = 'Test1', Email='testSalesUser1'+'@dell.com', LastName='Test1', ProfileId = '00eA0000000hNqFIAU', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', EmailEncodingKey='UTF-8', TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='Test1'+System.currentTimeMillis());
        insert boomi;
        
        Account acc = new Account(Name='testAccount'); 
        insert acc;
        Contact testCont = new Contact();
            testCont.FirstName='test';
            testCont.LastName='Test2';
            testCont.Email='test@dell.com';
            testCont.MailingStreet='test';
            testCont.MailingCity='test';
            testCont.MailingState='test';
            testCont.MailingCountry='test';
            testCont.phone = '11211211';
            testCont.MobilePhone = '1211121';
            testCont.Eloqua_ID__c = '1';
            testCont.AccountId=acc.id;
            insert testCont;
              
        
        Opportunity oppty = new Opportunity(AccountId = acc.Id, Name = 'testOpportunity', RecordTypeId = '012300000004zf2AAA', CurrencyIsoCode = 'USD', Type = 'Renewal',
                                                    CloseDate = system.Today(), Domain__c = 'Non Domain', Solution_Type__c = 'Cloud Integration', Solution_Name__c = 'Boomi Solution',
                                                    StageName = 'Plan - 1%',Quest_Software_Contact__c= testCont.id);
         
        insert oppty;
        
        TriggerExecutionController.setSkipAllTriggers(false);
        Test.startTest();
        
        // RT = Request Custom Service Support
        // Has Support Owner when insert Support Request
        // Not boomi user
        Support_Request__c cssSR3 = new Support_Request__c(RecordTypeId = '012700000005e26AAA', Opportunity__c = oppty.Id, Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = boomi.Id, Specialist_Role__c = 'testRole',
                                            Support_Owner__c = UserInfo.getUserId(), Services_Finance_Support__c = 'Yes', Pricing_Cycle_Status__c = 'Preliminary/indicative pricing', 
                                            HW_SW_or_other_Financing_Dell_owned__c = 'Yes', Customer_Pricing_Due_Date__c = system.today(), Support_Owner_Team_Role__c = 'Services Intake Manager');
        system.runAs(currentUser){
            insert cssSR3;
        }
        Integer recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :cssSR3.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount == 0);
        
        // RT = Request Specialist Support
        // Has Support Owner when insert Support Request
        // Not boomi user 
        Support_Request__c specialistSR = new Support_Request__c(RecordTypeId = '012A0000000ViNJIA0', Opportunity__c = oppty.Id, Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment', Specialist_Name__c = boomi.Id, Specialist_Role__c = 'testRole',
                                            Support_Owner__c = UserInfo.getUserId(), Support_Owner_Team_Role__c = 'Services Intake Manager');
        system.runAs(currentUser){
            insert specialistSR;
        }
        recordCount = [SELECT Count() FROM Services_Solutioning_Team__c WHERE Support_Request_ID__c = :specialistSR.Id AND Solution_Team_Role__c = 'Services Intake Manager' AND Solution_Team_Member__c = :UserInfo.getUserId()];
        system.assert(recordCount == 0);
        
        Test.stopTest();
    } // 3.0 - End
    
    static testMethod void afterInsertUpdateSupportRequestTest() {
        Profile profile = [SELECT Id, Name FROM Profile WHERE Name LIKE '%GBL Sales Rep' ORDER BY Name DESC LIMIT 1];
        List<User> testUser = new List<User>();
        Support_Request__c testSR = new Support_Request__c();
        
        testUser.add(new User(Username='testSalesUser1'+System.currentTimeMillis()+'@dell.com',
                                Alias = 'Test1', 
                                Email='testSalesUser1'+'@dell.com',            
                                LastName='Test1',
                                ProfileId = profile.Id, 
                                LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', 
                                EmailEncodingKey='UTF-8', 
                                TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='Test1'+System.currentTimeMillis()));
                                    
        testUser.add(new User(Username='testSalesUser2'+System.currentTimeMillis()+'@dell.com',
                                Alias = 'Test2', 
                                Email='testSalesUser2'+'@dell.com',            
                                LastName='Test2',
                                ProfileId = profile.Id, 
                                LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', 
                                EmailEncodingKey='UTF-8', 
                                TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='Test2'+System.currentTimeMillis()));
                                
        testUser.add(new User(Username='testSalesUser3'+System.currentTimeMillis()+'@dell.com',
                                Alias = 'Test3', 
                                Email='testSalesUser3'+'@dell.com',            
                                LastName='Test3',
                                ProfileId = profile.Id, 
                                LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', 
                                EmailEncodingKey='UTF-8', 
                                TimeZoneSidKey='America/Los_Angeles',
                                Badge_Number__c='Test3'+System.currentTimeMillis()));                       
        
        TriggerExecutionController.setSkipAllTriggers(true);
        insert testUser;
        
        System.runAs(testUser[0]){
            Account testAccount = new Account(Name='testAccount', Type = 'End User', OwnerId = testUser[0].Id);     
            insert testAccount; 
            Contact testCont = new Contact();
            testCont.FirstName='test';
            testCont.LastName='Test2';
            testCont.Email='test@dell.com';
            testCont.MailingStreet='test';
            testCont.MailingCity='test';
            testCont.MailingState='test';
            testCont.MailingCountry='test';
            testCont.phone = '11211211';
            testCont.MobilePhone = '1211121';
            testCont.Eloqua_ID__c = '1';
            testCont.AccountId=testAccount.id;
            insert testCont;

            
            Opportunity testOpp = new Opportunity(AccountId = testAccount.Id,
                                                    Name = 'testOpportunity',
                                                    RecordTypeId = '012300000004zf2AAA',
                                                    CurrencyIsoCode = 'USD',
                                                    Type = 'Renewal',
                                                    CloseDate = system.Today(),
                                                    Domain__c = 'Non Domain',
                                                    Solution_Type__c = 'Cloud Integration',
                                                    Solution_Name__c = 'Boomi Solution',
                                                    StageName = 'Plan - 1%',
                                                    Quest_Software_Contact__c= testCont.id
                                                    //,Verifiable_Outcome__c = 'Territory/Account/Opportunity Plan developed & reviewed by RSM'
                                                    ) ;                                    
            insert testOpp;
            TriggerExecutionController.setSkipAllTriggers(false);
            
            testSR = new Support_Request__c(
                                            RecordTypeId = '012A0000000ViNJIA0',
                                            Opportunity__c = testOpp.Id,
                                            Receive_Notification__c = 'Yes',
                                            Requestor_Comments__c = 'testComment',
                                            Specialist_Name__c = testUser[1].Id,
                                            Specialist_Role__c = 'testRole');
            Test.startTest();
            insert testSR;
            testSR.Status__c='Engagement complete';
            update testSR;
            Test.stopTest();
            /*
            System.assertEquals(true,primaryContact1);
            */
        }
        
        /*System.runAs(testUser[1]){
            testSR.Specialist_Name__c = testUser[2].Id;
            update testSR;
        }*/
    }
}