profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

profilelist1exp/unpackaged/objects/Solution_Certification__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DealCert_done_prior_proposal_submission__c</fullName>
        <label>DealCert done prior proposal submission?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disengage_Reason__c</fullName>
        <label>Disengage Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Complexity Lowered at DGR</fullName>
                </value>
                <value>
                    <fullName>Deal Lost/Cancelled</fullName>
                </value>
                <value>
                    <fullName>Hardware Only</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Services $ Below Threshold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Solution_Certifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deal Cert Not Yet Engaged</fullName>
                    <default>true</default>
                    <label>Deal Cert Not Yet Engaged</label>
                </value>
                <value>
                    <fullName>Initial Contact</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Certification Complete</fullName>
                </value>
                <value>
                    <fullName>Recertifying</fullName>
                </value>
                <value>
                    <fullName>Recertification Complete</fullName>
                </value>
                <value>
                    <fullName>Disengage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Certification</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Deal Certification  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/SolutionCertificationUtilsTest.cls
/***********************************************************
* Name          : SolutionCertificationUtilsTest
* Description   : Solution Certificate Insert functionality Test Class
* ---------------------------------------------------------
* Revision  Name           Date        Description
* 1.0       Hanan       22 Apr 2010  CR 2590 Solution Certificate Insert functionality
* 2.0       Shue        09 Mar 2015  Fix test class: Add Solution_Certification__c test data
* 3.0		Venugopal   04-Dec 2019	 Implemented TDF

************************************************************/
@isTest
private class SolutionCertificationUtilsTest{
    
    static Opportunity testOpportunity;
    static Account testAccount; 
    static Date dCloseDate; 
    static Product2 pdt1;       
    static Pricebook2 pb;
    static PricebookEntry pbe;       
    static Opportunity o ; 
    static OpportunityLineItem oli ;
    static RecordType rectype;
    static list<Account> listAcc;
    static list<Opportunity> listOpp;
    static list<OpportunityLineItem> listOppLineItem;
    @testSetup static void setup(){
        OWD__c oWDsetting = new OWD__c();
        oWDsetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        oWDsetting.Oppty_Stage10__c = 'Discover - 10%';
        oWDsetting.Oppty_Stage100__c = 'Win - 100%';
        oWDsetting.Oppty_Stage30__c = 'Qualify - 30%';
        oWDsetting.Oppty_Stage60__c = 'Propose - 60%';
        oWDsetting.Oppty_Stage90__c = 'Commit - 90%';
        oWDsetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        oWDsetting.Oppty_Stage1__c = 'Plan - 1%';
        
        insert oWDsetting;
        TriggerExecutionController.setSkipAllTriggers(true);
        
        list<Account> listAccTdf=TestDataFactory.createNAccount(1, 'Partner Account');
        insert listAccTdf;
        
        list<Opportunity> listOppTdf=TestDataFactory.createNOpportunities(2, 'Standard Opportunity');
        listOppTdf[0].AccountId=listAccTdf[0].id;
        listOppTdf[1].AccountId=listAccTdf[0].id;
        listOppTdf[0].Type='Deal/Bid Direct';
        insert listOppTdf;
        
        list<OpportunityLineItem> listOppLineItemTdf=TestDataFactory.createNOpportunityLineItem(2);
        listOppLineItemTdf[0].OpportunityID=listOppTdf[0].id;
        listOppLineItemTdf[1].OpportunityID=listOppTdf[1].id;
        
        insert listOppLineItemTdf;
    }
    
    static testMethod void testmethod1(){
        GlobalVariables.BYPASS_ALL_LOT_OCEAN_CALCULATION = true;
        List<string> listid;
        List<Opportunity> listoppty;
        List<Opportunity> listoppty2BUpdated;
        List<Opportunity> listopptyUpdate;
        List<OpportunityLineItem> listopptyLineItem;
        List<OpportunityLineItem> listopptyLineItem2BUpdated;
        Map<String,String> mapcountOpptyId;
        List<Solution_Certification__c> listsolnCert;
        
        TriggerExecutionController.setSkipAllTriggers(true);
        
        listAcc=[SELECT ID FROM Account LIMIT 1];
        listOpp=[SELECT ID FROM Opportunity LIMIT 2];
        List<string> listId2=new List<string>{listOpp[0].id,listOpp[1].id};
            listoppty=new List<Opportunity>();
        listopptyLineItem=new List<OpportunityLineItem>();
        listoppty2BUpdated=new List<Opportunity>();
        
        Test.startTest();
        listOppLineItem=[SELECT ID FROM OpportunityLineItem LIMIT 2];
        
        for(Integer intj=0;intj<listoppty.size();intj++){            
            oli = new OpportunityLineItem(opportunityid=listoppty[intj].id,
                                          UnitPrice=1000, quantity=2000, pricebookentryid=pbe.Id);
            listopptyLineItem.add(oli);
            listid.add(listoppty[intj].id);
        }    
        Test.stopTest();
        
        mapcountOpptyId=new Map<String,String>();
        
        //2.0 Starts
        listsolnCert = new List <Solution_Certification__c>();
        for(Integer intj=0;intj<listOpp.size();intj++){
            Solution_Certification__c solCert = new Solution_Certification__c();
            solCert.Comments__c = 'Comments test';
            solCert.DealCert_done_prior_proposal_submission__c = 'Deal Cert';
            solCert.Disengage_Reason__c = 'Design Test';
            solCert.Opportunity__c = listOpp[intj].id;
            solCert.Status__c = 'Status Test';
            listsolnCert.add(solCert);
        }
        insert listsolnCert;
        //2.0 Ends
        
        for(Solution_Certification__c solnElt:[select Id,Opportunity__c from Solution_Certification__c where Opportunity__c in:listId2]){
            mapcountOpptyId.put(solnElt.Opportunity__c,solnElt.Opportunity__c);
        }
        
        System.debug('###Test method 1 mapcountOpptyId.size() before update'+mapcountOpptyId.size());
        for(Integer intj=0;intj<listOpp.size();intj++){
            system.assertEquals(listOpp[intj].id,mapcountOpptyId.get(listOpp[intj].id));     
        }
        
        for(Integer intj=0;intj<listOpp.size();intj++){            
            listOpp[intj].name='test oppty'+intj;
            listoppty2BUpdated.add(listOpp[intj]); 
            
        }
        update listoppty2BUpdated;
        for(Solution_Certification__c solnElt:[select Id,Opportunity__c 
                                               from Solution_Certification__c where Opportunity__c in:listId2]){
                                                   //system.assertEquals(1,solnElt.count);   
                                               }
        TriggerExecutionController.setSkipAllTriggers(false);
        
    }
    
}