profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

profilelist1exp/unpackaged/objects/Role__c.object
<CustomObject>
    <description>This object is to create and maintain the roles for the teams that uses geography based owner assignment process for the relationship leads and Account Plays.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/S_P_Vendor_Automation__c.object
<CustomObject>
    <description>This custom object will represent vendors implementing the automated process for S&amp;P Deal Registrations</description>
    <fields>
        <fullName>Automation_Type__c</fullName>
        <label>Automation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Automation</fullName>
                    <default>true</default>
                    <label>Full Automation</label>
                </value>
                <value>
                    <fullName>Partial Automation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Key_Expiration_Days__c</fullName>
        <label>Integration Key Expiration Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key_for_Encoding_and_Decoding__c</fullName>
        <label>Key for Encoding and Decoding</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <label>Vendor Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>S&amp;P Vendor Automation</label>
    <nameField>
        <displayFormat>SVA #{000000000}</displayFormat>
        <label>S&amp;P Vendor Automation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S&amp;P Vendors Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/S_P_Vendor_Partner_Information__c.object
<CustomObject>
    <description>This custom object will hold records for Partner Information related to other system authentication processes</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Key__c</fullName>
        <label>Integration Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Username__c</fullName>
        <externalId>true</externalId>
        <label>Partner Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_P_Vendor_Automation_ID__c</fullName>
        <label>S&amp;P Vendor Automation ID</label>
        <referenceTo>S_P_Vendor_Automation__c</referenceTo>
        <relationshipLabel>S&amp;P Vendor: Partner Information</relationshipLabel>
        <relationshipName>S_P_Vendor_Partner_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>S&amp;P Vendor Partner Information</label>
    <nameField>
        <displayFormat>SVP #{000000000}</displayFormat>
        <label>S&amp;P Vendor Partner Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S&amp;P Vendor Partner Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S_P_Vendors__c/S_P_Vendors__c.object-meta.xml
<CustomObject>
    <label>S&amp;P Vendors</label>
    <nameField>
        <displayFormat>SV # {000000000}</displayFormat>
        <label>S&amp;P Vendors ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S&amp;P Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S_P_Vendors__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Opportunity__r.Account.Sales_Channel__r.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

profilelist1exp/unpackaged/objects/Sales_Channel_Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>Integrated / Non / Apex / Affininty Source -  Y||
WF / APP/ FU / OM -  N||
Desc -  ||
SFA / PRM - N||
VAL -N|| 
CR# - R 9.9 # 0166 ||</description>
        <externalId>true</externalId>
        <label>Group ID</label>
        <length>56</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment_Name__c</fullName>
        <description>INTEG-N/NON INTEG -Y/ APEX/CC -N||
WF / APP/ FU / OM -  N||
Desc -  ||
SFA -Y/ PRM -N||
VAL -N|| 
CR# - R 9.9 # 0166 ||</description>
        <label>Segment Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sales Channel Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Channel Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/SnPDealRegistrationMainClassTestClass.cls
/**
* Name: SnPDealRegistrationMainClassTestClass
* Author: Patrick Redor
* Date: November 05,2012
* Version    Author          Date               Description
-------    ------          ----               -------------        
1.0        venu           6-dec-2019          Implimented TestDataFactory    

*/
@isTest 
private class SnPDealRegistrationMainClassTestClass {
    static list<Account> listAcc;
    static list<Opportunity> listOpp;
    static list<OpportunityLineItem> listOppLineItem;
    @testSetup static void setup(){
        OWD__c oWDsetting = new OWD__c();
        oWDsetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        oWDsetting.Oppty_Stage10__c = 'Discover - 10%';
        oWDsetting.Oppty_Stage100__c = 'Win - 100%';
        oWDsetting.Oppty_Stage30__c = 'Qualify - 30%';
        oWDsetting.Oppty_Stage60__c = 'Propose - 60%';
        oWDsetting.Oppty_Stage90__c = 'Commit - 90%';
        oWDsetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        oWDsetting.Oppty_Stage1__c = 'Plan - 1%';
        
        insert oWDsetting;
        TriggerExecutionController.setSkipAllTriggers(true);
        list<Account> listAccTdf=TestDataFactory.createNAccount(2, 'Partner Account');
        insert listAccTdf;
        list<Opportunity> listOppTdf=TestDataFactory.createNOpportunities(2, 'Standard Opportunity');
        listOppTdf[0].AccountId=listAccTdf[0].id;
        listOppTdf[1].AccountId=listAccTdf[1].id;
        insert listOppTdf;
        list<OpportunityLineItem> listOppLineItemTdf=TestDataFactory.createNOpportunityLineItem(2);
        listOppLineItemTdf[0].OpportunityID=listOppTdf[0].id;
        listOppLineItemTdf[1].OpportunityID=listOppTdf[1].id;
        insert listOppLineItemTdf;
        TriggerExecutionController.setSkipAllTriggers(false);
    }
    
    private static testMethod void snPDealRegistrationMainClassTestMethod() {
        TriggerExecutionController.setSkipAllTriggers(true);
        Test.startTest(); 
        List<S_P_Vendor_Partner_Information__c> listsvpi = new List<S_P_Vendor_Partner_Information__c>();
        
        S_P_Vendor_Automation__c sva = new S_P_Vendor_Automation__c(Vendor_Name__c = 'Test', 
                                                                    Automation_Type__c = 'Partial Automation', Is_Active__c = true,
                                                                    Key_for_Encoding_and_Decoding__c = 'wEuqbRG0GruFXygWvQ2T3A==', 
                                                                    Integration_Key_Expiration_Days__c = 120);
        insert sva;
        
        Sales_Channel_Group__c testSCG = new Sales_Channel_Group__c (Name = 'Test SCG', Group_ID__c = '12345', 
                                                                     Segment_Name__c = '');
        insert testSCG;
        
        listOpp=[SELECT ID FROM Opportunity LIMIT 2];
        for(Opportunity opp : listOpp){
            opp.CloseDate = System.today();
        }
        update listOpp;
        system.assertNotEquals(listOpp[0].id, null);
        listOppLineItem=[SELECT ID FROM OpportunityLineItem LIMIT 1];
        listsvpi = [SELECT Account_Name__c, Integration_Key__c, S_P_Vendor_Automation_ID__c, Partner_Username__c, Is_Active__c,
                    Country__c, Partner_ID__c, Segment__c FROM S_P_Vendor_Partner_Information__c limit 5];
        for(Integer inti = 0; inti < 2; inti++){
            listsvpi.add(new S_P_Vendor_Partner_Information__c(Account_Name__c = 'testAccount' + inti, 
                                                               Integration_Key__c = '00001993020199553424242' + inti, S_P_Vendor_Automation_ID__c = sva.id,
                                                               Partner_Username__c = 'testAccount' + inti + '@dell.com.vmw', Is_Active__c = true,
                                                               Country__c = 'UNITED STATES',
                                                               Partner_ID__c = '11098' + inti, Segment__c = ''));
            listsvpi.add(new S_P_Vendor_Partner_Information__c(Account_Name__c = 'testAccount' + inti, 
                                                               Integration_Key__c = '00001993020199553424242' + inti, S_P_Vendor_Automation_ID__c = sva.id,
                                                               Partner_Username__c = 'testAccount' + inti + '@dell.com.vmw', Is_Active__c = true,
                                                               Partner_ID__c = '11098' + inti, 
                                                               Country__c = 'UNITED STATES', 
                                                               Segment__c = 'MPA'));
        }
        insert listsvpi;
        list<S_P_Vendors__c> listSpv=new list<S_P_Vendors__c>();
        S_P_Vendors__c sv = new S_P_Vendors__c(Opportunity__c = listOpp[0].Id,
                                               Sent_to_Vendor_Date__c = null, S_P_Deal_Status__c = 'Pending',
                                               Customer_Name__c = 'test', Contact_Name__c = 'test', Phone__c = '9999999', 
                                               Email__c = 'test@test.com', Role__c = 'test', Ship_to_Address__c = 'test', 
                                               City__c = 'test', Zip__c = 'test', Total_NET__c = 76556, 
                                               Country__c = 'UNITED STATES', State__c = 'FL', 
                                               CurrencyIsoCode = 'USD', 
                                               How_did_you_uncover_this_opportunity1__c = 'test', Sales_Activities_to_Date__c = 
                                               'Multiple meetings with customer and sent quote.', S_P_Vendors_Name__c = 'Test'); 
        listSpv.add(sv);
        S_P_Vendors__c sv2 = new S_P_Vendors__c(Opportunity__c = listOpp[0].Id,//opp2.Id,
                                                Sent_to_Vendor_Date__c = null, S_P_Deal_Status__c = 'Pending',
                                                Customer_Name__c = 'test', Contact_Name__c = 'test', Phone__c = '9999999', 
                                                Email__c = 'test@test.com', Role__c = 'test', Ship_to_Address__c = 'test', 
                                                City__c = 'test', Zip__c = 'test', Total_NET__c = 76556, 
                                                Country__c = 'UNITED STATES', State__c = 'FL', 
                                                CurrencyIsoCode = 'USD', 
                                                How_did_you_uncover_this_opportunity1__c = 'test', Sales_Activities_to_Date__c = 
                                                'Multiple meetings with customer and sent quote.', S_P_Vendors_Name__c = 'Test');
        listSpv.add(sv2);
        insert listSpv;
        sva.Expiration_Date__c = System.today().addDays(10);
        update sva;
        list<opportunitylineitem> listOpplnItem = [Select Id,S_P_Registerable__c,Brand_Desc__c from opportunitylineitem limit 2];
        SnPDealRegistrationMainClass.computeSnPProdQuantity(listOpplnItem, listSpv);
        Map<String, S_P_Vendor_Partner_Information__c> mapmspsvpi = new Map<String, S_P_Vendor_Partner_Information__c>();       
        String strsvKey = '';
        for(S_P_Vendor_Partner_Information__c svpi : listsvpi){
            strsvKey = '';
            try { 
                if(sv.Segment_Name__c != null){
                    strsvKey = (sv.S_P_Vendors_Name__c.toLowerCase().trim() + sv.Country__c.toLowerCase().trim() + sv.Segment_Name__c.toLowerCase()).trim();
                }else if(sv.Country__c != null){
                    strsvKey = sv.S_P_Vendors_Name__c.toLowerCase().trim() + sv.Country__c.toLowerCase().trim();
                }
                mapmspsvpi.put(strsvKey, svpi);   
            } catch(NullPointerException npe){
                
            }            
        }
        SnPDealRegistrationMainClass.sendEmailReminderForExpiringPartnerInformation();
        SnPDealRegistrationMainClass.updatePartnerID(sv, mapmspsvpi);
        new SnPRunApexOnceADayClass().execute(null);
        TriggerExecutionController.setSkipAllTriggers(false);
        Test.stopTest();
    }
    static testMethod void snPDealRegistrationMainClassTestMethod2() { 
        TriggerExecutionController.setSkipAllTriggers(true);
        listOpp=[SELECT ID FROM Opportunity LIMIT 1];
        Test.startTest();
        list<opportunitylineitem> listOpplnItem = [Select Id from opportunitylineitem limit 2];
       
        /*Id pbk1 = Test.getStandardPricebookId();
        List<Product2> listProduct2 =new List<Product2>();     
        Product2 newPrdct = new Product2(Name = 'Test Product',Product_Line_Desc__c = 'Test Product',Product_ID__c='test prod id1',IsActive = TRUE);
        listProduct2.add(newPrdct);                                 
        Product2 newappPrdct = new Product2(Name = 'Test Product', Product_Line_Desc__c = 'AppAssure',Product_ID__c='test prod id2', IsActive = TRUE);
        listProduct2.add(newappPrdct);
        insert listProduct2;
        List<PricebookEntry> listPricebook =new List<PricebookEntry>();        
        PricebookEntry pBE= new PricebookEntry (Product2ID=newPrdct.id,Pricebook2ID=pbk1, isActive=true, useStandardPrice=false,UnitPrice = 50);
        listPricebook.add(pBE);                                        
        PricebookEntry apppBE= new PricebookEntry (Product2ID=newappPrdct.id,Pricebook2ID=pbk1, isActive=true, useStandardPrice=false, UnitPrice = 50);
        listPricebook.add(apppBE);
        insert listPricebook; 
        TriggerExecutionController.setSkipAllTriggers(false);
        List<OpportunityLineItem> listOpplnItem =new List<OpportunityLineItem>();
        OpportunityLineItem  testLineItem = new OpportunityLineItem(Opportunityid =listOpp[0].Id,pricebookEntryId=listPricebook[0].id, Mrgn__c =6, Discount_off__c = 7, UnitPrice = 100,Quantity =2,Description = 'Line Description', Service_Support_US__c = 'ProSupport IT - Mission Critical');   
        OpportunityLineItem  testappLineItem = new OpportunityLineItem(Opportunityid =listOpp[0].Id,pricebookEntryId=listPricebook[1].id, Mrgn__c =6, Discount_off__c = 7, UnitPrice = 100,Quantity =2,Description = 'Line Description', Service_Support_US__c = 'ProSupport IT - Mission Critical');   
        listOpplnItem.add(testLineItem);
        listOpplnItem.add(testappLineItem); 
        //TriggerExecutionController.setSkipOpportunityTriggers(true);*/
        TriggerExecutionController.setSkipAllTriggers(false);
        
        // system.assertEquals('Line Description',testappLineItem.Description );
        //insert listOpplnItem;
        Test.stopTest();        
    }
}