profilelist1exp/unpackaged/objects/Partner_Type__c.object
<CustomObject>
    <label>Partner Type</label>
    <nameField>
        <label>Partner Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Vendor__c.object
<CustomObject>
    <description>Viper Project</description>
    <fields>
        <fullName>Contract_Types_eligible_for__c</fullName>
        <label>Contract Types eligible for</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Based</fullName>
                </value>
                <value>
                    <fullName>Ala Carte</fullName>
                </value>
                <value>
                    <fullName>Headcount</fullName>
                </value>
                <value>
                    <fullName>Rebates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vendor__c.Is_this_a_Parent_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Vendor__c.Partner_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Vendors</relationshipLabel>
        <relationshipName>Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Managed</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Rebate only</fullName>
                </value>
                <value>
                    <fullName>Headcount only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Memory</fullName>
                </value>
                <value>
                    <fullName>3rd Party Monitors</fullName>
                </value>
                <value>
                    <fullName>3rd Party Peripherals</fullName>
                </value>
                <value>
                    <fullName>3rd Party Printers</fullName>
                </value>
                <value>
                    <fullName>3rd Party Projectors</fullName>
                </value>
                <value>
                    <fullName>Cameras</fullName>
                </value>
                <value>
                    <fullName>Connected Classroom</fullName>
                </value>
                <value>
                    <fullName>Dell Memory</fullName>
                </value>
                <value>
                    <fullName>Dell Monitors</fullName>
                </value>
                <value>
                    <fullName>Dell Peripherals</fullName>
                </value>
                <value>
                    <fullName>Dell Printers</fullName>
                </value>
                <value>
                    <fullName>Dell Projectors</fullName>
                </value>
                <value>
                    <fullName>Digital Signage</fullName>
                </value>
                <value>
                    <fullName>Display Accessories</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Handhelds</fullName>
                </value>
                <value>
                    <fullName>Licensing Software</fullName>
                </value>
                <value>
                    <fullName>Networking &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Cooling</fullName>
                </value>
                <value>
                    <fullName>Retail Software</fullName>
                </value>
                <value>
                    <fullName>Scanners</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Spare Parts</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Telephony/Communications</fullName>
                </value>
                <value>
                    <fullName>Televisions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Unique_Field__c</fullName>
        <label>Vendor Unique Field</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vendor</label>
    <nameField>
        <label>Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Parent company (i.e. Microsoft)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/ActivateDeactivateVFControllerTest.cls
@isTest
private Class ActivateDeactivateVFControllerTest{
    static Vendor__c parentVendor=new Vendor__c();
    static List<Vendor__c> vendorList=new List<Vendor__c>();
    static Vendor__c subVendor=new Vendor__c(); 
    static Vendor__c parentVendorIA=new Vendor__c(); 
    
    public static void createData(){
       
       Map<String,RecordType> vendorRT=new Map<String,RecordType>();       
       for(RecordType rtElt:[Select Name, Id From RecordType where sObjectType='vendor__c']){
           vendorRT.put(rtElt.Name,rtElt);    
       }
       //parentVendor.name='TestVendor'; // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
       parentVendor.name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+'A'; // Fenny added on 21-Feb-2013
       parentVendor.Partner_Status__c='Active';
       parentVendor.recordTypeId=vendorRT.get('Vendor').Id;
       
       insert parentVendor;
       
       for(Integer i = 0; i<3; i++){
           vendorList.add(
               new Vendor__c(
                   Parent_Vendor__c=parentVendor.Id,
			       //Name='TestSubVendor Record'+i, // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
			       Name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+i, // Fenny added on 21-Feb-2013
                   Partner_Status__c='Active',
                   Partner_Type__c='Value',
                   Product_Category__c='Networking',
                   Contract_Types_eligible_for__c='Volume Based,Ala Carte',
                   recordTypeId=vendorRT.get('Sub Vendor').Id
               )
           );
       }
       
       insert vendorList;
       
       subVendor.Parent_Vendor__c=parentVendor.Id;
       //subVendor.Name='TestSubVendor'; // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
       subVendor.name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+'B'; // Fenny added on 21-Feb-2013
       subVendor.Partner_Status__c='Inactive';
       subVendor.Partner_Type__c='Value';
       subVendor.Product_Category__c='Networking';
       subVendor.Contract_Types_eligible_for__c='Volume Based,Ala Carte';
       subVendor.recordTypeId=vendorRT.get('Sub Vendor').Id;
       
       insert subVendor;
       
       //parentVendorIA.name='TestVendor Rec'; // Fenny commented on 21-Feb-2013 during 14.2 prod build week due to failure: DUPLICATE_VALUE, duplicate value found: Vendor_Unique_Field__c duplicates value
       parentVendorIA.name = string.valueOf(Time.newInstance(0,DateTime.Now().minute(),DateTime.Now().second(),0))+'C'; // Fenny added on 21-Feb-2013
       parentVendorIA.Partner_Status__c='Inactive';
       parentVendorIA.recordTypeId=vendorRT.get('Vendor').Id;
       
       insert parentVendorIA;
       
       
   }
   
   public static testMethod void testDeactivateVendor(){
       createData();
       
       PageReference  pr=new PageReference('/apex/DeactivateVendorPage?id='+parentVendor.id);
       Test.setCurrentPage(pr);
       ActivateDeactivateVFController controller = new  ActivateDeactivateVFController(new ApexPages.StandardController(parentVendor));
       PageReference  pageRef=controller.DeactivateVendor();
       boolean bol=controller.getdisplayerr();
       string pVendor=controller.getparentvendor();
                     
       PageReference  pr2=new PageReference('/apex/DeactivateVendorPage?id='+vendorList[1].id);
       Test.setCurrentPage(pr2);
       ActivateDeactivateVFController controller2 = new  ActivateDeactivateVFController(new ApexPages.StandardController(vendorList[1]));
       PageReference  pageRef2=controller2.DeactivateVendor();
   }
   
   public static testMethod void testActivateVendor(){
       createData();
       PageReference pr=new PageReference('/apex/ActivateVendorPage?id='+subVendor.id);
       Test.setCurrentPage(pr);
       ActivateDeactivateVFController controller = new  ActivateDeactivateVFController(new ApexPages.StandardController(subVendor));
       PageReference  pageRef=controller.ActivateVendor();
       
       PageReference pr2=new PageReference('/apex/ActivateVendorPage?id='+parentVendorIA.id);
       Test.setCurrentPage(pr2);
       ActivateDeactivateVFController controller2 = new  ActivateDeactivateVFController(new ApexPages.StandardController(parentVendorIA));
       PageReference  pageRef2=controller2.ActivateVendor();
       
   }
   
   
}