profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Approved_for_Partner_Finder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Find a Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_SMAffinity_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary SMAffinity Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Partner Tracks (Primary SMAffinity Account)</relationshipLabel>
        <relationshipName>Primary_SM_Affinity_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Name__c</fullName>
        <description>This is to display track name in portal pages</description>
        <formula>Track_Id__r.Name</formula>
        <label>Partner Program Track</label>
        <type>Text</type>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/FAPAccountUtilities.cls
/*
 * Author   : Naga
 * Purpose  : Utility class to hold simple and reusable functionalities which are related to Account object. 
 *        
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 * 1.0      CR18310     FY20-DCS-0102 20-Nov-2019   Naga            Adding code to fire PB on Account Partner Track when Sales Channel has changed
 * -------- ---------   ----------  -----------     ------------    -----------------------------------------------------------------------------------
 * Please DO NOT add revision history in the class level, instead add it in the corresponding methods. 
 */
public class FAPAccountUtilities {
    //This method will fire when Sales Channel has changed on account and it will flip the value of Approved for Partner Finder value on Account Partner Track
    public static void fireAccountPartnerTrackPB(List < Id > listIds) {
        List < Partner_Track__c > listAccPTracks = new List < Partner_Track__c > ();
        for (Partner_Track__c objAccPT: [select id, Approved_for_Partner_Finder__c from Partner_Track__c where Primary_SMAffinity_Account__c in: listIds and Track_Name__c like '%Federal Solution Provider%']) {
            if (objAccPT.Approved_for_Partner_Finder__c == true) {
                objAccPT.Approved_for_Partner_Finder__c = false;
            } else {
                objAccPT.Approved_for_Partner_Finder__c = true;
            }
            listAccPTracks.add(objAccPT);
        }
        if (!listAccPTracks.isEmpty() && listAccPTracks.size() > 0) {
            update listAccPTracks;
        }
    }
}