profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Service_Information__c.object
<CustomObject>
    <fields>
        <fullName>Authorized_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authorized Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cisco__c</fullName>
        <label>Cisco Specializations</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advanced Collaboration Architecture Specialization</fullName>
                </value>
                <value>
                    <fullName>Advanced Data Center Architecture Specialization</fullName>
                </value>
                <value>
                    <fullName>Advanced Enterprise Networks Architecture Specialization</fullName>
                </value>
                <value>
                    <fullName>Collaboration Specialization</fullName>
                </value>
                <value>
                    <fullName>Express Networking Specialization</fullName>
                </value>
                <value>
                    <fullName>Internet of Things Specialization Master Specialization</fullName>
                </value>
                <value>
                    <fullName>Security Specialization</fullName>
                </value>
                <value>
                    <fullName>Unified Computing Technology Specialization</fullName>
                </value>
                <value>
                    <fullName>Unified Fabric Technology Specialization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Co-Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Federation_Program_Tier__c</fullName>
        <label>Key Vendor Program Tier</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cisco Advanced</fullName>
                </value>
                <value>
                    <fullName>Cisco Registered</fullName>
                </value>
                <value>
                    <fullName>Data Dobi Certified Delivery Partner</fullName>
                </value>
                <value>
                    <fullName>Data Dobi Certified Sales Partner</fullName>
                </value>
                <value>
                    <fullName>Pivotal:MOU</fullName>
                </value>
                <value>
                    <fullName>Pivotal Advanced</fullName>
                </value>
                <value>
                    <fullName>Pivotal Registered</fullName>
                </value>
                <value>
                    <fullName>RSA Platinum</fullName>
                </value>
                <value>
                    <fullName>VCE Gold</fullName>
                </value>
                <value>
                    <fullName>VMWare: Premier</fullName>
                </value>
                <value>
                    <fullName>VMWare Enterprise</fullName>
                    <label>VmWare Enterprise</label>
                </value>
                <value>
                    <fullName>VMWare Platinum</fullName>
                </value>
                <value>
                    <fullName>VMware Premier</fullName>
                    <isActive>false</isActive>
                    <label>VMware Premier</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inside_DELL_EMC_Logistics_Network__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A new field to identify whether partner is Inside or outside dell emc logistics radius.</description>
        <label>Inside DELL EMC Logistics Network</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inside_DELL_EMC_Service_Radius__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A new field to identify whether partner is Inside or outside dell emc services radius.</description>
        <label>Inside DELL EMC Service Radius</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key_Vendor_Relationships__c</fullName>
        <label>Key Vendor Relationships</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cisco</fullName>
                </value>
                <value>
                    <fullName>Data Dobi</fullName>
                </value>
                <value>
                    <fullName>Vmware</fullName>
                    <label>VMware</label>
                </value>
                <value>
                    <fullName>Pivotal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Site_ID__c</fullName>
        <label>Master Site ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_Subcontracting_Tier__c</fullName>
        <label>PS Subcontracting Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS Tier 1</fullName>
                </value>
                <value>
                    <fullName>PS Tier 2</fullName>
                </value>
                <value>
                    <fullName>PS Tier 3</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Track</label>
        <referenceTo>Partner_Track__c</referenceTo>
        <relationshipLabel>Service Information</relationshipLabel>
        <relationshipName>Service_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pivotal__c</fullName>
        <label>Pivotal</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <description>This is the Partner site ID that has no equipment assigned to it</description>
        <label>Provider ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <description>Site Name</description>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services_Deployment_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Services Deployment Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Services_Onsite_Support_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Services Onsite Support Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Services_Performance_Deploy__c</fullName>
        <label>Services Performance Deploy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Below Base</fullName>
                </value>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Performance_Support__c</fullName>
        <label>Services Performance Support</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Below Base</fullName>
                </value>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Remote_Support_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Services Remote Support Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Third_Party_Networking__c</fullName>
        <label>Third Party Networking</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cisco</fullName>
                </value>
                <value>
                    <fullName>Brocade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Third_Party_Virtualization__c</fullName>
        <label>Third Party Virtualization</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VMWare</fullName>
                    <label>VMware</label>
                </value>
                <value>
                    <fullName>Citrix</fullName>
                </value>
                <value>
                    <fullName>Microsoft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Velocity_Services_Implement__c</fullName>
        <label>Services Deployment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Transitioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Velocity_Services_Managed__c</fullName>
        <label>Services Remote Support</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Transitioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Velocity_Services__c</fullName>
        <label>Services Onsite Support</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Transitioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vmware__c</fullName>
        <label>Vmware Certifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Continuity</fullName>
                </value>
                <value>
                    <fullName>Hybrid Cloud</fullName>
                </value>
                <value>
                    <fullName>Management &amp; Automation</fullName>
                </value>
                <value>
                    <fullName>Management &amp; Operations</fullName>
                </value>
                <value>
                    <fullName>Networking Virtualization</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Server Virtualization</fullName>
                </value>
                <value>
                    <fullName>Software Defined Storage</fullName>
                </value>
                <value>
                    <fullName>Virtualization of Business Critical Applications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Information</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Services Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/ServiceInfoTriggerHandlerBU.cls
/*
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 * 1.0
 * 2.0      17936       FY20-1002       20-Aug-2019     Fenny           Refactoring trigger framework. Below code copied from ServiceInfoTriggerHandler
 * 
 */ 
public class ServiceInfoTriggerHandlerBU implements BeforeUpdate{
    
    public void handleBeforeUpdate(List<sObject> listNew, Map<Id, sObject> mapOld){
        
        if(trigger.isBefore && trigger.isUpdate)
        {
            System.debug('onBeforeUpdate');
            Set<Id> setservInfo = new Set<Id>();
            for(Service_Information__c servInf : (List<Service_Information__c>)listNew)
            { 
                setservInfo.add(servInf.Id);
                Service_Information__c oldServicesInfo =(Service_Information__c)mapOld.get(servInf.Id);
                Service_Information__c newServicesInfo =(Service_Information__c)Trigger.NewMap.get(servInf.Id);
                if(oldServicesInfo.Authorized_Exception__c != newServicesInfo.Authorized_Exception__c ||
                  oldServicesInfo.Cisco__c != newServicesInfo.Cisco__c || 
                  oldServicesInfo.Delivery_Type__c != newServicesInfo.Delivery_Type__c ||
                  oldServicesInfo.Inside_DELL_EMC_Logistics_Network__c != newServicesInfo.Inside_DELL_EMC_Logistics_Network__c ||
                  oldServicesInfo.Inside_DELL_EMC_Service_Radius__c != newServicesInfo.Inside_DELL_EMC_Service_Radius__c ||
                  oldServicesInfo.Federation_Program_Tier__c != newServicesInfo.Federation_Program_Tier__c ||
                  oldServicesInfo.Key_Vendor_Relationships__c != newServicesInfo.Key_Vendor_Relationships__c ||
                  oldServicesInfo.Master_Site_ID__c != newServicesInfo.Master_Site_ID__c ||
                  oldServicesInfo.Partner_Track__c!= newServicesInfo.Partner_Track__c||
                  oldServicesInfo.Pivotal__c != newServicesInfo.Pivotal__c ||
                  oldServicesInfo.Provider_ID__c != newServicesInfo.Provider_ID__c ||
                  oldServicesInfo.Provider_Name__c != newServicesInfo.Provider_Name__c ||
                  oldServicesInfo.PS_Subcontracting_Tier__c != newServicesInfo.PS_Subcontracting_Tier__c ||
                  oldServicesInfo.Velocity_Services_Implement__c != newServicesInfo.Velocity_Services_Implement__c ||
                  oldServicesInfo.Services_Deployment_Exception__c != newServicesInfo.Services_Deployment_Exception__c ||
                  oldServicesInfo.Velocity_Services__c != newServicesInfo.Velocity_Services__c ||
                  oldServicesInfo.Services_Onsite_Support_Exception__c != newServicesInfo.Services_Onsite_Support_Exception__c ||
                  oldServicesInfo.Services_Performance_Deploy__c != newServicesInfo.Services_Performance_Deploy__c ||
                  oldServicesInfo.Velocity_Services_Managed__c != newServicesInfo.Velocity_Services_Managed__c ||
                  oldServicesInfo.Services_Remote_Support_Exception__c != newServicesInfo.Services_Remote_Support_Exception__c || 
                  oldServicesInfo.Services_Performance_Support__c != newServicesInfo.Services_Performance_Support__c || 
                  oldServicesInfo.Third_Party_Networking__c != newServicesInfo.Third_Party_Networking__c ||
                  oldServicesInfo.Third_Party_Virtualization__c != newServicesInfo.Third_Party_Virtualization__c ||
                  oldServicesInfo.Vmware__c != newServicesInfo.Vmware__c )
                {  
                    System.debug('newSIRecord.EMC_Operation__c'+servInf.EMC_Operation__c);
                    servInf.EMC_Operation__c ='Updation';
                    System.debug('New value EMC_Operation__c'+servInf.EMC_Operation__c);
               }  
            }
        }
    }
}