profilelist1exp/unpackaged/objects/Partner_Track_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Group_AffinityId__c</fullName>
        <externalId>true</externalId>
        <label>Master Group AffinityId</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Track_AffinityId__c</fullName>
        <externalId>true</externalId>
        <label>Partner Track AffinityId</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Motion_Account_AffinityId__c</fullName>
        <externalId>true</externalId>
        <label>Sales Motion Account AffinityId</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Track Relationship</label>
    <nameField>
        <displayFormat>PTR-{0000}</displayFormat>
        <label>PTR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Track Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/Batch_PTR.cls
global class Batch_PTR implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        String strquery = 'select id,Key__c,Sales_Motion_Account_AffinityId__c,Master_Group_AffinityId__c,Partner_Track_AffinityId__c from Partner_Track_Relationship__c where Is_Processed__c = false';
        return Database.getQueryLocator(strquery);
    }
    global void execute(Database.BatchableContext bc,List<Partner_Track_Relationship__c> listptrList){
        PTRUtility nu=new PTRUtility();
        list<Partner_Track_Relationship__c> listPtrProcessed = nu.InsertPTR(listptrList,'batch');
        if(listPtrProcessed.size() > 0){
            Database.update(listPtrProcessed, false);                
        }
    } 
    global void finish(Database.BatchableContext bc){
        
    }
    
}