profilelist1exp/unpackaged/objects/Partner_Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN (AF)</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS (AX)</fullName>
                </value>
                <value>
                    <fullName>ALBANIA (AL)</fullName>
                </value>
                <value>
                    <fullName>ALGERIA (DZ)</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA (AS)</fullName>
                </value>
                <value>
                    <fullName>ANDORRA (AD)</fullName>
                </value>
                <value>
                    <fullName>ANGOLA (AO)</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA (AI)</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA (AQ)</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA (AG)</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA (AR)</fullName>
                </value>
                <value>
                    <fullName>ARMENIA (AM)</fullName>
                </value>
                <value>
                    <fullName>ARUBA (AW)</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA (AU)</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA (AT)</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN (AZ)</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS (BS)</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN (BH)</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH (BD)</fullName>
                </value>
                <value>
                    <fullName>BARBADOS (BB)</fullName>
                </value>
                <value>
                    <fullName>BELARUS (BY)</fullName>
                </value>
                <value>
                    <fullName>BELGIUM (BE)</fullName>
                </value>
                <value>
                    <fullName>BELIZE (BZ)</fullName>
                </value>
                <value>
                    <fullName>BENIN (BJ)</fullName>
                </value>
                <value>
                    <fullName>BERMUDA (BM)</fullName>
                </value>
                <value>
                    <fullName>BHUTAN (BT)</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA (BO)</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA (BA)</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA (BW)</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND (BV)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Head Office for Country?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Partner Track</label>
        <referenceTo>Partner_Track__c</referenceTo>
        <relationshipName>Partner_Locations_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Point_of_Contact_Email__c</fullName>
        <label>Point of Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Point_of_Contact_Name__c</fullName>
        <label>Point of Contact Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Point_of_Contact_Phone__c</fullName>
        <label>Point of Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State / Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>isMainContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMainContact</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Location</label>
    <nameField>
        <label>Location	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>FAP_Category__c</fullName>
        <label>FAP Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DoMore Partner</fullName>
                </value>
                <value>
                    <fullName>National Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Small Business Reseller</fullName>
                </value>
                <value>
                    <fullName>Software Distributor</fullName>
                </value>
                <value>
                    <fullName>System Integrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logo</label>
        <referenceTo>Logo__c</referenceTo>
        <relationshipLabel>Account Partner Tracks</relationshipLabel>
        <relationshipName>Account_Partner_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Legal_Name__c</fullName>
        <formula>Master_Group_Id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Local_Name__c</fullName>
        <formula>Master_Group_Id__r.NameLocal</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Local Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Logo_ID__c</fullName>
        <formula>CASESAFEID(Master_Group_Id__r.Logo__c)</formula>
        <label>Master Logo ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Finder_Recommended_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Finder Recommended Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Track_Account_Local_Name__c</fullName>
        <label>Partner Track Account Local Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Sales_Motion_Account_Legal_Name__c</fullName>
        <formula>Primary_SMAffinity_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Sales Motion Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Sales_Motion_Account_Local_Name__c</fullName>
        <formula>Primary_SMAffinity_Account__r.NameLocal</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Sales Motion Account Local Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>partner_track_account_name__c</fullName>
        <formula>IF( Primary_SMAffinity_Account__r.Account_ID__c  = Primary_Sales_Motion_Affinity_ID__c , Primary_SMAffinity_Account__r.Name ,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Track Account Name</label>
        <type>Text</type>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Type__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner Types</relationshipLabel>
        <relationshipName>Partner_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Type</label>
    <nameField>
        <label>Partner Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FAP_SearchHit.cls
/** 
REVISION HISTORY
================
Version     Author      Date            Release#    CR#     Description
-------     ------      ----            --------    ---     -----------
1.1         Niveda    24-May-2019        FY20-07-02  17541   Tile to display address from Partner location
1.2         Vismy     13-Sep-2019        FY20-11-01  18088   FAP - Tile records on searching willdisplay the account name information only once
**/
global class FAP_SearchHit implements Comparable {
    private Partner_Location__c location;
    public static string minLocFields;
    
    
    public static Set<Object> minimumFields()
    {
        final Set < Object > returnValue = new Set < Object > ();
        final List < FAP_FieldConfiguration > combined = new List < FAP_FieldConfiguration > ();
        
        combined.addAll(FAP_Configuration.getInstance().searchMinFieldsforPartnerLoc);
        
        if (combined != null && combined.size() > 0) 
        {
            for (FAP_FieldConfiguration field: combined) 
            {
                returnValue.add(field.fieldName);
            }
        }
        system.debug('$$$$$Minimum Fields of Partner Location: ' +returnValue);
        
        for(FAP_FieldConfiguration fieldConfiguration : FAP_Configuration.getInstance().searchMinFieldsforAccount ){
            if(fieldConfiguration != null){
                returnValue.add((FAP_Configuration.StrObjectName.equalsIgnoreCase(fieldConfiguration.objectName) ? FAP_Configuration.keyValue : '') 
                            + fieldConfiguration.fieldName);
            }
        }
          
        system.debug('$$$$$Minimum Fields: ' +returnValue);
        return returnValue;
     }
    
    //Local Name code is added by Shravan
    
    global String partnerNameLocal {get{
    
    Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
    Schema.SObjectType accSchema = FAP_Configuration.keyValueWithoutDot == 'Account__r'? schemaMap.get('Account'):schemaMap.get('Partner_Track__c');
    Map<String, Schema.SObjectField> fieldMap = accSchema.getDescribe().fields.getMap();
        
    sObject sb = location.getSobject(FAP_Configuration.keyValueWithoutDot);
    // 1.2 Added by Vismy start - FAP - Tile records on searching willdisplay the account name information only once
   // string pNameLoc = (FAP_Configuration.keyValueWithoutDot == 'Account__r'? String.valueOf(sb.get('NameLocal')) : String.valueOf(sb.get('Partner_Track_Account_Local_Name__c')));
    
   // if(pNameLoc==null && FAP_Configuration.keyValueWithoutDot != 'Account__r')
   // {
    //    pNameLoc = String.valueOf(sb.get('Master_Local_Name__c'));
    //}
    
    string strpNameLoc;
    if(String.valueOf(sb.get('Partner_Track_Account_Local_Name__c')) != null){
        strpNameLoc = String.valueOf(sb.get('Partner_Track_Account_Local_Name__c'));  
    } 
    else if(String.valueOf(sb.get('Primary_Sales_Motion_Account_Local_Name__c')) != null){
          strpNameLoc = String.valueOf(sb.get('Primary_Sales_Motion_Account_Local_Name__c')); 

    }
    else {
        strpNameLoc = String.valueOf(sb.get('partner_track_account_name__c'));    
       
    }
    
    return strpNameLoc;}}
    //End 1.2
    
    global string searchSerialize{get;set;}
    global Integer resultSequenceNumber {get;set;}
    global String locationName {get{ return location.name;}}
    global ID locationId {get{ return location.id;}}
    
    // Code for Legal Name by Shravan & Neeti
    
    global String partnerName {get{ 
    
    String pName = FAP_Configuration.keyValueWithoutDot == 'Account__r' ? string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Name')):string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Primary_Sales_Motion_Account_Legal_Name__c'));
    
    if(pName == null  && FAP_Configuration.keyValueWithoutDot != 'Account__r')
    {
         pName = string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Master_Legal_Name__c'));
    }
    
    if(pName!= null  && pName.length() > 36){
        pName = pName.substring(0, 35); 
        pName = pName.substringBeforeLast(' ');     
    }
    return pName;}}
    
    //Added FAP Category for summary box. By Sree 
    
    global String fapCategory{get{
    string fCategory = string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('FAP_Category__c'));
    if(fCategory!=null && fCategory!='' && fCategory.length()>31){
    fCategory = fCategory.substring(0,30);  
    }
    return fCategory;}}
    
    global ID partnerAccountId {get{ return string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('id'));}}
    global String website {get{ return FAP_UrlUtils.ensureUrlBeginsWithHttp(location.Website__c);}}
    global Boolean isPrimary {get{ return location.Is_Primary__c;}}
    global Boolean isMainContact {get{ return location.isMainContact__c;}}
    global String pointOfContactPhone {get{ return location.Point_of_Contact_Phone__c;}}
    global String pointOfContactName {get{ return location.Point_of_Contact_Name__c;}}
    global String pointOfContactEmail {get{ return location.Point_of_Contact_Email__c;}}
    global String description {get{ return location.Description__c;}}
    
    global String street {get{ 
            string streetStr;
            streetStr = location.Street__c ;                     
            if(streetStr != null && streetStr.length() > 0)
            {
                if(streetStr.length() > 45)
                {
                    streetStr = streetStr.substring(0,44);
                    streetStr = streetStr.substringBeforeLast(' ');
                    streetStr = streetStr.substringBeforeLast(',');                        
                }                  
            }
        
    return streetStr;}}
    
    global string city {get{return location.City__c;}}
    
    global Map<String,String> mapServiceCompetency = new Map<String,String>();
    global Map<Id,String> mapPL = new Map<Id,String>();//3.0
     //Ver 1.1
    global String stateProvince {get{return location.State_Province__c; }}     
    global String postalCode {get{ return location.Postal_Code__c;}}
    global String country {get{ return location.Country__c ;}}
    global Double longitude {get{ return location.Longitude__c;}}
    global Double latitude {get{ return location.Latitude__c;}}
    global FAP_GeoPoint point {get;private set;}
    global Boolean containsDistance {get{return distanceInKilometers != null;}}
    global Double distanceInKilometers {get;private set;}
    global Double distanceInMiles {get{ return FAP_ConversionUtils.convert(distanceInKilometers,FAP_UnitOfLength.KILOMETERS,FAP_UnitOfLength.MILES);}}
    global string keyConfigValue {get{return string.valueof(FAP_Configuration.getInstance().KeyObject);}}
    
    global Boolean isRecommended {get{return Boolean.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Partner_Finder_Recommended_Flag__c'));}}
    global String logoId {get;set;}
    
    
    global String logoRecordId {get {return  FAP_Configuration.keyValueWithoutDot == 'Account__r' ? ( (string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('logo__c')) == null) ? null : string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('logo__c')) ) : ( string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('logo__c')) != null ? string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('logo__c')) : (String.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Master_Logo_ID__c'))== null?null:String.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Master_Logo_ID__c'))));}}
   
    global Map<String,Object> userRequestedFieldValues {get;set;}
    
    // Ver 1.0: Added partnerRelationship and partnerType
    global String partnerRelationship {get{return  FAP_Configuration.keyValueWithoutDot == 'Account__r' ? ( location.getSobject(FAP_Configuration.keyValueWithoutDot) == null ? null : string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Partner_Relationship__c')) ) : string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Partner_Program_Tier__c'));}} 
    
    global String partnerType {get{return location.getSobject(FAP_Configuration.keyValueWithoutDot) == null ? null : string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Partner_Type__c'));}}
    
    //global String certiCompleted {get{return location.getSobject(FAP_Configuration.keyValueWithoutDot) == null ? null :string.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Certification_Completed__c'));}}
 
    global FAP_SearchHit(Partner_Location__c location){
        if(location == null){
            throw new FAP_IllegalArgumentException('Invalid argument: location is null');
        }
        this.location = location;
        this.point = new FAP_GeoPoint(latitude, longitude);
    }
    
    global boolean dellTechPartner {get{return FAP_Configuration.keyValueWithoutDot == 'Partner_Track__r'? Boolean.valueof(Location.getSobject(FAP_Configuration.keyValueWithoutDot).get('Dell_Technologies_Partner__c')): false;}} 
    
    global void setDistanceToPoint(FAP_GeoPoint point){
        distanceInKilometers = FAP_GeoMath.distanceInKilometers(this.point,point);
    }

    global static List<FAP_SearchHit> sortByDistance(List<FAP_SearchHit> hits){
        return (List<FAP_SearchHit>) FAP_ArrayUtils.qsort(hits,new SearchHitSortByDistComparator());        
    }
    
    // Ver 2.0: Implement the compareTo() method derived from Comparable interface
    global Integer compareTo(Object compareTo) {
        FAP_SearchHit compareToHit = (FAP_SearchHit)compareTo;
        if (distanceInKilometers == compareToHit.distanceInKilometers) {
            return 0;
        }
        if (distanceInKilometers > compareToHit.distanceInKilometers){ 
            return 1;
        }
        return -1;        
    }

    global class SearchHitSortByDistComparator implements FAP_ObjectComparator{

        global Integer compare(Object object1, Object object2){
            final Double r1 = ((FAP_SearchHit)object1).distanceInKilometers;
            final Double r2 = ((FAP_SearchHit)object2).distanceInKilometers;
            return (r1 == r2 || (r1 == null && r2 == null)) ? 0 : ((r1 < r2) ? -1 : 1);
        }
    }
}