profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Sales_Motion_Affinity_ID__c</fullName>
        <label>Primary Sales Motion Affinity ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Name__c</fullName>
        <description>This is to display track name in portal pages</description>
        <formula>Track_Id__r.Name</formula>
        <label>Partner Program Track</label>
        <type>Text</type>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/ViewMyEligiblePartnerTracksCtrl.cls
public class ViewMyEligiblePartnerTracksCtrl {
    
    public Id contactId;
    public Contact conObj;
    public list<Partner_Track__c> listtotalPT{get;set;}
    
    public ViewMyEligiblePartnerTracksCtrl(){
        contactId = [SELECT Id,contactId FROM User WHERE Id =: UserInfo.getUserId()].contactId;
    If(contactID!=null){
          conObj = [SELECT id,EligibleTracks__c FROM Contact WHERE id = :contactID];
        } 
        List<String> listeligibleTracksId = new List<String>();
        if(conObj!=null){
            if(conObj.EligibleTracks__c != null){
                List<String> listeligibleTracksIds = conObj.EligibleTracks__c.split(';');
                
                system.debug('listeligibleTracksIds '+listeligibleTracksIds);
                for(String stregTrackId: listeligibleTracksIds){
                    listeligibleTracksId.add(stregTrackId);    
                } 
            }       
        }
        
        if(listeligibleTracksId !=null){
           listtotalPT = [SELECT Id,Track_Name__c,Primary_Sales_Motion_Affinity_ID__c FROM Partner_Track__c WHERE Id IN: listeligibleTracksId];
        } 
    }

}