profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Service_Information__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Track</label>
        <referenceTo>Partner_Track__c</referenceTo>
        <relationshipLabel>Service Information</relationshipLabel>
        <relationshipName>Service_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Information</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Services Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ServiceInfoTriggerHandlerBI.cls
/*
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 * 1.0
 * 2.0      17936       FY20-1002       20-Aug-2019     Fenny           Refactoring trigger framework. Below code copied from ServiceInfoTriggerHandler
 * 
 */ 
public class ServiceInfoTriggerHandlerBI implements BeforeInsert {
    
    public void handleBeforeInsert(List<sObject> listNew){
         
        Set<ID> setservInfo = new Set<ID>();
         
        for(Service_Information__c servInf : (List<Service_Information__c>)listNew)
        { 
            system.debug('>>>setservInfo '+setservInfo );
            if(servInf.Partner_Track__c!= null)
            {
                setservInfo.add(servInf.Partner_Track__c);
            }
        }

        if(setservInfo !=null && !setservInfo.isempty()){
         
            List<Service_Information__c> listexstServInfo = [select name,id from service_information__C where Partner_Track__c in :setservInfo ];
                
            for(Service_Information__c servInf : (List<Service_Information__c>)listNew)
            { 
                if(listexstServInfo.size()>0){
                    system.debug('<<<<setservInfo '+listexstServInfo);
                    servInf.addError('Service information already exists for this partner. Please view or edit the existing record');
                }
            }
        }
    }
}