profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Send_Confirmation_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Confirmation Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-submitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Incomplete &amp; Expired</fullName>
                </value>
                <value>
                    <fullName>Lead Draft</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Submitted</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Completed</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Rejected</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Created</fullName>
                </value>
                <value>
                    <fullName>Aborted By Partner</fullName>
                </value>
                <value>
                    <fullName>Owned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerOnboardingPRUtility.cls
/***********************************************************
* Name          : Partner Request Utility
*  
* ---------------------------------------------------------
* Revision  Name            Date                Description
* 1.0                                           created

************************************************************/
public class PartnerOnboardingPRUtility {
    
    
    public static void sendConfirmationFlagSet(List<Partner_Request__ChangeEvent> listNewPRs){
        List<String> listPRName = new List<String>();
        List<Partner_Request__c> listPRsToUpdate = new List<Partner_Request__c>();
        try{
                for(Partner_Request__ChangeEvent prChange : listNewPRs){
                    if (prChange.ChangeEventHeader.getChangetype()  == 'CREATE') {
                        EventBus.ChangeEventHeader header = prChange.ChangeEventHeader;
                        System.debug('Received change event for ' + header.entityName +' for the ' + header.changeType + ' operation.'); 
                        
                        Map<String,Object> mapEventChanges = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(prChange));
                        system.debug('mapEventChanges*****'+mapEventChanges);
                        if(mapEventChanges.containsKey('RecordTypeId') && mapEventChanges.get('RecordTypeId') == '012700000005cfa' &&
                           mapEventChanges.containsKey('Status__c') && mapEventChanges.get('Status__c') == 'New'){
                               listPRName.add(prChange.Name);
                           }
                        // System.debug('listPRName::'+listPRName);
                        
                    }
                   
                }
                 if(listPRName.size() > 0){
                    for(Partner_Request__c pr: [SELECT Id,Name,Send_Confirmation_Mail__c FROM Partner_Request__c WHERE Name IN: listPRName]){
                    		pr.Send_Confirmation_Mail__c = true;
                        	listPRsToUpdate.add(pr);
                    } 
                    System.debug('listPRsToUpdate::'+listPRsToUpdate[0]);
                     if(listPRsToUpdate.size() > 0){
                         Database.SaveResult[] listSRPRList = Database.update(listPRsToUpdate,false);
               
                     }
                 
                 }
                     
                
            }
    	catch(Exception e){}
    
    }
}