profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Other_Reason__c</fullName>
        <label>Other Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Rejection Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Business Plan Not Aligned</fullName>
                </value>
                <value>
                    <fullName>Invalid E-mail Address</fullName>
                </value>
                <value>
                    <fullName>Lack of Requested documents</fullName>
                </value>
                <value>
                    <fullName>No response to email update</fullName>
                </value>
                <value>
                    <fullName>Not Qualified after Profiling</fullName>
                </value>
                <value>
                    <fullName>No Website</fullName>
                </value>
                <value>
                    <fullName>Partner Exists in Denied Party List</fullName>
                </value>
                <value>
                    <fullName>To Clarify</fullName>
                </value>
                <value>
                    <fullName>Unable to locate a DUNS number</fullName>
                </value>
                <value>
                    <fullName>Vetting process not completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-submitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Incomplete &amp; Expired</fullName>
                </value>
                <value>
                    <fullName>Lead Draft</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Submitted</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Completed</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Rejected</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Created</fullName>
                </value>
                <value>
                    <fullName>Aborted By Partner</fullName>
                </value>
                <value>
                    <fullName>Owned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PartnerRegistrationMarkRejectedCtrlExt.cls
public class PartnerRegistrationMarkRejectedCtrlExt{
    public Partner_Request__c registration {get;set;}
    public Boolean isVisible {get;set;} //CR 3410 : add control to other reason textarea box
    
    public PartnerRegistrationMarkRejectedCtrlExt(ApexPages.StandardController c){
        registration = (Partner_Request__c) c.getRecord();
        List<Partner_Request__c> recordList = 
            [select id, Rejection_Reason__c, name
            from Partner_Request__c 
            where id = :registration.id limit 1];
        if(recordList.isEmpty()){ 
            PageUtils.addError('Record not found.');
            return;
        }
        registration = recordList.get(0);
        registration.Rejection_Reason__c = '';
    }
    
    //CR 3410 : Rejection Reason for Partner and Deal Reg Enhancement
    //Purpose : When picklist value change, if it is "other" as picklist value, then visible = true 
    public PageReference doRejectionReasonChange(){
        if(StringUtils.isNotBlank(registration.Rejection_Reason__c)){
            String[] retStrList = doParsePicklistStr(registration.Rejection_Reason__c);     
            isVisible           = isTargetValue(retStrList);
        }else{
            isVisible           = false; 
        }
        return null;
    } 
    
    public String[] doParsePicklistStr(String tempStr){
        return StringUtils.split(tempStr, ';');     
    }
    
    public Boolean isTargetValue(String[] tempStrList){     
        for(String listValue : tempStrList){
            if(StringUtils.equalsIgnoreCase(listValue, 'To Clarify')) return true;
        }       
        return false;       
    }
     
    public PageReference doSave(){
        if(StringUtils.isBlank(registration.Rejection_Reason__c)){
            PageUtils.addError('Please select a Rejection Reason');
            return null;
        }
        
        if(isVisible && StringUtils.isBlank(registration.Other_Reason__c)){
            PageUtils.addError('Please enter comment for To Clarify Reason(s)');
            return null;
        }
        
        registration.Status__c = PartnerConstants.REG_STATUS_REJECTED;
        try{
            update registration;
        }catch( Exception e ){
            PageUtils.addError('Failed update Registration status to: ' + PartnerConstants.REG_STATUS_INCOMPLETE 
                + '.  Error is: ' + e.getMessage());
            return null;
        }
        return PageUtils.redirect('/' + registration.id);
    }

    public PageReference doCancel(){
        return PageUtils.redirect('/' + registration.id);
    }
}