profilelist1exp/unpackaged/objects/Partner_Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Head Office for Country?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Partner Track</label>
        <referenceTo>Partner_Track__c</referenceTo>
        <relationshipName>Partner_Locations_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Point_of_Contact_Email__c</fullName>
        <label>Point of Contact Email</label>
        <type>Email</type>
    </fields>
    <label>Partner Location</label>
    <nameField>
        <label>Location	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Program_Track__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Track_Name__c</fullName>
        <formula>Country_Code__c + &apos; - &apos; + Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Track Name</label>
        <type>Text</type>
    </fields>
    <label>Secondary Partner Type</label>
    <nameField>
        <label>Partner Program Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Partner Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Approved_for_Partner_Finder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Find a Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dell_Technologies_Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dell Technologies Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_Group_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Group Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Partner Tracks</relationshipLabel>
        <relationshipName>Master_Group_Id</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Date_Agreed_to_PF_Terms_Cond__c</fullName>
        <label>Partner Date Agreed to PF Terms &amp; Cond</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Program_Tier__c</fullName>
        <label>Partner Program Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Track_Account_Local_Name__c</fullName>
        <label>Partner Track Account Local Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Track_Name__c</fullName>
        <label>Partner Track Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_User_Agreed_to_PF_Terms_Cond__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner User Agreed to PF Terms AND Cond</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_SMAffinity_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary SMAffinity Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Partner Tracks (Primary SMAffinity Account)</relationshipLabel>
        <relationshipName>Primary_SM_Affinity_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Published_to_Partner_Finder__c</fullName>
        <label>Profile Published to Partner Finder</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Track_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Track Id</label>
        <referenceTo>Track__c</referenceTo>
        <relationshipLabel>Account Partner Tracks</relationshipLabel>
        <relationshipName>Account_Partner_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Agreed_to_PF_Terms_Cond__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Partner User who agreed to the Partner Finder application Terms &amp; Conditions.</description>
        <label>Partner User Agreed to PF Terms &amp; Cond</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Partner_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zone__c</fullName>
        <formula>TEXT(Track_Id__r.Zone__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Channel_Group__c.object
<CustomObject>
    <fields>
        <fullName>Regional_Parent_Name__c</fullName>
        <description>INTEG-N/NON INTEG -Y/ APEX/CC -N||
WF / APP/ FU / OM -  N||
Desc -  ||
SFA -Y/ PRM -N||
VAL -N|| 
CR# - R 9.9 # 0166 ||</description>
        <label>Regional Parent Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sales Channel Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Channel Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Track__c.object
<CustomObject>
    <description>Track related data which helps to identify the business relationship with Dell</description>
    <fields>
        <fullName>Partner_Program_Track__c</fullName>
        <label>Partner Program Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Consumer Partner</fullName>
                </value>
                <value>
                    <fullName>Consumer Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM Distributor</fullName>
                </value>
                <value>
                    <fullName>Sub Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>OEM Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Federal Distributor</fullName>
                </value>
                <value>
                    <fullName>Federal OEM</fullName>
                </value>
                <value>
                    <fullName>Federal OEM Distributor</fullName>
                </value>
                <value>
                    <fullName>Federal OEM Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Federal Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Federal Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Commercial Distributor</fullName>
                </value>
                <value>
                    <fullName>Federal OEM Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Financial Service Provider</fullName>
                </value>
                <value>
                    <fullName>OEM Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>A country or group of countries who are bucketed based on their market type. 
Zone 1 = mature markets
Zone 2 = emerging and/or smaller markets</description>
        <label>Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Zone 1</fullName>
                </value>
                <value>
                    <fullName>Zone 2</fullName>
                </value>
                <value>
                    <fullName>Zone 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/FAPAccountUtilitiesTest.cls
@IsTest
private class FAPAccountUtilitiesTest{
     private static testmethod void testSearchByAccountName(){
        //verifyCriteriaProducesExtraResult(new FAP_FieldCondition('Account__r.name').likex('%Aerugo%'),null);
        account acc = new account(Name = 'Test Account');
        insert acc;
        system.assertEquals(acc.Name,'Test Account');            
    }
     private static Double random(Double dblMin, Double dblMax){
      return dblMin + (Math.random() * (dblMax - dblMin));
    }  
    private static testmethod void testSearchByLocationName(){
      
         FAP_Configuration.keyValue ='Partner_Track__r.';   
        Account acct = new Account();
        acct.Name='Test';
        acct.Profile_Published_to_Partner_Finder__c='Yes';
        acct.Approved_for_Partner_Finder__c=true;
        acct.Partner_User_Agreed_to_PF_Terms_Cond__c=UserInfo.getUserId();
        acct.Partner_Date_Agreed_to_PF_Terms_Cond__c=Datetime.now();
        acct.Account_Type_Integration__c='Account';

        insert acct;
        acct.IsPartner = true;
        update acct;
        Track__c trackObj = new Track__c(Name = 'Federal Solution Provider',Zone__c = 'Zone 1',Partner_Program_Track__c = 'OEM');
        insert trackObj;
        
        Partner_Track__c testPartnerTrackObj = new Partner_Track__c();
        testPartnerTrackObj.Partner_Track_Name__c = 'Tech Data';
        testPartnerTrackObj.Track_Id__c = trackObj.id;
        testPartnerTrackObj.Master_Group_Id__c = acct.Id;
        testPartnerTrackObj.Partner_Track__c='Distributor';
        testPartnerTrackObj.Approved_for_Partner_Finder__c = true;
        testPartnerTrackObj.Profile_Published_to_Partner_Finder__c = 'Yes';
        testPartnerTrackObj.User_Agreed_to_PF_Terms_Cond__c = userinfo.getUserId();
        
        testPartnerTrackObj.Primary_SMAffinity_Account__c =acct.Id;
        testPartnerTrackObj.Partner_Track_Account_Local_Name__c = 'Test Name';
        testPartnerTrackObj.Partner_Program_Tier__c = 'Gold';
        testPartnerTrackObj.Dell_Technologies_Partner__c = true;
        insert testPartnerTrackObj; 
        
        Partner_Location__c loc = new Partner_Location__c();              
        loc.Name = acct.Name + ' - Test Location 1 ';
        loc.Latitude__c =  random(-90, 90);
        loc.Longitude__c =  random(-180,180);
        loc.Account__c = acct.Id;
        loc.Partner_Track__c = testPartnerTrackObj.Id;

        loc.Point_of_Contact_Email__c = 'tloc1'+'@testlocation.com';
        loc.Is_Primary__c=true;
        insert loc;  
        
        Partner_Location__c loc1 = new Partner_Location__c();              
        loc1.Name = acct.Name + ' - Test Location ';
        loc1.Latitude__c =  random(-90, 90);
        loc1.Longitude__c =  random(-180,180);
        loc1.Account__c = acct.Id;
        loc1.Point_of_Contact_Email__c = 'tloc2'+'@testlocation.com';
        loc1.Is_Primary__c=false;
        loc1.Partner_Track__c = testPartnerTrackObj.Id;
        insert loc1;   
        
        Sales_Channel_Group__c testSalesChanGrp = new Sales_Channel_Group__c(Name = 'Test Sales channel', Regional_Parent_Name__c = 'APJ');
        insert testSalesChanGrp; 
        
        Sales_Channel_Group__c testSalesChanGrp1 = new Sales_Channel_Group__c(Name = 'Dormant Sales channel1', Regional_Parent_Name__c = 'APJ');
        insert testSalesChanGrp1; 
        
        Account acc1 = new Account(Name = 'Test Account', Account_Type_Integration__c = 'Account', Approved_for_Partner_Finder__c = True, Profile_Published_to_Partner_Finder__c= 'Yes', Partner_User_Agreed_to_PF_Terms_Cond__c = UserInfo.getUserId(), Partner_Date_Agreed_to_PF_Terms_Cond__c = System.today()+10,Sales_Channel__c=testSalesChanGrp.id);
        insert acc1;
        
        acct.Sales_Channel__c = testSalesChanGrp.id;
        update acct;
        
        acct.Sales_Channel__c = testSalesChanGrp1.id;
        update acct;
        
        Partner_Location__c loc2 = new Partner_Location__c();
        loc2.Name = 'test';
        loc2.Latitude__c =  random(-90, 90);
        loc2.Longitude__c =  random(-180,180);
        loc2.Account__c = acct.Id;
        loc2.Is_Primary__c = True;
        insert loc2; 
        

        //verifyCriteriaProducesExtraResult(new FAP_FieldCondition('name').likex('%Aleurometer%'),null);
        
        system.assertEquals(acct.Name,'Test');         
    }
    
}