profilelist1exp/unpackaged/objects/Partner_Track__c.object
<CustomObject>
    <fields>
        <fullName>Authorized_Countries__c</fullName>
        <label>Distributor Authorized Countries</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>BRUNEI DARUSSALAM</fullName>
                </value>
                <value>
                    <fullName>BULGARIA</fullName>
                </value>
                <value>
                    <fullName>BURKINA FASO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DELLEMC_Ts_and_Cs_agreed_date__c</fullName>
        <label>DELL EMC Ts &amp; Cs Agreed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DELLEMC_Ts_and_Cs_agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DELL EMC Ts &amp; Cs Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Program_Tier__c</fullName>
        <label>Partner Program Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Track__c</fullName>
        <label>Partner Track</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Solution Provider</fullName>
                </value>
                <value>
                    <fullName>Systems Integrator</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <formula>Text(Track_Id__r.Partner_Program_Track__c)</formula>
        <label>Partner Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Path__c</fullName>
        <label>Purchase Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speciality_Product_Purchase_Path__c</fullName>
        <label>Specialty Product Purchase Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_PPT__c</fullName>
        <description>Formula Field To Update Sales Motion Fields.</description>
        <formula>TEXT(Track_Id__r.Partner_Program_Track__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Track_PPT</label>
        <type>Text</type>
    </fields>
    <label>Account Partner Track</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Partner Track ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partner Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Type__c.object
<CustomObject>
    <label>Partner Type</label>
    <nameField>
        <label>Partner Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerOnboardingUpdateAccount.cls
public class PartnerOnboardingUpdateAccount {

     public static void updateUDAValuesOnAccount(List<AccountChangeEvent> listNewAccounts){
         List<AccountChangeEvent> listOfChanges = listNewAccounts;
    
    Set<String> setOfAccountIds = new Set<String>();
    map<id,account> mapOfAccMap = new map<id,account>();
    List<Account> listOfAcctList = new List<Account>(); 
    try{
        for(AccountChangeEvent accountChange : listOfChanges){
            if (accountChange.ChangeEventHeader.getChangetype()  == 'UPDATE' ) {
                EventBus.ChangeEventHeader header = accountChange.ChangeEventHeader;
                List<String> listOfRecordId = accountChange.ChangeEventHeader.getRecordIds();
                system.debug('listOfRecordId******'+listOfRecordId);
                Map<String,Object> mapOfEventChanges = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(accountChange));
                system.debug('mapOfEventChanges*****'+mapOfEventChanges);
                if(mapOfEventChanges.keySet().contains('Partner_Track__c') ){
                    System.debug('The Partner_Track__c updated during update operation:');
                    setOfAccountIds.addAll(listOfRecordId);
                }
                else if(header.nulledFields.size() > 0) {
                    for (String strOfField : header.nulledFields) {
                      System.debug(strOfField);
                      if(strOfField.contains('Partner_Track__c') ){
                        System.debug('22 The Partner_Track__c updated during update operation:');
                        setOfAccountIds.addAll(listOfRecordId);
                      }
                     
                    }
              } 
                
            }
        }
        System.debug('setOfAccountIds****'+setOfAccountIds.size());
        if(setOfAccountIds.size() > 0){
            List<Account> listOfSalesMotionAccountList=[select id,Distribution_Sell_To_Countries__c,Partner_Track__r.DELLEMC_Ts_and_Cs_agreed_date__c,Partner_Track__r.DELLEMC_Ts_and_Cs_agreement__c,Purchasing_Model__c,Partner_Relationship__c,Partner_Track__c,
                                                  Partner_Tier__c,New_Partner_Programme_T_C_s_agreed_on__c,New_Partner_Programme_T_C_s__c,Partner_Type__c,Partner_Track__r.Authorized_Countries__c,Partner_Track__r.Purchase_Path__c,
                                                  Partner_Track__r.Track_PPT__c,Partner_Track__r.Partner_Program_Tier__c,Partner_Track__r.Speciality_Product_Purchase_Path__c
                                                  from Account 
                                                  where Id IN: setOfAccountIds];
            System.debug('listOfSalesMotionAccountList'+listOfSalesMotionAccountList.size());
            for(Account salesmotionAcc:listOfSalesMotionAccountList){
                System.debug('salesmotionAcc'+salesmotionAcc);
                if(salesmotionAcc.Partner_Track__c != null ){
                    salesmotionAcc.Distribution_Sell_To_Countries__c =salesmotionAcc.Partner_Track__r.Authorized_Countries__c;
                    salesmotionAcc.Partner_Tier__c = salesmotionAcc.Partner_Track__r.Purchase_Path__c;
                    salesmotionAcc.Partner_Type__c = salesmotionAcc.Partner_Track__r.Track_PPT__c;
                    salesmotionAcc.Partner_Relationship__c = salesmotionAcc.Partner_Track__r.Partner_Program_Tier__c;
                    salesmotionAcc.Purchasing_Model__c =salesmotionAcc.Partner_Track__r.Speciality_Product_Purchase_Path__c;
                    salesmotionAcc.New_Partner_Programme_T_C_s_agreed_on__c = salesmotionAcc.Partner_Track__r.DELLEMC_Ts_and_Cs_agreed_date__c;
                    salesmotionAcc.New_Partner_Programme_T_C_s__c = salesmotionAcc.Partner_Track__r.DELLEMC_Ts_and_Cs_agreement__c;
                }
                else {
                    salesmotionAcc.Distribution_Sell_To_Countries__c = null;
                    salesmotionAcc.Partner_Tier__c = null;
                    salesmotionAcc.Partner_Type__c = null;
                    salesmotionAcc.Partner_Relationship__c = null;
                    salesmotionAcc.Purchasing_Model__c =null;
                    salesmotionAcc.New_Partner_Programme_T_C_s_agreed_on__c = null;
                    salesmotionAcc.New_Partner_Programme_T_C_s__c = false;
                }
                System.debug('salesmotionAcc'+salesmotionAcc);
                listOfAcctList.add(salesmotionAcc);
            }
            
            if(listOfAcctList.size() > 0){
                mapOfAccMap.putall(listOfAcctList);
                Database.SaveResult[] listsrAccList = Database.update(mapOfAccMap.values(),false);
                WebServiceExceptionHandling.exceptionHandlingMethod(listsrAccList,'Account','UpdateUDAonAccount','Exception',null,mapOfAccMap.values());
            }
            
        }
    }catch(Exception e){
        system.debug('Exception occured in Update UDA Values on Account'+e.getMessage());
    }
    }
}