profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Hard_cpy_Rcvd_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreement Hard-copy Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approve_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Approve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_Denied_Party_List_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Check Denied Party List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_For_Duplicates_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Check For Duplicates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Order_Management_access_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Order Management access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Premier_Pages_access_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Premier Pages access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Export_Compliance_Check_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Check Export Compliance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Link_to_Account_Record_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Link to Account Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Perform_Credit_Check_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Check Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provision_First_User_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Provision First User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provisioned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Provisioned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N70000002MebNEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_for_Completeness_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Review for Completeness</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Account_Suggestion_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the suggestion sent to affinity</description>
        <label>Send Account Suggestion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Welcome_Packet_to_Partner_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Welcome Packet to Partner</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerRegistrationProgressBarCtrlExt.cls
public class PartnerRegistrationProgressBarCtrlExt {

    public Double percentComplete {get;set;}
    public static Long TOTAL_COMPLETE_FLAG_COUNT = 13;
    
    public PartnerRegistrationProgressBarCtrlExt(ApexPages.StandardController c){
    	percentComplete = 0;
        Partner_Request__c registration = (Partner_Request__c) c.getRecord();
        final List<Partner_Request__c> records = 
            [select 
            	Review_for_Completeness_Is_Complete_Flag__c, Provision_First_User_Is_Complete_Flag__c, 
            	Perform_Credit_Check_Is_Complete_Flag__c, Agreement_Hard_cpy_Rcvd_Is_Complete_Flag__c,
            	Link_to_Account_Record_Is_Complete_Flag__c, 
            	Export_Compliance_Check_Is_Complete_Flag__c, Check_For_Duplicates_Is_Complete_Flag__c, 
            	Check_Denied_Party_List_Is_Complete_Flag__c, Approve_Is_Complete_Flag__c, Provisioned_User__c, 
            	Enable_Order_Management_access_Flag__c , Enable_Premier_Pages_access_Flag__c, 
            	Send_Welcome_Packet_to_Partner_Flag__c , Send_Account_Suggestion_Is_Complete_Flag__c,recordtype.name
            from Partner_Request__c 
            where id = :registration.id limit 1];
        if(!records.isEmpty()){
	    	registration = records.get(0);
	    	Integer completeCount = 0;
	    	if(registration.Review_for_Completeness_Is_Complete_Flag__c){ 
	    		completeCount++;
	    	}
	    	if(registration.Check_For_Duplicates_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Export_Compliance_Check_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Check_Denied_Party_List_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Perform_Credit_Check_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Agreement_Hard_cpy_Rcvd_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Approve_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Link_to_Account_Record_Is_Complete_Flag__c) {
	    		completeCount++;
	    	}
	    	if(registration.Provision_First_User_Is_Complete_Flag__c){ 
	    		completeCount++;
	    	}
	    	if(registration.Enable_Order_Management_access_Flag__c){ 
	    		completeCount++;
	    	}
	    	if(registration.Enable_Premier_Pages_access_Flag__c){ 
	    		completeCount++;
	    	}
	    	if(registration.Send_Welcome_Packet_to_Partner_Flag__c){ 
	    		completeCount++;
	    	}
	    	if(registration.Send_Account_Suggestion_Is_Complete_Flag__c){ 
	    		completeCount++;
	    	}
	    	if(StringUtils.equalsIgnoreCase(registration.recordtype.name, 'Existing Partner')){
	    		TOTAL_COMPLETE_FLAG_COUNT = 12;
	    	}

System.debug('Review_for_Completeness_Is_Complete_Flag__c = [' + registration.Review_for_Completeness_Is_Complete_Flag__c + ']');
System.debug('Check_For_Duplicates_Is_Complete_Flag__c = [' + registration.Check_For_Duplicates_Is_Complete_Flag__c + ']');
System.debug('Export_Compliance_Check_Is_Complete_Flag__c = [' + registration.Export_Compliance_Check_Is_Complete_Flag__c + ']');
System.debug('Check_Denied_Party_List_Is_Complete_Flag__c = [' + registration.Check_Denied_Party_List_Is_Complete_Flag__c + ']');
System.debug('Perform_Credit_Check_Is_Complete_Flag__c = [' + registration.Perform_Credit_Check_Is_Complete_Flag__c + ']');
System.debug('Agreement_Hard_cpy_Rcvd_Is_Complete_Flag__c = [' + registration.Agreement_Hard_cpy_Rcvd_Is_Complete_Flag__c + ']');
System.debug('Approve_Is_Complete_Flag__c = [' + registration.Approve_Is_Complete_Flag__c + ']');
System.debug('Link_to_Account_Record_Is_Complete_Flag__c = [' + registration.Link_to_Account_Record_Is_Complete_Flag__c + ']');
System.debug('Provision_First_User_Is_Complete_Flag__c = [' + registration.Provision_First_User_Is_Complete_Flag__c + ']');
	    	
	    	percentComplete = (completeCount*100)/TOTAL_COMPLETE_FLAG_COUNT;

System.debug('completeCount = [' + completeCount + ']');
System.debug('TOTAL_COMPLETE_FLAG_COUNT = [' + TOTAL_COMPLETE_FLAG_COUNT + ']');
System.debug('percentComplete = [' + percentComplete + ']');
        } 
    }

}