profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approve_Is_Complete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Approve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Full Legal Name of Your Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PR_Email_Approval_SDCntrl_Test.cls
@isTest
public class PR_Email_Approval_SDCntrl_Test {
	@isTest
    public static void emailTest(){
        Partner_Request__c p=new Partner_Request__c(Company__c='test',First_Name__c='testfirst');
        insert p;
        test.startTest();
        PR_Email_Approval_SDCntrl.gettingData(null);
        Partner_Request__c pr=PR_Email_Approval_SDCntrl.gettingData(p.id);
        PR_Email_Approval_SDCntrl.update_PR_Data(null);
        PR_Email_Approval_SDCntrl.update_PR_Data(pr);
        pr.Approve_Is_Complete_Flag__c=true;
        PR_Email_Approval_SDCntrl.update_PR_Data(pr);
        test.stopTest();
    }
}