profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Full Legal Name of Your Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duplicate_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Duplicate Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Requests (Duplicate Account)</relationshipLabel>
        <relationshipName>R00N70000002MeYTEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Duplicate Registration</label>
        <referenceTo>Partner_Request__c</referenceTo>
        <relationshipLabel>Partner Requests</relationshipLabel>
        <relationshipName>R00N70000002MeYYEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerRegistrationGetDupDetailsCtrl.cls
public class PartnerRegistrationGetDupDetailsCtrl {
	public Id partnerRequestId {get;set;}
	
	private String companyName = '';
	public String getCompanyName(){ init(); return companyName; }
	private String requestNumber = '';
	public String getRequestNumber(){ init(); return requestNumber; }
	private String requestorName = '';
	public String getRequestorName(){ init(); return requestorName; }
	
	private Boolean initialized = false;
	public void init(){
		if(initialized){ return; }
		if(partnerRequestId == null){ return; }
		
		List<Partner_Request__c> requestList = [
			select id, 
				Duplicate_Account__r.Name, Duplicate_Account__r.Partner_Registration__r.Name, 
					Duplicate_Account__r.Partner_Registration__r.First_Name__c, Duplicate_Account__r.Partner_Registration__r.Last_Name__c,
				Duplicate_Registration__r.Name, Duplicate_Registration__r.First_Name__c, 
					Duplicate_Registration__r.Last_Name__c, Duplicate_Registration__r.Company__c
			from Partner_Request__c
			where id = :partnerRequestId];
		if(!requestList.isEmpty()){
			Partner_Request__c request = requestList.get(0);
			if(request.Duplicate_Account__r != null){
				companyName 	= request.Duplicate_Account__r.Name;
				if(request.Duplicate_Account__r.Partner_Registration__r != null){
					requestNumber 	= request.Duplicate_Account__r.Partner_Registration__r.name;
					requestorName 	= request.Duplicate_Account__r.Partner_Registration__r.First_Name__c + ' ' + 
						request.Duplicate_Account__r.Partner_Registration__r.Last_Name__c;
				}
			} else if(request.Duplicate_Registration__r != null){
				companyName 	= request.Duplicate_Registration__r.Company__c;
				requestNumber 	= request.Duplicate_Registration__r.Name;
				requestorName 	= request.Duplicate_Registration__r.First_Name__c + ' ' +
					request.Duplicate_Registration__r.Last_Name__c;
			}
			initialized = true;
		}
	}
	
}