profilelist1exp/unpackaged/objects/Relationship_Lead__c.object
<CustomObject>
    <description>These records are used to capture the marketing qualified sales ready leads. These records will be created by marketing users in SFDC</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Leads</relationshipLabel>
        <relationshipName>Relationship_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consent_to_engage_Dell_Channel_Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Customer consent is required to route a Dell lead to a channel partner; upon checking the box, click “continue” to complete the “route to channel” process.</inlineHelpText>
        <label>Customer consents to engage Partner?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SalesLeads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Data_Center_Optimization__c</fullName>
        <label>Data Center Optimization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Decision_Making_Role__c</fullName>
        <label>Decision Making Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Power Sponsor / Decision Maker</fullName>
                    <color>#0B6FCE</color>
                    <label>Power Sponsor / Decision Maker</label>
                </value>
                <value>
                    <fullName>Sponsor/ Champion</fullName>
                    <color>#78C953</color>
                    <label>Sponsor/ Champion</label>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                    <color>#E27001</color>
                    <label>Influencer</label>
                </value>
                <value>
                    <fullName>Business User</fullName>
                    <color>#A845DC</color>
                    <label>Business User</label>
                </value>
                <value>
                    <fullName>Evaluator</fullName>
                    <color>#F3D904</color>
                    <label>Evaluator</label>
                </value>
                <value>
                    <fullName>Purchasing / Procurement</fullName>
                    <color>#A53711</color>
                    <label>Purchasing / Procurement</label>
                </value>
                <value>
                    <fullName>Financial Buyer</fullName>
                    <color>#66E9BD</color>
                    <label>Financial Buyer</label>
                </value>
                <value>
                    <fullName>Technical Buyer</fullName>
                    <color>#0B24BE</color>
                    <label>Technical Buyer</label>
                </value>
                <value>
                    <fullName>Operational Buyer</fullName>
                    <color>#419249</color>
                    <label>Operational Buyer</label>
                </value>
                <value>
                    <fullName>Legal Approver</fullName>
                    <color>#B6E32E</color>
                    <label>Legal Approver</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dell_can_contact_me_in_the_future__c</fullName>
        <label>Dell can contact me in the future</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <color>#33CC00</color>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <color>#FF0000</color>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - 25</fullName>
                    <color>#0B6FCE</color>
                    <label>1 - 25</label>
                </value>
                <value>
                    <fullName>26 - 99</fullName>
                    <color>#CC33CC</color>
                    <label>26 - 99</label>
                </value>
                <value>
                    <fullName>100 - 499</fullName>
                    <color>#78C953</color>
                    <label>100 - 499</label>
                </value>
                <value>
                    <fullName>500 - 999</fullName>
                    <color>#E27001</color>
                    <label>500 - 999</label>
                </value>
                <value>
                    <fullName>1000 - 4999</fullName>
                    <color>#A845DC</color>
                    <label>1000 - 4999</label>
                </value>
                <value>
                    <fullName>5000 - 9999</fullName>
                    <color>#F3D904</color>
                    <label>5000 - 9999</label>
                </value>
                <value>
                    <fullName>10000+</fullName>
                    <color>#A53711</color>
                    <label>10000+</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_user_Productivity__c</fullName>
        <label>End-user Productivity</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IT_Process_Simplification__c</fullName>
        <label>IT Process Simplification</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_ID_Do_Not_Edit__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Do not change this field value.</inlineHelpText>
        <label>Lead ID (Do Not Edit)</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Marketing_Comments__c</fullName>
        <label>Marketing Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Purchase_Timeframe__c</fullName>
        <label>Purchase Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Immediately</fullName>
                    <color>#0B6FCE</color>
                    <label>Immediately</label>
                </value>
                <value>
                    <fullName>1-6 months</fullName>
                    <color>#78C953</color>
                    <label>1-6 months</label>
                </value>
                <value>
                    <fullName>7-12 months</fullName>
                    <color>#E27001</color>
                    <label>7-12 months</label>
                </value>
                <value>
                    <fullName>Undecided</fullName>
                    <color>#A845DC</color>
                    <label>Undecided</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Questions_Comments__c</fullName>
        <inlineHelpText>Comments or questions raised by customer during interaction with Dell</inlineHelpText>
        <label>Customer Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_Lead_Score__c</fullName>
        <label>Relationship Lead Score</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High Priority (Extremely hot leads; SLA = 48 hours)</fullName>
                    <color>#0B6FCE</color>
                    <label>High Priority (Extremely hot leads; SLA = 48 hours)</label>
                </value>
                <value>
                    <fullName>TeleQualified Lead (Potential Opportunity; SLA = 48 hours)</fullName>
                    <color>#E27001</color>
                    <label>TeleQualified Lead (Potential Opportunity; SLA = 48 hours)</label>
                </value>
                <value>
                    <fullName>Priority (Contact participated in Marketing program; SLA = 1 Week)</fullName>
                    <color>#78C953</color>
                    <label>Priority (Contact participated in Marketing program; SLA = 1 Week)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Comments__c</fullName>
        <label>Sales Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Relationship Lead</label>
    <nameField>
        <displayFormat>RL - {000000000}</displayFormat>
        <label>Relationship Lead #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/CMAP_LeadRoutingController.cls
/* 
REVISION HISTORY
================
Version     Author      Date            Release#    CR#     Description
-------     ------      ----            --------    ---     -----------
1.0         Jiji        12-Nov-2012     14.2         --     Controller for Route to Channel.
2.0         Sandhya     29-jan-2013     14.2                CRQ -0637
3.0         Jiji        13-Feb-2013     14.2         --     CRQ -0655
4.0         Jiji        05-Aug-2013     14.10        --     FR7.1 to FR7.19
5.0         Annie       17-Sep-2013     14.10               CRQ - 0786
6.0         Jiji        19-Sep-2013     14.10       CRQ0797  Remove Cancel button from the PL.
7.0         Manju       07-Nov-2-13     15.3         8840    To map Lead Score from RL to CL
8.0         Jiji        01-Apr-2014     15.07        --      Update R2C source
*/
public class CMAP_LeadRoutingController {
    String rlId{get;set;}
    Relationship_Lead__c rlRecord =  new Relationship_Lead__c();
    Lead leadRecord = new Lead();
    //Ver4.0: Code Start: CMAP FR-7.1: Autopopulate Values to New Channel Lead
    Lead DirLeadRecord = new Lead();
    public Lead clRecord { get; set; }
    public Id newId;
    String retURL;
    Public Boolean Show2ndBlock{get;set;}
    //Ver4.0: Code End: CMAP FR-7.1: Autopopulate Values to New Channel Lead
    Id leadRTId;
    Public Boolean showFirstBlock {get;set;}
    public Relationship_Lead__c rLeadObj{ get; set; }
    
    public CMAP_LeadRoutingController(ApexPages.StandardController controller) {
      try{
        
        showFirstBlock = TRUE;
        rLeadObj = new Relationship_Lead__c();
        leadRTId= IdLookupUtils.getRecordTypeId('Channel Lead - Cleansing & Scoring Complete','Lead',true);
        rlId = ApexPages.currentPage().getParameters().get('rlId');
        //Ver 4.0: FR7.13
        Show2ndBlock = False;
        newId = ApexPages.currentPage().getParameters().get('newId');
        
        retURL= ApexPages.currentPage().getParameters().get('retURL');
        if(newId != NULL){
             Show2ndBlock = TRUE;
             showFirstBlock = False;
             clRecord = [Select Id, Questions_Comments__c, 
                         Sales_Comments__c
                         from  Lead 
                         where Id = :newId];
        }
        
        //Ver 4.0: FR7.13
        if(rlId != NULL){
             //Ver4.0: Code Start: CMAP FR-7.1: Autopopulate Values to New Channel Lead
             rlRecord = [Select Id, Contact__r.FirstName,Contact__r.LastName,
                               Contact__r.Title, 
                               Contact__r.Email, 
                               Contact__r.Phone, 
                               Contact__r.MobilePhone, 
                               Contact__r.Fax,
                               Contact__r.MailingStreet, 
                               Contact__r.MailingState, 
                               Contact__r.MailingPostalCode, 
                               Contact__r.MailingCountry, 
                               Contact__r.MailingCity,
                               //Ver 5.0
                               Contact__r.Salutation,
                               Account_Name__r.Industry, 
                               Account_Name__r.BillingStreet, 
                               Account_Name__r.BillingState, 
                               Account_Name__r.BillingPostalCode,
                               Account_Name__r.BillingCountry,
                               Account_Name__r.BillingCity,
                               //Ver 7.0 Code start
                               Relationship_Lead_Score__c,
                               //Ver 7.0 Code end
                               //Code Start:Defect 80411
                               Account_Name__r.Name,
                               //Code End: Defect 80411
                               Lead_ID_Do_Not_Edit__c, Name,
                               Consent_to_engage_Dell_Channel_Partner__c, 
                               Purchase_Timeframe__c, Employee__c, 
                               Dell_can_contact_me_in_the_future__c, 
                               Decision_Making_Role__c
                         From  Relationship_Lead__c 
                         where Id = :rlId];
             //Ver4.0: CMAP FR-7.1: Autopopulate Values to New Channel Lead
             //ver 5.0 : CRQ 0786 : Commented
            /*If(rlRecord.Lead_ID_Do_Not_Edit__c != NULL){
                DirLeadRecord = [Select Salutation From Lead Where Id = :rlRecord.Lead_ID_Do_Not_Edit__c];
            }*/
             //ver 5.0 : CRQ 0786 : Commented 
             //Ver4.0: Code End: CMAP FR-7.1: Autopopulate Values to New Channel Lead
            //if(rlRecord){
            rLeadObj = rlRecord;
            //}
        }
      }
      catch (Exception e) {
          ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,System.Label.CMAP_Default_Error_Message));
      } 
    }
    
    public pagereference cancelButton(){
        String URL = '/'+rlId ;
        pagereference page = new pagereference(URL);
        page.setRedirect(TRUE);
        return page;
    }  
    
    public pagereference redirect(){
        //new change with page display
        if(rLeadObj.Consent_to_engage_Dell_Channel_Partner__c == FALSE){
            showFirstBlock = True;
            pageUtils.AddError('Customer consent is required to route a Dell lead to a channel partner; upon checking the box, click “continue” to complete the “route to channel” process.');
        }
        else{
           //new change with page display
           String Status = pageUtils.encodeVariable('Qualified - Channel Ready');
           String cityString;
           String stateString;
           String postalString;
           String countryString;
           String R2CSource  = pageUtils.encodeVariable('Relationship Lead');//Ver 8.0:  Update R2C source
           if(rlRecord.Contact__r.MailingStreet == NULL &&
              rlRecord.Contact__r.MailingState == NULL && 
              rlRecord.Contact__r.MailingPostalCode == NULL && 
              rlRecord.Contact__r.MailingCountry== NULL  && 
              rlRecord.Contact__r.MailingCity == NULL){
                cityString = rlRecord.Account_Name__r.BillingCity;
                stateString = rlRecord.Account_Name__r.BillingState;
                postalString = rlRecord.Account_Name__r.BillingPostalCode;
                countryString = rlRecord.Account_Name__r.BillingCountry;
           }
           else{
                cityString = rlRecord.Contact__r.MailingCity;
                stateString = rlRecord.Contact__r.MailingState;
                postalString = rlRecord.Contact__r.MailingPostalCode;
                countryString = rlRecord.Contact__r.MailingCountry;
           }
           string saveURLstring ='/apex/CMAP_RouteToChannel?retURL='+rlRecord.Id;
           String URL = '/00Q/e?lea13='+Status+'&RecordType='+leadRTId+
                     '&nooverride=1&retURL='+rlRecord.Id+
                     '&saveURL='+saveURLstring+
                     '&00NA00000064hVv='+R2CSource+  //Ver 8.0:  Update R2C source
                     '&CF00NA00000063aoO_lkid='+rlRecord.Id+'&CF00NA00000063aoO='+rlRecord.Name+
                     //(rlRecord.Name!=NULL?'&CF00NZ0000000bA0S='+pageUtils.encodeVariable(rlRecord.Name):'')+
                     (rlRecord.Contact__r.FirstName!=NULL?'&name_firstlea2='+pageUtils.encodeVariable(rlRecord.Contact__r.FirstName):'')+
                     (rlRecord.Contact__r.LastName!=NULL?'&name_lastlea2='+pageUtils.encodeVariable(rlRecord.Contact__r.LastName):'')+
                     
                     //Ver4.0: Code Start: CMAP FR-7.1: Autopopulate Values to New Channel Lead
                     //Ver 5.0
                     (rlRecord.Contact__r.Salutation!=NULL?'&name_salutationlea2='+pageUtils.encodeVariable(rlRecord.Contact__r.Salutation):'')+
                     //ver 5.0
                     (rlRecord.Contact__r.MobilePhone!=NULL?'&lea9='+pageUtils.encodeVariable(rlRecord.Contact__r.MobilePhone):'')+
                     (rlRecord.Contact__r.Fax!=NULL?'&lea10='+pageUtils.encodeVariable(rlRecord.Contact__r.Fax):'')+
                     (rlRecord.Account_Name__r.Industry!=NULL?'&lea6='+pageUtils.encodeVariable(rlRecord.Account_Name__r.Industry):'')+
                     (cityString!=NULL?'&lea16city='+pageUtils.encodeVariable(cityString):'')+
                     (stateString!=NULL?'&lea16state='+pageUtils.encodeVariable(stateString):'')+
                     (postalString!=NULL?'&lea16zip='+pageUtils.encodeVariable(postalString):'')+
                     (countryString!=NULL?'&lea16country='+pageUtils.encodeVariable(countryString):'')+
                     //Ver 7.0 Code start
                     (rlRecord.Relationship_Lead_Score__c!=NULL?'&00NA0000009ZFtB='+pageUtils.encodeVariable(rlRecord.Relationship_Lead_Score__c):'')+
                     //Ver 7.0 Code end
                     //Ver4.0: Code End: CMAP FR-7.1: Autopopulate Values to New Channel Lead
                     //Code start: Defect 80411: To populate Company through URL
                     (rlRecord.Account_Name__r.Name!=NULL?'&lea3='+pageUtils.encodeVariable(rlRecord.Account_Name__r.Name ):'')+
                     //Code End: Defect 80411: To populate Company through URL
                     (rlRecord.Contact__r.Title!=NULL?'&lea4='+pageUtils.encodeVariable(rlRecord.Contact__r.Title):'')+
                     (rlRecord.Contact__r.Email!=NULL?'&lea11='+pageUtils.encodeVariable(rlRecord.Contact__r.Email):'')+
                     (rlRecord.Contact__r.Phone!=NULL?'&lea8='+pageUtils.encodeVariable(rlRecord.Contact__r.Phone):'')+
                     /*Ver2.0(rlRecord.Marketing_Comments__c!=NULL?'&00NA00000063WGw='+pageUtils.encodeVariable(rlRecord.Marketing_Comments__c):'')+
                     (rlRecord.Sales_Comments__c!=NULL?'&00NA00000063UTv='+pageUtils.encodeVariable(rlRecord.Sales_Comments__c):'')+
                     (rlRecord.Data_Center_Optimization__c!=NULL?'&00N70000002MSmi='+pageUtils.encodeVariable(rlRecord.Data_Center_Optimization__c):'')+
                     (rlRecord.End_user_Productivity__c!=NULL?'&00N70000002MSmn='+pageUtils.encodeVariable(rlRecord.End_user_Productivity__c):'')+
                     (rlRecord.IT_Process_Simplification__c!=NULL?'&00N70000002MSnb='+pageUtils.encodeVariable(rlRecord.IT_Process_Simplification__c):'')+ Ver 2.0*/
                     
                     (rlRecord.Purchase_Timeframe__c!=NULL?'&00N70000002MSnl='+pageUtils.encodeVariable(rlRecord.Purchase_Timeframe__c):'')+
                     (rlRecord.Dell_can_contact_me_in_the_future__c!=NULL?'&00N70000002MSnq='+pageUtils.encodeVariable(rlRecord.Dell_can_contact_me_in_the_future__c):'')+
                     (rlRecord.Decision_Making_Role__c!=NULL?'&00N70000002MSo0='+pageUtils.encodeVariable(rlRecord.Decision_Making_Role__c):'');
        
            pagereference page = new pagereference(URL);
            page.setRedirect(TRUE);
            return page;
        }
        return NULL;
    }
    public pagereference saveButton(){
        system.debug('----clRecord--'+clRecord);
        update clRecord;
        String URL= '/'+newId;
        system.debug('----URL--'+URL);
        pagereference page = new pagereference(URL);
        page.setRedirect(TRUE);
        return page;
        
    }
     /*Ver 6.0: Code Start: CRQ0797:  Remove Cancel button from the PL.
     public pagereference cancelButton2(){
        String URL = '/'+newId;
        pagereference page = new pagereference(URL);
        page.setRedirect(TRUE);
        return page;
    }
    Ver 6.0: Code Start: CRQ0797:  Remove Cancel button from the PL.*/
}