profilelist1exp/unpackaged/objects/Role__c.object
<CustomObject>
    <description>This object is to create and maintain the roles for the teams that uses geography based owner assignment process for the relationship leads and Account Plays.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Motion_User_Role__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Business Consultant</fullName>
                </value>
                <value>
                    <fullName>CSE Admin</fullName>
                </value>
                <value>
                    <fullName>CSE Intake Manager</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>SOC Intake Manager</fullName>
                </value>
                <value>
                    <fullName>SOC SOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Username</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Motion_User_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Motion User Role</label>
    <nameField>
        <label>Sales Motion User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Motion User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Request__c/Support_Request__c.object-meta.xml
<CustomObject>
    <label>Support Request</label>
    <nameField>
        <displayFormat>SR # {000000000}</displayFormat>
        <label>Support Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>CR#1241-Look Up field to opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>CEM_Support</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/SOM__c.field-meta.xml
<CustomField>
    <fullName>SOM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Motion_User_Role__c.Role__c</field>
            <operation>equals</operation>
            <value>SOC SOM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Motion_User_Role__c</referenceTo>
    <relationshipLabel>Support Requests</relationshipLabel>
    <relationshipName>Support_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/SOM_Email__c.field-meta.xml
<CustomField>
    <fullName>SOM_Email__c</fullName>
    <label>SOM Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Support_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Reassigned</fullName>
            </value>
            <value>
                <fullName>Engagement complete</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Unqualified Opp</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Pending Al Sales</fullName>
            </value>
            <value>
                <fullName>Quoting</fullName>
            </value>
            <value>
                <fullName>Proposal Submitted</fullName>
            </value>
            <value>
                <fullName>Pending AT</fullName>
            </value>
            <value>
                <fullName>SOC Monitoring</fullName>
            </value>
            <value>
                <fullName>Lost Opp</fullName>
            </value>
            <value>
                <fullName>Cancelled Opp</fullName>
            </value>
            <value>
                <fullName>Order Mgmt</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>In Quote</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>In Sustaining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailNotificationonstagechangeTest.cls
/*
Test class for SendEmailNotificationonstagechange trigger
*/
@isTest
public class SendEmailNotificationonstagechangeTest{
    
    static Account testAccount;
    static User us;
    static Opportunity testOpp;
    static Support_Request__c suppReq;
    static Sales_Motion_User_Role__c salMotionusrol;

    /* Create Test Support Request */
    static testmethod void createTestNotification() {
        
        
        Id testpro = [SELECT Id FROM profile WHERE Name = 'System Administrator'].id;
        Test.StartTest();
        //Creating Test Users:
        us = new USER();
        us.FirstName= 'Demo';
        us.LastName = 'Test User';
        us.Email = 'abc@dell.com';
        us.Username = 'testvaliduser' +'@dell.com';
        us.CommunityNickname = 'testcomname';
        us.LanguageLocaleKey = 'en_US';
        us.LocaleSidKey = 'en_GB';
        us.timezonesidkey = 'GMT';
        us.emailencodingkey = 'ISO-8859-1';
        us.alias = 'tAls';        
        us.Profileid = testpro;     
        us.phone = '58694258';
        us.Mobilephone = '9858685925';
        us.fax='89652358';
        us.Street ='Test Street';
        us.City = 'Test City';
        us.State = 'Tx';
        us.PostalCode ='1234';
        us.Country ='Test COuntry';
        //us.Badge_Number__c='Test'+System.currentTimeMillis();
        insert us;
        
        //Create Test Data SalesMotion User Role    
        salMotionusrol = new Sales_Motion_User_Role__c();
        salMotionusrol.Name = 'TestSalesMonstionuser';
        salMotionusrol.Role__c = 'SOC SOM';
        salMotionusrol.Username__c = us.Id;
        insert salMotionusrol;
        
        
        for( Integer i=0; i<200; i++ ) {    
        //inserting the opportunity
            testOpp = new Opportunity();            
            testOpp.Name = 'test opportunity';
            testOpp.StageName = 'Qualify - 30%';
            testOpp.recordtypeid = '012300000004zf2';
            testOpp.Description = 'Automatically closed out because Book Date is past due over 6 months.';
            testOpp.Won_Lost_Comment__c = 'Automatically closed out because Book Date is past due over 6 months.';
           // testOpp.Past_Due_Auto_Closed__c = True;
            testOpp.Competitor_Lost_To__c = 'Unknown';
           // testOpp.Reason_Won_Lost__c = 'Past Due Auto Closed';
            testOpp.CloseDate = date.today()+30;
        }   
        insert testOpp;
       
        Test.StopTest();
        suppReq = new Support_Request__c();        
        //suppReq.SOM__c = salMotionusrol.Id;   
        suppReq.SOM_Email__c = 'SOC_Engagement@Dell.com';
        suppReq.Status__c = 'new';
        suppReq.Opportunity__c=testOpp.Id;
        suppReq.recordtypeid = '012A0000000ViNO';
        insert suppReq;
        
        suppReq.Status__c = 'Accept';
        suppReq.SOM__c = salMotionusrol.Id;  
        update suppReq; 
        
        testOpp.StageName='Commit - 90%';
        update testOpp;
        
    }
      
}