profilelist1exp/unpackaged/objects/Sales_Coach_Activity__c.object
<CustomObject>
    <description>Sales Coach Activity used to display details for Sales Coach in Opportunity</description>
    <fields>
        <fullName>Activity_Details__c</fullName>
        <label>Activity Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ordering_Number__c</fullName>
        <label>Ordering Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Coach_Setup__c</fullName>
        <label>Sales Coach Setup</label>
        <referenceTo>Sales_Coach_Setup__c</referenceTo>
        <relationshipLabel>Sales Coach Activities</relationshipLabel>
        <relationshipName>Sales_Coach_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Coach Activity</label>
    <nameField>
        <displayFormat>SCAN-{000000}</displayFormat>
        <label>Sales Coach Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Coach Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Sales_Coach_Setup__c.object
<CustomObject>
    <description>Sales Coach Setup used to display details for Sales Coach stages.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Goal_Stage__c</fullName>
        <label>Goal of Selling Stage:</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <label>LanguageCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sales Coach Setup</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Coach Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_SalesCoachSetup.cls
@isTest(SeeAllData = false)
private class Test_SalesCoachSetup{
  
 
  public static testmethod void controllerMethod(){
  
    Opportunity oppRecord = new Opportunity();
    oppRecord.StageName = 'Plan - 1%';
    oppRecord.CloseDate = System.Today();
    oppRecord.Name = 'Test Opp';
    insert oppRecord;
    
    Sales_Coach_Setup__c salesCoachRecord = new Sales_Coach_Setup__c();
    salesCoachRecord.Name = 'Plan - 1%';
    salesCoachRecord.Language__c = 'English';
    salesCoachRecord.LanguageCode__c = 'en_US';
    salesCoachRecord.Active__c = true;
    salesCoachRecord.Goal_Stage__c = 'Goal Sales Coach';
    insert salesCoachRecord;
    
    List<Sales_Coach_Activity__c> salesActivityList = new List<Sales_Coach_Activity__c>();
    for(integer i =0 ; i<6 ; i++){
      Sales_Coach_Activity__c salesActivityRecord = new Sales_Coach_Activity__c();
      salesActivityRecord.Activity_Details__c ='Sales Activity'+i;
      salesActivityRecord.Ordering_Number__c = i;
      salesActivityRecord.Sales_Coach_Setup__c= salesCoachRecord.Id;
      salesActivityList.add(salesActivityRecord);
    }  
    insert salesActivityList;
    
    PageReference pageRef =Page.SalesCoachSetup;
    Test.setCurrentPage(pageRef);
    ApexPages.StandardController  stdCon = new ApexPages.StandardController(salesCoachRecord);
    SalesCoachSetup controller = new SalesCoachSetup (stdCon); 
    
    SalesCoachSetup.getOpptyStages();
    SalesCoachSetup.getKeyprefix();
    
    controller.getLanguages();
    controller.saveClose();
    controller.btncancel();
    controller.saveActivities();    
    controller.deleteActivity();
  }
  
    
}