profilelist1exp/unpackaged/objects/SFDC_Acct_Plan__c.object
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an Account</description>
    <fields>
        <fullName>Account_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the Account Executive responsible for this Account Plan. Account Executive is responsible to submit the Account Plan for Approval.</inlineHelpText>
        <label>Account Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>R00N60000001PRP8EAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approved_by_Sales_Management__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Sales Manager that approved this account plan</inlineHelpText>
        <label>Approved by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is RSD/RSM for Channel/Partner Account Plan RT</description>
        <inlineHelpText>The Manager is the person responsible for approving the Plan</inlineHelpText>
        <label>Manager</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The current user in the “Manager” field is now an Inactive User, please update.</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans4STv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Waiting for Strategies</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Reviewed and Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The RSD/RSM is the person responsible for approving the Account Plan</inlineHelpText>
        <label>RSD/RSM</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The current user in the “RSD/RSM” field is now an Inactive User, please update.</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Plan_Status__c)</formula>
        <inlineHelpText>Account plan approval process status</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/SFDC_Strategy__c.object
<CustomObject>
    <description>Specific set of strategies tied to each account that the sales manager needs to executive. Each strategy lists specific revenue goals and products/services to be sold to a particular division or department. Tasks and milestones are also attached to each strategy.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N70000002MeyzEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFDC_Acct_Plan__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account Plan</label>
        <referenceTo>SFDC_Acct_Plan__c</referenceTo>
        <relationshipLabel>Strategy</relationshipLabel>
        <relationshipName>Product_Strategy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AccountPlanAfterInsertUpdateTest.cls
@isTest
private class AccountPlanAfterInsertUpdateTest {

    static User userRecord;
    static Account testEUAccount;
    static SFDC_Acct_Plan__c testAccountPlan;
    static SFDC_Acct_Plan__c testPartnerAccountPlan;
    
    static testMethod void Test_AccountPlanCreateAndUpdate_DirectAccountPlan() {
        TriggerExecutionController.setSkipAllTriggers(true);
        //TestDataCreation();
        Profile profile = [select Id from profile where Name = 'System Administrator' limit 1];
        
        userRecord = new User(Username = 'TestValidUser1@dell.com',
                               Alias = 'Test', 
                               Email = 'Test212@dell.com', 
                               LastName = 'Test22',
                               Title = 'GCC Program Manager', 
                               ProfileId = profile.Id, 
                               LanguageLocaleKey = 'en_US', 
                               LocaleSidKey = 'en_US', 
                               EmailEncodingKey = 'UTF-8', 
                               TimeZoneSidKey = 'America/Los_Angeles',
                               Country = 'US',
                               Badge_Number__c = 'Test' + System.currentTimeMillis());
        insert userRecord;
        User salesMgr = new User(Username = 'TestValidUserAccPlan2@dell.com',
                                Alias = 'Test', 
                                Email = 'Test212@dell.com', 
                                LastName = 'Test22',
                                Title = 'GCC Program Manager', 
                                ProfileId = profile.Id, 
                                LanguageLocaleKey = 'en_US', 
                                LocaleSidKey = 'en_US', 
                                EmailEncodingKey = 'UTF-8', 
                                TimeZoneSidKey = 'America/Los_Angeles',
                                Country = 'US',
                                Badge_Number__c = 'Test' + System.currentTimeMillis());
        insert salesMgr;
        Id partnerAccPlanRTId= IdLookupUtils.getRecordTypeId('Channel/Partner Account Plan','SFDC_Acct_Plan__c',true);
        Id directAccPlanRTId= IdLookupUtils.getRecordTypeId('Direct Relationship Account Plan','SFDC_Acct_Plan__c',true);
        
        
            //Create Account
            testEUAccount = new Account(Name = 'Test EU Account for Account Plan Test', Type = 'End User', Participating_in_LOB_Program__c = true, OwnerId = userRecord.Id);
            insert testEUAccount;
        testAccountPlan = new SFDC_Acct_Plan__c(Name = 'TestPlan01', Account__c = testEUAccount.Id, Sales_Manager__c = salesMgr.Id , Approved_by_Sales_Management__c=null,Manager__c=null,RecordTypeId=partnerAccPlanRTId);            
            
            insert testAccountPlan;        
            
            //Create Strategy for Account Plan
            SFDC_Strategy__c testStrategy = new SFDC_Strategy__c(Name = 'Test Strategy', SFDC_Acct_Plan__c = testAccountPlan.Id);
            insert testStrategy;
        
        //Update the Account plan status to Pending
        testAccountPlan.Plan_Status__c = 'Pending';    
        update testAccountPlan;
        System.debug('**Test Class Debug -- testAccountPlan.Sales_Manager__c** ::'+testAccountPlan.Sales_Manager__c);   
            System.debug('**Test Class Debug -- testAccountPlan.RecordType.Namec** ::'+testAccountPlan.RecordType.Name);
                 System.debug('**Test Class Debug -- testAccountPlan.Manager__c** ::'+testAccountPlan.Manager__c);   
       
        TriggerExecutionController.setSkipAllTriggers(false);  
        Test.startTest();
        system.debug('###Account Plan Status is :: ' + testAccountPlan.Status__c);
        AccountPlanUpdateStatusController controller = new AccountPlanUpdateStatusController(new ApexPages.StandardController(testAccountPlan));
        
        PageReference pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.updateAccountPlanStatus();
        
        system.debug('###Account Plan Status is :: ' + testAccountPlan.Status__c);
        
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.redirectBack();
        system.debug('###Account Plan Status is :: ' + testAccountPlan.Status__c);
        
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.getHasMessage();
        
        testAccountPlan.Sales_Manager__c = userRecord.Id;
        update testAccountPlan;
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.updateAccountPlanStatus();
        Test.stopTest();
    }
    
    //Modified - to cover for submitted fro approval 
     static testMethod void Test_AccountPlanCreateAndUpdate_DirectAccountPlanapp() {
         // Skill all trigger to avoid too many SOQL Query Issue
        TriggerExecutionController.setSkipAllTriggers(true);
        
        //TestDataCreation();
        
        Profile profile = [select Id from profile where Name = 'System Administrator' limit 1];
        
        userRecord = new User(Username = 'TestValidUser1@dell.com',
                               Alias = 'Test', 
                               Email = 'Test212@dell.com', 
                               LastName = 'Test22',
                               Title = 'GCC Program Manager', 
                               ProfileId = profile.Id, 
                               LanguageLocaleKey = 'en_US', 
                               LocaleSidKey = 'en_US', 
                               EmailEncodingKey = 'UTF-8', 
                               TimeZoneSidKey = 'America/Los_Angeles',
                               Country = 'US',
                               Badge_Number__c = 'Test' + System.currentTimeMillis());
        insert userRecord;
        User salesMgr = new User(Username = 'TestValidUserAccPlan2@dell.com',
                                Alias = 'Test', 
                                Email = 'Test212@dell.com', 
                                LastName = 'Test22',
                                Title = 'GCC Program Manager', 
                                ProfileId = profile.Id, 
                                LanguageLocaleKey = 'en_US', 
                                LocaleSidKey = 'en_US', 
                                EmailEncodingKey = 'UTF-8', 
                                TimeZoneSidKey = 'America/Los_Angeles',
                                Country = 'US',
                                Badge_Number__c = 'Test' + System.currentTimeMillis());
        insert salesMgr;
        Id partnerAccPlanRTId= IdLookupUtils.getRecordTypeId('Channel/Partner Account Plan','SFDC_Acct_Plan__c',true);
        Id directAccPlanRTId= IdLookupUtils.getRecordTypeId('Direct Relationship Account Plan','SFDC_Acct_Plan__c',true);
        
        
            //Create Account
            testEUAccount = new Account(Name = 'Test EU Account for Account Plan Test', Type = 'End User', Participating_in_LOB_Program__c = true, OwnerId = userRecord.Id);
            insert testEUAccount;
        testAccountPlan = new SFDC_Acct_Plan__c(Name = 'TestPlan01', Account__c = testEUAccount.Id, Sales_Manager__c = salesMgr.Id , Approved_by_Sales_Management__c=null,Manager__c=null,RecordTypeId=partnerAccPlanRTId);            
            
            insert testAccountPlan;        
            
            //Create Strategy for Account Plan
            SFDC_Strategy__c testStrategy = new SFDC_Strategy__c(Name = 'Test Strategy', SFDC_Acct_Plan__c = testAccountPlan.Id);
            insert testStrategy;
 
        
        //Update the Account plan status to Pending
        testAccountPlan.Plan_Status__c = 'Pending';    
        
        
        testAccountPlan.Plan_Status__c = 'Submitted for Approval'; 
        testAccountPlan.Account_Executive__c=userRecord.Id;    
        update testAccountPlan;
        System.debug('**Test Class Debug -- testAccountPlan.Sales_Manager__c** ::'+testAccountPlan.Sales_Manager__c);   
            System.debug('**Test Class Debug -- testAccountPlan.RecordType.Namec** ::'+testAccountPlan.RecordType.Name);
                 System.debug('**Test Class Debug -- testAccountPlan.Manager__c** ::'+testAccountPlan.Manager__c);   
       
        //Revert back the skip all triggers
        TriggerExecutionController.setSkipAllTriggers(false);  
        Test.startTest();
        system.debug('###Account Plan Status is :: ' + testAccountPlan.Status__c);
        AccountPlanUpdateStatusController controller = new AccountPlanUpdateStatusController(new ApexPages.StandardController(testAccountPlan));
        
        PageReference pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.updateAccountPlanStatus();
        
        system.debug('###Account Plan Status is :: ' + testAccountPlan.Status__c);
        //Test.startTest();
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.redirectBack();
        system.debug('###Account Plan Status is :: ' + testAccountPlan.Status__c);
        
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.getHasMessage();
        
        testAccountPlan.Sales_Manager__c = userRecord.Id;
        update testAccountPlan;
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.updateAccountPlanStatus();  
        Test.stopTest();      
    }
    
    static testMethod void Test_AccountPlanCreateAndUpdate_PartnerAccountPlan() {
        TriggerExecutionController.setSkipAllTriggers(true);
        //TestDataCreation();
        
        Profile profile = [select Id from profile where Name = 'System Administrator' limit 1];
        
        userRecord = new User(Username = 'TestValidUser1@dell.com',
                               Alias = 'Test', 
                               Email = 'Test212@dell.com', 
                               LastName = 'Test22',
                               Title = 'GCC Program Manager', 
                               ProfileId = profile.Id, 
                               LanguageLocaleKey = 'en_US', 
                               LocaleSidKey = 'en_US', 
                               EmailEncodingKey = 'UTF-8', 
                               TimeZoneSidKey = 'America/Los_Angeles',
                               Country = 'US',
                               Badge_Number__c = 'Test' + System.currentTimeMillis());
        insert userRecord;
        User salesMgr = new User(Username = 'TestValidUserAccPlan2@dell.com',
                                Alias = 'Test', 
                                Email = 'Test212@dell.com', 
                                LastName = 'Test22',
                                Title = 'GCC Program Manager', 
                                ProfileId = profile.Id, 
                                LanguageLocaleKey = 'en_US', 
                                LocaleSidKey = 'en_US', 
                                EmailEncodingKey = 'UTF-8', 
                                TimeZoneSidKey = 'America/Los_Angeles',
                                Country = 'US',
                                Badge_Number__c = 'Test' + System.currentTimeMillis());
        insert salesMgr;
        User pdmMgr = new User(Username = 'TestPDM@dell.com',
                                Alias = 'Test', 
                                Email = 'TestPDM@dell.com', 
                                LastName = 'Testpdm22',
                                Title = 'GCC Program Manager', 
                                ProfileId = profile.Id, 
                                LanguageLocaleKey = 'en_US', 
                                LocaleSidKey = 'en_US', 
                                EmailEncodingKey = 'UTF-8', 
                                TimeZoneSidKey = 'America/Los_Angeles',
                                Country = 'US',
                                Badge_Number__c = 'Tst' + System.currentTimeMillis());
        insert pdmMgr;
        
        Id partnerAccPlanRTId= IdLookupUtils.getRecordTypeId('Channel/Partner Account Plan','SFDC_Acct_Plan__c',true);
        Id directAccPlanRTId= IdLookupUtils.getRecordTypeId('Direct Relationship Account Plan','SFDC_Acct_Plan__c',true);
        
        
            //Create Account
            testEUAccount = new Account(Name = 'Test EU Account for Account Plan Test', Type = 'End User', Participating_in_LOB_Program__c = true, OwnerId = userRecord.Id);
            insert testEUAccount;
        testPartnerAccountPlan = new SFDC_Acct_Plan__c(Name = 'TestPlan01', Account__c = testEUAccount.Id, Sales_Manager__c = salesMgr.Id , Approved_by_Sales_Management__c=null,Manager__c=pdmMgr.Id,RecordTypeId=partnerAccPlanRTId);
            insert testPartnerAccountPlan;
            
            //Create Partner Strategy for Account Plan
            SFDC_Strategy__c testPartnerStrategy = new SFDC_Strategy__c(Name = 'Test Partner Strategy', SFDC_Acct_Plan__c = testPartnerAccountPlan.Id);
            insert testPartnerStrategy;
 
        
        //Update the Account plan status to Pending
        testPartnerAccountPlan.Plan_Status__c = 'Pending';
        update testPartnerAccountPlan;
        System.debug('**Test Class Debug -- testPartnerAccountPlan.Sales_Manager__c** ::'+testPartnerAccountPlan.Sales_Manager__c);   
            System.debug('**Test Class Debug -- testPartnerAccountPlan.RecordType.Namec** ::'+testPartnerAccountPlan.RecordType.Name);
                 System.debug('**Test Class Debug -- testPartnerAccountPlan.Manager__c** ::'+testPartnerAccountPlan.Manager__c);   
       
        TriggerExecutionController.setSkipAllTriggers(false);  
        Test.startTest();
        system.debug('###Account Plan Status is :: ' + testPartnerAccountPlan.Status__c);
        AccountPlanUpdateStatusController controller = new AccountPlanUpdateStatusController(new ApexPages.StandardController(testPartnerAccountPlan));
        
        PageReference pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testPartnerAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.updateAccountPlanStatus();
        
        system.debug('###Account Plan Status is :: ' + testPartnerAccountPlan.Status__c);
        
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testPartnerAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.redirectBack();
        system.debug('###Account Plan Status is :: ' + testPartnerAccountPlan.Status__c);
        
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testPartnerAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.getHasMessage();
        
        testPartnerAccountPlan.Manager__c = userRecord.Id;
        update testPartnerAccountPlan;
        pageRef = new PageReference('/apex/AccountPlanUpdateStatus?id=' + testPartnerAccountPlan.Id);
        Test.setCurrentPage(pageRef);
        controller.updateAccountPlanStatus();
        Test.stopTest();
    }
 }