profilelist1exp/unpackaged/objects/SFDC_Strategy__c.object
<CustomObject>
    <description>Specific set of strategies tied to each account that the sales manager needs to executive. Each strategy lists specific revenue goals and products/services to be sold to a particular division or department. Tasks and milestones are also attached to each strategy.</description>
    <fields>
        <fullName>Strategy_Status__c</fullName>
        <description>Strategy Status</description>
        <label>Strategy Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Pending Specialist</fullName>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_for_Review_Comments__c</fullName>
        <description>Submit for Review Comments</description>
        <label>Submit for Review Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/StrategyDetailPage.cls
public without sharing class StrategyDetailPage{

    //Use @AuraEnabled to enable client- and server-side access to the method
    @AuraEnabled
    public static String submitForReview(Id recordId,String commentsValue) {
        try
        {
            //Get the RecordId and update status field
            SFDC_Strategy__c  StrategyData;
            StrategyData= [select Id,Strategy_Status__c,Name from SFDC_Strategy__c WHERE Id=:recordId];
            StrategyData.Strategy_Status__c= 'Submitted for Review';
            StrategyData.Submit_for_Review_Comments__c=commentsValue; 
            update StrategyData;
            return StrategyData.Name;
         }
         catch(DmlException e) {
             System.debug('The following exception has occurred: ' + e.getMessage());
             return null;
             
         }

    }
}