profilelist1exp/unpackaged/objects/SFDC_Acct_Plan__c.object
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>R00N60000001PRP8EAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Calculated_Annual_Value_of_Strategies__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Calculated Annual Value of Strategies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Plan_Starting_Fiscal_Year__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <inlineHelpText>Dell&apos;s fiscal year (February - January)</inlineHelpText>
        <label>Planning Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY17</fullName>
                </value>
                <value>
                    <fullName>FY18</fullName>
                </value>
                <value>
                    <fullName>FY19</fullName>
                </value>
                <value>
                    <fullName>FY20</fullName>
                </value>
                <value>
                    <fullName>FY21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RSD_Review_Feedback__c</fullName>
        <label>RSD Review Feedback</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The RSD/RSM is the person responsible for approving the Account Plan</inlineHelpText>
        <label>RSD/RSM</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The current user in the “RSD/RSM” field is now an Inactive User, please update.</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Account_Sales_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SOM R15.10 - Value is populate when user with title &quot;SVC_ASE&quot; is add into Account Team</description>
        <label>Services Account Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Customer_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SOM R15.10 - Value is populate when user with title &quot;SVC_CE&quot; is add into Account Team</description>
        <label>Services Customer Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plans7</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/SFDC_Strategy__c.object
<CustomObject>
    <description>Specific set of strategies tied to each account that the sales manager needs to executive. Each strategy lists specific revenue goals and products/services to be sold to a particular division or department. Tasks and milestones are also attached to each strategy.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N70000002MeyzEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_Strategy_Value__c</fullName>
        <inlineHelpText>Add the Estimated total value</inlineHelpText>
        <label>Potential Strategy Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SFDC_Acct_Plan__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account Plan</label>
        <referenceTo>SFDC_Acct_Plan__c</referenceTo>
        <relationshipLabel>Strategy</relationshipLabel>
        <relationshipName>Product_Strategy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>When_do_you_plan_to_realize_Strategy__c</fullName>
        <inlineHelpText>Select the appropriate Fiscal year</inlineHelpText>
        <label>When do you plan to realize Strategy?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY17</fullName>
                </value>
                <value>
                    <fullName>FY18</fullName>
                </value>
                <value>
                    <fullName>FY19</fullName>
                </value>
                <value>
                    <fullName>FY20 Q1</fullName>
                </value>
                <value>
                    <fullName>FY20 Q2</fullName>
                </value>
                <value>
                    <fullName>FY20 Q3</fullName>
                </value>
                <value>
                    <fullName>FY20 Q4</fullName>
                </value>
                <value>
                    <fullName>FY21 Q1</fullName>
                </value>
                <value>
                    <fullName>FY21 Q2</fullName>
                </value>
                <value>
                    <fullName>FY21 Q3</fullName>
                </value>
                <value>
                    <fullName>FY21 Q4</fullName>
                </value>
                <value>
                    <fullName>FY22 Q1</fullName>
                </value>
                <value>
                    <fullName>FY22 Q2</fullName>
                </value>
                <value>
                    <fullName>FY22 Q3</fullName>
                </value>
                <value>
                    <fullName>FY22 Q4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/AccountPlanBeforeInsertBeforeUpdateTest.cls
@isTest
private class AccountPlanBeforeInsertBeforeUpdateTest {
    private static Account testAccount;
    private static SFDC_Acct_Plan__c testAccPlan;
    
    
    private static testMethod void test() {
        Map<String, Id> userMap = new Map<String, Id>();
        
        createTestData();
        
        Test.startTest();
        List<AccountTeamMember> queryAccTM = [SELECT AccountId,Id,UserId,User.Title FROM AccountTeamMember WHERE AccountId = :testAccount.id AND User.Title IN ('SVC_ASE', 'SVC_CE') ORDER BY LastModifiedDate];
        System.assertEquals(2, queryAccTM.size());

        if(!queryAccTM.isEmpty() & queryAccTM.size() > 0){
            for(AccountTeamMember atm: queryAccTM){
                if(atm != null){
                    if(atm.User.Title == 'SVC_ASE'){
                        userMap.put('SVC_ASE_'+atm.AccountId, atm.User.Id);
                    }
                    if(atm.User.Title == 'SVC_CE'){
                        userMap.put('SVC_CE_'+atm.AccountId, atm.User.Id);
                    }       
                }
            }
        }
        
        List<SFDC_Acct_Plan__c> apList = [SELECT id, RSD_Review_Feedback__c, Services_Account_Sales_Executive__c, Services_Customer_Executive__c, Account__c FROM SFDC_Acct_Plan__c WHERE Account__c = :testAccount.Id];
        List<SFDC_Acct_Plan__c> apListUpdate = new List<SFDC_Acct_Plan__c>();
        for(SFDC_Acct_Plan__c ap: apList){
            ap.Services_Account_Sales_Executive__c = userMap.get('SVC_ASE_'+testAccount.id);
            ap.Services_Customer_Executive__c = userMap.get('SVC_CE_'+testAccount.id);
            ap.RSD_Review_Feedback__c = 'update test RSD review feedback';
            apListUpdate.add(ap);
        }
        update apListUpdate;
        Test.stopTest();
    }
    
    /*private static testMethod void testModifyPlanningYear() {
        
        createTestDataSet2();
        
        Test.startTest();
               
        SFDC_Acct_Plan__c foundAp = [SELECT id, Plan_Starting_Fiscal_Year__c, Calculated_Annual_Value_of_Strategies__c, Account__c FROM SFDC_Acct_Plan__c WHERE Id = :testAccPlan.Id];
        
        System.AssertEquals(foundAp.Calculated_Annual_Value_of_Strategies__c, 1.00);
                
        foundAp.Plan_Starting_Fiscal_Year__c = 'FY17';
        
        update foundAp;
        
        foundAp = [SELECT id, Plan_Starting_Fiscal_Year__c, Calculated_Annual_Value_of_Strategies__c, Account__c FROM SFDC_Acct_Plan__c WHERE Id = :testAccPlan.Id];
        
        System.AssertEquals(foundAp.Calculated_Annual_Value_of_Strategies__c, 2.00);
        
        Test.stopTest();
    }*/
    
    private static void createTestData(){
        List<AccountTeamMember> testATM = new List<AccountTeamMember>();
        AccountTeamMember atm = new AccountTeamMember();
        
        TriggerExecutionController.setSkipAccounttriggers(true);
        //Create test account
        testAccount = new Account(Name='Test Account', Type='End User');
        insert testAccount;
		
        
        //Create a user with Standard User profile       
        List<User> userList = new List<User>();
        Profile profile = [select id from profile where Name = 'System Administrator' limit 1];
        
        User userRecord = new User(Username='testUser1'+ System.currentTimeMillis()+'@dell.com',
                                        Alias = 'Test1', 
                                        Email='testUser1'+'@dell.com',            
                                        LastName='Test1',
                                        Title='SVC_ASE', 
                                        ProfileId = profile.Id, 
                                        LanguageLocaleKey='en_US', 
                                        LocaleSidKey='en_US', 
                                        EmailEncodingKey='UTF-8', 
                                        TimeZoneSidKey='America/Los_Angeles',
                                        Country='US',
                                        Badge_Number__c='Test1'+System.currentTimeMillis());
        User userRecord2 = new User(Username='testUser2'+ System.currentTimeMillis()+'@dell.com',
                                        Alias = 'Test2', 
                                        Email='testUser2'+'@dell.com',            
                                        LastName='Test2',
                                        Title='SVC_CE', 
                                        ProfileId = profile.Id, 
                                        LanguageLocaleKey='en_US', 
                                        LocaleSidKey='en_US', 
                                        EmailEncodingKey='UTF-8', 
                                        TimeZoneSidKey='America/Los_Angeles',
                                        Country='US',
                                        Badge_Number__c='Test2'+System.currentTimeMillis());
        userList.add(userRecord);
        userList.add(userRecord2);
        insert userList;

        //Create Account Plan
        testAccPlan = new SFDC_Acct_Plan__c (name='TestPlan01',Plan_Starting_Fiscal_Year__c= 'FY19', Account__c= testAccount.Id, Sales_Manager__c = userList[0].Id, RSD_Review_Feedback__c ='test RSD review feedback');
        insert testAccPlan;
        
        SFDC_Acct_Plan__c testAccPlan1 = new SFDC_Acct_Plan__c (name='TestPlan01',Plan_Starting_Fiscal_Year__c= 'FY19', Account__c= testAccount.Id, Sales_Manager__c = userList[0].Id, RSD_Review_Feedback__c ='test RSD review feedback', recordtypeId = IdLookupUtils.getRecordTypeId('Channel/Partner Account Plan','SFDC_Acct_Plan__c',true));
        
        Database.SaveResult[] listATMResult = Database.insert(new List<SFDC_Acct_Plan__c>{testAccPlan1},false);
        
        
        //Create Account Team Memmber
        for(integer i=0;i<userList.size();i++){
            atm = new AccountTeamMember (AccountId=testAccount.Id, userId = userList[i].Id, AccountAccessLevel='Read', CaseAccessLevel='Read', OpportunityAccessLevel='Read');
            testATM.add(atm);
        }
        insert testATM;
        TriggerExecutionController.setSkipAccounttriggers(false);
    }

    private static void createTestDataSet2(){
        
        //Create test account
        testAccount = new Account(Name='Test Account', Type='End User');
        insert testAccount;

        //Create Account Plan
        testAccPlan = new SFDC_Acct_Plan__c (name='TestPlan01',Account__c= testAccount.Id, Plan_Starting_Fiscal_Year__c='FY16');
        insert testAccPlan;

        //create strategy
        
        List<SFDC_Strategy__c> strategyList = new List<SFDC_Strategy__c>();
        
        SFDC_Strategy__c StrategyRec1 = new SFDC_Strategy__c(
            SFDC_Acct_Plan__c = testAccPlan.id,
            When_do_you_plan_to_realize_Strategy__c = 'FY16',
            Potential_Strategy_Value__c = 1.00
        );        
        strategyList.add(StrategyRec1);
        
        SFDC_Strategy__c StrategyRec2 = new SFDC_Strategy__c(
            SFDC_Acct_Plan__c = testAccPlan.id,
            When_do_you_plan_to_realize_Strategy__c = 'FY17',
            Potential_Strategy_Value__c = 1.00
        );
        strategyList.add(StrategyRec2);
        
        SFDC_Strategy__c StrategyRec3 = new SFDC_Strategy__c(
            SFDC_Acct_Plan__c = testAccPlan.id,
            When_do_you_plan_to_realize_Strategy__c = 'FY16',
            Potential_Strategy_Value__c = null
        );
        strategyList.add(StrategyRec3);
        
        SFDC_Strategy__c StrategyRec4 = new SFDC_Strategy__c(
            SFDC_Acct_Plan__c = testAccPlan.id,
            When_do_you_plan_to_realize_Strategy__c = 'FY17',
            Potential_Strategy_Value__c = 1.00
        );
        strategyList.add(StrategyRec4);
        
        insert strategyList ;
        
    }
    
}