profilelist1exp/unpackaged/objects/SFDC_Acct_Plan__c.object
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc - R.10.2 Custom Field for Account Planning||
SFA -Y/PRM-N||
VAL -  N||
CR# -R10.2 # 35778  ||</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>R00N60000001PRP8EAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Plans</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Trigger_Handler__mdt.object
<CustomObject>
    <description>A trigger handler class to run on the given sObject and trigger event</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>The Apex class to run</description>
        <inlineHelpText>The Apex class to run</inlineHelpText>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Trigger event to run this handler</description>
        <inlineHelpText>Trigger event to run this handler</inlineHelpText>
        <label>Event</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                    <default>true</default>
                    <label>BeforeInsert</label>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>BeforeUndelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <description>The sObject to run the handler on</description>
        <inlineHelpText>The sObject to run the handler on</inlineHelpText>
        <label>sObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trigger Handler</label>
    <pluralLabel>Trigger Handlers</pluralLabel>
</CustomObject>

profilelist1exp/unpackaged/classes/ContentDocLinkTriggerHandlerADTest.cls
/*
 * Revision CR Number   Release No  Date            Modified By     Description
 * -------- ---------   ----------  -----------     ------------    -----------
 * 1.0       CR18117    FY20-1101   23-Sept-2019     Hari A        Test class for ContentDocLinkTriggerHandlerAD/ContentDocLinkUtilities
 * 
 */ 

@isTest
public class ContentDocLinkTriggerHandlerADTest{

public static testmethod void deleteCDLTest(){
    String strMockMetaData = '';
    
    Map<String, List<Boolean>> mapEvents = new Map<String, List<Boolean>> {
        'AfterDelete' => new List<Boolean>{false, false, false, true, false}
    };
    
    for(String strEvent : mapEvents.keySet()) {
    strMockMetaData += '{"DeveloperName": "TestHandler' + strEvent + '", '
            + '"NamespacePrefix": "",'
            + '"Event__c": "' + strEvent + '", '
            + '"sObject__c": "ContentDocumentLink", "Class_Name__c": "ContentDocLinkTriggerHandlerAD"},';
    }
    
    strMockMetaData = '[' + strMockMetaData.substringBeforeLast(',') + ']';
    
    MetadataTriggerManager.listMockMetaData = (List<Trigger_Handler__mdt>)JSON.deserializeStrict(strMockMetaData, List<Trigger_Handler__mdt>.class);
      
    Test.startTest();
    Account acc = new Account(Name = 'Testacc');
    insert acc;
    
    SFDC_Acct_Plan__c sap = new SFDC_Acct_Plan__c();
    sap.Account__c = acc.id;
    sap.name = 'Test AP';
    
    insert sap;
    system.assertEquals('Test AP',sap.Name);
    SFDC_Acct_Plan__c sapDel = new SFDC_Acct_Plan__c();
    sapDel.Account__c = acc.id;
    sapDel.name = 'Test AP Del';
    
    insert sapDel;
    
    ContentVersion content=new ContentVersion(); 
    content.Title='Header_Picture1'; 
    content.PathOnClient='/' + content.Title + '.jpg'; 
    Blob blbBody=Blob.valueOf('Unit Test ContentVersion Body'); 
    content.VersionData=blbBody; 
    content.origin = 'H';
    insert content;
    
    
    ContentDocumentLink contentlink=new ContentDocumentLink();
    contentlink.LinkedEntityId=sap.id;
    contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
    contentlink.ShareType = 'I';
    contentlink.Visibility = 'AllUsers'; 
    
    insert contentlink;
    
    ContentDocumentLink contentlinkDel=new ContentDocumentLink();
    contentlinkDel.LinkedEntityId=sapDel.id;
    contentlinkDel.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
    contentlinkDel.ShareType = 'I';
    contentlinkDel.Visibility = 'AllUsers'; 
    
    insert contentlinkDel;
    
    ContentDocumentLink cdl = [select id from ContentDocumentLink where id=:contentlinkDel.id];
    delete cdl;
    Test.stopTest();

    }
}