profilelist1exp/unpackaged/objects/Work_Items__c.object
<CustomObject>
    <description>This object is to track all Account Owner Updates</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accountid</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Items</relationshipLabel>
        <relationshipName>Work_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>Stores the primary object of the WorkItem. Read Only for UI. Useful in reports.</description>
        <inlineHelpText>Primary object of the Work Items</inlineHelpText>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Relationship Lead</fullName>
                </value>
                <value>
                    <fullName>Account Play</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed-Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Items</label>
    <nameField>
        <displayFormat>WI-{00000000}</displayFormat>
        <label>Work Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/BatchUpdateAccountTaskExecute.cls
/*
Author: Azwanti Zuber

History:
Version Date            Modified By     Description     
--------------------------------------------------------------------------------------
1.0      29-SEPT-2010   Azwanti         Created for CR4117, R11.10

*/ 
global class BatchUpdateAccountTaskExecute implements Schedulable{
    
    global void execute(SchedulableContext sc){
        BatchUpdateAccountTask buAccountTask = new BatchUpdateAccountTask();
        buAccountTask.queryAccTask = 'SELECT WhatId, AccountId, OwnerId '+
                                     'FROM Task WHERE WhatId in (SELECT Account__c FROM Work_Items__c WHERE Status__c = \'In Progress\' AND Object_Type__c = \'Account\') AND '+
                                     'IsClosed = false';
                                              
        ID batchprocessid1 = Database.executeBatch(buAccountTask,200); 
    }
}