force-app/main/default/objects/Account/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Account Country</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

profilelist1exp/unpackaged/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Account_Department__c</fullName>
        <inlineHelpText>End Customer account department</inlineHelpText>
        <label>Account Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Industry__c</fullName>
        <inlineHelpText>End Customer account industry</inlineHelpText>
        <label>Account Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not For Profit</fullName>
                </value>
                <value>
                    <fullName>Recreation</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Telecommunications</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <inlineHelpText>End Customer mailing State</inlineHelpText>
        <label>Mailing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_city__c</fullName>
        <inlineHelpText>End Customer mailing city</inlineHelpText>
        <label>Mailing city</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_country__c</fullName>
        <label>Mailing country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_street__c</fullName>
        <inlineHelpText>End Customer mailing street</inlineHelpText>
        <label>Mailing street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005A00000018286</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>End Customers</relationshipLabel>
        <relationshipName>End_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial/SMB (&lt;500 Emp)</fullName>
                </value>
                <value>
                    <fullName>Commercial/Med &amp; Large Business (&gt;500 emp)</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>State/Provincial &amp; Local/Municipal Gov&apos;t</fullName>
                </value>
                <value>
                    <fullName>Health Care &amp; Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Federal / Government</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/End_Customer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>End Customers Contact</relationshipLabel>
        <relationshipName>End_Customers_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>End Customer Contact</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers Contact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification Desc -||SFA -Y/PRM-Y||VAL -  N||CR# -R10.2 # 816  ||</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Requests (Account)</relationshipLabel>
        <relationshipName>R00N70000002MeWhEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Full Legal Name of Your Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF - Y - PRM English Partner Registration Duplicate;PRM English Partner Registration Incomplete;PRM English Partner Registration Submitted;PRM English Partner Registration Rejected/ APP/ FU / OM - N ||Email alert-Y-PRM English Partner Registration Duplicate;PRM English Partner Registration Incomplete;PRM English Partner Registration Submitted;PRM English Partner Registration Rejected
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>End_Customer__c</referenceTo>
        <relationshipLabel>Partner Requests</relationshipLabel>
        <relationshipName>Partner_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Partner Requests</relationshipLabel>
        <relationshipName>R00N70000002MeZWEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/PartnerRegistrationLinkToAcctCtlExtTest.cls
@IsTest
private class PartnerRegistrationLinkToAcctCtlExtTest {
  
    private static testMethod void testScreenIsForUpdateOnly() {
        Partner_Request__c request = new Partner_Request__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@acme.com',
            Company__c = 'Tyama');
        PartnerRegistrationLinkToAcctCtrlrExt extension = new PartnerRegistrationLinkToAcctCtrlrExt(
            new ApexPages.standardController(request));
        TestUtils.assertErrorMessagesExist();
        System.assertEquals(extension.doPageLoad(),null);
        System.assertNotEquals(extension.getAccountSearchResults(),null);
        System.assert(extension.getAccountSearchResults().isEmpty());
        TestUtils.assertErrorMessagesExist();
    }
    
    private static testMethod void testRegistrationIsNotSaved() {
        Partner_Request__c request = new Partner_Request__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@acme.com');
        PartnerRegistrationLinkToAcctCtrlrExt extension = new PartnerRegistrationLinkToAcctCtrlrExt(
            new ApexPages.standardController(request));
        System.assertEquals(extension.doPageLoad(),null);

        insert request;
        extension = new PartnerRegistrationLinkToAcctCtrlrExt(
            new ApexPages.standardController(request));
        System.assertEquals(extension.doPageLoad(),null);
    } 
    
    private static testMethod void testNormalFlow() {
        Lead lead = new Lead(lastName='test',Company='test',Phone='1234567899');
        insert lead;
        Account acct2Link = new Account(name='Tyama');
        insert acct2Link;       
        Test.setFixedSearchResults(new Id[]{acct2Link.id});
        Partner_Request__c request = new Partner_Request__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@acme.com',
            Company__c = 'Tyama',
            Lead__c = lead.id);
        insert request;  
        lead.Partner_Request__c = request.id;
        update lead;
        PartnerRegistrationLinkToAcctCtrlrExt extension = new PartnerRegistrationLinkToAcctCtrlrExt(
            new ApexPages.standardController(request));
        System.assertEquals(extension.getAccountSearchResultsCount(),0);
        System.assertEquals(extension.doPageLoad(),null);
        TestUtils.assertNoErrorMessagesExist();
        System.assertEquals(extension.getIsAccountSelected(),false);
        System.assertNotEquals(extension.getAccountSearchResults(),null);
        System.assertNotEquals(extension.getAccountSearchResultsCount(),0);
        System.assert(!extension.getAccountSearchResults().isEmpty());
        
        System.assertEquals(extension.doConfirmAccount(),null);
        TestUtils.assertNoErrorMessagesExist();
 
        ApexPages.currentPage().getParameters().put('accountId', '');
        System.assertEquals(extension.doSelectAccount(),null);
        ApexPages.currentPage().getParameters().put('accountId', '123');
        System.assertEquals(extension.doSelectAccount(),null);
        ApexPages.currentPage().getParameters().put('accountId', acct2Link.id);
        System.assertEquals(extension.doSelectAccount(),null);
        TestUtils.assertNoErrorMessagesExist();
        System.assertEquals(extension.getIsAccountSelected(),true);
        System.assertNotEquals(extension.selectedAccount,null);
        
        PageReference next = extension.doCancel();
        System.assertNotEquals(next,null);
        System.assertEquals(next.getUrl(),'/' + request.id);

        next = extension.doConfirmAccount();
        TestUtils.assertNoErrorMessagesExist();
        System.assertNotEquals(next,null);
        System.assertEquals(next.getUrl(),'/' + request.id);
        
    }
    
    
    private static testMethod void testSelectAccountAlreadyPartner() {
        Lead lead = new Lead(lastName='test',Company='test',phone='1234567891');
        insert lead;
        Account acct2Link = new Account(name='Tyama');
        insert acct2Link;  
        acct2Link.IsPartner = true;
        update acct2Link;     
        Test.setFixedSearchResults(new Id[]{acct2Link.id});
        Partner_Request__c request = new Partner_Request__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@acme.com',
            Company__c = 'Tyama',
            Lead__c = lead.id);
        insert request;
        PartnerRegistrationLinkToAcctCtrlrExt extension = new PartnerRegistrationLinkToAcctCtrlrExt(
            new ApexPages.standardController(request));
        TestUtils.assertNoErrorMessagesExist();

        ApexPages.currentPage().getParameters().put('accountId', acct2Link.id);
        System.assertEquals(extension.doSelectAccount(),null);
        TestUtils.assertErrorMessagesExist();
    }
    
    
    
    private static testMethod void testNewCustomer() {
        RecordType recType=[SELECT Name,Id,SobjectType FROM RecordType WHERE Name ='New Customer' AND SobjectType='Partner_Request__c'];
        
        Account acct2Link = new Account(name='Tyama');
        insert acct2Link;
        
        Account partnerAccount=new Account();
        partnerAccount.name='PartnerAccount';
        partnerAccount.Account_Country_Code__c='AI';
        partnerAccount.Account_Country__c = 'ANGUILIA';              
        insert partnerAccount;
        partnerAccount.IsPartner = true;
        partnerAccount.RecordTypeId = System.Label.RecType_Partner_Account;                
        update partnerAccount;
        
        //Creating end customer
        End_Customer__c endCustomer=new End_Customer__c();                   
        endCustomer.Account_Department__c='xxx';
        endCustomer.Account_Industry__c='Biotechnology';             
        endCustomer.Mailing_city__c='ff';
        endCustomer.Mailing_country__c='dasssa';
        endCustomer.Mailing_State__c='sdawwqwq';
        endCustomer.Mailing_street__c='ddsdqwewdc';
        endCustomer.Partner_Account__c=partnerAccount.id;
        endCustomer.Segment__c='Education';
        endCustomer.Status__c='Active';
        endCustomer.Tax_Id__c='aaaaa';
        endCustomer.Total_of_End_User_Employees__c='100 - 199';           
        endCustomer.Zip_Code__c='333333';
        endCustomer.Name='Company';           
        insert endCustomer;
        
        End_Customer_Contact__c endCstmrCntct=new End_Customer_Contact__c();
        endCstmrCntct.Name='test';
        endCstmrCntct.Email__c='testemail@Company31.com';
        endCstmrCntct.End_Customer__c=endCustomer.Id;
        endCstmrCntct.Fax__c='222';
        endCstmrCntct.Last_Name__c='tester';
        endCstmrCntct.Mobile__c='333';
        endCstmrCntct.Phone__c='4444';
        endCstmrCntct.Status__c='Active';
        endCstmrCntct.Title__c='xsad';        
        insert endCstmrCntct;
            
        Test.setFixedSearchResults(new Id[]{acct2Link.id});
        
        Partner_Request__c request = new Partner_Request__c(
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Email__c = 'john.doe@acme.com',
            Company__c = 'Tyama',
            recordtypeId=recType.Id,
            end_customer__c=endCustomer.Id,
            Account__c=partnerAccount.id
            );
        insert request;
        
        
            
        //Partner_Request__c request=[select id,end_customer__c,First_Name__c,Last_Name__c,Email__c,Company__c,recordtypeId from Partner_Request__c where end_customer__c=:endCustomer.Id];
         
         
         PartnerRegistrationLinkToAcctCtrlrExt extension = new PartnerRegistrationLinkToAcctCtrlrExt(
            new ApexPages.standardController(request));
                  
        //TestUtils.assertNoErrorMessagesExist();
        PageReference pageRef3 = Page.PartnerRegistrationLinkToAcct;
        Test.setCurrentPage(pageRef3);
        ApexPages.currentPage().getParameters().put('accountId2', acct2Link.id);
        extension.getConfirmEUAcc();
        extension.getConfirmAccount();
        System.assertEquals(extension.doSelectAccount(),null);
        Pagereference pageRef=new Pagereference('/' + request.id);
        
        //System.debug('###Actual extension.doConfirmEndUserAccount()'+extension.doConfirmEndUserAccount());
        //System.debug('###Expected pageRef'+pageRef);
        //extension.setsearchString('Tyama');
        extension.doSearch();
        Pagereference result = extension.doConfirmEndUserAccount();
        System.debug('### result : ' + result);
        System.debug('### request: ' + request);
        //System.assertNotEquals(result,null);

        End_Customer__c endCstmr=[select id,EU_Affinity_ID__c , End_User_Account__c from End_Customer__c where id=:endCustomer.Id]; 
        System.debug('### Partner Acc : ' + partnerAccount.Id);
        System.debug('### Acc : ' + acct2Link.Id);
        System.debug('### Partner Acc Account_ID__c  : ' + partnerAccount.Account_ID__c );
        System.debug('### end cust EU_Affinity_ID__c   : ' + endCstmr.EU_Affinity_ID__c );
        System.debug('### reg end user: ' + request .End_Customer__c);
        
        End_Customer__c endCstmr2=[select id,EU_Affinity_ID__c , End_User_Account__c from End_Customer__c where id=:request .End_Customer__c]; 
        System.debug('### reg end user2 End_User_Account__c : ' + endCstmr2.End_User_Account__c);
        System.assertEquals(endCstmr.End_User_Account__c,endCstmr2.End_User_Account__c);
        
        //TestUtils.assertErrorMessagesExist();
    }
}