force-app/main/default/objects/Account/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Account Country</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Pakisthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -ISO 3166 Country Code||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <externalId>true</externalId>
        <label>ISO 3166-1 Country Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Language_Locale_Key__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>User Language Locale Key</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification Desc -||SFA -Y/PRM-Y||VAL -  N||CR# -R10.2 # 816  ||</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Requests (Account)</relationshipLabel>
        <relationshipName>R00N70000002MeWhEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Partner Requests (Country)</relationshipLabel>
        <relationshipName>R00N70000002MeXqEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF - Y - PRM English Partner Registration Duplicate;PRM English Partner Registration Incomplete;PRM English Partner Registration Submitted;PRM English Partner Registration Rejected/ APP/ FU / OM - N ||Email alert-Y-PRM English Partner Registration Duplicate;PRM English Partner Registration Incomplete;PRM English Partner Registration Submitted;PRM English Partner Registration Rejected
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Export_Compliance_Agreed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Export Compliance Agreed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Feature_Request_Deal_Registration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feature Request: Deal Registration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Customers__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Other Customers</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer (home)</fullName>
                </value>
                <value>
                    <fullName>Small Medium Business (1-99 employees)</fullName>
                </value>
                <value>
                    <fullName>Midsize Companies (100-499)</fullName>
                </value>
                <value>
                    <fullName>Corporate (+500 employees)</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>State Government</fullName>
                </value>
                <value>
                    <fullName>Small Government Entities</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Terms_Conditions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Agreed to conditions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Dell_Distribution_Partner__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -|The main distributor they use to purchase Dell from (Used in the Partner Registration form) |
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Preferred Dell Distribution Partner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>States_Provinces_doing_business__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>States / Provinces doing business in</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia And Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF / APP/ FU / OM - N ||
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Re-submitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Incomplete &amp; Expired</fullName>
                </value>
                <value>
                    <fullName>Lead Draft</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Submitted</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Completed</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Rejected</fullName>
                </value>
                <value>
                    <fullName>Account Suggestion Created</fullName>
                </value>
                <value>
                    <fullName>Aborted By Partner</fullName>
                </value>
                <value>
                    <fullName>Owned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Request</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PartnerPortalProfilingIntegrationTest.cls
/*---------------------------------------------
* Revision CR Number   Release No      Date            Modified By     Description
* -------- ---------   ----------      -----------     ------------    -----------
* 1.0 -     16018      FY18-DCS-0102   12.06.2018:     Jatin           Commented NET exam logic statements as part of NET003 story
* 1.1 -     16001      FY18-DCS-0102   18-06-2018:     manip4          removed NET exam reference, story #5171130   
*/
@isTest(seealldata = true)
public class PartnerPortalProfilingIntegrationTest {

 private static testmethod void MethodOne() {
  Test.startTest();
  
  TriggerExecutionController.setSkipUserTriggers(true);
TriggerExecutionController.setSkipContactTriggers(true);
TriggerExecutionController.setSkipAccountTriggers(true);

    Country__c country = [select id,name,Code__c,User_Language_Locale_Key__c from Country__c limit 1];
  //creating PR data
  Partner_Request__c request = new Partner_Request__c();

  request.RecordTypeId = IdLookupUtils.getRecordTypeId(PartnerConstants.REQUEST_RECORD_TYPE_NEW_PARTNER,
   'Partner_Request__c', true);
  request.email__c = 'test@dell.com';
  request.Export_Compliance_Agreed__c = true;
  request.Partner_Terms_Conditions__c = true;
  request.Other_Customers__c = 'test1';
  request.Preferred_Dell_Distribution_Partner__c = 'Test prefer';
  request.Feature_Request_Deal_Registration__c = true;
  request.country__c = country .id;
  insert request;

  //Creating test data for partner account. IsPartner=true and recordtype = Partner Account
  Map < String, String > paraMap = new Map < String, String > {
   'str_RecordTypeId' => System.Label.RecType_Partner_Account
  };
  List < Account > validAccount = (List < Account > ) TestDataGenerator.getObject(new Account(), 1, paraMap);

  validAccount[0].isPartner = true;
  validAccount[0].Partner_Registration__c = request.id;
  validAccount[0].Account_Country_Code__c = 'AI';
  validAccount[0].Account_Country__c = 'ANGUILIA';
  validAccount[0].Account_ID__c = '12345';
  validAccount[0].States_Provinces_doing_business__c = 'Test';
  update validAccount;
  request.Account__c = validAccount[0].id;
  update request;

  System.debug('###DEBUG### validAccount = ' + validAccount);



  Contact testcontact = new Contact(FirstName = 'cmapmodifiedfirst',
   LastName = 'cmapmodified',
   Status__c = 'Active',
   AccountId = validAccount[0].Id,
   EMEA_Decision_Making_Role__c = 'End User',
   Decision_Making_Role__c = 'Business User',
   Job_Function_Role__c = 'CFO',
   Job_Function__c = 'IT',
   Purchaser_Influence_over_Merged__c = 'Other',
   Partner_My_Account_GUID__c = 'test-test-test',
   Phone = '11111111',
   Email = 'abc@abc1.com');


  insert testcontact;


  final List < Profile > partnerProfiles = [select id, name from Profile where Name LIKE '%PRM Portal%'
   limit 1
  ];
  //The user is tied to the first contact 
  User testUser = new User(
   Username = 'testuser126753324@dell.com',
   Alias = 'test1',
   Email = '1@test.com',
   FirstName = 'Test',
   LastName = 'User',
   ProfileId = partnerProfiles.get(0).Id,
   LanguageLocaleKey = 'en_US',
   LocaleSidKey = 'en_US',
   EmailEncodingKey = 'UTF-8',
   TimeZoneSidKey = 'America/Los_Angeles',
   Badge_Number__c = null,
   ContactId = testcontact.id,
   Enable_Partner_Admin__c = true);
  insert testUser;
  PartnerPortalProfilingserviceIntegration.integratePartnerDataWithContact(String.valueOf(testcontact.id));
  PartnerPortalProfilingserviceIntegration.sendAccountInfo(String.valueOf(validAccount[0].id), String.valueOf(testUser.id));
  PartnerPortalProfilingserviceIntegration.integratePartnerDataWithAccount(String.valueOf(validAccount[0].id));
 }


}