force-app/main/default/objects/Account/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Account Country</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

profilelist1exp/unpackaged/objects/End_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <inlineHelpText>End Customer mailing State</inlineHelpText>
        <label>Mailing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_city__c</fullName>
        <inlineHelpText>End Customer mailing city</inlineHelpText>
        <label>Mailing city</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005A00000018286</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>End Customers</relationshipLabel>
        <relationshipName>End_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Channel DB</fullName>
                </value>
                <value>
                    <fullName>Deal Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>End Customer</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/OWD__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object Wide Definition : This Custom Setting is to store static value of fields for usage of whole Org.</description>
    <fields>
        <fullName>Oppty_Stage0__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Lost, Cancelled - 0%</description>
        <label>Oppty_Stage0</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage100__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Win - 100%</description>
        <label>Oppty_Stage100</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage10__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Discover - 10%</description>
        <label>Oppty_Stage10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage1__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Plan - 1%</description>
        <label>Oppty_Stage1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage30__c</fullName>
        <description>To store value of: 
Object: Opportunity
Field: StageName
Value: Qualify - 30%</description>
        <label>Oppty_Stage30</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage60__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Propose - 60%</description>
        <label>Oppty_Stage60</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage90__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Commit - 90%</description>
        <label>Oppty_Stage90</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oppty_Stage99__c</fullName>
        <description>To store value of: 
Object: Opportunity 
Field: StageName 
Value: Order Submitted - 99%</description>
        <label>Oppty_Stage99</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OWD</label>
</CustomObject>

profilelist1exp/unpackaged/objects/Partner_Type__c.object
<CustomObject>
    <label>Partner Type</label>
    <nameField>
        <label>Partner Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/classes/Batch_DeactivateInvalid_EndCustomersTest.cls
/*====================================================================================================================+
|  HISTORY |                                                                 
|                                                                           
| DATE         Modified              Story           DESCRIPTION                               
| ===========  =========           =========          =========== 
| 06-Dec-2019  Venu K 				  0102			   Implemented TDF
+====================================================================================================================*/

@isTest
public class Batch_DeactivateInvalid_EndCustomersTest {
    static List<Account> listAcc;
    static list<Opportunity> listOpp;
    @testSetup static void setup() {
        // Create common test OWD settings
        OWD__c owdSetting = new OWD__c();
        owdSetting.Oppty_Stage1__c = 'Plan - 1%';
        owdSetting.Oppty_Stage10__c = 'Discover - 10%';
        owdSetting.Oppty_Stage30__c = 'Qualify - 30%';
        owdSetting.Oppty_Stage60__c = 'Propose - 60%';
        owdSetting.Oppty_Stage90__c = 'Commit - 90%';
        owdSetting.Oppty_Stage99__c = 'Order Submitted - 99%';
        owdSetting.Oppty_Stage100__c = 'Win - 100%';
        owdSetting.Oppty_Stage0__c = 'Lost, Cancelled - 0%';
        Insert owdSetting;
        TriggerExecutionController.setSkipAllTriggers(true);
        list<Account> listAccTdf=TestDataFactory.createNAccount(2, 'Partner Account');
        for(Account acc : listAccTdf){
            acc.Partner_Relationship__c = 'Authorized';
            acc.Status__c = 'Active';
            acc.DMU__c = false;
        }
        listAccTdf[0].Account_Country__c = 'UNITED STATES';
        listAccTdf[0].Type = 'Partner';
        listAccTdf[1].Partner_Type__c = 'Distributor (GCC)';
        listAccTdf[1].Distribution_Sell_To_Countries__c = 'UNITED STATES';
        listAccTdf[1].Account_Country__c = 'UNITED KINGDOM';
        listAccTdf[1].Partner_Tier__c = 'Tier 1';
        insert listAccTdf;
        list<Opportunity> listOppTdf=TestDataFactory.createNOpportunities(1, 'Deal Registration');
        insert listOppTdf;
        list<User> listUserTdf=TestDataFactory.createNPortalUser(1);
        listUserTdf[0].Enable_Partner_Admin__c = true;
        listUserTdf[0].Enable_Partner_Deal_Registration__c = true;
        insert listUserTdf;
    }
    static testMethod void inActivateEndCUstomersScenario1(){
        TriggerExecutionController.setSkipAllTriggers(true);
        listAcc=[SELECT ID FROM Account Limit 2];
        // End Customer Creation
        End_Customer__c endCustomerString = new End_Customer__c(Name = 'TestEndCustomer',
                                                                Mailing_city__c = 'City',
                                                                Mailing_State__c ='state',
                                                                Status__c = 'Active',
                                                                Source_System__c = 'Deal Registration',
                                                                Partner_Account__c = listAcc[0].id );
        insert endCustomerString;      
        Datetime dtendCusCreDate = Datetime.now().addDays(-45);
        Test.setCreatedDate(endCustomerString.Id, dtendCusCreDate);
        system.assertNotEquals(listAcc[0].id, null);
        Test.startTest();
        Batch_DeactiveInvalid_EndCust_Scheduler dr = new Batch_DeactiveInvalid_EndCust_Scheduler();
        String strsch = '0 0 22 ? * SAT';
        System.schedule('Test',strsch,dr);
        Test.stopTest();
        TriggerExecutionController.setSkipAllTriggers(false);
    }
    static testMethod void inActivateEndCUstomersScenario2(){
        TriggerExecutionController.setSkipAllTriggers(true);
        listAcc=[SELECT ID FROM Account Limit 2];
        // End Customer Creation
        End_Customer__c endCustomerString = new End_Customer__c(Name = 'TestEndCustomer',
                                                                Mailing_city__c = 'City',
                                                                Mailing_State__c ='state',
                                                                Status__c = 'Active',
                                                                Source_System__c = 'Deal Registration',
                                                                Partner_Account__c = listAcc[0].id );
        insert endCustomerString;      
        Datetime dtendCusCreDate = Datetime.now().addDays(-45);
        Test.setCreatedDate(endCustomerString.Id, dtendCusCreDate);
        list<user> listUser=[Select id from user limit 1];
        listOpp=[select id from Opportunity limit 1];
        listOpp[0].AccountId=listAcc[1].id;
        listOpp[0].Save_End_Customer_to_my_list__c = 'No';
        listOpp[0].End_Customer__c = endCustomerString.id;
        listOpp[0].Is_the_Customer_Part_of_a_Larger_Group__c = 'Yes';
        update listOpp;
        system.assertNotEquals(listOpp[0].id, null);
        Test.startTest();
        Batch_DeactiveInvalid_EndCust_Scheduler dr = new Batch_DeactiveInvalid_EndCust_Scheduler();
        String strsch = '0 0 22 ? * Mon';
        System.schedule('Test',strsch,dr);
        Test.stopTest(); 
        TriggerExecutionController.setSkipAllTriggers(false);
    }    
}