force-app/main/default/objects/Account/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Account Country</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Pakisthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Project_Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Project Services to store Client Id and Client Secret of Application</description>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Services</label>
</CustomObject>

force-app/main/default/objects/S_P_Vendors__c/S_P_Vendors__c.object-meta.xml
<CustomObject>
    <label>S&amp;P Vendors</label>
    <nameField>
        <displayFormat>SV # {000000000}</displayFormat>
        <label>S&amp;P Vendors ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S&amp;P Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S_P_Vendors__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BOUVET ISLAND</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/S_P_Vendors__c/fields/Customer_Domain__c.field-meta.xml
<CustomField>
    <fullName>Customer_Domain__c</fullName>
    <description>This text field to show on VMware S&amp;P Vendor page layout and the information captured by Sales Users on the VMware S&amp;P Vendor records and the info can be sent to VMware, via Boomi integration, to increase chances of a successful registration.</description>
    <inlineHelpText>Text following @ in customer email address, ex. dell.com</inlineHelpText>
    <label>Customer Domain</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S_P_Vendors__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S_P_Vendors__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>S&amp;P Vendors</relationshipLabel>
    <relationshipName>S_P_Vendors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/S_P_Vendors__c/fields/Ship_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Address__c</fullName>
    <label>Ship to Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S_P_Vendors__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Ags</fullName>
            </value>
            <value>
                <fullName>Aichi</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>Akita</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Aomori</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BCS</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chattisgarh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/S_P_Vendors__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

profilelist1exp/unpackaged/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VMwareSearchCapabilityControllerTest.cls
/*
  * Author   : Ravali K
  * Purpose  : This class is a test class associated to VMwareSearchCapabilityController and VMwareSearchApiCallOut.
  *
  * Revision   CR Number   Release No          Date          Modified By      Description
  * --------  ---------   ----------        -----------     ------------      -----------
  * 1.0         14782     FY18-DCS-1001       25-Aug-17      Ravali - UST      Created Test class
  *
*/

@IsTest
private class VMwareSearchCapabilityControllerTest {    
    
      
    static testMethod void TestVMwareSearch()
    {
        TriggerExecutionController.setSkipAllTriggers(true);
        
        
        Account acc=new Account(name='test contact', Account_Country_Code__c='US',Account_Country__c='United States');
        insert acc;
        
         Opportunity testOppty= new Opportunity(Name = 'test', CloseDate = System.today(), StageName = 'Plan - 1%');
         insert testOppty;
            
        
        
        S_P_Vendors__c SnPRecord = new S_P_Vendors__c();
        
        SnPRecord.Customer_Name__c = 'Test Company';
        SnPRecord.Customer_Domain__c = 'Test Domain';
        SnPRecord.Ship_to_Address__c= 'Test Address';
        SnPRecord.Country__c= 'Test Country';
        SnPRecord.City__c= 'Test City';
        SnPRecord.State__c= 'Test State';
        SnPRecord.Zip__c= 'Test Zip';
        SnPRecord.Opportunity__c =testOppty.id; 
        
        Insert SnPRecord;
        
        
         Project_Services__c ps = new Project_Services__c(name='Mulesoft',Client_Id__c='00000000A',Client_Secret__c='00000000B');
         insert Ps;  
         
         PageReference tpageRef = Page.VF_VMwareSearchCapability;
         Test.setCurrentPage(tpageRef);
         
         
         ApexPages.currentPage().getParameters().put('Id', SnpRecord.Id);
         system.debug('*********SnP Record ID********* '+ApexPages.currentPage().getParameters().get('Id'));
         ApexPages.currentPage().getParameters().put('selectedRow', 'CUST-0001573041');
         
         System.Assert(ApexPages.currentPage().getParameters().get('selectedRow')=='CUST-0001573041');
         System.Assert(ApexPages.currentPage().getParameters().get('Id')== SnpRecord.Id);
    
         Test.startTest();
                  
         //Test.setMock(HttpCalloutMock.class, new Mulesoft_MockHttpResponseGenerator());
         Test.setMock(HttpCalloutMock.class, new VMWare_MockHttpResponseGenerator());
         
         //System.assert(contentType == 'application/json');
         VMwareSearchCapabilityController controller = new VMwareSearchCapabilityController();
         Controller.Search();
         
                  
         controller.SnPRecord.Country__c= 'INDIA';
         //controller.getEnable();
         //controller.companyname = 'Wells';
         controller.Search();
         System.assert(controller.SnPRecord.Country__c == 'INDIA');
         controller.companyname = 'Wells';
         controller.Search();
         
         

         

         
         Controller.Save();

         
         //Controller.overrideDetails();
         //Controller.cancelOverrideDetails();
         
         Test.stopTest();
         TriggerExecutionController.setSkipAllTriggers(false);

         
         
         
    }

}