force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Pakisthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

profilelist1exp/unpackaged/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -ISO 3166 Country Code||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <externalId>true</externalId>
        <label>ISO 3166-1 Country Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Inc_Vendor_End_Point__c</fullName>
        <description>Vendor Service end-point that salesforce uses to pass information.</description>
        <inlineHelpText>Webservice end point for Vendor</inlineHelpText>
        <label>Incentives End Point</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Inc_Vendor_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>https://www.dellachievers.com</fullName>
                </value>
                <value>
                    <fullName>https://www.dellpartnerincentives.com/UserManagement/UserManagementService.svc/Process</fullName>
                </value>
                <value>
                    <fullName>https://dell.performnet.com/dell/rest/accountMaintenance.biws</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inc_Vendor_Name__c</fullName>
        <description>Identifies the vendor who runs the incentives program for the logged in-users.</description>
        <inlineHelpText>Not Applicable / On Hold  - Not enabled for Incentives
PartnerDirect Rewards Center    - Enabled for Incentives - BINA
Partner Advantage    - Enabled for Incentives - BIEU
Dell Achievers - Enabled for Incentives - GRG</inlineHelpText>
        <label>Incentives Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable/On Hold</fullName>
                    <default>true</default>
                    <label>Not Applicable/On Hold</label>
                </value>
                <value>
                    <fullName>Partner Direct Rewards Center</fullName>
                </value>
                <value>
                    <fullName>Partner Advantage</fullName>
                </value>
                <value>
                    <fullName>Dell Achievers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Operation_Performed__c</fullName>
        <description>The last process happen to the particular record, such as SFDC updated, Vendor updated, Vendor Update Failure.</description>
        <inlineHelpText>SFDC_UPDATED: Waiting for Vendor response
VENDOR UPDATED: Successfully integrated with Vendor
VENDOR SYNC FAILED: Integration with Vendor failed</inlineHelpText>
        <label>Last Operation Performed</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>INTEG-N / NON INTEG - Y / APEX/CC - N||
WF -Y - PRM Duplicate Partner Registration Account Owner Notification/ APP/ FU / OM - N ||Email alert -Y:PRM Duplicate Partner Registration Account Owner Notification
Desc -||
SFA -Y/PRM-Y||
VAL -  N||
CR# -R10.2 # 816  ||</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EC-EMEA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profilelist1exp/unpackaged/objects/Trigger_Handler__mdt.object
<CustomObject>
    <description>A trigger handler class to run on the given sObject and trigger event</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>The Apex class to run</description>
        <inlineHelpText>The Apex class to run</inlineHelpText>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Trigger event to run this handler</description>
        <inlineHelpText>Trigger event to run this handler</inlineHelpText>
        <label>Event</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                    <default>true</default>
                    <label>BeforeInsert</label>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>BeforeUndelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <description>The sObject to run the handler on</description>
        <inlineHelpText>The sObject to run the handler on</inlineHelpText>
        <label>sObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trigger Handler</label>
    <pluralLabel>Trigger Handlers</pluralLabel>
</CustomObject>

profilelist1exp/unpackaged/objects/TriggerExecutionControl__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>RecursiveCount__c</fullName>
        <defaultValue>4</defaultValue>
        <description>Specifies total number of recursive execution.
Setting this value to 1 =&gt; Skips the recursive execution initiated because of Workflow Field Updates.</description>
        <label>Recursive Count</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trigger Execution Control</label>
</CustomObject>

profilelist1exp/unpackaged/classes/ContactTriggerHandlerBUTest.cls
@IsTest
public class ContactTriggerHandlerBUTest {
public static boolean bCreate = true;
    public static integer iNumberOfContacts = 5;
    public static list<Contact> lstContacts;
  
    public static testMethod void updateContact(){
        populateCommonContactFields();
      
      Country__c country = new Country__c();
      country.Name = 'India';
      country.Code__c = 'IN';
      country.Region__c = 'APJ';
      country.Inc_Vendor_Name__c = 'Partner Advantage';
      country.Inc_Vendor_End_Point__c = 'https://www.dellpartnerincentives.com/UserManagement/UserManagementService.svc/Process';
      insert country;
      
      Account acc = new Account();
      acc.Name = 'testAccount123';
      acc.Type = 'Partner';
      acc.RecordTypeId = System.Label.RecType_Partner_Account;
      acc.Account_Country_Code__c = 'IN';
      insert acc;
     
      Contact con = new Contact();
      con.AccountId = acc.Id;
      con.Email = 'test@test.com';
      con.phone = '6739';
      con.LastName = 'conLastName';
      con.FirstName = 'conFirstName';
      con.Status__c = 'Customer';
      con.Email_Opt_In__c = 'yes';
      con.Survey__c = 'yes';
      con.Decision_Making_Role__c = 'Technical Buyer';
        insert con;
        
        Profile PRMprofile = [select id from profile where name like '%PRM Portal%' Limit 1];
       User testUser = new User(Username='testvaliduser' +'@dell.com',
                                    Alias = 'Test', 
                                    Email='Test'+'@dell.com',            
                                    LastName='Test',
                                    ContactId = con.Id,
                                    ProfileId = PRMprofile.Id, 
                                    LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', 
                                    EmailEncodingKey='UTF-8', 
                                    TimeZoneSidKey='America/Los_Angeles',
                                    Badge_Number__c='Test'+System.currentTimeMillis());
        
        insert testUser;

      Contact con1 = [Select Id,AccountId,FirstName,LastName,Email from Contact Where AccountId =: acc.Id];
        con1.FirstName = 'FirstNameCon';
        con1.Last_Operation_Performed__c = 'Vendor Sync failed';
        con1.Is_Incentives_Updated__c = true;
        update con1;
    }
     
    private static testMethod void populateCommonContactFields() {
        String strMockMetaData = '';

        Map<String, List<Boolean>> mapEvents = new Map<String, List<Boolean>> {
                'BeforeUpdate' => new List<Boolean>{true, true, false, false, false}
        };

        for(String strEvent : mapEvents.keySet()) {
            strMockMetaData += '{"DeveloperName": "TestHandler' + strEvent + '", '
                    + '"NamespacePrefix": "",'
                    + '"Event__c": "' + strEvent + '", '
                    + '"sObject__c": "Contact", "Class_Name__c": "ContactTriggerHandlerBU"},';
        }

        strMockMetaData = '[' + strMockMetaData.substringBeforeLast(',') + ']';

        MetadataTriggerManager.listMockMetaData = (List<Trigger_Handler__mdt>)JSON.deserializeStrict(strMockMetaData, List<Trigger_Handler__mdt>.class);
        
        TriggerExecutionControl__c tec = new TriggerExecutionControl__c();
        tec.Name = 'Contact';
        tec.RecursiveCount__c = 2;
        insert tec;
    }
    
}